### ISSUE TITLE
Detach repo

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/docker-lineage-cicd#10]
Can you please detach this repo from the fork?

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) **or** – which I recommend – just contact the GitHub support to do it for you.

I don't know why you use some personal repo as the "upstream" here anyway. Does not seem to be ued like that, but rather seems to be main service.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. linking to the original repo on every page does not make sense anymore as it seems to be a different project and you…
3. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
4. allows searching in this repo on GitHub and
5. it just looks much nicer

**Comment by corna** [comment]
You're right.

I've sent an email to the GitHub support.

**Comment by corna** [comment]
Done!
