### ISSUE TITLE
Build for river broken

### ISSUE THREAD

**Issue by MindfulProtons** [lineageos4microg/docker-lineage-cicd#102]
The build for river, 20200820, is broken, as it causes the touchscreen to be completely non-functional on reboot, as well as creating a long boot time for the system.

**Comment by spolack** [comment]
This issue seems to be out of scope to the project. If you can confirm this issue is not occuring with official LinageOS, please reopen.

[https://lineage.microg.org/images/bug_reporting.svg](url)
