### ISSUE TITLE
The Updater always shows updates even if the lastest update has been installed.

### ISSUE THREAD

**Issue by h0cheung** [lineageos4microg/docker-lineage-cicd#103]

**Comment by spolack** [comment]
What LineageOS version are you using?

**Comment by h0cheung** [comment]
@spolack 17.1-20200825-microG-dipper

**Comment by kurt-by** [comment]
Same issue with 16.0-20200816-microG-klte

**Comment by smac89** [comment]
Same issue for mata

**Comment by kurt-by** [comment]
This is a duplicate of https://github.com/lineageos4microg/docker-lineage-cicd/issues/171
