### ISSUE TITLE
Error building Wireguard on 17.1

### ISSUE THREAD

**Issue by ZJaume** [lineageos4microg/docker-lineage-cicd#104]
Hi,

I was building my own lineage4microg image succesfully adding wireguard support, but on 17.1 branch it fails building saying:
```
kernel/wireguard/Android.mk:7: error: writing to readonly directory: "TARGET_KERNEL_BINARIES"
```

To add wiregurad to the build it only needs to be [added](https://git.zx2c4.com/android_kernel_wireguard/about/#method-b-integrating-into-roms) to the local manifest, but [this](https://git.zx2c4.com/android_kernel_wireguard/tree/Android.mk) Android makefile is failing. I know that this is not part of the project but I wonder if you could give some advise on what it's happening.

**Comment by JuniorJPDJ** [comment]
Are you using `BUILD_OVERLAY` option?

**Comment by ZJaume** [comment]
Nope

**Comment by SleepingShell** [comment]
@ZJaume Did you manage to get this working?

**Comment by ZJaume** [comment]
Nope

**Comment by whirm** [comment]
I'm building it with  ` -e "TEMPORARY_DISABLE_PATH_RESTRICTIONS=true" ` on the docker command and this remote on the manifest:
```xml
    <remote name="drizzt" fetch="https://github.com/drizzt/" />
    <project remote="drizzt" name="android_kernel_wireguard" path="kernel/wireguard" revision="746823ee10de8146cb5f9fe01cd66961da5b7e5d" sync-s="true" />
```
Hope it helps!

**Comment by ZJaume** [comment]
Built succesfully! Thanks @whirm

**Comment by ZJaume** [comment]
In case someone is using this, it is no longer needed for 17.1 and 18.1 since Lineage added the wireguard to their kernel.
