### ISSUE TITLE
Build LineageOS MicroG manually (without docker)

### ISSUE THREAD

**Issue by hesoyamhh** [lineageos4microg/docker-lineage-cicd#107]
Hi Team, 
I have a remote VM on which Internet is not accessible but I am able to ssh to that device (via internal network). So, I use squid proxy on my local machine to allow internet access to that remote VM via port forwarding. So, I am able to execute all the steps provided in lineageos wiki and I am able to build lineageos zips. But due to proxies and port forwarding between my local machine and remote VM, docker-lineage-cicd doesn't work properly for me.

I have already set HTTP_PROXY and HTTPS_PROXY in `/etc/systemd/system/docker.service.d/http-proxy.conf` file. docker is able to pull images. `docker run hello-world` works without any issues.

My Docker command:
`docker run \
    -e "BRANCH_NAME=cm-14.1" \
    -e "DEVICE_LIST=armani" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -v "/home/ubuntu/android/lineage14:/srv/src" \
    -v "/home/ubuntu/android/docker/output_zips:/srv/zips" \
    -v "/home/ubuntu/android/docker/output_logs:/srv/logs" \
    -v "/home/ubuntu/android/docker/ccache:/srv/ccache" \
    -v "/home/ubuntu/android/docker/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd`

The remote VM is able to pull container and start it too but as soon as the container starts its execution via `./build.sh`, it gives `Error 111` and with `--net host` it gives `Error 404`.

I tried using urllib2 and urllib modules manually by executing sample code in python.

`import urllib2
response = urllib2.urlopen('http://python.org/')
html = response.read()`

On my remote VM, this works without any issues due to port forwarding. But If I try to run the same code on container created via docker-lineage-cicd, it starts throwing Error 111/404 as mentioned above.

So, Is it possible to build LineageOS with MicroG by adding
`<project name="lineageos4microg/android_prebuilts_prebuiltapks" path="prebuilts/prebuiltapks" remote="github" revision="master" />` along with the Muppets repo in `.repo/local_manifests/roomservice.xml` or is there anything more to do ?

**Comment by hesoyamhh** [comment]
Docker Info Output:
`Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-117-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.41GiB
 Name: linux
 ID: 4U2D:BHCK:6YO4:7ONX:47UW:O7L6:UETP:BXSI:YGMD:7STN:6VGB:7MZ6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://127.0.0.1:3129
 HTTPS Proxy: http://127.0.0.1:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`

**Comment by spolack** [comment]
I'm sorry but this doesnt seem to be related to this project.
