### ISSUE TITLE
Builds for dumpling have stopped

### ISSUE THREAD

**Issue by alecdotninja** [lineageos4microg/docker-lineage-cicd#108]
Hello :wave: 

Thank you for all of your work on this! I have been running Lineage OS for microG on my OnePlus 5T (`dumpling`) for over a year now with no issues. :tada: 

However, recently it seems that OTA updates have stopped. I think my device is still supported, and I see that vanilla Lineage has [builds for `20200901`, `20200908`, and `20200915`](https://download.lineageos.org/dumpling), yet Lineage for microG [stops at `20200816`](https://download.lineage.microg.org/dumpling/).

Was this intentional? And if not, is there a place where I can go to see build logs for troubleshooting?

**Comment by drake-newell** [comment]
I would also like to know this. Will there ever be a 17.1 or eventual 18 build for dumpling?

**Comment by gxtu** [comment]
Builds appear to be ongoing at the moment. A new 17.1 dumpling build should be finished in a few hours I think.

**Comment by alecdotninja** [comment]
@drake-newell I think that depends on upstream support from Lineage.

**Comment by drake-newell** [comment]
@gxtu Wait so there will be a 17.1 build for dumpling today?

**Comment by kurt-by** [comment]
16.0 dumpling has been built. There is no automatic build cycle at the moment. @alecdotninja 
Yes it looks like there is something going on opstream:
https://review.lineageos.org/q/project:LineageOS/android_device_oneplus_msm8998-common
Maybe the issue can be closed?

**Comment by alecdotninja** [comment]
Yep, I got a notification to update this morning! :tada:  I'll go ahead and close this for now.

---

@kurt-by :

> There is no automatic build cycle at the moment. 

I'm sorry if this is already documented elsewhere, but I don't see it. Is there a reason for this change? And is it permanent?

I've enjoyed getting almost weekly security updates, and I'm wondering if it would be better for me to switch back to vanilla Lineage and install microG myself.

**Comment by kurt-by** [comment]
@alecdotninja you don't get weekly security updates, even if the ROM gets built weekly or even daily. Especially for 16.0 there is no change in source code, except the merge of security patches once per month. Even in 17.1 there is tot much change these days, as developers are busy with 18.0

So for me it is enough to get one update in the second half of each month, when the patches are merged. I don't update more often, anyway.

And yes, the going manual is not well documented and I hav no info about future plans. Main reason was a change in build system necessitated for 17.1
