### ISSUE TITLE
Who is maintainer for Xiaomi Mi A1 a.k.a tissot

### ISSUE THREAD

**Issue by neroichi** [lineageos4microg/docker-lineage-cicd#109]
I'm trying to asking to my device global forum but nobody know who's maintainer of LineageOS MicroG for Xiaomi Mi A1. So can you tell me who's him/her?

I have some desire and wanna asking for build update, since it haven't updated yet for 1 months (without coercion). Also i don't have an experience to build a rom by myself, maybe anyone can tell me how to do (because i wanna to, but not having a teacher/guru).

I'm sorry if I'm asking at a wrong place. But let me know if you have information about my question. Thanks!

**Comment by Zeik0s** [comment]
From reading the issues here: please wait. Either the build is somehow failing, or there is something with the build server. @corna for sure has reasons.

**Comment by Zeik0s** [comment]
@neroichi tissot Update is live: https://download.lineage.microg.org/tissot/lineage-17.1-20200925-microG-tissot.zip
