### ISSUE TITLE
Remove the privileged app-only restriction on signature spoofing

### ISSUE THREAD

**Issue by Lanchon** [lineageos4microg/docker-lineage-cicd#11]
l4m uses a modified signature spoofing patch which allows only privileged apps to obtain the FAKE_SIGNATURE permission. please remove this privileged app-only restriction.

there are too many legitimate uses of sigspoof to count. for instance, i publish an apk modding toolchain (https://dexpatcher.github.io/). some apks have an anti-tamper mechanism that check their own signature and can be trivially bypassed with sigspoof. for a more concrete example. i am still stopped from using microg as my daily driver because hangouts doesn't work and i need VoIP access to my google voice number. i could try patching hangouts, except i can't sigspoof it later so i'm sure it will give me trouble.

as a question of principle, users should have as much power as developers on their systems. that's reason enough to have sigspoof open to users.

i understand fears of misuse by apps, but the privileged-only solution sucks. a global developer setting could be added to enable sigspoof for non-privileged apps instead. code for such a setting can be found on some of marvin patches or [here](https://github.com/Lanchon/haystack/tree/master/patches-src/sigspoof-ui-global-7.0-7.1). please note that per-app runtime permission requesting dialog should not be shown at all if the global setting is disabled.

another solution would be a hidden setting without a UI. for example, the user creating a special file in say /data/somewhere/special_file would enable global sigspoof. whatever works, just please do something.

thank you!!!

**Comment by rugk** [comment]
So where is this issue?

Also BTW, the privileged-only restriction on signature spoofing is a **security feature**. You can't just remove that, because then the claim that LineageOS devs have that microG introduces security issues is true. Because if it is unlimited, every app can spoof any app, including permissions etc. (At least taht's how I understand it.)
You could, however, theoretically limit signature spoofing to all microG apps, IMHO. I don't know any other app, which would have a reason to use it, anyway.

---

moved from https://github.com/lineageos4microg/l4m_website/issues/14#issuecomment-379548799

**Comment by rugk** [comment]
@corna [claims to have a solution that is secure but works](https://github.com/lineageos4microg/l4m_website/issues/14#issuecomment-379555276). So okay, I am interested to hear that.

**Comment by Lanchon** [comment]
> The privileged-only restriction on signature spoofing is a security feature.

no, sigspoof does not break android security in any meaningful way. also it doesn't have to be enabled by default. also, it can be enabled per-app. in contrast, some common features like root do break android security completely, yet many people use them, including me. i would not use unrooted android for anything at all.

> You can't just remove that, because then the claim that LineageOS devs have that microG introduces security issues is true.

no it isn't. LOS guys could just be wrong, but i'm more inclined to believe they have their agenda.

> Because if it is unlimited, every app can spoof any app, including permissions etc. (At least taht's how I understand it.)

it doesn't work that way.

> You could, however, theoretically limit signature spoofing to all microG apps, IMHO.

this is exactly what i ask shouldn't be done.

> I don't know any other app, which would have a reason to use it, anyway.

i do, i use it on my patched apps. see my first post.

**Comment by rugk** [comment]
> some common features like root do break android security completely, yet many people use them, including me

Are you kidding me? Of course not, unless you use a crappy CustomROM. (and don't install superSU or so)
Of course, root rights are also per app. Yet alone rooting your device does not bring in a problem, only when you grant root access to specific apps.

And that's the same as with privileges. Yes, of course, it can be a permission per app. Only if it is unrestricted (that's what my sentence was about) it is a security issue.

> it doesn't work that way.

So tell me, how does it work then?

**Comment by ArchangeGabriel** [comment]
I think you are both agreeing to the fact this need to be a per-app permission, just like it is on OmniROM.

**Comment by rugk** [comment]
Yeah, and the permission should make it clear that it an be dangerous to enable it. So maybe a manual option in the settings per app, you have to enable, e.g. how Android does it with the "draw on screen" permission, etc.

**Comment by Lanchon** [comment]
i think you mean "draw over other apps".

how is it under OmniROM? is it any different from a regular runtime permission? i see no problem with the runtime permission style, but i think corna wants something that is harder to phish. that's why i suggested runtime permission plus a global enable in developer settings.

**Comment by ArchangeGabriel** [comment]
Yes, “draw over other apps”.

Under OmniROM, it is treated like “Install APK from unknown sources” (in 8+) and “draw over other apps”, you have to go in a specific settings menu to allow it.

**Comment by ArchangeGabriel** [comment]
I’ll try to make screenshots later.

**Comment by corna** [comment]
> there are too many legitimate uses of sigspoof to count [...]

Actually this is the first time I see another use for the fake signature permission. ;)

> as a question of principle, users should have as much power as developers on their systems. that's reason enough to have sigspoof open to users.

We started LineageOS for microG to bring microG to the standard user without the need of complicated tools to patch the system or the introduction of potentially unsafe stuff. Bringing back the "open" signature spoofing only weakens the security (even if, I agree, not by much) without any major gain. I believe that the majority of the LineageOS for microG just want a Google-free system without hassle and don't need the fake signature permission on user apps.

Given that, we can still find a good compromise for everyone: I propose to add the allowViaWhitelist property, as described [here](https://review.lineageos.org/#/c/LineageOS/android_frameworks_base/+/195284/2/core/res/AndroidManifest.xml). In this way the signature spoofing permission, in addition to the privileged apps, can also be granted to the apps signed with a key in a whitelist, like [this one](https://review.lineageos.org/#/c/LineageOS/android_vendor_cm/+/195283/1/config/permissions/com.google.android.gms.xml) for microG. The whitelist is in /system/etc/permissions/*.xml, so only root (or recovery) can write to it so the security is not reduced.

So, the procedure for an user which needs the signature spoofing on his apps is:
 * download from us the template recovery zip which pushes a new key in the whitelist
 * modify the zip adding his own key
 * flash it

From that moment every app signed with his key can automatically obtain the FAKE_SIGNATURE permission.

It seems to me a valid compromise, what do you think?

**Comment by ArchangeGabriel** [comment]
@corna Well now that you say this, I’m not sure you should change anything: as you said, this fork is not about adding signature spoofing, it’s about using μG hassle-free.

**Comment by Lanchon** [comment]
hey @corna,

first let me thank you for putting in thought and effort on this issue, it does not go unnoticed.

that said, please forget about this route. signature whitelisting is IMHO aggravating and insulting, and the kind of anti-feature that finishes my relationship with a product. i would never use such a system myself or publish anything for it. computing should be fun, not aggravating.

IMHO this is acceptable:

- OmniROM's solution is perfect. sigspoof is nowhere nearly as dangerous as other stuff people routinely use. compare to stock "draw over other apps" permission. or in the non-stock world, compare to root. sigspoof is kids play compared to those things.

- a regular per-app runtime permission, as first implemented by marvin, might be a bit too dangerous for your taste and i can relate to that. then simply add a global enable. the global enable could be:

  - a toggle in the developer menu, as i proposed before. is this really reckless? i do not agree, but i still see your point. then an option would be...
  - an "addonspoof" flashable toggle, a la addonsu. the simple existence of a file could be the toggle. the file could be in /data or /system. (and if it is on /system you would need to provide an addonspoof zip that survives flashes via the addon mechanism, just as you propose doing with signature whitelisting, only easier to implement.)

> this fork is not about adding signature spoofing, it’s about using μG hassle-free.

this fork is not supposed to add anything besides microG. but the point is that sigspoof **is being added** already to support microG, and added in the wrong way IMHO.

_(the following is based on my understanding of the current state of L4M. apks in priv-app might require special signatures, but i am not aware of that.)_

i will go the other way around and show you the damage you are doing to your users by adding sigspoof the wrong way.

note that this is not applicable to LOS. if you need sigspoof in LOS you would use some solution like my Haystack, and you would not be exposed to this danger. this is exclusively a danger of adding sigspoof the wrong way.

if users want to run a sigspoof app in LOS they cannot. in L4M, same thing. but contrary to LOS, L4M is dangerous because there is a loophole. you say users are fools and will be tricked -phished- into ticking the sigspoof enable option, so they cannot have an option. well maybe some would, but check out the alternative: **instead of ticking an option, users will be told to flash the app in priv-app to gain sigspoof; and suddenly the rouge app will be all powerful.** so tell me how this hand-holding is not hurting your users.

in your proposed L4M, your users could flash the whitelist instead and avert this risk. but...

most people cannot be bothered with signatures and they will just cheat. most developers tinkering with 3rd party apps will be lazy and just install an old version in /system then update in /data while debugging and be done with it, thinking that the app will not notice its elevated privileges and will not do undue harm. why tempt your users to take this route? when it is time to publish their hack, they could just flash it to priv-app in user's phones too.

on the other hand, your proposal could work for responsible hack publishers that do the proper whitelist work. but really, do you want your users to trust their obscure whitelist zip and flash it? why force your users to such a horrible trust relationship with the unknown?

you might not care about opening sigspoof, but you should still care about not adding sigspoof in a way that encourages dangerous practices.

please consider providing a safe way to open sigspoof instead of the dangerous loophole you have now. any sane way to open sigspoof **must not** include flashing an untrusted zip.

**Comment by rugk** [comment]
@corna your plan sounds good. As @ArchangeGabriel correctly says, maybe the aim of this fork really is not to enable signspoof, but rather enable **microG**. That microG needs it, is just a coincidence.
In other words: If we could enable microG without sigspoof, I would really advocate to do so and drop all that signature spoofing.
However, once we have it now, I do not strongly have something against enabling it for other apps, too – if it is done securely.

Also the target audience is _not_ a more technical one than LineageOS (people also flash LineageOS and give the device away to others), just people who don't want to use Google stuff. So in any case you need to keep phishing and stuff in mind. And yes, even technical people can get tricked or so.
That said; I think an UI option, which is sufficiently hard (or has enough warnings) may be okay, too.

However the certificate way is also a nice idea. If they can be provided as XML files or so and do not need a flashable ZIP, one could just use `adb root` and some commands and add it to the device. This is a step, that can be explained by anyone, who really wants that feature for their app.
In such a case one would not have to tangle with some "black-box ZIP"… :wink: 

Also, BTW, nobody has told me for now, how dangerous signature spoofing now really is. Someone said, they cannot take over permissions of other apps. So what is the risk, then?

So as said, I personally do not need that feature. I doubt many people need it. It is not strictly a goal/part of LineageOS4microG, but I understand the desire to put it in here. Just nobody wants feature creep… :wink:

**Comment by nExXxuS** [comment]
>  It is not strictly a goal/part of LineageOS4microG, but I understand the desire to put it in here. 

If everybody is fine with that statement i'd like to close that issue. Feel free to raise you finger now or be quite forever :-)

**Comment by Lanchon** [comment]
i'm the OP. of course i'm not fine with that statement. a feature that is useful enough to require implementation will not be kept under control of others in my computing devices. this fork does exactly that: introduces a feature, then forbids *ME*, the owner of the device, to use it. this is wrong and insulting, and doesn't pass my ethical software requirements. i've chosen not to use this fork over this issue. after saying that, it follows that i don't care what the project does with this defect report. keep it open or close it as won't fix, whatever; just don't mark it as solved because it isn't.

i did my part, i raised the issue. this is mostly a political issue btw, it shows the mindset of the project: "our users are stupid and cannot be trusted with important things. educating (warnings and stuff) is not an option, we need to remove freedom from them so that they don't shoot themselves in the foot. and this all jibes with our ethics." for me this works as a predictor of outcomes of future similar conundrums, and is a strong signal to avoid this fork. i've much respect for @corna, a man who has worked to free us all from intel's stronghold, and i'm dismayed to find out he'll back using comparable tactics when on the other side of the fence. (and yes, i know the severity of these issues is absolutely different: the simple workaround -avoiding this fork- doesn't have a real cost-effective parallel in intel's case.)

**Comment by rugk** [comment]
I don't agree with that and could now defend this awesome project, but actually better agree to disagree. As it seems this case is closed here and no one seems to feel the need to discuss it any further. 😃

**Comment by Lanchon** [comment]
speak for yourself, man.

**Comment by futuretoast** [comment]
Just gonna add to this. As @ArchangeGabriel has said the purpose of this rom is to enable microg usage hassle-free. @Lanchon is proposing to expand the sig-spoof patch to be able to be applied to all apps under the premise of computer freedom. Now imho expanding sig-spoofing beyond what is needed for microg to function is beyond the scope of this project. For that matter this fork only exists because lineage wouldn't parch in sig-spoofing, thus preventing microg from working. Consequently this fork is an exact replica of lineage with only the exceptions of what is needed for microg functionality.

As this issue was opened under the premise of having the freedom to do as you please with your own device the easy resolution there is to use the docker image to build it yourself with the SIGNATURE_SPOOFING option set to yes instead of restricted. I believe that solution should resolve @Lanchon 's problem without causing the project to move beyond its own scope

**Comment by spolack** [comment]
If you require SignatureSpoofing unrestricted, please run your own builds. The aim of LineageOS for microG is mainly to provide most secure and simple microG integration.

**Comment by Lanchon** [comment]
yes i had to, ages ago.
