### ISSUE TITLE
Missing network traffic monitor in Mata

### ISSUE THREAD

**Issue by smac89** [lineageos4microg/docker-lineage-cicd#110]
Not sure about others, but on my essential Ph-1 mata, lineageos network traffic monitor is missing.

It should be under the section for `Status bar`, but it is completely missing.

![netowork](https://user-images.githubusercontent.com/8305511/93858167-41193680-fcab-11ea-88d0-d7cae01385d1.gif)

**Comment by gxtu** [comment]
That's a notched device, right?

>StatusBarSettings: Hide network traffic settings if device has a notch
>* Now a must, since the view is horizontally centered.

\- https://review.lineageos.org/c/LineageOS/android_packages_apps_LineageParts/+/238702

**Comment by smac89** [comment]
> That's a notched device, right?
> 
> > StatusBarSettings: Hide network traffic settings if device has a notch
> > 
> > * Now a must, since the view is horizontally centered.
> 
> - https://review.lineageos.org/c/LineageOS/android_packages_apps_LineageParts/+/238702

Indeed it is notched, and thanks for clarifying this
