### ISSUE TITLE
Have not recieved any new builds for Mata since August 26th

### ISSUE THREAD

**Issue by smac89** [lineageos4microg/docker-lineage-cicd#111]
Related to #89

But I just wanted to point out that Mata has really been lacking in updates. Since I started running this ROM, I've only recieved 2 updates in the course of over 9 months.

This is a stark contrast to the promise of weekly updates, as outlined on the home page.

**Comment by jw243** [comment]
It seems that most builds have not seen an update in September, yet.

Have you changed the update cycle? For me, it would be OK if updates didn't appear every week, but I would appreciate monthly updates that include the newest android security patch.

I am looking for builds for **z3**, **payton** and **gts28vewifi**.

In addition, I would be extremely happy, if builds for **flo** could be included. There are weekly inofficial builds on this site, but unfortunately, they don't include microg:

[https://lineageos.wickenberg.nu/flo/](url)

Thanks for your effort!

**Comment by smac89** [comment]
After opening this issue, I saw an update about 2 days later. Not sure if that was due to this issue, but I'm grateful nonetheless.

Please keep those updates coming.

Thank you!
