### ISSUE TITLE
Missing davinci and ginko device builds

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [lineageos4microg/docker-lineage-cicd#113]
I hope this is the right area to ask friendly for two fresh micro-g-LOS build.
https://download.lineageos.org/davinci
https://download.lineageos.org/ginkgo

Did not understand the wiki 100%. How often did the builds are made? Monthly? Random?

I will thank all persons who contribute to this! ❤️

**Comment by heretoenhance** [comment]
klte* and hlte* builds for 17.1 are now available too.

There needs to be a clarification on release schedule, why has it slowed down from weekly OTA? And if it is a permanent change the website should be updated with the new schedule.

I am really thankful for this project too, keep it up guys!

**Comment by sorryusernameisalreadytaken** [comment]
Both availible now. THX
https://download.lineage.microg.org/ginkgo/
https://download.lineage.microg.org/davinci/
