### ISSUE TITLE
Don't include Sim Tool kit into builds

### ISSUE THREAD

**Issue by jlHertel** [lineageos4microg/docker-lineage-cicd#114]
The [Sim Tool Kit application or STK][1] is a way for carriers to provide "value-added" services to customers. In my experience this usually translates to inconvenient pop-ups asking to subscribe to some random service.
By default we are embedding the STK in all our builds as a root application, making it hard to remove (actually you need to disable/remove it after each update).

Given that the focus of this project is more privacy it makes sense to avoid such potentially bad-behaving application to be included.
It would be nice to have an option to easily disable it, or to don't include it in the builds at all.
The package name is: `com.android.stk`.

[1]: https://en.wikipedia.org/wiki/SIM_Application_Toolkit

**Comment by spolack** [comment]
Altough i personally agree with you thats beyond the scope of this project. Please report to upstream in order to fix that privacy issue.

Best
