### ISSUE TITLE
Please provide the used commandline

### ISSUE THREAD

**Issue by eike-fokken** [lineageos4microg/docker-lineage-cicd#115]
The Readme currently does not contain a commandline for lineage17.1
Could someone please provide it?

Last time I tried to build lineage4microg I failed and got only into a bootloop. I would like to build my own to have more frequent updates. If someone is interested I might setup a server that is publically available solely for sailfish builds. But no promises on that one for now.
I would especially like to build with fdroid privileged extension and with only system apps being able to spoof signatures.
In essence I would like to build the same os as I also get from lineage.microg.org.

Also pointers on replacing my current lineageos4microg (signed with keys I don't have obviously) without having to wipe data would be very welcome!

**Comment by bananer** [comment]
The commands listed in the readme work for me by just replacing `16.0` with ` 17.1`

As for the signing key changing, I think if you flash with TWRP it will allow you to ignore the mismatching keys. Otherwise you might need to build your own migration zip like the ones for migrating from lineageos to lineageos4microg. https://download.lineage.microg.org/extra/

**Comment by eike-fokken** [comment]
Oh, good to know. Do I need something else, like extra third-party package urls?
I'll try the twrp way, thanks!
Could you, for reference post your complete commandline, with which you build?

**Comment by bananer** [comment]
Here's what I did to build for `river`:

```
docker volume create lineageos_src
docker volume create lineageos_zips
docker volume create lineageos_logs
docker volume create lineageos_ccache
docker volume create lineageos_mirror
docker volume create lineageos_keys
docker volume create lineageos_local_manifests
```

put your `custom_packages.xml` into `/var/lib/docker/volumes/lineageos_local_manifests/_data/`

then run the build:
```
docker run -it -e BRANCH_NAME=lineage-17.1 -e DEVICE_LIST=river -e LOCAL_MIRROR=true -e SIGNATURE_SPOOFING=yes -e SIGN_BUILDS=true -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps FDroid FDroidPrivilegedExtension additional_repos.xml" -e "RELEASE_TYPE=BANANER" -v "lineageos_src:/srv/src" -v "lineageos_zips:/srv/zips" -v "lineageos_logs:/srv/logs" -v "lineageos_ccache:/srv/ccache" -v "lineageos_mirror:/srv/mirror" -v "lineageos_keys:/srv/keys" -v "lineageos_local_manifests:/srv/local_manifests" --memory="14g" --cpus="3.7" lineageos4microg/docker-lineage-cicd
```

**Comment by eike-fokken** [comment]
Thanks, I'll give it a try!

**Comment by bananer** [comment]
@eike-fokken I've created a pull request to update the example. You might want to close this issue.

**Comment by eike-fokken** [comment]
Oh, sorry, should have done so with my last comment. Thank you!
