### ISSUE TITLE
Update microG version to include contact tracing/COVID-19 compatibility

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/docker-lineage-cicd#119]
[v0.2.12.203315](https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.12.203315) of microG adds support for the exposure notification API (for Corona/COVID-19 tracking) of Google, so people can use their national health service apps.

I'm not sure whether this is already included in the current builds of LineageOS4microG. If not, it would really be a good thing (and needed) to include it. :slightly_smiling_face:

**Comment by gxtu** [comment]
It was updated over a month ago... See https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/commit/02df76ef155aef2cca501b44e466932d391a9a3f

**Comment by rugk** [comment]
Awesome! :tada:

**Comment by tlaurion** [comment]
@rugk @gxtu : possibility to opt out from microg? Enabled by default?

**Comment by gxtu** [comment]
@tlaurion Not, it's not enabled by default. It's also just an API, so it doesn't do anything unless you actually have a corona tracing app installed. That said, using it is completely harmless from a privacy perspective, so you should definitely consider installing a corona tracing app.

**Comment by ArchangeGabriel** [comment]
> That said, using it is completely harmless from a privacy perspective

That’s false. They are issues, so claiming “completely harmless” is a bit bold (e.g., it is possible to know whether someone in particular did get the coronavirus or not once they entered it into the app —whether or not that is an issue for you is subjective of course).
