### ISSUE TITLE
OTA Doesn't work

### ISSUE THREAD

**Issue by As4fN1v** [lineageos4microg/docker-lineage-cicd#12]
Hello. Since April 10, every time I check for updates I get:

 "The update check failed. Please check your internet connection and try again later." 

The newest build shows the same error. It's probably something on the server side.

Device: Xiaomi Mi 5s (capricorn)

Thanks.

**Comment by corna** [comment]
The LineageOS developers have broken the updater of every unofficial build by changing the updater properties (both on [15.1](https://review.lineageos.org/#/c/LineageOS/android_packages_apps_Updater/+/210569/) and [14.1](https://review.lineageos.org/#/c/LineageOS/android_packages_apps_Updater/+/211247/)). We'll fix the issue soon, however a manual update in recovery is needed.

**Comment by nExXxuS** [comment]
The issue is fixed, today we're spinning up new builds with fixed OTA. Expect them during that week.
