### ISSUE TITLE
Integrate microG Services Core 0.2.13.x to make the German Corona app work properly

### ISSUE THREAD

**Issue by generalmanager** [lineageos4microg/docker-lineage-cicd#123]
I was a bit surprised to see that the latest builds didn't contain the current stable com.google.android.gms build, which is necessary to run the German Corona app without getting this error message:
"Something went wrong. Error during communication with Google Interface (8)"

I'm on lineage-17.1-20201107-microG and tried updating via F-Droid but that's not possible as the repo doesn't show any updates even after removing and readding it.
Could be related to it having the same identifier as the UnifiedNLP, but I don't really think so.
https://github.com/microg/android_packages_apps_GmsCore/issues/424
https://gitlab.com/fdroid/fdroidclient/-/issues/1904

Anyhow it would be great to include the GMS core builds into the updates so one doesn't have to sideload system apks.

Edit: I was able to install 0.2.13 by enabling "unstable" updates in the advanced f-droid settings. It still makes sense to ship the current stable releases via OTA imo as the current situation isn't ideal for less technically enclined users who are wondering why one of the most important apps at this time doesn't work and constantly throws error messages.

**Comment by spolack** [comment]
I'm not sure why 0.2.13 didnt make it into the image. The build infrastructure really needs an overhaul, but i'm currently too busy. 

https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/commit/db0ca9506be038752870a8e497cbc6646fa56d9e

**Comment by spolack** [comment]
Please reopen if this issue still occurs.
