### ISSUE TITLE
tissot (Xiaomi Mi A1) does not install via TWRP

### ISSUE THREAD

**Issue by pajot** [lineageos4microg/docker-lineage-cicd#124]
I have tried to do a "clean install" of lineage-17.1-20201016-microG-tissot.zip according to the directions on the [LineageOS for microG website](https://lineage.microg.org/):

> Clean install (wipe data and installed apps)
> 
> If you don't care about losing your current data just reboot into recovery, wipe System, Data, Cache and Dalvik and, without rebooting, install LineageOS for microG.

After doing this, TWRP reports "No OS installed!" If I reboot, I end up in recovery mode.

I have tried the "dirty install" approach:
> Finally download the migration ZIP and a build of LineageOS for microG (make sure the ZIP you're installing is newer than the current installed ROM, if it is not, wait for the next build), reboot in recovery, install the migration ZIP and, without rebooting, install LineageOS for microG.

First, I install LineageOS (specifically `lineage-17.1-20201013-nightly-tissot-signed.zip`) to slot A, then test this by setting the active slot to a and rebooting. This works. Then I reboot to bootloader and do `fastboot boot twrp-3.4.0-0-tissot.img`. After rebooting to TWRP, I set the active slot to B (because TWRP installs to the inactive slot) and install the migration keys using the Install function of TWRP and then install `lineage-17.1-20201016-microG-tissot.zip` immediately following, as per instructions.

After doing this, LineageOS will boot, but when it launches services, everything fails. The phone has booted, but it is unusable. Possible reason: Although the migration keys are installed, the LineageOS for microG installation is not completing (hence the message "no OS installed!" when trying to do a "clean install"). Because the keys don't match and we are still running pure LineageOS, nothing runs.

A further note: no version of LineageOS (with or without microG) will boot from slot B.

**Comment by spolack** [comment]
With #134 fixed we ship recovery images. Please test once the next build including recovery image is pushed.

**Comment by pajot** [comment]
Flashing stock LineageOS to slot B still doesn't work.

What procedure should I follow exactly to test the microG builds?

**Comment by pajot** [comment]
Performing

`fastboot boot lineage-17.1-20210909-microG-tissot-recovery.img`

does not work. The system boots normally into the last active slot. If it's a, it boots to the old image. If it's b, it enters a bootloop.

**Comment by petefoth** [comment]
Is this still a problem for you with recent builds? If not, I will close the issue (or you can do it yourself)
Assigning back to you for comment

**Comment by pajot** [comment]
I don't know, I'm still running an ancient build (OTA updates don't work either!) and I haven't dared try since all these attempts in 2020 and 2021. The phone is in desperate need of an update, and I could test it then, but I need to arrange a couple of days to do it. I was planning the third week in August. Can this hold until then?

**Comment by petefoth** [comment]
Thanks. No problem. I'm just working through old issues to see if we still need to do anything. I'm happy to leave it with you, until you have time to look again. There's no rush

**Comment by vanMacG** [comment]
On a friends device, I also struggled hard with twrp on this device. I think I read on xda that only older versions of twrp work... We ended up using offical LOS recovery and images, that worked.

**Comment by vanMacG** [comment]
> And you still got microG to work? Can you elaborate?

No, after hours of time to even get a working recovery we ended up using official LOS without microg.
We strictly followed the LOS-wiki page, although this was different than I used to do it on other devices (and with twrp). In the end, it worked that way. So if you follow the official guide but use instead recovery and image from los4microg I think you have good chances to get it work.

> Because I had similar problems with the LOS recovery and images. I tried a lot of different combinations and was never able to get OTA updates working. I found it very frustrating. The Xiaomi Mi A1 is only marginally friendly to non-stock ROM (you can't lock the device if you're running non-stock, for example).

OTA updates are working.

> But it's such a good device overall that the extra effort is just enough to be worth it.
I also got very positive feedback from my friend. Only thing that is not working bulletproof is the status LED.

**Comment by petefoth** [comment]
From these comments, it seems that 
- following [LOS installation instructions](https://wiki.lineageos.org/devices/tissot/install) and using their recovery - `boot.img` from [here](https://download.lineageos.org/devices/tissot/builds) or ours  from [here](https://download.lineage.microg.org/tissot/) should work
- OTA updates are working

Working with TWRP - desirable though it may be - is out of scope for this project.

Given all that, I'm closing this issue. If installing using our recovery fails then please raise a new issue
