### ISSUE TITLE
17.1 for cheeseburger

### ISSUE THREAD

**Issue by leo-lb** [lineageos4microg/docker-lineage-cicd#126]
Lineage OS upstream has 17.1 since a little while: https://download.lineageos.org/cheeseburger

However, Lineage OS for MicroG does not: https://download.lineage.microg.org/cheeseburger/

What can I do to help and make it happen?

Thank you

**Comment by ArchangeGabriel** [comment]
Duplicate of https://github.com/lineageos4microg/l4m_website/issues/61.

Device get updated when some maintainer has the time to review and enable them.

**Comment by leo-lb** [comment]
@ArchangeGabriel Thank you, how can we become that maintainer? :-) I have good enough skills in pretty much every topic from development to sysadmin to handle such things.

**Comment by leo-lb** [comment]
It is now available! Closing
