### ISSUE TITLE
Update to LineageOS 18.1 Branch

### ISSUE THREAD

**Issue by Scrumplex** [lineageos4microg/docker-lineage-cicd#129]
The first devices were promoted to 18.1 in upstream today. (See [Gerrit](https://review.lineageos.org/c/LineageOS/hudson/+/292619))

See [announcement on Reddit](https://www.reddit.com/r/LineageOS/comments/kdkb0y/lineageos_181_in_the_tubes/)

Notably
```
cheeseburger userdebug lineage-18.1 W
discovery userdebug lineage-18.1 W
dumpling userdebug lineage-18.1 W
gemini userdebug lineage-18.1 W
gts4lv userdebug lineage-18.1 W
gts4lvwifi userdebug lineage-18.1 W
h830 userdebug lineage-18.1 W
h850 userdebug lineage-18.1 W
h910 userdebug lineage-18.1 W
h918 userdebug lineage-18.1 W
h990 userdebug lineage-18.1 W
kirin userdebug lineage-18.1 W
lithium userdebug lineage-18.1 W
ls997 userdebug lineage-18.1 W
mermaid userdebug lineage-18.1 W
natrium userdebug lineage-18.1 W
pioneer userdebug lineage-18.1 W
PL2 userdebug lineage-18.1 W
rs988 userdebug lineage-18.1 W
scorpio userdebug lineage-18.1 W
us996 userdebug lineage-18.1 W
voyager userdebug lineage-18.1 W
vs995 userdebug lineage-18.1 W
```

I hope there is a device these builds can be tested against (personally I own a OP5 `cheeseburger`, so I am in luck).

**Comment by kurt-by** [comment]
That's no announcement. That's just a fanboy publishing a preliminary list and getting criticised by lineage director for doing so.

**Comment by spolack** [comment]
wontfix, 18.1 is not stable yet.

**Comment by kurt-by** [comment]
One Main issue with 18.1 is the availability of GApps. Lineage4microG would be a fine workaround

**Comment by spolack** [comment]
Is there any official 18.1 build available yet?

**Comment by ArchangeGabriel** [comment]
No (you can see that nothing has been merged yet [here](https://review.lineageos.org/q/topic:%2522eighteen%2522)), but as @kurt-by said this might be due to unavailability of GApps for Android 11.

However I understand that due to how LOS4μG works, this means that no 18.1 build can happen as long as LOS upstream don’t make their official first.

**Comment by kurt-by** [comment]
Kevin Haggerty already ships quite complete 18.1 for klte and similar
https://forum.xda-developers.com/t/rom-unofficial-11-lineageos-18-1-for-samsung-galaxy-s5-klte.4209545/

**Comment by ArchangeGabriel** [comment]
Those are unofficial builds. They are plenty of others, generally advising NikGApps.

This project cares about official LOS builds, while LOS likely cares about OpenGApps.
