### ISSUE TITLE
Wrong handling of for loops in build/envsetup.sh and other scripts

### ISSUE THREAD

**Issue by gerion0** [lineageos4microg/docker-lineage-cicd#13]
I tried to build an image with the scripts provided in src and frequently get an error in build/envsetup.sh

After some debugging, I saw that IFS is set in [build.sh](../blob/master/src/build.sh#L20) and applies to all included shell scripts. I guess, this setting is done for [this loop](../blob/master/src/build.sh#L249), but also has the result that all other for loops are broken.

Please modify IFS only for the one for loop.

**Comment by corna** [comment]
They seem to be harmless errors, however you're right, I forgot that envsetup is sourced and not executed in a new shell, thanks for noticing.

Can you test with corna/docker-lineage-cicd@72cdc6ca38767adc100ab840470531515fb97f38?
