### ISSUE TITLE
Where to get the build.prop file after build finished?

### ISSUE THREAD

**Issue by MartiniMoe** [lineageos4microg/docker-lineage-cicd#133]
Hi all and thanks for this amazing build container! It works really nice! :)
The only problem I am facing is that I cannot find the build.prop file after build. The LineageOS OTA Server strongly recommends providing the file together with the built ZIPs.

Can you please give me a hint where to find them? Thanks!

**Comment by bxgaillard** [comment]
The file is located here: src/LINEAGE_${version}/out/target/product/${device}/system/build.prop
Of course you have to replace ${version} and ${device} by the appropriate values.
Maybe the build script could/should be updated to copy this file to the output directory as well?

**Comment by bananer** [comment]
PR #152

**Comment by bananer** [comment]
Implemented with #152 

See #153 for documentation
