### ISSUE TITLE
provide recovery images

### ISSUE THREAD

**Issue by thrillfall** [lineageos4microg/docker-lineage-cicd#134]
There are some devices where one cannot use TWRP as recovery to flash lineageos4microg like sargo (pixel 3A). 
There is one solution described [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/105#issuecomment-700635488) how to use an official lineageos recovery and exchange keys to enable flashing a lineageos4micro. These manual steps would not be needed (also the many hours of fruitless online search to find this solution)

It would really help if the recovery images (boot.img) including the specific keys would already be provided per devices

**Comment by spolack** [comment]
Please provide a PR and i'm willing to incorporate the changes. Unfortunately i'm quite busy with daywork, so i cant look into this from bottom up.

**Comment by thrillfall** [comment]
gladly. which repository deals with exposing build artifacts to the download page?

**Comment by spolack** [comment]
Its not yet in a repository. We make use of a post-build userscript, which rsyncs the artifacts to server. I can easiely include other files on the transfer.

**Comment by thrillfall** [comment]
the file is called boot.img

**Comment by spolack** [comment]
> the file is called boot.img

Please also include the build date in order to maintain different versions. Similar to official naming.

**Comment by thrillfall** [comment]
i am confused. How can i modify that script if i cant access it?

**Comment by spolack** [comment]
Before the artifacts can be synced to the download server they need to moved to the OUT directory.

https://github.com/lineageos4microg/docker-lineage-cicd/blob/30405bb940bf77d15027aa775a530af640d104a9/src/build.sh#L297

**Comment by kurt-by** [comment]
@spolack installed recovery image via twrp on my one plus one bacon. Now each time I boot into recovery, lineageOS system starts.

**Comment by spolack** [comment]
> @spolack installed recovery image via twrp on my one plus one bacon. Now each time I boot into recovery, lineageOS system starts.

Please file an issue if you are confident this doesnt happens with official LineageOS recovery.

**Comment by JuniorJPDJ** [comment]
@kurt-by that's probably because you have A-only device, where boot and recovery are separate partitions.
It would be good to take that in account when copying images, as some devices should produce recovery.img, and you guys are always copying boot.img as recovery image.

**Comment by thrillfall** [comment]
@JuniorJPDJ so what do suggest? what file(s) should we expose?
if there are both files generated (boot.img and recovery.img) expose only recovery.img. And if only boot.img is generated (as for sargo for example) we should expose that (as recovery.img)?

**Comment by JuniorJPDJ** [comment]
That seems like a good solution @thrillfall !

**Comment by thrillfall** [comment]
@spolack i'll provide a PR for dynamic recovery image exposition during next week.
Are we sure about the created files and filenames? Its either only boot.img or recovery.img and boot.img, right? @JuniorJPDJ
