### ISSUE TITLE
Request for a new build for device ginkgo

### ISSUE THREAD

**Issue by kvelakur** [lineageos4microg/docker-lineage-cicd#137]
Hello maintainers. Thanks for this project. 

Can we get a new build for ginkgo? 

As of now, latest microG LOS build is from 2020-12-04 (https://download.lineage.microg.org/ginkgo/).
LOS is at 2021-01-11 (https://download.lineageos.org/ginkgo)

There seems so be some issues with the sound in the build I'm running, hoping the new build solves it. Thanks again for this project!

**Comment by ArchangeGabriel** [comment]
More generally they are a lot of devices with “old” builds. For instance I’m interested in FP3, the latest build is also from early December (and appears to be monthly) and for 16.0, while upstream moved to 17.1.

@ncorna once said that the list of devices to build for were retrieved automatically from hudson and tried in order, but it seems to me that something is stuck somewhere?

**Comment by kvelakur** [comment]
Hi @spolack, your fix doesn't seem to have fixed the build for ginkgo. Could we reopen this issue and take a second look?

**Comment by Bydgew7** [comment]
@spolack, please reopen, ginkgo still missing

**Comment by Bydgew7** [comment]
@spolack, please reopen, ginkgo missing again
