### ISSUE TITLE
LineageOS 18.1 support

### ISSUE THREAD

**Issue by spolack** [lineageos4microg/docker-lineage-cicd#139]
18.1 is upcoming. We might want to adopt the build script and patch to that :-)

**Comment by bananer** [comment]
Trying to figure out what needs to be done:

* Wait for LineageOS upstream to be ready. Some progress can be followed [on gerrit](https://review.lineageos.org/q/topic:%2522eighteen%2522) but I don't know exactly what we should look out for.
* in [build.sh](https://github.com/lineageos4microg/docker-lineage-cicd/blob/3792a9d3b27cafc05c4827cce5228afb7a2e6977/src/build.sh#L87) there is some configuration conditional on the branch, expand that for `lineage-18.1`
  * `themuppets_branch` - looking throug [their repositories](https://github.com/TheMuppets) the correct value should be `lineage-18.1`
  * `android_version` - most likely `11`
  * `patch_name` - the [signature spoofing patch](https://github.com/lineageos4microg/docker-lineage-cicd/tree/master/src/signature_spoofing_patches) needs to be created. Since it was unchanged for the last couple of versions, maybe just making a copy will work for `R` 

Anything else I'm missing?

I'm used to building my own ROMs using this project and know my way around Docker. My device `river` seems to be getting official 18.1 support from LineageOS, so I'm willing to help as good as I can.

**Comment by spolack** [comment]
I think you cover everything. Very appreciated that someones tacking care of it!

**Comment by odlg** [comment]
There is an other patch here that might be better: https://github.com/microg/GmsCore/pull/1222

**Comment by kurt-by** [comment]
Here is another patch
https://github.com/ProtonAOSP/android_frameworks_base/commit/67d661ce0253b099255eef2690f1437df41a8094
https://github.com/ProtonAOSP/android_packages_apps_PermissionController/commit/f7a946c37afe83e57cea03ccd00086ccba2dbdb5

The trigger for official 18.1 are merged commits in Hudson

**Comment by bananer** [comment]
Thanks for all the help!

Work in progress: https://github.com/bananer/docker-lineage-cicd/commits/lineage-18.1

A first build for `river` completed successfully, though I did not dare to run it on a device yet.

The spoofing patches failed to apply, it seems there are some changes in the relevant [PackageManagerService.java`](https://github.com/LineageOS/android_frameworks_base/blob/lineage-18.1/services/core/java/com/android/server/pm/PackageManagerService.java) method by LineageOS ontop of AOSP. It's a 25k lines monstrosity so I could not easily figure out the origin of these changes but I think I might be able to adjust the patches anyways.

The patches provided by @odlg and @kurt-by als contain some changes in `packages/apps/PermissionController`, which is outside of  the `android/frameworks/base` directory covered by the  [existing patch mechanism in `build.sh`](https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L171-L189).

Going to try to get the patches working and start another build soon.

**Comment by bananer** [comment]
There is no 18.1 version yet for this file: https://gitlab.com/the-muppets/manifest/-/blob/lineage-17.1/muppets.xml

It causes an error message during the build but it seems to be only relevant for xiaomi devices. Manifest for other vendors is pulled from GitHub: https://github.com/TheMuppets/manifests/blob/lineage-18.1/muppets.xml

**Comment by a-huk** [comment]
Sorry to pile up, but what is the status on los18, can we build it?

**Comment by bananer** [comment]
@a-huk if your device is in either this list of [additions](https://review.lineageos.org/c/LineageOS/hudson/+/300920) or [promotions](https://review.lineageos.org/c/LineageOS/hudson/+/292619) you should have good chances of getting a usable build when using [my branch](https://github.com/lineageos4microg/docker-lineage-cicd/pull/148) for your docker image.

**Comment by a-huk** [comment]
> @a-huk if your device is in either this list of [additions](https://review.lineageos.org/c/LineageOS/hudson/+/300920) or [promotions](https://review.lineageos.org/c/LineageOS/hudson/+/292619) you should have good chances of getting a usable build when using [my branch](https://github.com/lineageos4microg/docker-lineage-cicd/pull/148) for your docker image.

Thanks, my device is not on any lists, but I have unnoficial normal los18 builds. So it should probably work.

**Comment by kurt-by** [comment]
@bananer official tries without success up till now. I can test bacon, if that helps
https://buildkite.com/lineageos/android/builds?branch=lineage-18.1

**Comment by angarod** [comment]
I tried to build lineageos 18.1 for herolte but this Docker image raise this error 
`clang: error: unable to execute command: Executable "ld" doesn't exist!
`

**Comment by bananer** [comment]
@angarod could you explain the exact steps to reproduce?

**Comment by kurt-by** [comment]
Merged
https://review.lineageos.org/292619

**Comment by spolack** [comment]
Huge thanks to @bananer for his work on 18.1 support. First build has finished. https://download.lineage.microg.org/bacon/

@ all
Please test ASAP, so i could withdraw the builds if broken.

**Comment by kurt-by** [comment]
@spolack bacon with twrp 3.4.0-0 wiped and formatted. Your build boots. MicroG all selfcheck boxes checked. NLP works. Fdroid OK. Installs without addition confirmation.

**Comment by radhta** [comment]
dumpling seems fine

**Comment by bigCrash** [comment]
h850 dirty flash from lineage4microg 17.1 build works like a charm.

**Comment by spolack** [comment]
Great!

**Comment by SpaceAgeHero** [comment]
polaris dirty flash from lineage4microg 17.1 worked well too!
Auto brightness seems messy though. Can anyone confirm?

**Comment by uok** [comment]
Looking for v18.1 for jasmine_sprout and can help testing

**Comment by steadfasterX** [comment]
> > I tried to build lineageos 18.1 for herolte but this Docker image raise this error
> > `clang: error: unable to execute command: Executable "ld" doesn't exist! `
> 
> I am glad that I am not the only one! You might want to try these changes: [LineageOS/android_kernel_samsung_universal8890#4](https://github.com/LineageOS/android_kernel_samsung_universal8890/pull/4) They seemed to work for me, otherwise the first dirty patch that I used was adding /usr/bin to the PATH variable right before [this line](https://github.com/LineageOS/android_kernel_samsung_universal8890/blob/f931028fef97776cf6edf0a22c5be6fb6f7ad5ea/scripts/fips_kaslr_crypto_hmac.sh#L256).

u saved my day!
