### ISSUE TITLE
Please provide information on using builds with custom keys

### ISSUE THREAD

**Issue by r-vit** [lineageos4microg/docker-lineage-cicd#142]
I successfully built image for the dumpling device and was able to upload it. One problem, though - during the flashing the bootloader complained about being unable to verify keys or something like that.
Before flashing my build I used the only 17.1 microg build available and I guess it installed the bootloader with the original MicroG keys. So, I suppose now I need to replace the MicroG keys with mine, but I have no idea how to do that. I would really appreciate the instruction. Thanks!

**Comment by thrillfall** [comment]
see the FAQ here https://lineage.microg.org/
```I am running a custom build of LineageOS, but yours is way cooler! How can I migrate to it without losing my data?
Replace the LineageOS official keys in our migration ZIP with your keys (or follow the suggestions in the LineageOS migration guide).```

**Comment by r-vit** [comment]
Thank you, I read that document, but unfortunately I couldn't find the explanation which keys should I put where. I've got a folder named 'keys' with the following files:
```
@cyngn-app.pk8          
@cyngn-app.x509.pem     
@cyngn-priv-app.pk8     
@cyngn-priv-app.x509.pem
 media.pk8              
 media.x509.pem         
 networkstack.pk8       
 networkstack.x509.pem  
 platform.pk8           
 platform.x509.pem      
 releasekey.pk8         
 releasekey.x509.pem    
 shared.pk8             
 shared.x509.pem        
@testkey.pk8            
@testkey.x509.pem    
```   
When I checked the key migration script I saw these lines:
```
media_cert_official='308203b3...
platform_cert_official='30820...
shared_cert_official='308203b...
official_cert='308203b3308202...
                             
media_key_official='MIIBIjANB...
platform_key_official='MIIBIj...
shared_key_official='MIIBIjAN...
official_key='MIIBIjANBgkqhki...
                             
media_cert_release="3082034e3...
platform_cert_release="308203...
shared_cert_release="3082034e...
release_cert="3082034e3082023...
                             
media_key_release="MIIBIjANBg...
platform_key_release="MIIBIjA...
shared_key_release="MIIBIjANB...
release_key="MIIBIjANBgkqhkiG...
```

And now I'm confused - how do the files in the 'keys' folder correspond to these lines

**Comment by Findus23** [comment]
Hi,

You can check the official lineageos docs for an explanation on this:
https://wiki.lineageos.org/signing_builds.html

And check the scripts in https://github.com/LineageOS/scripts/tree/master/key-migration
for how to format the keys in the correct format.

**Comment by r-vit** [comment]
I will, thank you

**Comment by spolack** [comment]
I'm willing to accept PRs on this, although i dont consider this to be an issue.
