### ISSUE TITLE
MotoX4-Payton affected by known persist sehash issue

### ISSUE THREAD

**Issue by braveheart777** [lineageos4microg/docker-lineage-cicd#149]
Please see issue located here: https://gitlab.com/LineageOS/issues/android/-/issues/2854#note_487024510

**Comment by braveheart777** [comment]
To clarify, it's basically a boot loop issue.

**Comment by spolack** [comment]
Next build round has been started.

**Comment by petefoth** [comment]
Closing. Please re-open if there is a problem with the latest builds at https://download.lineage.microg.org/payton/
