### ISSUE TITLE
"Signature spoofing" does not show up in system settings

### ISSUE THREAD

**Issue by zilti** [lineageos4microg/docker-lineage-cicd#15]
I've installed LineageOS for microG on my FP2 with the link from your wiki. But when I go to Settings - Apps - Advanced - App Permissions, there is no signature spoofing - nor anywhere else for that matter.

**Comment by corna** [comment]
I suppose you got that information from [this](https://github.com/microg/android_packages_apps_GmsCore/wiki/Signature-Spoofing) page: it was an error, I've fixed it. No signature spoofing activation is required on this ROM as the two apps that requires it (FakeStore and GmsCore) already have the permission automatically.

**Comment by zilti** [comment]
Alright. As a followup though: signature spoofing checker tells me "Signature Spoofing: DISABLED". Shouldn't that be automagically enabled?

**Comment by corna** [comment]
Nope, because only [privileged apps (or apps signed with the microG's key)](https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L180) can obtain the signature spoofing permission, so the checker app can't obtain it and reports a failure.

**Comment by zilti** [comment]
So basically, the signature spoofing is useless for the very usecase it was made for, i.e. 3rd party apps using Google SafetyNet?

**Comment by zilti** [comment]
Well, apparently that isn't working still. Or why else does a fresh lineageos4microg install with the droidguard apk in /system/priv-app still completely fail even the "basicIntegrity" test, which afaik checks for Play Services and for the signatures in priv-apps?

**Comment by ArchangeGabriel** [comment]
Because currently all μG installs fail SafetyNet completely, see https://github.com/microg/android_packages_apps_GmsCore/issues/482, https://github.com/microg/android_packages_apps_GmsCore/issues/526, https://github.com/microg/android_packages_apps_GmsCore/issues/543 for instance and https://github.com/microg/android_packages_apps_GmsCore/issues/553 for a part of the solution.
