### ISSUE TITLE
microG, F-Droid missing in blueline build, looks like plain lineageOS

### ISSUE THREAD

**Issue by patientimprover** [lineageos4microg/docker-lineage-cicd#151]
Hi,
just flashed 
lineage-17.1-20210125-microG-blueline.zip
via ADB sideload onto factory reset blueline/ Pixel3, 
coming from stock 
10_blueline-qq1a.191205.008-factory-bc480ac4.zip

After successful boot I'm looking at a plain lineage OS, 
no microG-Setting app nor F-Droid is present.

I did also try the older build
lineage-17.1-20210107-microG-blueline.zip
same result.

I've caught the build from
https://download.lineage.microg.org/blueline/
and checksumed correctly.

Every advice appreciated.
Thanks

**Comment by spolack** [comment]
Can anyone else confirm. Once whyred is built i'll test.

**Comment by compilebunny** [comment]
Anecdotally, this seems to be a problem with a lot of roms compiled using docker-lineage-cicd. They come out without microg, root, signature spoofing, pre-installed fdroid, etc. Just plain lineage. 

The log to the console says that signature spoofing & requested apps are being installed, but "grep -i fdroid" on the logs saved in /srv/logs/model_number produces no hits. Needless to say, signature spoofing, fdroid, etc are not present when the rom is installed.

I'll do a compile of d855 soon to provide a clean example. Same thread or new?

**Comment by patientimprover** [comment]
Thanks for the info!

**Comment by telent** [comment]
For what it's worth, I have the same issue with building 15.1 for potter. I assumed it was due to my custom manifest perhaps mounting some plain lineageos repo over the top of a directory that  los4µG needs but maybe that isn't the problem if it's happening for supported devices too

**Comment by compilebunny** [comment]
> For what it's worth, I have the same issue with building 15.1 for potter. I assumed it was due to my custom manifest perhaps mounting some plain lineageos repo over the top of a directory that los4µG needs but maybe that isn't the problem if it's happening for supported devices too

It also happens when building 14.1 for the LG G4. I didn't report it because the G4 is no longer supported, but (what appears to be) the same bug is affecting both supported and non-supported devices. See bug [#151,](https://github.com/lineageos4microg/docker-lineage-cicd/issues/154) which reports the details of the same bug on d855, which is supported.

Does anyone know if there is anywhere that we can ask about this in addition to reporting here?

**Comment by bananer** [comment]
By default, the build is without microG and FDroid packages, that might not be clear enough in the readme... In #154 the problem seems to be the missing manifest for prebuild microG and FDroid, see my comment there. @telent could you be missing the same thing? Maybe share what's in your local manifests?

**Comment by telent** [comment]
>  that might not be clear enough in the readme... 

Empirically  it's not clear enough for me, but that's only a single data point :slightly_smiling_face: 

I added that line in my manifest (Moto Potter 15.1) which now looks like this

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
	<project name="LineageOS/android_external_bson" path="external/bson" remote="github" revision="cm-14.1" />
	<project name="LineageOS/android_device_qcom_common" path="device/qcom/common" remote="github" revision="lineage-15.1" />
	<project name="LineageOS/android_packages_resources_devicesettings" path="packages/resources/devicesettings" remote="github" revision="staging/lineage-15.1" />
	<project name="boulzordev/android_device_motorola_potter" path="device/motorola/potter" remote="github" revision="lineage-15.1-64" />
	<project name="boulzordev/android_vendor_motorola_potter" path="vendor/motorola/potter" remote="github" revision="lineage-15.1-64" />
	<project name="boulzordev/android_kernel_motorola_msm8953" path="kernel/motorola/msm8953" remote="github" revision="lineage-15.1-64" />
	<project name="lineageos4microg/android_prebuilts_prebuiltapks" path="prebuilts/prebuiltapks" remote="github" revision="master" />
</manifest>
```

It's building as I write [*], so too early to say for sure if it's succeeded, but I do see GmsCore messages in the logs now which weren't there previously, so looks promising

```
$ grep GmsCore logs/potter/lineage-15.1-20210213-UNOFFICIAL-potter.log 
[707/1080] including ./prebuilts/prebuiltapks/GmsCore/Android.mk ...
[707/1080] including ./prebuilts/prebuiltapks/GmsCore/Android.mk ...
```

[*] I'll edit this message when it's done

**Comment by patientimprover** [comment]
thank you for pointing out:
    "bananer commented Feb 13, 2021
      By default, the build is without microG and FDroid
        packages"
    
    Does this mean, that anything available on 
    
    https://download.lineage.microg.org/
    is going to be pure Lineage OS
    and one has to build on their own?

**Comment by bananer** [comment]
@patientimprover it's just the default when building yourself with this docker image. The official lineageos4microg zips should have microG and F-Droid included.

**Comment by patientimprover** [comment]
@bananer
    this is the initial Problem:
    
    this thread got started because Micro-G and F-Droid are missing
      in the official lineageos4microg zips.
    Tested on blueline release.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lineageos4microg/docker-lineage-cicd/issues/151#issuecomment-778814671",
"url": "https://github.com/lineageos4microg/docker-lineage-cicd/issues/151#issuecomment-778814671",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by patientimprover** [comment]
Good Evening,
    I have just checked 
    
    https://download.lineage.microg.org/blueline/
    it seems, that after starting this thread, builds have not been
      updated yet,
    which also means, that micro-g and f-droid are still missing on
      the blueline-builds.
    Will there be updated builds adressing this problem 
    
    or do I have to build myself?
    Cheers
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lineageos4microg/docker-lineage-cicd/issues/151#issuecomment-778814671",
"url": "https://github.com/lineageos4microg/docker-lineage-cicd/issues/151#issuecomment-778814671",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by felschr** [comment]
Since builds are running again as anyone tested the new blueline images?

**Comment by patientimprover** [comment]
yes! thanks felschr for drawing my attention to the new builds.
Even though there is no difference in size
microG and fdroid are available!

microG Version 0.2.18.204714
FDroid Version 1.11

Happy Easter tinkering!
Cheers
