### ISSUE TITLE
Compiling CM 14.1 for d855 produces a ROM with signature spoofing, microg, fdroid missing. Looks like plain Lineageos.

### ISSUE THREAD

**Issue by compilebunny** [lineageos4microg/docker-lineage-cicd#154]
This is an attempt to provide a clear, complete bug report for the issue referenced in #151.

The issue is that (some?) roms compiled with the appropriate signature spoofing and app inclusion flags using docker-lineage-cicd come out without the specified options. That is, they come out as plain lineageos.

I have observed this in various other situations that are unsupported. However, this "sample bug" should be fully supported.

I pulled a brand new docker-lineage-cicd on Jan 28, 2021 and ran:

docker run \
    -e "BRANCH_NAME=cm-14.1" \
    -e "DEVICE_LIST_CM_14_1=d855" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "WITH_SU=true" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend FDroid FDroidPrivilegedExtension com.google.android.maps.jar" \
    -v "/XXX/srv/src:/srv/src" \
    -v "/XXX/srv/zips:/srv/zips" \
    -v "/XXX/srv/logs:/srv/logs" \
    -v "/XXX/srv/ccache:/srv/cache" \
    -v "/XXX/srv/keys:/srv/keys" \
        lineageos4microg/docker-lineage-cicd

First run: STDERR: 
Traceback (most recent call last):
  File "/root/build_manifest.py", line 37, in <module>
    source_manifest = urlopen(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

First run: STDOUT:
>> [Fri Jan 29 08:27:15 UTC 2021] Branch:  cm-14.1
>> [Fri Jan 29 08:27:15 UTC 2021] Devices: d855
>> [Fri Jan 29 08:27:15 UTC 2021] (Re)initializing branch repository
>> [Fri Jan 29 08:27:21 UTC 2021] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Fri Jan 29 08:27:22 UTC 2021] Syncing branch repository
>> [Fri Jan 29 11:16:50 UTC 2021] Applying the restricted signature spoofing patch (based on android_frameworks_base-N.patch) to frameworks/base
>> [Fri Jan 29 11:17:56 UTC 2021] Setting "UNOFFICIAL" as release type
>> [Fri Jan 29 11:17:56 UTC 2021] Adding OTA URL overlay (for custom URL )
>> [Fri Jan 29 11:17:56 UTC 2021] Adding custom packages (GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend FDroid FDroidPrivilegedExtension com.google.android.maps.jar)
>> [Fri Jan 29 11:17:56 UTC 2021] Preparing build environment
>> [Fri Jan 29 11:18:47 UTC 2021] Starting build for d855, cm-14.1 branch
>> [Fri Jan 29 11:41:21 UTC 2021] Failed build for d855
>> [Fri Jan 29 11:41:21 UTC 2021] Finishing build for d855
>> [Fri Jan 29 11:41:21 UTC 2021] Cleaning source dir for device d855

Second run: STDERR:
Traceback (most recent call last):
  File "/root/build_manifest.py", line 37, in <module>
    source_manifest = urlopen(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

Second run: STDOUT:
Set cache size limit to 50.0 GB
>> [Fri Jan 29 12:40:17 UTC 2021] Branch:  cm-14.1
>> [Fri Jan 29 12:40:17 UTC 2021] Devices: d855
>> [Fri Jan 29 12:44:21 UTC 2021] (Re)initializing branch repository
>> [Fri Jan 29 12:44:53 UTC 2021] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Fri Jan 29 12:44:55 UTC 2021] Syncing branch repository
>> [Fri Jan 29 13:13:50 UTC 2021] Applying the restricted signature spoofing patch (based on android_frameworks_base-N.patch) to frameworks/base
>> [Fri Jan 29 13:14:34 UTC 2021] Setting "UNOFFICIAL" as release type
>> [Fri Jan 29 13:14:34 UTC 2021] Adding OTA URL overlay (for custom URL )
>> [Fri Jan 29 13:14:34 UTC 2021] Adding custom packages (GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend FDroid FDroidPrivilegedExtension com.google.android.maps.jar)
>> [Fri Jan 29 13:14:34 UTC 2021] Preparing build environment
>> [Fri Jan 29 13:15:26 UTC 2021] Starting build for d855, cm-14.1 branch
>> [Fri Jan 29 16:22:11 UTC 2021] Moving build artifacts for d855 to '/srv/zips/d855'
>> [Fri Jan 29 16:22:16 UTC 2021] Finishing build for d855
>> [Fri Jan 29 16:22:16 UTC 2021] Cleaning source dir for device d855

Log files attached.

I do not have a d855 to verify with however, I ran "grep -R -i fdroid" on the following locations and got no hits:
- The log directory
- Unzipped ROM
- Unzipped rom with unzipped system.new.dat

This leads me to believe that, at least, fdroid was not included. 

I have observed in various other contexts that microg & signature spoofing were not included when similar compiles were performed for other devices. This is also what is observed in bug #151.
[lineage-14.1-20210129-UNOFFICIAL-d855.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/5895901/lineage-14.1-20210129-UNOFFICIAL-d855.log)

The rom itself is too large to attach, but can be provided upon request.

**Comment by compilebunny** [comment]
Is there any more information that I can give to make this issue easier to work on?

**Comment by bananer** [comment]
It seems like you're missing a manifest with the prebuilt apks for microG and FDroid. It should be in a directory mounted at `/src/local_manifests`. [This section](https://github.com/lineageos4microg/docker-lineage-cicd#build-for-angler-lineage-151-officially-supported-custom-keys-restricted-signature-spoofing-with-integrated-microg-and-fdroid) of the readme gives an example.

**Comment by compilebunny** [comment]
You're right. This works for d855. GmsCore, fdroid, etc seem to be included when including an XML file with 

<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="lineageos4microg/android_prebuilts_prebuiltapks" path="prebuilts/prebuiltapks" remote="github" revision="master" />
</manifest>

in /srv/local_manifests

**Comment by bananer** [comment]
> Please close this issue report.

Since you opened it, you should be able to close it yourelf.
