### ISSUE TITLE
lineage-17.1-20210119-microG-whyred-recovery.img Seems Broken

### ISSUE THREAD

**Issue by husen010899** [lineageos4microg/docker-lineage-cicd#156]
when I flash the "lineage-17.1-20210119-microG-whyred-recovery.img" using Google ADB in fastboot mode and when I boot into recovery it returns to fastboot

**Comment by kurt-by** [comment]
Wait for next build. Bug has been fixed. Use twrp in the meantime.

**Comment by JuniorJPDJ** [comment]
can this be closed @husen010899 ?

**Comment by petefoth** [comment]
Closing. `whyred` is no longer on the list of build targets 
https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets
