### ISSUE TITLE
[Feature] Option to skip repo sync in docker image

### ISSUE THREAD

**Issue by ameyagokhale** [lineageos4microg/docker-lineage-cicd#157]
Hi team,

is it possible to add an option (an extra environment variable) which when set, will skip the repo sync command and will build the microg builds as per the code which is present currently in the directory. ?

It will be of great help for those who use ```repopick``` command for picking specific commits for their device before triggering the brunch command.

Example: cm-14.1 topics are not being merged quickly and so, I tend to repopick the topic and build LOS for my own device. But as soon as I provide the directory to docker-lineage-cicd, it executes repo sync which in turn, reverts all my changes.

**Solution:**

Add an environment variable (REPO_SYNC for example), which if set to false, will skip it. Default can be set to true so that for others, there is no change in execution.

So, this should work as is:
```
docker run \
    -e "BRANCH_NAME=lineage-16.0" \
    -e "DEVICE_LIST=bacon" \
    -v "/home/user/lineage:/srv/src" \
    -v "/home/user/zips:/srv/zips" \
    -v "/home/user/logs:/srv/logs" \
    -v "/home/user/cache:/srv/ccache" \
    lineageos4microg/docker-lineage-cicd
```

But this should skip ```repo sync``` execution and should start with signature patching, adding overlays, etc:
```
docker run \
    -e "BRANCH_NAME=lineage-16.0" \
    -e "DEVICE_LIST=bacon" \
    -e "REPO_SYNC=false" \
    -v "/home/user/lineage:/srv/src" \
    -v "/home/user/zips:/srv/zips" \
    -v "/home/user/logs:/srv/logs" \
    -v "/home/user/cache:/srv/ccache" \
    lineageos4microg/docker-lineage-cicd
```

**Comment by ameyagokhale** [comment]
@spolack @corna It only requires minor changes and will not affect existing ci/cd jobs.

```
if [ "$REPO_SYNC" = true ]; then
  repo sync -c --force-sync &>> "$repo_log"
fi
```

Kindly take this feature into consideration

**Comment by bananer** [comment]
I would also find this feature useful from time to time. @ameyagokhale since you already seem to know what needs to be changed, maybe you could prepare a pull request?

Besides that, maybe you could also achieve your desired result by putting the `repopick` commands in a `before.sh` userscript.

**Comment by ameyagokhale** [comment]
Thank you @bananer for the suggestion. Actually, if we only add ```if statements```, then the change would be quite simple, straight-forward and quick. Analyzing and moving code to other files will take more time that the solution stated above.

But still, if you want to go with your idea, kindly let me know.

**Comment by bananer** [comment]
My suggestion was that you might achieve the desired result without any changes to the docker image, just by putting scripts into a directory mounted at `/srv/userscripts`. 

These get executed at certain points of the build process, e.g. [here](https://github.com/lineageos4microg/docker-lineage-cicd/blob/f012e2084b5b18bf86412b096b752a1cc1fd5d49/src/build.sh#L284)

Whether that works for you or not, a way to build without running `repo sync` would be cool!

**Comment by ameyagokhale** [comment]
Okay, so things like repopick and git apply could be applied via this method. Will try this along with raising PR to make repo sync conditional.
Thanks!

**Comment by jisakiel** [comment]
Another alternative in the meantime, which is quite terrible but seems to work (while at it, adding threads on repo sync because it's quite slow as it is!):

begin.sh:
```
#!/bin/bash
# this one is before in the PATH :D
cp /root/userscripts/repo /usr/local/sbin/
```

repo:
```
#!/bin/bash
echo "intercepted: repo $@"
if [ "$1" != "sync" ]; then
	/usr/local/bin/repo "$@"
else
	if [ "$REPO_SYNC" = true ]; then
		shift
		/usr/local/bin/repo sync -j$(nproc) "$@"
	else
		echo "Skipping repo $@"
	fi
fi
```

Is resetting the branches created on ```repo start``` to their upstream intentional, by the way?

**Comment by solarkraft** [comment]
note that [akaoraki/docker-lineage-cicd](https://github.com/pakaoraki/docker-lineage-cicd) seems to have the option to skip repo sync (and more).

**Comment by petefoth** [comment]
Please see this proposal #508 which makes `repo sync` and several other operations 'skippable'

I have a working implementation of this proposal in [my fork of this repo](https://github.com/petefoth/docker-lineage-cicd/tree/pf-120-make-jobs-switchable). The implementation still needs documentation, but please feel free to give it a try.

- the main operations are switchable using the environment variables added in [this commit](https://github.com/petefoth/docker-lineage-cicd/pull/4/commits/b4d65a810d0eca3c13de5dffa72bc10d7f6b78ba) and [this commit](https://github.com/petefoth/docker-lineage-cicd/pull/4/commits/54a6f2e7f33c31a8efe5bc11ca3f30675766ef7f)
 - to switch an operation, change the default value of the the variable in an  -e clause in the docker run command e.g.
     -e "CALL_REPO-SYNC=false" \
 - handling of the .img and .zip files is controlled by the ZIP_UP_IMAGES and MAKE_IMG_ZIP_FILE variables

The image is available [on dockerhub](https://hub.docker.com/layers/petefothl4m/docker-lineage-cicd/pf-120-make-jobs-switchable/images/sha256-a147d3aa1a0d931c47544934ef703a5d28781fa269a5f341735ce30a284e633d?context=repo)

**Comment by petefoth** [comment]
> Please see this proposal #508 which makes `repo sync` and several other operations 'skippable'
> 
> I have a working implementation of this proposal in [my fork of this repo](https://github.com/petefoth/docker-lineage-cicd/tree/pf-120-make-jobs-switchable). The implementation still needs documentation, but please feel free to give it a try.
> 
>     * the main operations are switchable using the environment variables added in [this commit](https://github.com/petefoth/docker-lineage-cicd/pull/4/commits/b4d65a810d0eca3c13de5dffa72bc10d7f6b78ba) and [this commit](https://github.com/petefoth/docker-lineage-cicd/pull/4/commits/54a6f2e7f33c31a8efe5bc11ca3f30675766ef7f)
> 
>     * to switch an operation, change the default value of the the variable in an  -e clause in the docker run command e.g.
>       -e "CALL_REPO-SYNC=false" \
> 
>     * handling of the .img and .zip files is controlled by the ZIP_UP_IMAGES and MAKE_IMG_ZIP_FILE variables
> 
> 
> The image is available [on dockerhub](https://hub.docker.com/layers/petefothl4m/docker-lineage-cicd/pf-120-make-jobs-switchable/images/sha256-a147d3aa1a0d931c47544934ef703a5d28781fa269a5f341735ce30a284e633d?context=repo)

The code is now available in [the `experimental` branch](https://github.com/lineageos4microg/docker-lineage-cicd/tree/experimental) , and its associated docker image `docker pull lineageos4microg/docker-lineage-cicd:experimental`

Draft Merge Request #579 is created, to push the features to the `master` branch. It will be merged (probably) when the March build run is complete
