### ISSUE TITLE
Help with unsupported device

### ISSUE THREAD

**Issue by zefrs** [lineageos4microg/docker-lineage-cicd#158]
Hi there,

If possible, could someone have a quick look to assist in understanding why the build for my unsupported device is failing?

`docker run \
    -e "BRANCH_NAME=lineage-17.1" \
    -e "DEVICE_LIST=judyln" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -e "INCLUDE_PROPRIETARY=false" \
    -v "/Users/xxxx/Documents/Code/Android/lge/lineage:/srv/src" \
    -v "/Users/xxxx/Documents/Code/Android/lge/zips:/srv/zips" \
    -v "/Users/xxxx/Documents/Code/Android/lge/logs:/srv/logs" \
    -v "/Users/xxxx/Documents/Code/Android/lge/cache:/srv/ccache" \
    -v "/Users/xxxx/Documents/Code/Android/lge/keys:/srv/keys" \
    -v "/Users/xxxx/Documents/Code/Android/lge/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd`

Manifests being used:
**judyln.xml**
`<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="Emanuel000000/android_device_lge_judyln" path="device/lge/judyln" remote="github" />
  <project name="Emanuel000000/android_device_lge_sdm845-common" path="device/lge/sdm845-common" remote="github" />
  <project name="Emanuel000000/android_kernel_lge_sdm845" path="kernel/lge/sdm845" remote="github" />
  <project name="Emanuel000000/proprietary_vendor_lge" path="vendor/lge" remote="github" />
  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" remote="github" />
</manifest>`

**custom_packages.xml**
`<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="lineageos4microg/android_prebuilts_prebuiltapks" path="prebuilts/prebuiltapks" remote="github" revision="master" />
</manifest>`

**Terminal output**
`Set cache size limit to 50.0 GB
>> [Tue Feb  9 12:32:18 UTC 2021] Branch:  lineage-17.1
>> [Tue Feb  9 12:32:18 UTC 2021] Devices: judyln,
>> [Tue Feb  9 12:32:50 UTC 2021] (Re)initializing branch repository
>> [Tue Feb  9 12:32:55 UTC 2021] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Tue Feb  9 12:32:55 UTC 2021] Syncing branch repository
>> [Tue Feb  9 12:41:03 UTC 2021] Applying the restricted signature spoofing patch (based on android_frameworks_base-Q.patch) to frameworks/base
>> [Tue Feb  9 12:41:18 UTC 2021] Setting "UNOFFICIAL" as release type
>> [Tue Feb  9 12:41:18 UTC 2021] Adding OTA URL overlay (for custom URL )
>> [Tue Feb  9 12:41:18 UTC 2021] Adding custom packages (GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension )
>> [Tue Feb  9 12:41:18 UTC 2021] Adding keys path (/srv/keys)
>> [Tue Feb  9 12:41:18 UTC 2021] Preparing build environment
>> [Tue Feb  9 12:41:19 UTC 2021] Starting build for judyln, lineage-17.1 branch
>> [Tue Feb  9 12:43:43 UTC 2021] Failed build for judyln
>> [Tue Feb  9 12:43:43 UTC 2021] Finishing build for judyln
>> [Tue Feb  9 12:43:43 UTC 2021] Cleaning source dir for device judyln`

**Log files**

**repo-20210209.log**
>> [Tue Feb  9 12:32:50 UTC 2021] (Re)initializing branch repository

repo has been initialized in /srv/src/LINEAGE_17_1
>> [Tue Feb  9 12:32:55 UTC 2021] Syncing branch repository
fatal: couldn't find remote ref refs/heads/lineage-17.1
fatal: couldn't find remote ref refs/heads/lineage-17.1
fatal: couldn't find remote ref refs/heads/lineage-17.1
fatal: couldn't find remote ref refs/heads/lineage-17.1
fatal: couldn't find remote ref refs/heads/lineage-17.1
fatal: couldn't find remote ref refs/heads/lineage-17.1
fatal: couldn't find remote ref refs/heads/lineage-17.1
fatal: couldn't find remote ref refs/heads/lineage-17.1
fatal: couldn't find remote ref refs/heads/lineage-17.1
fatal: couldn't find remote ref refs/heads/lineage-17.1
Emanuel000000/proprietary_vendor_lge:
fatal: couldn't find remote ref refs/heads/lineage-17.1

Emanuel000000/android_device_lge_sdm845-common:
fatal: couldn't find remote ref refs/heads/lineage-17.1

Emanuel000000/android_kernel_lge_sdm845:
fatal: couldn't find remote ref refs/heads/lineage-17.1

LineageOS/android_device_qcom_common:
fatal: couldn't find remote ref refs/heads/lineage-17.1

Emanuel000000/android_kernel_lge_sdm845:
fatal: couldn't find remote ref refs/heads/lineage-17.1

Emanuel000000/proprietary_vendor_lge:
fatal: couldn't find remote ref refs/heads/lineage-17.1

LineageOS/android_device_qcom_common:
fatal: couldn't find remote ref refs/heads/lineage-17.1

Emanuel000000/android_device_lge_sdm845-common:
fatal: couldn't find remote ref refs/heads/lineage-17.1

error: Cannot fetch Emanuel000000/proprietary_vendor_lge from https://github.com/Emanuel000000/proprietary_vendor_lge
Emanuel000000/android_device_lge_judyln:
fatal: couldn't find remote ref refs/heads/lineage-17.1

error: Cannot fetch Emanuel000000/android_kernel_lge_sdm845 from https://github.com/Emanuel000000/android_kernel_lge_sdm845
error: Cannot fetch Emanuel000000/android_device_lge_sdm845-common from https://github.com/Emanuel000000/android_device_lge_sdm845-common
error: Cannot fetch LineageOS/android_device_qcom_common from https://github.com/LineageOS/android_device_qcom_common
Emanuel000000/android_device_lge_judyln:
fatal: couldn't find remote ref refs/heads/lineage-17.1

error: Cannot fetch Emanuel000000/android_device_lge_judyln from https://github.com/Emanuel000000/android_device_lge_judyln
error: Cannot checkout Emanuel000000/android_device_lge_judyln: ManifestInvalidRevisionError: revision refs/heads/lineage-17.1 in Emanuel000000/android_device_lge_judyln not found
error: in `sync -c --force-sync`: revision refs/heads/lineage-17.1 in Emanuel000000/android_device_lge_judyln not found
hardware/qcom-caf/apq8084/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/msm8916/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/msm8952/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/msm8960/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/msm8974/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/msm8994/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/msm8996/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/msm8998/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/sdm845/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/sm8150/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/sm8250/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom/audio: Shared project LineageOS/android_hardware_qcom_audio found, disabling pruning.
hardware/qcom-caf/apq8084/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/msm8916/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/msm8952/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/msm8960/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/msm8974/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/msm8994/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/msm8996/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/msm8998/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/sdm845/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/sm8150/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/sm8250/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom/media: Shared project LineageOS/android_hardware_qcom_media found, disabling pruning.
hardware/qcom-caf/apq8084/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/msm8916/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/msm8952/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/msm8960/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/msm8974/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/msm8994/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/msm8996/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/msm8998/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/sdm845/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/sm8150/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom-caf/sm8250/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
hardware/qcom/display: Shared project LineageOS/android_hardware_qcom_display found, disabling pruning.
device/qcom/sepolicy: Shared project LineageOS/android_device_qcom_sepolicy found, disabling pruning.
device/qcom/sepolicy-legacy: Shared project LineageOS/android_device_qcom_sepolicy found, disabling pruning.
device/qcom/sepolicy-legacy-um: Shared project LineageOS/android_device_qcom_sepolicy found, disabling pruning.
hardware/qcom-caf/bt: Shared project LineageOS/android_hardware_qcom_bt found, disabling pruning.
hardware/qcom/bt: Shared project LineageOS/android_hardware_qcom_bt found, disabling pruning.
vendor/nxp/opensource/pn5xx/halimpl: Shared project LineageOS/android_vendor_nxp_opensource_halimpl found, disabling pruning.
vendor/nxp/opensource/sn100x/halimpl: Shared project LineageOS/android_vendor_nxp_opensource_halimpl found, disabling pruning.
vendor/nxp/opensource/pn5xx/hidlimpl: Shared project LineageOS/android_vendor_nxp_opensource_hidlimpl found, disabling pruning.
vendor/nxp/opensource/sn100x/hidlimpl: Shared project LineageOS/android_vendor_nxp_opensource_hidlimpl found, disabling pruning.

**lineage-17.1-20210209-UNOFFICIAL-judyln.log**
>> [Tue Feb  9 12:41:19 UTC 2021] Starting build for judyln, lineage-17.1 branch
12:43:10 Build sandboxing disabled due to nsjail error.
[1mbuild/make/core/product_config.mk:223: [31merror: [0m[1mCan not locate config makefile for product "lineage_judyln".[0m
12:43:10 dumpvars failed with: exit status 1
Device judyln not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Repository for judyln not found in the LineageOS Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
12:43:41 Build sandboxing disabled due to nsjail error.
[1mbuild/make/core/product_config.mk:223: [31merror: [0m[1mCan not locate config makefile for product "lineage_judyln".[0m
12:43:42 dumpvars failed with: exit status 1
12:43:43 Build sandboxing disabled due to nsjail error.
[1mbuild/make/core/product_config.mk:223: [31merror: [0m[1mCan not locate config makefile for product "lineage_judyln".[0m
12:43:43 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_judyln'
** Do you have the right repo manifest?

No such item in brunch menu. Try 'breakfast'
>> [Tue Feb  9 12:43:43 UTC 2021] Failed build for judyln
>> [Tue Feb  9 12:43:43 UTC 2021] Finishing build for judyln
>> [Tue Feb  9 12:43:43 UTC 2021] Cleaning source dir for device judyln
12:43:44 Entire build directory removed.

**Comment by bananer** [comment]
` fatal: couldn't find remote ref refs/heads/lineage-17.1`

That means there is no branch `lineage-17.1` in these repositories.

You could define an alternate branch using the `revision` attribute in your manifest's `project` elements.

**Comment by zefrs** [comment]
I see, thanks @bananer, i will give that a bash.

**Comment by zefrs** [comment]
@bananer, your suggestion worked to resolve the  `fatal: couldn't find remote ref refs/heads/lineage-17.1` error.

It is still failing to build unfortunately, output below:

`>> [Tue Feb  9 14:01:00 UTC 2021] Starting build for judyln, lineage-17.1 branch
14:02:51 Build sandboxing disabled due to nsjail error.
[1mbuild/make/core/product_config.mk:223: [31merror: [0m[1mCan not locate config makefile for product "lineage_judyln".[0m
14:02:52 dumpvars failed with: exit status 1
Device judyln not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Repository for judyln not found in the LineageOS Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
14:03:23 Build sandboxing disabled due to nsjail error.
[1mbuild/make/core/product_config.mk:223: [31merror: [0m[1mCan not locate config makefile for product "lineage_judyln".[0m
14:03:23 dumpvars failed with: exit status 1
14:03:25 Build sandboxing disabled due to nsjail error.
[1mbuild/make/core/product_config.mk:223: [31merror: [0m[1mCan not locate config makefile for product "lineage_judyln".[0m
14:03:25 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_judyln'
** Do you have the right repo manifest?

No such item in brunch menu. Try 'breakfast'
>> [Tue Feb  9 14:03:25 UTC 2021] Failed build for judyln
>> [Tue Feb  9 14:03:25 UTC 2021] Finishing build for judyln
>> [Tue Feb  9 14:03:25 UTC 2021] Cleaning source dir for device judyln
14:03:26 Entire build directory removed.

#### build completed successfully (1 seconds) ####`

**Comment by bananer** [comment]
I think if you provide your own device and kernel repository, the manifest file needs to be named `roomservice.xml` (not `judyln.xml`) so that [roomservice.py](https://github.com/LineageOS/android_vendor_lineage/blob/lineage-18.1/build/tools/roomservice.py) finds the projects there.

**Comment by zefrs** [comment]
Yeah, no dice, after renaming the xml i'm still faced with the same error.

**Comment by adinechin** [comment]
This type of error
`1mCan not locate config makefile for product "lineage_judyln".�[`
Is generally when the device tree is not adapted to the rom. For example you should have at the root of your device tree some files named under the name of your ROM (i.e. lineage.mk), or some specific paths in them.

You have a little tip on DotOS to know how to transform a tree for DotOS, you can adapt it to transform a tree for LineageOS ;-)
https://github.com/DotOS/android_vendor_dot/tree/dot-o#getting-started-with-making-tree-for-dotos-from-los

**Comment by zefrs** [comment]
Got this sorted after sorting out device tree.
