### ISSUE TITLE
dumpling builds have stopped?

### ISSUE THREAD

**Issue by radhta** [lineageos4microg/docker-lineage-cicd#159]
upstream is 2 weekly builds ahead

**Comment by doodhout** [comment]
It seems that Lineage for MicroG builds have stopped somewhere during late January, because most models have builds up until that date, but nothing after.

I have no idea what's wrong and where to fix it.

**Comment by make-free-code** [comment]
The latest builds I could find are from 2021-02-04.
Is anybody aware of what the reason might be?
Where and how are builds executed normally? How are they published on https://download.lineage.microg.org?

**Comment by thepartisan** [comment]
My local builds also failed (avicii). There seems to be an increase in memory usage. On my 16 GB RAM build server I needed to assign an additional 12 GB of swap, together with increasing memory for JAVA:
```
    -e "JAVA_TOOL_OPTIONS=-Xmx12g" \
    -e "ANDROID_JACK_VM_ARGS=-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx12G" \
```
After this the builds succeeded again.
I assume the CICD-servers also just run out of memory and thus don't create new images.

**Comment by rashil2000** [comment]
I try to build the image for cheeseburger on my PC, but it gets stuck at 
```
Set cache size limit to 50.0 GB
>> [Sun Mar 21 20:19:27 UTC 2021] Branch:  lineage-17.1
>> [Sun Mar 21 20:19:27 UTC 2021] Devices: cheeseburger,
>> [Sun Mar 21 20:19:27 UTC 2021] (Re)initializing branch repository
>> [Sun Mar 21 20:19:29 UTC 2021] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Sun Mar 21 20:19:31 UTC 2021] Syncing branch repository
```

Increasing memory to 12GB (I have 16 GB total) using your method didn't help either...

**Comment by thepartisan** [comment]
> Increasing memory to 12GB (I have 16 GB total) using your method didn't help either...

Are you certain that you habe enough swap space? I had to use an additional swap file with 12 GB, my 16 GB RAM were not enough by far.

**Comment by odlg** [comment]
I usually reduce the number of CPUs available, the build scripts spawns a compile job for every (cpu + 2) - each job requires significant memory, so either you add more memory or reduce the number of CPUs. 
On linux (the host system), CPUs can be disabled by doing something like this:
`echo 0 > /sys/devices/system/cpu/cpu1/online
echo 0 > /sys/devices/system/cpu/cpu3/online
echo 0 > /sys/devices/system/cpu/cpu5/online`
3-4 online CPUs works fine when you have 16 GB memory and most of it free.

**Comment by rashil2000** [comment]
Just a on an unrelated note, how large is your `lineage/LINEAGE_17_1/.repo` folder when the container is running? 

My container gets stuck at the 'syncing branch repository' step, while in fact it keeps downloading too much stuff (over 50GB and counting...).

For reference, here's the command I run (everything is just the same as the example given in the Readme, except for device name):
```bash
docker run \
  -e "BRANCH_NAME=lineage-17.1" \
  -e "DEVICE_LIST=cheeseburger" \
  -e "SIGN_BUILDS=true" \
  -e "SIGNATURE_SPOOFING=restricted" \
  -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
  -v "/home/wskali/Downloads/docker-lineage-cicd/lineage:/srv/src" \
  -v "/home/wskali/Downloads/docker-lineage-cicd/zips:/srv/zips" \
  -v "/home/wskali/Downloads/docker-lineage-cicd/logs:/srv/logs" \
  -v "/home/wskali/Downloads/docker-lineage-cicd/cache:/srv/ccache" \
  -v "/home/wskali/Downloads/docker-lineage-cicd/keys:/srv/keys" \
  -v "/home/wskali/Downloads/docker-lineage-cicd/manifests:/srv/local_manifests" \
  lineageos4microg/docker-lineage-cicd
```

And here's the XML file in the `/home/wskali/Downloads/docker-lineage-cicd/manifests` folder:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="lineageos4microg/android_prebuilts_prebuiltapks" path="prebuilts/prebuiltapks" remote="github" revision="master" />
</manifest>
```

**Comment by Ammako** [comment]
> My container gets stuck at the 'syncing branch repository' step, while in fact it keeps downloading too much stuff (over 50GB and counting...)

Let it sit for a while. This is most likely normal. Android source is *huge*.

I don't know about 17.1, but 15.1 takes up 59.1 GB of space. Newer android versions may take up even more.

**Comment by MartiniMoe** [comment]
> My local builds also failed (avicii). There seems to be an increase in memory usage. On my 16 GB RAM build server I needed to assign an additional 12 GB of swap, together with increasing memory for JAVA:
> 
> ```
>     -e "JAVA_TOOL_OPTIONS=-Xmx12g" \
>     -e "ANDROID_JACK_VM_ARGS=-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx12G" \
> ```
> 
> After this the builds succeeded again.
> I assume the CICD-servers also just run out of memory and thus don't create new images.

What errors did you face when you ran out of RAM? I need to also try assigning swap, since my builds are also failing...

**Comment by MartiniMoe** [comment]
> I usually reduce the number of CPUs available, the build scripts spawns a compile job for every (cpu + 2) - each job requires significant memory, so either you add more memory or reduce the number of CPUs.
> On linux (the host system), CPUs can be disabled by doing something like this:
> `echo 0 > /sys/devices/system/cpu/cpu1/online`
> `echo 0 > /sys/devices/system/cpu/cpu3/online`
> `echo 0 > /sys/devices/system/cpu/cpu5/online`
> 3-4 online CPUs works fine when you have 16 GB memory and most of it free.

Couldn't you also limit the number of cores docker uses with something like `$ docker run --cpus=2 nginx` ?

**Comment by rashil2000** [comment]
I tried assigning more swap, but the builds still fail. I get the same error regardless: 

```
...
[100% 139/139] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: vendor/bq/bardock/Android.bp:136:1: module "libsdm-disp-vndapis" variant "android_arm64_armv8-a_core_shared": module source path "vendor/bq/bardock/proprietary/vendor/lib64/libsdm-disp-vndapis.so" does not exist
error: vendor/bq/bardock/Android.bp:60:1: module "libqmi" variant "android_arm64_armv8-a_core_shared": module source path "vendor/bq/bardock/proprietary/vendor/lib64/libqmi.so" does not exist
error: vendor/bq/bardock/Android.bp:117:1: module "libqmiservices" variant "android_arm64_armv8-a_core_shared": module source path "vendor/bq/bardock/proprietary/vendor/lib64/libqmiservices.so" does not exist
error: vendor/bq/bardock/Android.bp:41:1: module "libgpustats" variant "android_arm64_armv8-a_core_shared": module source path "vendor/bq/bardock/proprietary/vendor/lib64/libgpustats.so" does not exist
ninja: build stopped: subcommand failed.
09:28:15 soong bootstrap failed with: exit status 1

#### failed to build some targets (01:52 (mm:ss)) ####

>> [Tue Mar 23 09:28:15 UTC 2021] Failed build for cheeseburger
...
```

**Comment by odlg** [comment]
> > I usually reduce the number of CPUs available, the build scripts spawns a compile job for every (cpu + 2) - each job requires significant memory, so either you add more memory or reduce the number of CPUs.
> > On linux (the host system), CPUs can be disabled by doing something like this:
> > `echo 0 > /sys/devices/system/cpu/cpu1/online`
> > `echo 0 > /sys/devices/system/cpu/cpu3/online`
> > `echo 0 > /sys/devices/system/cpu/cpu5/online`
> > 3-4 online CPUs works fine when you have 16 GB memory and most of it free.
> 
> Couldn't you also limit the number of cores docker uses with something like `$ docker run --cpus=2 nginx` ?

It seems that the build scripts uses several methods to determine the number of cpus, the scripts are not consequently using docker compliant ways to do it - unfortunately.

**Comment by Ammako** [comment]
I use a VM with 2 CPU cores and 8 GB of ram, with 2 GB swap. Never had an issue with my builds, but that being said I don't do 17.1, and for a different device entirely. I'm going to try building 17.1 for dumpling and cheeseburger right now, see if that succeeds or if I get a different error.

**Comment by rashil2000** [comment]
> I use a VM with 2 CPU cores and 8 GB of ram, with 2 GB swap. Never had an issue with my builds, but that being said I don't do 17.1, and for a different device entirely. I'm going to try building 17.1 for dumpling and cheeseburger right now, see if that succeeds or if I get a different error.

That sounds interesting! If you succeed, do let us know more VM specs. I might just end up using a VM for this lol

**Comment by MartiniMoe** [comment]
I still need to confirm it, but I got the impression, that when a local build fails, it succeeds again, when I exit my buildserver and create a new SSH session with a new shell session etc...

**Comment by Ammako** [comment]
Turns out, 17.1 is huge. Like, the 183.6 GB kind of huge. Took 3 hours for sync, and 4 hours into the build it had barely even got 40% of the way through. I don't think I can recommend 2 cores and 8 GB of ram for this lol. I've got to leave it at that.

That being said a VM might not be a bad choice if you need to reliably limit the amount of cores or memory available, as long as you have enough ram that you can assign to a VM and still keep your host system running.

**Comment by rashil2000** [comment]
> Turns out, 17.1 is huge. Like, the 183.6 GB kind of huge. Took 3 hours for sync, and 4 hours into the build it had barely even got 40% of the way through.

Was going to say this. It doesn't stop at 185GB. 5 hours in, my build failed at 76%, because guess what, my HDD got full. The build process generates an additional ~60GB of output and cache files. I was using Docker, with WSL2 backend, and WSL was configured with 6 cores, 8GB RAM and 12GB swap.

Looks like I'm gonna have to fall back to vanilla Lineage builds and use the Nanodroid patcher for microG.

**Comment by jtagcat** [comment]
I have the resources available to do builds, but don't have the time to figure it out. If somebody wants to put together a sequence of commands to go from zero to a finished build, I can get that done. Though, I would guess we don't have the OTA keys available.

**Comment by rashil2000** [comment]
The builds are back up again, by the way. #166 

@radhta you can consider closing this now

**Comment by slim8shady9** [comment]
> My local builds also failed (avicii). There seems to be an increase in memory usage. On my 16 GB RAM build server I needed to assign an additional 12 GB of swap, together with increasing memory for JAVA:
> 
> ```
>     -e "JAVA_TOOL_OPTIONS=-Xmx12g" \
>     -e "ANDROID_JACK_VM_ARGS=-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx12G" \
> ```
> 
> After this the builds succeeded again.
> I assume the CICD-servers also just run out of memory and thus don't create new images.

Anyone knows what is the docker image default for those variables?
