### ISSUE TITLE
Is the build server publicly accessable for viewing?

### ISSUE THREAD

**Issue by xenithorb** [lineageos4microg/docker-lineage-cicd#16]
Bacon's 15.1 has been out for a few days now, and now that their ROM is odex'd you can no longer use haystack to patch the framework.jar for signature spoofing. (I used to do this with NanoMod/Droid + Magisk for about a year no problems)

**This makes this fork extremely relevant, because it's the only way to run microg in a meaningful way going forward on bacon, and I assume all other 15.x LOS phones.**

That being said, there are no 15.1 build available for L4M for bacon yet and I'm just sort of wondering what's up?

It'd be nice if there was a page to view build status like LOS has their jenkins server viewable.

**Comment by ArchangeGabriel** [comment]
I think it’s just that @corna has to flip a switch somewhere when a device switch to 15.1 from 14.1.

**Comment by corna** [comment]
> I think it’s just that @corna has to flip a switch somewhere when a device switch to 15.1 from 14.1.

No switch, every day at 00:00 UTC the [list of the devices](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets) is automatically downloaded, parsed and the correct builds start. From [the history](https://github.com/LineageOS/hudson/commits/master/lineage-build-targets) it seems that bacon has been promoted to 15.1 some hours after midnight (commit "[bey-kuh n]", why don't they use decent commit messages??), so it will be built automatically next Monday.

> It'd be nice if there was a page to view build status like LOS has their jenkins server viewable.

It's on the top of my personal TODO list, however I don't have much spare time in this period and I prefer using it to keeps the builds flowing.

**Comment by ds6** [comment]
It appears ```pioneer``` is not building properly, as it is not available on the download page. Are there problems with the build?

**Comment by corna** [comment]
@ds6 Wrong place for this request; anyway, same issue as [tissot](https://forum.xda-developers.com/showpost.php?p=77106501&postcount=954), new builds will appear next Tuesday.

**Comment by ds6** [comment]
@corna And where is the correct place? I looked around before posting. I didn't want to make a new issue so I just commented here.

**Comment by riesnerd** [comment]
@corna
> It's on the top of my personal TODO list, however I don't have much spare time in this period and I prefer using it to keeps the builds flowing.

Can you be supported with that?

**Comment by spolack** [comment]
related to #71
