### ISSUE TITLE
Z3 screen rotation not working since Feb 05 build

### ISSUE THREAD

**Issue by jw243** [lineageos4microg/docker-lineage-cicd#161]
On the Z3 February 5th build screen rotation is broken. Screen cannot be rotated when screen rotation is switched on.

This bug was not present in January 19th build, where screen rotation worked as expected.

I freshly installed the build on stock rom 23.5.A.1.291, which I had freshly flashed using flashtool. On stock, rotation worked as expected.

**Comment by jw243** [comment]
Screen rotation is not the only bug in this build. The **nearby-sensor** does not work in the telephone app. The result is that the screen stays switched on when the phone is put to the ear. This results in phone calls being cut off, because the ear touches the respective button. The phone is not usable with this bug!

I wonder whether you use the same sources as the official Lineage rom. I deleted your build and installed the most up to date official build. Both bugs are not present!

**Comment by bananer** [comment]
Builds are not precisely in sync with LineageOS. Changes including bugs or bugfixes might turn up here or there earlier.

I'm assuming this issue is no longer present.
