### ISSUE TITLE
No new Pixel 4 (flame) builds

### ISSUE THREAD

**Issue by Lefl1** [lineageos4microg/docker-lineage-cicd#164]
Hello,

this is a great project and I really love this, but the builds for the Pixel 4 (flame) are lagging behind.
The last microg build is from January 16th while upstream's oldest build is from January 24th (the newest is from 14th February).

Why hasn't been newer builds?

**Comment by doodhout** [comment]
It seems that Lineage for MicroG builds have stopped somewhere during late January, because most models have builds up until that date, but nothing after.

I have no idea what's wrong and where to fix it.

**Comment by make-free-code** [comment]
Related: https://github.com/lineageos4microg/docker-lineage-cicd/issues/159

**Comment by bananer** [comment]
Thanks, let's keep the discussion for this in #166
