### ISSUE TITLE
No New Builds for Any Lineage for Micro G Devices

### ISSUE THREAD

**Issue by YoungRiker** [lineageos4microg/docker-lineage-cicd#166]
What is going on with Lineage for Micro G? Is the project continuing or not? A yes/no or alternatively additional info would be very much appreciated.

**Comment by Jonny007-MKD** [comment]
Yes, the last build was uploaded at 2021-02-05. @spolack?

**Comment by HJMVR** [comment]
I really hope that this project is still alive.

**Comment by tokariu** [comment]
it's been 2 month without any updates for most devices and without any information about the issue why that's the case (if you have information please tell us!)
anyone who is involved with the project: please give us information about the status.
we need to know whether this project:
a) is going to be updated (at all)
b) ETA when (if so)
c) project is dead, we shall look for other ROM options with up2date security levels.

not knowing anything is the worst situation.

**Comment by kurt-by** [comment]
Despite the many contributes, running the build server is a one-man-show at the moment. Maybe we get a new round of builds next week.

**Comment by bananer** [comment]
@kurt-by can we do anything to improve this situation and to ensure this project remains alive? contributions of code, time or money?

**Comment by kurt-by** [comment]
@bananer now you can help with code
https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/issues/47

**Comment by kurt-by** [comment]
@bananer thank you
@YoungRiker 17.1 builds are running now in alphabetical order.

**Comment by martin-v** [comment]
:+1: Thanks to both of you for your work!

Is there anything more we can help? e.g.: is it possible to find the build logfiles somewhere to investigate failing builds proactive?

**Comment by YoungRiker** [comment]
Thanks all!

**Comment by uok** [comment]
Looking at https://download.lineage.microg.org it seems the newest builds stopped at April 16th, most other device builds are dated March. It would be great to get this project going again! Looking for v18.1 for jasmine_sprout and can help testing. Thanks!

**Comment by antoinevth** [comment]
Actually, all devices have a build dated from April, except 5 of them. jasmine_sprout just got promoted to 18.1, so I guess it will get its build during the next 18.1 builds.

**Comment by Iey4iej3** [comment]
> +1 Thanks to both of you for your work!
> 
> Is there anything more we can help? e.g.: is it possible to find the build logfiles somewhere to investigate failing builds proactive?

Build logs would help, of course.

**Comment by Iey4iej3** [comment]
> Looking at https://download.lineage.microg.org it seems the newest builds stopped at April 16th, most other device builds are dated March. It would be great to get this project going again! Looking for v18.1 for jasmine_sprout and can help testing. Thanks!

I [proposed](https://github.com/lineageos4microg/docker-lineage-cicd/issues/170) more frequent builds. There might be difficulties to build frequently. I suppose that twice a month might be acceptable, but once a month would lead to problems now if there are issues in that build.

**Comment by uok** [comment]
@antoinevth, thanks for checking, I'm just trying to understand the build cycle. 
For example: device "pioneer" already has 2 [MicroG v18.1 builds](https://download.lineage.microg.org/pioneer/) (April 4h and 11th) while last "jasmine_sprout" dates back to March 28th. Also I don't understand how they "match" the dates of regular Lineage builds, where "pioneer" has 4 [Lineage v18.1 builds](https://download.lineageos.org/pioneer) (April 2nd, 8th, 15th, 22nd)

**Comment by Iey4iej3** [comment]
> @antoinevth, thanks for checking, I'm just trying to understand the build cycle.
> For example: device "pioneer" already has 2 [MicroG v18.1 builds](https://download.lineage.microg.org/pioneer/) (April 4h and 11th) while last "jasmine_sprout" build dates back to March 28th. Also I don't understand how they "match" the dates of regular Lineage builds, where "pioneer" has 4 [Lineage v18.1 builds](https://download.lineageos.org/pioneer) (April 2nd, 8th, 15th, 22nd)

It is possible that the builds are still triggered manually.

**Comment by amo13** [comment]
Looks like new builds are available again!

**Comment by uok** [comment]
Confirmed! Running jasmine_sprout 18.1 and all Micro G checks are green :heavy_check_mark: 
Thanks to all devs and contributors, this is a great project :+1:

**Comment by martin-v** [comment]
It looks like a lot of builds are failing again, the latest new build is PL2 2021-05-10, but a lot of devices don't have the May build yet. So I come back to my last question (@kurt-by): https://github.com/lineageos4microg/docker-lineage-cicd/issues/166#issuecomment-808172886

**Comment by Akruidenberg** [comment]
When will the new builds for cedric be available? 18.1 is out for this device. (moto g5)

**Comment by cRaZy-bisCuiT** [comment]
There are no more builds for lavender. The latest MicroG build is:
- 2021_04_15

The latest LineageOS official build (non-MicroG) is:
- 2021_06_01

In addition: The official LineageOS builds are already 18.1, while the latest MicroG build is still stuck at 17.1


What could we do to help to keep the builds automated running? Is there any kind of user interaction needed? Please advice. And please do also make the developement cycle a little more transparent to us. This is like a black box.

Thank you very much.

**Comment by Iey4iej3** [comment]
Note that the pull request https://github.com/lineageos4microg/docker-lineage-cicd/pull/178 has not been merged. Maybe the developers are busy.

**Comment by thrillfall** [comment]
Looks like this horse is dead for now.

How about reviving it? Can somebody recommend a service where we could run the docker build containers and make the resulting images public?
From my own experience it'll take at least 300GB storage and 32GB memory for a build during runtime

**Comment by amo13** [comment]
You could turn an old laptop into a build server, keep it connected and running and dedicate it to that task. 300GB of storage should not be a problem and getting up to 32 GB might well work with a big swap file on SSD. 
I'd be willing to help set up the OS, but I can't help with anything related to docker and the actual lineage build process.

**Comment by Iey4iej3** [comment]
> Looks like this horse is dead for now.
> 
> How about reviving it? Can somebody recommend a service where we could run the docker build containers and make the resulting images public?
> From my own experience it'll take at least 300GB storage and 32GB memory for a build during runtime

In addition, we first need maintainers - there are several pull requests which contain important bug fixes...

**Comment by cRaZy-bisCuiT** [comment]
And we also don't have the official signing keys I assume. No idea what went wrong here.

**Comment by bananer** [comment]
I'm happy to announce that this horse is not quite dead just yet!

I was invited to join the project as maintainer with access to the build server. Stay tuned!

**Comment by Iey4iej3** [comment]
> I'm happy to announce that this horse is not quite dead just yet!
> 
> I was invited to join the project as maintainer with access to the build server. Stay tuned!

Will your own pull requests be merged soon?

**Comment by Shiandow** [comment]
@bananer When you have access could you remove the latest builds for channel? The last build results in the SIM not working. See https://github.com/lineageos4microg/l4m_website/issues/77 for more info.

**Comment by Iey4iej3** [comment]
A [new round](https://download.lineage.microg.org/ahannah/) of building seems starting. Congratulations!

**Comment by bananer** [comment]
I merged most pull requests earlier, the updated image is available on docker hub.

Note that the round of builds which was started today still uses the old image, so #176 will not yet be fixed in them.

**Comment by 4n0nym0u53** [comment]
Maybe a dumb question, but how does the building of L4M work? Does the build server(s) just pull the latest build of upstream LOS, apply the L4M patches, build the OS and push it to the downloads website, or how does that work?

> A [new round](https://download.lineage.microg.org/ahannah/) of building seems starting. Congratulations!

Does that mean that all devices will be built, or only some of them?

**Comment by Iey4iej3** [comment]
> I merged most pull requests earlier, the updated image is available on docker hub.
> 
> Note that the round of builds which was started today still uses the old image, so #176 will not yet be fixed in them.

Oh, that is a bit disappointing.

**Comment by Iey4iej3** [comment]
> Maybe a dumb question, but how does the building of L4M work? Does the build server(s) just pull the latest build of upstream LOS, apply the L4M patches, build the OS and push it to the downloads website, or how does that work?
> 
> > A [new round](https://download.lineage.microg.org/ahannah/) of building seems starting. Congratulations!
> 
> Does that mean that all devices will be built, or only some of them?

I guess that every round of building is for all devices, and for some of previous buildings, only some of these devices had updates because the building failed.

**Comment by 4n0nym0u53** [comment]
> > Maybe a dumb question, but how does the building of L4M work? Does the build server(s) just pull the latest build of upstream LOS, apply the L4M patches, build the OS and push it to the downloads website, or how does that work?
> > > A [new round](https://download.lineage.microg.org/ahannah/) of building seems starting. Congratulations!
> > 
> > 
> > Does that mean that all devices will be built, or only some of them?
> 
> I guess that every round of building is for all devices, and for some of previous buildings, only some of these devices had updates because the building failed.

Okay, where do you see which builds failed and which succeeded?

**Comment by bananer** [comment]
> Maybe a dumb question, but how does the building of L4M work? Does the build server(s) just pull the latest build of upstream LOS, apply the L4M patches, build the OS and push it to the downloads website, or how does that work?

Mostly, yes. This repository contains the code which executes these steps inside a docker container.

> Does that mean that all devices will be built, or only some of them?

The currently running round of builds was started mostly to demostrate to me how the build server works internally. IIRC it will only build 18.1 devices.

Right now I don't yet have access to the build server nor a precise plan on how to continue running the builds in the future. Bear with me for a few days please, periodical builds for as many devices as we can support will come again soon.

**Comment by bananer** [comment]
> Okay, where do you see which builds failed and which succeeded?

At the moment you can only see the zip files as results of successful builds

**Comment by 4n0nym0u53** [comment]
@bananer if there's anything I can do, I'd be happy to help. I'm familier with Linux server management and Docker.

**Comment by cRaZy-bisCuiT** [comment]
I can also help do deploy a CI/CD Pipeline which is automatically building new images and informs you about the status.

**Comment by Iey4iej3** [comment]
By the way, if the builds are out once a month, then I would suggest that we apply the security patches every two months, so that there are two builds with the same security patch level, if possible. Otherwise, it would be troublesome if the package has a bug, since new Android does not allow us to revert to a nandroid backup with an earlier security patch level.

**Comment by 4n0nym0u53** [comment]
> By the way, if the builds are out once a month, then I would suggest that we apply the security patches every two months, so that there are two builds with the same security patch level, if possible. Otherwise, it would be troublesome if the package has a bug, since new Android does not allow us to revert to a nandroid backup with an earlier security patch level.

@Iey4iej3 I see your point, but from a security perspective I would prefer having security patches applied as soon as possible. ROMs like LOS/L4M are quite vulnerable by themselves (due to lack of verified boot, unlocked bootloader etc), so not having the latest security patch would worsen the issue IMO.

Also, why can't one revert to a NANDroid with an earlier security patch, if everything is wiped/formatted before reverting? Is something in the firmware or something updated with security patches which makes this impossible, or how does that work?

**Comment by bananer** [comment]
Security patches are merged by the LineageOS maintainers on their own schedule.

**Comment by kurt-by** [comment]
> Security patches are merged by the LineageOS maintainers on their own schedule.

You are right. Kernel security patches are merged by device maintainers. The security patch level you see in settings is from platform. Its usually merged by haggertk in the first half of each month

**Comment by Iey4iej3** [comment]
> > By the way, if the builds are out once a month, then I would suggest that we apply the security patches every two months, so that there are two builds with the same security patch level, if possible. Otherwise, it would be troublesome if the package has a bug, since new Android does not allow us to revert to a nandroid backup with an earlier security patch level.
> 
> @Iey4iej3 I see your point, but from a security perspective I would prefer having security patches applied as soon as possible. ROMs like LOS/L4M are already quite vulnerable by themselves (due to lack of verified boot, unlocked bootloader etc), so not having the latest security patch would worsen the issue IMO.
> 
> Also, why can't one revert to a NANDroid with an earlier security patch, if everything is wiped/formatted before reverting? Is something in the firmware or something updated with security patches which makes this impossible, or how does that work?

I am still not sure whether my understanding is correct, but it seems to me that, in order to restore a NANDroid backup with an earlier security patch level, we need to at least format `/data` partition because, if I understand correctly, the encryption key is encrypted with respect to the security patch level (I looked at [this document](https://source.android.com/security/keystore/version-binding)).

It seems much more difficult to format `/data` which wipes the internal storage. In my use case, it is even more complicated because I have work profiles (I did not even try to resume the backups of work profiles before).

**Comment by 4n0nym0u53** [comment]
> It seems much harder to format `/data` which wipes the internal storage. In my use case, it is even more complicated because I have work profiles (I did not even try to restore the backups of work profiles before).

@ley4iej3 when you do NANDroid backups, you usually backup `/data` as well, so wiping it shouldn't be a concern. Is it technically hard, or what do you mean by harder?

**Comment by Iey4iej3** [comment]
> > It seems much harder to format `/data` which wipes the internal storage. In my use case, it is even more complicated because I have work profiles (I did not even try to restore the backups of work profiles before).
> 
> @ley4iej3 when you do NANDroid backups, you usually backup `/data` as well, so wiping it shouldn't be a concern. Is it technically hard, or what do you mean by harder?

The usual backup (to be precise, today's TWRP backups are not really NANDroid) does not backup the internal storage (at least in TWRP). If there is no work profile, then I should also backup the internal storage, which is a bit more cumbersome (I don't know whether I need to use `tar` to backup the internal storage in order to keep the correct permissions - note that the current permission of the internal storage is a bit more complicated than it used to be; and I don't know whether the existence of SELinux would complicate it more).

The work profile complicates more because seemingly I need to recreate the work profile with the same user id, and then restore the backup. I don't know how to do that in practice (I am using [Shelter](https://github.com/PeterCxy/Shelter)).

**Comment by 4n0nym0u53** [comment]
> The usual backup (to be precise, today's TWRP backups are not really NANDroid) does not backup the internal storage (at least in TWRP). If there were no work profile, then I should also backup the internal storage, which is just a bit more cumbersome (I don't know whether I need to use `tar` to backup the internal storage in order to keep the correct permissions - note that the current permission of the internal storage is a bit more complicated than it used to be; and I don't know whether the existence of SELinux would complicate it more).
> 
> The work profile complicates more because seemingly I need to recreate the work profile with the same user id, and then restore the backup. I don't know how to do that in practice (I am using [Shelter](https://github.com/PeterCxy/Shelter)).

I've done backups with TWRP in the past, which backed up internal storage as well. I think that you need to enable encrypted backups to have it backup internal storage tho. Restoring that backup was no problem as well. I don't think I had a work profile, so can't say anything about that tho.

**Comment by Iey4iej3** [comment]
> > The usual backup (to be precise, today's TWRP backups are not really NANDroid) does not backup the internal storage (at least in TWRP). If there were no work profile, then I should also backup the internal storage, which is just a bit more cumbersome (I don't know whether I need to use `tar` to backup the internal storage in order to keep the correct permissions - note that the current permission of the internal storage is a bit more complicated than it used to be; and I don't know whether the existence of SELinux would complicate it more).
> > The work profile complicates more because seemingly I need to recreate the work profile with the same user id, and then restore the backup. I don't know how to do that in practice (I am using [Shelter](https://github.com/PeterCxy/Shelter)).
> 
> I've done backups with TWRP in the past, which backed up internal storage as well, tho I think that you need to enable encrypted backups to have it backup internal storage. Restoring that backup was no problem as well. I don't think I had a work profile, so can't say anything about that tho.

Unfortunately, the [official FAQ](https://twrp.me/faq/backupexclusions.html) says explicitly that it is impossible to back up the internal storage through GUI.

**Comment by bananer** [comment]
Started a new round of builds for all devices, with fix for #176

**Comment by Wyrrrd** [comment]
Are there efforts to bring 17.1 devices up to pace, or are they deprecated?

(Asking for my a5y17lte, which is now afraid of being finally abandoned after barely surviving the last update shortage...)

**Comment by bananer** [comment]
If nothing fails, all LineageOS official and some unofficial devices are getting builds, with versions 15.1 and up.

**Comment by kurt-by** [comment]
Justtt migrated a3xelte from lineageOS 17.1 to MicroG fork. Migration zip works. #176 is fixed. Security patch level is updated. Updater bug still present

**Comment by joshuaBS5** [comment]
Updated OTA on my a5y17lte (17.1) worked fine. Same:
> #176 is fixed. Security patch level is updated. Updater bug #171 still present
![IMG_20210626_060703_566](https://user-images.githubusercontent.com/41905170/123501390-daafb300-d644-11eb-84fa-dffa03c79f28.jpg)
Thank you all for your great work!

**Comment by kurt-by** [comment]
@bananer are you aware, you are building 17.1 for official 18.1 devices like lavender or klte?

**Comment by Akruidenberg** [comment]
> @bananer are you aware, you are building 17.1 for official 18.1 devices like lavender or klte?

Same for cedric

**Comment by bananer** [comment]
Current list of devices built:

18.1: ahannah,akari,akatsuki,aura,bacon,beckham,beryllium,blueline,bonito,bramble,cedric,channel,cheeseburger,chef,cheryl,chiron,coral,crosshatch,d800,d801,d802,d803,d850,d851,d852,d855,dipper,discovery,dumpling,enchilada,ether,evert,f400,fajita,flame,flox,gemini,gta4xlwifi,gts4lv,gts4lvwifi,guacamole,h830,h850,h910,h918,h990,hannah,hlte,hltechn,hltekor,hltetmo,hotdog,hotdogb,instantnoodle,instantnoodlep,jactivelte,jasmine_sprout,jason,jflteatt,jfltespr,jfltevzw,jfltexx,jfvelte,kebab,kirin,klte,klteactivexx,klteaio,kltechn,kltechnduo,klteduos,kltedv,kltekdi,kltekor,kuntao,lake,lavender,lemonadep,lithium,ls990,ls997,mata,mermaid,montana,nash,natrium,ocean,onclite,oneplus3,payton,pioneer,polaris,pro1,PL2,platina,redfin,rhannah,river,rs988,sagit,sargo,scorpio,shamu,sunfish,taimen,us996,victara,voyager,vs985,vs995,walleye,whyred,X00TD,X01AD,X01BD,x2,xz2c,YTX703F,YTX703L,Z01R,zippo,zl1

17.1: a3xelte,a5xelte,a5y17lte,a7xelte,a7y17lte,ahannah,akari,avicii,Amber,bardock,bardockpro,blueline,castor,cedric,chiron,crackling,crosshatch,d850,d851,d852,d855,davinci,enchilada,FP2,FP3,f400,fajita,ginkgo,guacamoleb,griffin,hannah,harpia,hlte,hltechn,hltekor,hltetmo,I001D,I01WD,j7elte,jason,kiwi,klte,klteactivexx,kltechn,kltechnduo,klteduos,kltedv,kltekdi,kltekor,kuntao,lavender,ls990,lux,m8,m8d,marlin,merlin,montana,nx563j,oneplus2,osprey,racer,rhannah,RMX1801,s2,s3ve3gds,s3ve3gjv,s3ve3gxx,s5neolte,sagit,sailfish,surnia,tissot,twolip,vs985,wayne,wt88047,xz2c,Z01R,z2_plus,z3,z3c

inofficial 17.1: crownlte,lavender,star2lte

inofficial 16: anne,berkeley,capricorn,charlotte,f1f,figo,find7,gts210vewifi,gts28vewifi,ham,kccat6,land,lentislte,mido,ms013g,r5,r7sf,r7plus,santoni,X00TD,X01BD,YTX703F,YTX703L,zangya,zangyapro,zenfone3

inofficial 15.1: angler,bullhead,che10,cherry,dogo,dragon,foster,fugu,hayabusa,huashan,mint,odin,pollux,pollux_windy,tsubasa,yuga


I would like to move the scripts to a publicly visible repo in the future.

**Comment by martin-v** [comment]
@bananer Nice, thx for your work!

**Comment by vanMacG** [comment]
> 
> 
> Current list of devices built:
> 
> 18.1: [...],klte,[...]
>
> I would like to move the scripts to a publicly visible repo in the future.

@bananer 
But in fact a 17.1 build was made (https://download.lineage.microg.org/klte/lineage-17.1-20210627-microG-klte.zip). 
The latest 18.1. build is from the run before (https://download.lineage.microg.org/klte/lineage-18.1-20210620-microG-klte.zip)

That's what's meant with the comments from @kurt-by & @Akruidenberg

**Comment by Iey4iej3** [comment]
And it seems to me that many devices have not been built (such as `polaris`). Maybe there are many errors?

**Comment by Akruidenberg** [comment]
> And it seems to me that many devices have not been built (such as `polaris`). Maybe there are many errors?

No 18.1 build for cedric yet.

**Comment by BonaBeavis** [comment]
What alternatives are there?

Until now I just found [/e/](https://e.foundation/de/).

**Comment by antoinevth** [comment]
From the download page and [this post](https://github.com/lineageos4microg/docker-lineage-cicd/issues/166#issuecomment-869768562), I have analysed what is going on (chronological order):
- official 17.1 builds : everything built except `m8`
- unofficial 17.1 builds : everything built
- unofficial 16.0 builds : everything built except `anne`, `berkeley`, `charlotte` and `figo`
- unofficial 15.1 builds : still waiting
- official 18.1 builds : still waiting

**Comment by bananer** [comment]
15.1 builds all failed for various reasons, 18.1 builds failed because the server was running out of disk space. 

Kicked off a new round now, starting with 18.1 and with remediation for the low disk space

@antoinevth thanks, I pulled the logs for the failed builds and put them into #197 - maybe someone can figure out how we could fix them.

**Comment by kurt-by** [comment]
Shouldn't  star2lte be named UNOFFICIAL-microG?

**Comment by bananer** [comment]
I've updated the list of devices to build for 17.1 and 18.1 from [LineageOS' CI configuration](https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets) and will start a new round of builds now.

**Comment by kurt-by** [comment]
18.1 bacon update went smoothly. August security patches included. MicroG is still 0.2.19 but update to 0.2.21 was OK with f-droid after switching repository.

**Comment by choduram** [comment]
> I've updated the list of devices to build for 17.1 and 18.1 from [LineageOS' CI configuration](https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets) and will start a new round of builds now.

Hey man, when you get the time pl. check the ota json file for s10e beyond0lte https://download.lineage.microg.org/beyond0lte/ even after updating the single release via the updater, shows the same update as available - not a biggie, just fyi

Thanks

**Comment by kurt-by** [comment]
> > I've updated the list of devices to build for 17.1 and 18.1 from [LineageOS' CI configuration](https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets) and will start a new round of builds now.
> 
> Hey man, when you get the time pl. check the ota json file for s10e beyond0lte https://download.lineage.microg.org/beyond0lte/ even after updating the single release via the updater, shows the same update as available - not a biggie, just fyi
> 
> Thanks

I guess your device updated correctly. It should now show august security patch level. Showing already installed updates as installable is a known bug.

**Comment by choduram** [comment]
> 18.1 bacon update went smoothly. August security patches included. MicroG is still 0.2.19 but update to 0.2.21 was OK with f-droid after switching repository.

Could you pl. share how to switch repository and to which one to get the latest microG

**Comment by kurt-by** [comment]
F-droid settings repositories (disable f-droid) back latest (swipe down)

12.08.2021 07:24:58 choduram ***@***.***>:

**Comment by bananer** [comment]
As explained [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/197#issuecomment-918110759), there should now be two builds per month for the following devices:

- All 18.1 and 17.1 devices that [LineageOS builds](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets) (list updates automatically)
- For 17.1 additionally `jfltexx, crownlte, star2lte`
- For 16.0 `capricorn, f1f, find7, gts210vewifi, gts28vewifi, ham, kccat6, land, lentislte, mido, ms013g, r5, r7sf, r7plus, santoni, X00TD, X01BD, YTX703F, YTX703L, zangya, zangyapro, zenfone3`
- For 15.1 `angler, bullhead, che10, cherry, dogo, dragon, foster, fugu, hayabusa, huashan, mint, odin, pollux, pollux_windy, tsubasa, yuga`

If you would like to have another device/branch included in the official builds, I would require some support in making it happen. Please verify at least that it can be built with the docker image, then open a new issue.

**Comment by Mhowser** [comment]
> As explained [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/197#issuecomment-918110759), there should now be two builds per month for the following devices:
> 
> * All 18.1 and 17.1 devices that [LineageOS builds](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets) (list updates automatically)
> * For 17.1 additionally `jfltexx, crownlte, star2lte`
> * For 16.0 `capricorn, f1f, find7, gts210vewifi, gts28vewifi, ham, kccat6, land, lentislte, mido, ms013g, r5, r7sf, r7plus, santoni, X00TD, X01BD, YTX703F, YTX703L, zangya, zangyapro, zenfone3`
> * For 15.1 `angler, bullhead, che10, cherry, dogo, dragon, foster, fugu, hayabusa, huashan, mint, odin, pollux, pollux_windy, tsubasa, yuga`

Could this information be added to the project website? This will help out newcomers looking for a new build like I was a few hours ago.

**Comment by kurt-by** [comment]
That was 2021

**Comment by Mhowser** [comment]
I should have been more specific, sorry. I was asking if just the target build dates could be included somewhere on the website if not already. Or perhaps there could be a build server status page, too.

**Comment by petefoth** [comment]
There are a number of changes needed to the website. However I have limited time to spend on this project, and my  main focus is ensuring that the monthly builds get delivered without problems. Also, working on this project is not the only thing I do in my spare time, so I have not got round to doing any of the several updates that are needed to the website.

Until I have the time to make changes to the website, there is [a section in the README.md](https://github.com/lineageos4microg/docker-lineage-cicd#web-site-text) which says
> ### Web Site Text
>
> The following should be published on [the LineageOS for microG website](https://lineage.microg.org/). It is included here until the website can be updated

To address your specific points, 
> the target build dates could be included somewhere on the website if not already.

& 
> Or perhaps there could be a build server status page, too.

[that section in the README](https://github.com/lineageos4microg/docker-lineage-cicd#build-targets-and-frequency) says
> We currently make builds monthly, starting on the first day of the month. The devices included in a build run are defined by the content of the [LOS target list](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets) at the point the build run starts. Our monthly build run takes 15-16 days to complete. You can see the current status of the build in [the dedicated matrix room](https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net)

That is as much information as we can provide, and I think it is enough

**Comment by Mhowser** [comment]
Ah, I missed that section! Thank you for clarifying everything!
