### ISSUE TITLE
Modify max RAM usage

### ISSUE THREAD

**Issue by Roxxor91** [lineageos4microg/docker-lineage-cicd#167]
Hi,
I am at the moment building LOS 17.1 for oneplus 3, I hope it works out. But there is a setting which is slowing down the process. I see that max RAM usage is set as 2GB. I still got 11GB to spare. Is there a way to modify this setting using docker variables?

Thanks!

**Comment by thepartisan** [comment]
See https://github.com/lineageos4microg/docker-lineage-cicd/issues/159#issuecomment-803646134
