### ISSUE TITLE
Please, provide last update for kccat6

### ISSUE THREAD

**Issue by bege10** [lineageos4microg/docker-lineage-cicd#169]
LineageOS seems to have stopped support for Galaxy S5 Plus. The last update is 20210211, the last one from LineageOS for microG is 20210128 . Can you, please, provide this probably last update for this device for LineageOS for microG?

**Comment by kurt-by** [comment]
@bananer does that mean we will get no last round of 16.0 builds?
https://github.com/lineageos4microg/docker-lineage-cicd/commit/b4ee898f3f0bb9ff580b132a311e30f735160613

**Comment by bananer** [comment]
@kurt-by I did not remove the option to build older versions. Even 14.1 should still work https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L90

**Comment by Ammako** [comment]
Could've sworn I had replied to this... guess it never actually went through.

You really should just be making your own builds, at this point. One final official update with February's patches might seem nice, but you'd already be missing March's patches, and soon April's, and it would only get worse from then on.

What kind of computer do you have? As long as your processor is good enough and that it has enough memory, you should be able to make your own builds every month. I'll walk you through it if you need to.

**Comment by bege10** [comment]
> 
> 
> Could've sworn I had replied to this... guess it never actually went through.
> 
> You really should just be making your own builds, at this point. One final official update with February's patches might seem nice, but you'd already be missing March's patches, and soon April's, and it would only get worse from then on.
> 
> What kind of computer do you have? As long as your processor is good enough and that it has enough memory, you should be able to make your own builds every month. I'll walk you through it if you need to.

Thank you very much for your answer. I will not try to make my own builds because I don't want to spend more time at the computer as I do already. And my computer is rather slow.
Do you know who we owe the unofficial build that is now available for download?

**Comment by Ammako** [comment]
> Do you know who we owe the unofficial build that is now available for download?

No idea, but I guess they may have opted to continue making new builds for the microG fork despite the official LineageOS being discontinued for your device, so it seems you're in luck.
