### ISSUE TITLE
Microg not there after successful build

### ISSUE THREAD

**Issue by ceptonit** [lineageos4microg/docker-lineage-cicd#17]
Phone: Sony Xperia Z5 (sumire)

The prebuilds available on https://lineage.microg.org/ for the sumire don't seem to have microg in them.
They're just basic Lineage with FDroid and GSF pre-installed. No sign of microg in the app list.
I also have an old Nexus 4 (mako) and the builds are fine (microg in the app list and no GSF).

I tried building for my sumire and while the build goes without problem, the result after flashing the build is the same: No microg.

```
docker run \
    -e "BRANCH_NAME=cm-14.1" \
    -e "DEVICE_LIST=sumire" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -v "/hdd/lineage/src:/srv/src" \
    -v "/hdd/lineage/zips:/srv/zips" \
    -v "/hdd/lineage/logs:/srv/logs" \
    -v "/hdd/lineage/cache:/srv/ccache" \
    -v "/hdd/lineage/keys:/srv/keys" \
    -v "/hdd/lineage/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
```

The apk manifest is included in "/hdd/lineage/manifests":

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="lineageos4microg/android_prebuilts_prebuiltapks" path="prebuilts/prebuiltapks" remote="github" revision="master" />
</manifest>
```

Here's the log:
[lineage-14.1-20180621-UNOFFICIAL-sumire.log.txt](https://github.com/lineageos4microg/docker-lineage-cicd/files/2125454/lineage-14.1-20180621-UNOFFICIAL-sumire.log.txt)

**Comment by corna** [comment]
From your log it seems it was installed, line 149039.

Moreover all the microG apps seem to be present in `lineage-14.1-20180617-microG-sumire.zip`:

```
sumire-zip/system# ls priv-app/
AudioFX			   CalendarProvider	  CtsShimPrivPrebuilt	   EmergencyInfo	      FusedLocation	   MediaProvider	 Recorder	      StatementService	TelephonyProvider  WeatherManagerService
BackupRestoreConfirmation  CallLogBackup	  DefaultContainerService  ExtServices		      Gallery2		   MmsService		 Settings	      StorageManager	TimeKeep	   WeatherProvider
BlockedNumberProvider	   CarrierConfig	  Dialer		   ExternalStorageProvider    GmsCore		   MtpDocumentsProvider  SettingsProvider     SystemUI		Trebuchet
CMAudioService		   CellBroadcastReceiver  DocumentsUI		   FDroidPrivilegedExtension  InputDevices	   OneTimeInitializer	 SharedStorageBackup  Tag		Updater
CMParts			   Contacts		  DownloadProvider	   FMRadio		      LineageSetupWizard   PackageInstaller	 Shell		      TeleService	VpnDialogs
CMSettingsProvider	   ContactsProvider	  Eleven		   FakeStore		      ManagedProvisioning  ProxyHandler		 Snap		      Telecom		WallpaperCropper
```

As you can see GmsCore and FakeStore are present. Are you sure microG is missing?

**Comment by ceptonit** [comment]
Microg just doesn't show in the app list somehow, so I have no access to any microg settings.
And Google services seems to be installed when it shouldn't be... I'm really at a loss here.
Looking in the /system/priv-app folder, it looks like I have "GmsCoreSetupPrebuilt" instead of "GmsCore".

![screenshot_20180623-010014](https://user-images.githubusercontent.com/12678743/41807488-55b68368-7684-11e8-93e5-b5300cb7f257.png)
![screenshot_20180623-010315](https://user-images.githubusercontent.com/12678743/41807489-55d3b6a4-7684-11e8-978b-c79bf150aff1.png)

Here are 2 screenshots. These are from a brand clean flash.
Does Lineage actually come with Google Services pre-installed for the sumire? Because on my Nexus 4, it sure doesn't.

**Comment by corna** [comment]
Have you wiped the /system partition before installing LineageOS for microG? It could be that the update scripts have preserved the GApps during the flash process.

**Comment by ceptonit** [comment]
Oh man, I was actually filming this to show you, so I did a "Format Data", then a "Factory Reset", then a "Advanced Wipe" with everything checked except "Micro SD card", then installed Lineage-microg and guess what, it's all working now O.o
I could swear I did that before and it never worked but hey, it all works out now.
I feel stupid for wasting your time, thanks man.

**Comment by corna** [comment]
No worries, happens ;)
