### ISSUE TITLE
More frequent builds

### ISSUE THREAD

**Issue by Iey4iej3** [lineageos4microg/docker-lineage-cicd#170]
I hope that we can build more frequently. For me, I am running polaris, which is built only once a month. The problem is that, once there is a bug in the latest version, if I understand correctly, I can at least rollback to an earlier version with the same level of security patch. Although I backup before every update, I have just found that, after restoring a backup, the system no longer boots. Seemingly there is some machinery to obstruct reverting too far.

**Comment by bananer** [comment]
Thanks, let's keep the discussion for this in #166
