### ISSUE TITLE
The installed version is available as an update

### ISSUE THREAD

**Issue by antoinevth** [lineageos4microg/docker-lineage-cicd#171]
Firstly, thanks all for the great work.

Currently, running `lineage-18.1-20210402-microG-dumpling` from [download.lineage.microg.org](https://download.lineage.microg.org), the updater shows an available update which is the one installed (it runs circle, I tried). As this issue isn't in LineageOS without microG, I guess it's a bug from the Lineage for MicroG build.

Am I the only one facing this (minimal) issue ?

**Comment by kurt-by** [comment]
Its a common issue. Thanks for reporting.

**Comment by bananer** [comment]
I saw the same issue in my own setup and traced it back to a bug in LineageOTA: https://github.com/julianxhokaxhiu/LineageOTA/pull/68

Might be fixable just by updating to the latest version of it.

**Comment by kurt-by** [comment]
I don't see, where that should show up in source code

**Comment by bananer** [comment]
In my case, the OTA server could not determine the zip's build id correctly and used some default value. The updater app then did not identify it as the currently installed build.

**Comment by uok** [comment]
The updater seems to check "https://download.lineage.microg.org/ota/full/<devicename>" which is empty

**Comment by antoinevth** [comment]
@bananer as you now have access to the servers (if I understood it right), would you try to resolve this issue by updating the OTA server ?

**Comment by bananer** [comment]
> @bananer as you now have access to the servers (if I understood it right), would you try to resolve this issue by updating the OTA server ?

The official l4m download server does not use https://github.com/julianxhokaxhiu/LineageOTA but a custom script. I'm not yet comfortable enough to change that.

**Comment by kurt-by** [comment]
> > @bananer as you now have access to the servers (if I understood it right), would you try to resolve this issue by updating the OTA server ?
> 
> The official l4m download server does not use https://github.com/julianxhokaxhiu/LineageOTA but a custom script. I'm not yet comfortable enough to change that.

Could we gain comfort by seting up a test system with that custom script.? Can that server setup be shared in github?

**Comment by spolack** [comment]
I've extended the script, which is now called mini_ota to compare the timestamp of the by-device sent incremental version against the set of returned versions. hacky, but robust, yet simple. Gives us some time for a migration to a proper tool.

https://github.com/lineageos4microg/mini_ota

**Comment by kurt-by** [comment]
@spolack i just updated Bacon and the buggy behaviour did not change. Do we have to wipe anything, for mini_ota to work correctly?

**Comment by spolack** [comment]
@kurt-by

From my perspective it seems to work as expected. What build are you running?

Compare 
lineage-18.1-20211202-microG-bacon.zip -> https://lineage.microg.org/api/v1/bacon/microg/eng.root.20211202.040742
vs
lineage-18.1-20220102-microG-bacon.zip -> https://lineage.microg.org/api/v1/bacon/microg/eng.root.20220102.033154

**Comment by kurt-by** [comment]
![Screenshot_20220103-153222_Updater](https://user-images.githubusercontent.com/26526996/147942784-de21d249-f340-4b9b-8bdb-c451fa904ab2.png)

**Comment by spolack** [comment]
Likely i was able to identify you in the logs. From my persepective it looks how it should (check the last digit which indicates the size of the response) -  so i assume its an issue with your updater application. Maybe clear cache for it? 
```
"REDACTED - - [03/Jan/2022:11:49:28 +0000] \"GET /api//v1/bacon/microg/eng.root.20211216.041051 HTTP/1.1\" 200 250"
"REDACTED - - [03/Jan/2022:13:31:35 +0000] \"GET /api//v1/bacon/microg/eng.root.20211216.041051 HTTP/1.1\" 200 250"
"REDACTED - - [03/Jan/2022:13:35:16 +0000] \"GET /api//v1/bacon/microg/eng.root.20211216.041051 HTTP/1.1\" 200 250"
"REDACTED - - [03/Jan/2022:14:00:56 +0000] \"GET /api//v1/bacon/microg/eng.root.20211216.041051 HTTP/1.1\" 200 250"
"REDACTED - - [03/Jan/2022:14:03:01 +0000] \"GET /api//v1/bacon/microg/eng.root.20220102.033154 HTTP/1.1\" 200 15"
"REDACTED - - [03/Jan/2022:14:03:14 +0000] \"GET /api//v1/bacon/microg/eng.root.20220102.033154 HTTP/1.1\" 200 15"
"REDACTED - - [03/Jan/2022:14:31:51 +0000] \"GET /api//v1/bacon/microg/eng.root.20220102.033154 HTTP/1.1\" 200 15"
"REDACTED - - [03/Jan/2022:14:31:59 +0000] \"GET /api//v1/bacon/microg/eng.root.20220102.033154 HTTP/1.1\" 200 15"
"REDACTED - - [03/Jan/2022:14:32:06 +0000] \"GET /api//v1/bacon/microg/eng.root.20220102.033154 HTTP/1.1\" 200 15"
"REDACTED - - [03/Jan/2022:14:32:08 +0000] \"GET /api//v1/bacon/microg/eng.root.20220102.033154 HTTP/1.1\" 200 15"
"REDACTED - - [03/Jan/2022:14:34:11 +0000] \"GET /api/v1/bacon/microg/eng.root.20211202.040742 HTTP/2.0\" 200 486"
````

**Comment by kurt-by** [comment]
Clearing cache of updater changed nothing. After clearing storage i get "no new updates found"

**Comment by spolack** [comment]
Well, this issue is being worked on in another repo which has to remain private for now, therefore you cant see the referencing pull request, which closed the ticket as it got merged.

**Comment by kurt-by** [comment]
Starting from what build should we see an improvement?

**Comment by kurt-by** [comment]
Just updated bacon to April 1st build. Updater still provides install button instead of "delete". Should I wipe anything for pull request to give visible effect?

**Comment by bananer** [comment]
> Starting from what build should we see an improvement?

It's not fixed yet. We will let you know here.

**Comment by bananer** [comment]
This should be fixed in builds starting May 1st.

**Comment by kurt-by** [comment]
> This should be fixed in builds starting May 1st.

Sorry, no
![Screenshot_20220505-174522_Updater](https://user-images.githubusercontent.com/26526996/166962452-88ca2d4e-4975-464f-a4cc-ab6c1c165b77.png)

**Comment by kurt-by** [comment]
Updating bacon from may 2 to may 6 finally shows: issue is fixed. All installed updates now show the option "delete"

**Comment by petefoth** [comment]
@kurt-by Is it OK to close this issue now?

Assigning back to you for a response

**Comment by kurt-by** [comment]
@petefoth confirmed. Issue can be closed.
