### ISSUE TITLE
Google device registration not sticking after reboot

### ISSUE THREAD

**Issue by adinechin** [lineageos4microg/docker-lineage-cicd#172]
I've built for my device with the following parameters : 
```
-e "BRANCH_NAME=lineage-15.1" \
-e "DEVICE_LIST=A6020" \
-e "SIGN_BUILDS=true" \
-e "SIGNATURE_SPOOFING=restricted" \
-e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
-e "INCLUDE_PROPRIETARY=false" \
-v "/home/adinechin/android/lineage/src:/srv/src" \
-v "/home/adinechin/android/lineage/zips:/srv/zips" \
-v "/home/adinechin/android/lineage/logs:/srv/logs" \
-v "/home/adinechin/.android-certs:/srv/keys" \
-v "/home/adinechin/android/lineage/manifests:/srv/local_manifests" \
```
The build went well and the ROM is booting, all is in place, but despite a successful auto-check, when I tick "Google device registration" and "Google Cloud Messaging" and reboot, the first one is not ticked anymore afterwards. And if I don't reboot, the installation and launch of an app with notifications does not appear in the microG settings.

**Comment by DPTJKKVH** [comment]
This is an issue you should rather post over at Marvin's microG repo than here. This project just grabs the official LineageOS code (which grabs a lot of ASOP code from Google) and ties it together with Marvin's microG code, all in a convenient docker image. This project doesn't do anything that you wouldn't do yourself if you would compile it by hand.

microG acting up is not an build issue but a software issue which should be reported in the respective software's repo. Good luck!
