### ISSUE TITLE
18.1 - DeadSystemException: The system died

### ISSUE THREAD

**Issue by hubbty** [lineageos4microg/docker-lineage-cicd#175]
A few days ago I upgraded from 17.1 to lineage-18.1-20210409-microG-cheeseburger. Since this upgrade the phone multiple times a day does kind of reboot. The screen goes black, mostly then the animated Lineage bootscreen appears. This process is clearly much faster than a real reboot.

In Logcat Reader I found several passages headed "FATAL EXCEPTION". So I guess there is a connection to the obove mentionned "crashes". I do not understand a thing about which errors these messages indicate. I can only present some examples to you, see attached file.

[logcat_fatal_errors.txt](https://github.com/lineageos4microg/docker-lineage-cicd/files/6314050/logcat_fatal_errors.txt)

**Comment by bananer** [comment]
Looks like https://github.com/microg/GmsCore/issues/1380 which should be fixed with the next release of GmsCore.

**Comment by ale5000-git** [comment]
@bananer: The new version with the fix got released.

**Comment by JuniorJPDJ** [comment]
@hubbty could you check if updating microG on your phone does actually fix the issue? If it does please close this ;)

**Comment by petefoth** [comment]
No response from original reporter, so I'll assume it's fixed

Closing
