### ISSUE TITLE
How to trim the required amount of ram when the build fails

### ISSUE THREAD

**Issue by slim8shady9** [lineageos4microg/docker-lineage-cicd#177]
I'm trying to complete an unofficial build for one divice but fails complaining the amount of RAM like this:
```
[ 98% 181/183] test android/soong/sdk
[ 99% 182/183] cp out/soong/.bootstrap/bin/soong_build
[100% 183/183] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: device/xiaomi/laurel_sprout/fod/Android.bp:16:1: "vendor.lineage.biometrics.fingerprint.inscreen@1.0-service.xiaomi_laurel_sprout" depends on undefined module "//hardware/xiaomi:vendor.xiaomi.hardware.fingerprintextension@1.0"
ninja: build stopped: subcommand failed.
18:31:43 soong bootstrap failed with: exit status 1

#### failed to build some targets (04:07 (mm:ss)) ####

>> [Sun Apr 18 18:31:43 UTC 2021] Failed build for laurel_sprout
>> [Sun Apr 18 18:31:43 UTC 2021] Finishing build for laurel_sprout
>> [Sun Apr 18 18:31:43 UTC 2021] Cleaning source dir for device laurel_sprout
18:31:47 ************************************************************
18:31:47 You are building on a machine with 15.7GB of RAM
18:31:47 
18:31:47 The minimum required amount of free memory is around 16GB,
18:31:47 and even with that, some configurations may not work.
18:31:47 
18:31:47 If you run into segfaults or other errors, try reducing your
18:31:47 -j value.
18:31:47 ************************************************************
18:31:48 Entire build directory removed.
```

Since I cannot modify RAM and swap on that machine, I'm looking for a way to trim the required resources during the build process.
I read this [#159 (comment)](https://github.com/lineageos4microg/docker-lineage-cicd/issues/159#issuecomment-803646134) and this [#132 (comment)](https://github.com/lineageos4microg/docker-lineage-cicd/issues/132#issuecomment-754129930)

[#132 (comment)](https://github.com/lineageos4microg/docker-lineage-cicd/issues/132#issuecomment-754129930) this didn't work for me since the build failed even with cpus=1

Can someone explain how to trim the ram value?

**Comment by bananer** [comment]
Building with 15.7GB on a single CPU core should take a long time but eventually work. You can probably ignore that warning.

I think your problem is somewhere else:

    error: device/xiaomi/laurel_sprout/fod/Android.bp:16:1: "vendor.lineage.biometrics.fingerprint.inscreen@1.0-service.xiaomi_laurel_sprout" depends on undefined module "//hardware/xiaomi:vendor.xiaomi.hardware.fingerprintextension@1.0"

Seems like your unofficial build is missing something. Maybe there is more info in the logs earlier.

**Comment by slim8shady9** [comment]
> Building with 15.7GB on a single CPU core should take a long time but eventually work. You can probably ignore that warning.

I tried but it fails anyway.

> I think your problem is somewhere else:
> 
> ```
> error: device/xiaomi/laurel_sprout/fod/Android.bp:16:1: "vendor.lineage.biometrics.fingerprint.inscreen@1.0-service.xiaomi_laurel_sprout" depends on undefined module "//hardware/xiaomi:vendor.xiaomi.hardware.fingerprintextension@1.0"
> ```
> 
> Seems like your unofficial build is missing something. Maybe there is more info in the logs earlier.

I will look into it.

Anyway, how can I trim the amount of ram needed? I face this problem with other devices too.

**Comment by bananer** [comment]
> Anyway, how can I trim the amount of ram needed? I face this problem with other devices too.

I heard that limiting the [number of cpu cores](https://docs.docker.com/config/containers/resource_constraints/#cpu) will make the build run fewer processes in parallel which in turn reduces how much ram is needed. However, I've never had problems building on a 16GB machine with 4 cores.

**Comment by slim8shady9** [comment]
I will give it another try.

> Seems like your unofficial build is missing something. Maybe there is more info in the logs earlier.

Thank you

> I heard that limiting the [number of cpu cores](https://docs.docker.com/config/containers/resource_constraints/#cpu) will make the build run fewer processes in parallel which in turn reduces how much ram is needed. However, I've never had problems building on a 16GB machine with 4 cores.

and thank you again

;)
