### ISSUE TITLE
Bacon 20210506 not patched

### ISSUE THREAD

**Issue by kurt-by** [lineageos4microg/docker-lineage-cicd#179]
Thank you for the new 18.1 build round. Sadly the the security level patch has not been merged yet
https://review.lineageos.org/c/LineageOS/android_build/+/309174

**Comment by Iey4iej3** [comment]
What is the current frequency of builds? Every two weeks or every month?

**Comment by bananer** [comment]
Thanks, let's keep the discussion for this in #166
