### ISSUE TITLE
Creating treble builds

### ISSUE THREAD

**Issue by sjdrc** [lineageos4microg/docker-lineage-cicd#18]
I am using a Pixel 2 XL and was wondering if I could use this docker image to compile an unofficial treble build.

There is a docker image for building the treble build [here](https://github.com/phhusson/treble_experimentations).

Thanks for your help.

**Comment by JuniorJPDJ** [comment]
Yes, GSI build would be super-cool for workaround for plenty of unsupported devices.

**Comment by kurt-by** [comment]
not necessary. There are enough GSIs with signature spoofing. Even LineageOS 17.1
[https://forum.xda-developers.com/showpost.php?p=81677561&postcount=322](https://forum.xda-developers.com/showpost.php?p=81677561&postcount=322)

**Comment by JuniorJPDJ** [comment]
> not necessary. There are enough GSIs with signature spoofing. Even LineageOS 17.1
> https://forum.xda-developers.com/showpost.php?p=81677561&postcount=322

But if we had "official" microG builds.. ;)

**Comment by bananer** [comment]
Closing this out of scope & old issue
