### ISSUE TITLE
Only userdebug builds are created by the container

### ISSUE THREAD

**Issue by bencejuhaasz** [lineageos4microg/docker-lineage-cicd#182]
The result of the build process is a userdebug build, not release, which leaves the recovery accessible to untrusted 3rd parties by disabling any authentication in it. Afaik this has been fixed in standard lineageos builds, why not allow the same level of security here too ? I can't find anything related to this in the build script... where is it defined, and can I change it ? Should be just in the parameter for lunch, but this one uses something called brunch instead, is this a lineage common practice ?

**Comment by bananer** [comment]
I think official LineageOS builds are also userdebug: https://github.com/LineageOS/hudson/blob/master/lineage-build-targets

You can find the source for the brunch command here: https://github.com/LineageOS/android_vendor_lineage/blob/lineage-18.1/build/envsetup.sh#L55

Seems like you could just add the variant as second argument. Should be "user", not "release" though.

**Comment by bencejuhaasz** [comment]
Thank you for the clarification, I'll try adding the argument in the build script

**Comment by bananer** [comment]
I'm assuming you were successful here
