### ISSUE TITLE
Why do we need to patch signature spoofing in?

### ISSUE THREAD

**Issue by gohanko** [lineageos4microg/docker-lineage-cicd#183]
If Google Play Services does not exists on the device in the first place, won't microg simply takes it place? afaik, microg is compiled in a way that it looks like play services so apps can interact with it.

**Comment by ArchangeGabriel** [comment]
In order for microG to “look like” PlayServices, it needs to spoof PlayServices signature. That’s exactly what the patch is for.

**Comment by gohanko** [comment]
I understand that part, but I'm not sure how it works. What is a signature? a md5 hash? the `com.google.maps` part of apps?, I was under the assumption that other apps access gplay by searching for its name, e.g `com.google.maps`  part of apps.

**Comment by FintasticMan** [comment]
Android apps have a signature, which acts kind of like a handwritten signature. A signature is generated using the developers' keys. Two different keys will always generate a different signature. Android uses this to make sure that, for example, an update to an app isn't made by a malicious party, by comparing the signatures.

The Google Play Services are signed with Google's signing key, which means that nobody else can make an app with the same signature. To use Google APIs, apps check whether the signature matches Google's. This is where signature spoofing comes in. MicroG wants to pretend to be Google Play Services, but for apps to trust it, they need to see Google's signature. Signature spoofing lets microG pretend to have Google's signature without having their signing key.

I hope I explained that well enough!

**Comment by gohanko** [comment]
Thank you @FintasticMan , its very clear.
