### ISSUE TITLE
[LineageOS 18][Pro1]  UnifiedNlp doesn't block GPS positioning

### ISSUE THREAD

**Issue by steffenWi** [lineageos4microg/docker-lineage-cicd#184]
Hi,

I used the image from [here](https://download.lineage.microg.org/pro1/).

Imagename: lineage-18.1-20210509-microG-pro1.zip 
Recovery-Image: lineage-18.1-20210509-microG-pro1-recovery.zip

I wiped my previous LineageOS installation, used fastboot to flash the recovery image and then sideloaded the zip file. All without error. Boot was successful and setup also didn't run into any issues.

When I now open the self-test everything I can see shows up checked. However, there is no mention or section for UnifiedNlp. When I go into the microG-settings I have the entry for location modules and I can install and select modules but that doesn't do anything. Applications that use location services still manage to get GPS locations and in the Settings => Location screen I don't see any further settings.

From searching around a bit there should - somewhere - be a setting screen for UnifiedNlp related things that doesn't seem to be accessible on this installation.

I didn't install any store yet so I only have the F-Store available. The application I used to test was SatStat. Given that there are no other people with this issue that I can find I'm assuming I'm missing something?

**Comment by steffenWi** [comment]
I now also tried lineage-17.1-20210330-microG-pro1.zip and the appropriate .img file. Same result. Next I went into the F-Droid store and searched for unifiedNlp. The version "(without GAPPS)" is marked as installed. Clicking the "Open" button just opens the microG settings application.

Installing the "(with GAPPS)" version and rebooting results in a UnifiedNlp application icon appearing that opens the UnifiedNlp settings app. Obviously it doesn't work as it can't bind to the system.

To me it seems like there is some issue when the UnifiedNlp application is added to the ROM? Though I don't understand why the application entry in the F-Droid store opens/links to the microG settings application.

**Comment by FintasticMan** [comment]
The UnifiedNlp settings should be under "Location modules" in the microG Settings app. There it lets you choose which backends you want to use. I don't have any issues with it, so I think there might be an issue with your build.  
Do check whether you can see "Location modules" in the settings first though, just to be sure.

**Comment by steffenWi** [comment]
I do have the setting entry for the modules. I also enabled the Mozilla module. How did you verify that the module you chose was actually utilized?

**Comment by FintasticMan** [comment]
I think that those checks have just been removed from the microG self-check, because I don't have them either, and UnifiedNlp is working fine for me.  I don't think there's any issue with not having it, as all of the apps I use are working fine.

**Comment by steffenWi** [comment]
Interesting. Thank you. Though I'd still like to know how you confirmed that UnifiedNlp is working?

**Comment by Iey4iej3** [comment]
There seems no longer the option to disable the device GPS and only use the network location, maybe starting from Android 9: https://www.reddit.com/r/tasker/comments/b154a6/location_modes_on_android_9/

**Comment by steffenWi** [comment]
Yes, I know about that. However I thought that the point of UnifiedNlp is to fix that.

**Comment by Iey4iej3** [comment]
No, UnifiedNlp is the provider for the network location, which appeared much earlier than Android 9, without which you don't have network location (unless you install other providers such as those in GApps).

**Comment by steffenWi** [comment]
That doesn't explain the reason for the different backends. If it were just a replacement, it would just require one GPS backend. Not multiple different cellular and wifi backends. In either case that is something for me to research and obviously not an issue with this project.

**Comment by Iey4iej3** [comment]
You *can* have multiple backends, but the "trusted" signatures of these backends are hardcoded in the OS (so the users cannot modify them directly, at least not in a non-intrusive fashion) and this project has a patch to add MicroG to this "trusted" list.

**Comment by steffenWi** [comment]
Sorry, yes I am aware of the multiple backends part. What I'm confused on is how the satellite based positioning 'backend' ties in to this and why it isn't 'manageable' like the other backends. I suspect the answer is that it isn't a backend at all and something tied into Android more directly at which point I'm a bit disappointed as I had looked forward to using UnifiedNlp to reduce my phone's battery consumption while still being able to use the Covid tracing app of my country.
