### ISSUE TITLE
blueline: needs WITH_GMS=true set to not fail

### ISSUE THREAD

**Issue by TinfoilSubmarine** [lineageos4microg/docker-lineage-cicd#185]
I've been building my own ROMs for fajita for personal use so that I have the latest and greatest and also to start trying to fix the issues with Verizon+RTT. 

I recently picked up a Pixel 3 (blueline) and wanted to install this same ROM so I tried to build it. However, it fails due to partition constraints. Luckily, we can change those constraints by passing WITH_GMS=true to the docker run. See the BoardConfig for blueline/crosshatch: https://github.com/LineageOS/android_device_google_crosshatch/blob/lineage-18.1/BoardConfigLineage.mk

**Comment by KenVanHoeylandt** [comment]
To recap the closed issue above: the same is happening for `kebab` and `redfin` devices.

**Comment by petefoth** [comment]
Recent builds of `blueline` & `kebab` are succeeding fine now

Closing
