### ISSUE TITLE
Migrate from Docker Hub Autobuilds to GitHub Actions

### ISSUE THREAD

**Issue by bananer** [lineageos4microg/docker-lineage-cicd#188]
Currently, with Docker Hub Autobuilds, every change to this repostory's master branch results in a new Docker image being built and hosted on Docker Hub. It was [announced recently](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/) that Docker Hub would no longer provide free build infrastructure.

It seems to me that the best way forward would be to use GitHub Actions for building the Docker image and pushing to Docker Hub. GitHub provides enough free build time to cover our needs and this would avoid depending on another service.

Documentation can be found here:

https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub
https://github.com/marketplace/actions/build-and-push-docker-images

Write access to https://hub.docker.com/r/lineageos4microg/docker-lineage-cicd would be granted to the action through a token in a [secret](https://docs.github.com/en/actions/reference/encrypted-secrets).

A good pull request for this should be tested on a separate GH repo and Docker Hub before being merged.

**Comment by bananer** [comment]
@4n0nym0u53 thanks for offering to help. Maybe this would be something for you to look into?

**Comment by martin-v** [comment]
Should be fixed with PR #189

@bananer if something fails after adding the secrets and merge mention it here or in PR, I will look into it.

**Comment by DPTJKKVH** [comment]
Two questions:

Docker Hub does offer [free autobuilds for open source projects](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/) that meet certain criteria. Did you consider using that option?

If I'm reading the announcement correctly Docker Hub does not remove free building altogether but only autobuilds for free plans. I know it might be annoying but as far as I can tell all that changes is that after merging a pull request on GitHub you have to click the build/trigger button on Docker Hub manually. Please correct me if I'm wrong.

![index-dashboard](https://user-images.githubusercontent.com/7238653/122688404-8e5f1000-d20b-11eb-9be1-33c8406a9444.png)

**Comment by bananer** [comment]
> Docker Hub does offer [free autobuilds for open source projects](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/) that meet certain criteria. Did you consider using that option?

I did consider this for a different project some time ago, applied and never got a response.

 
> If I'm reading the announcement correctly Docker Hub does not remove free building altogether but only autobuilds for free plans. I know it might be annoying but as far as I can tell all that changes is that after merging a pull request on GitHub you have to click the build/trigger button on Docker Hub manually. Please correct me if I'm wrong.
> 
> ![index-dashboard](https://user-images.githubusercontent.com/7238653/122688404-8e5f1000-d20b-11eb-9be1-33c8406a9444.png)

Trying to automate as much as I can here.

Another advantage we have with GH Actions is that PRs are built (not pushed), so we might catch mistakes earlier.

**Comment by bananer** [comment]
Excellent work, @martin-v !

https://hub.docker.com/repository/docker/lineageos4microg/docker-lineage-cicd/tags?page=1&ordering=last_updated
