### ISSUE TITLE
Is there a way to bundle my own build with magisk?

### ISSUE THREAD

**Issue by githtz** [lineageos4microg/docker-lineage-cicd#19]
Hi there,

I'm building microg.lineageos for my device on my server with this docker image. I'd like to somehow deliver it with magisk.

Currently when I update microg.lineageos on my device I always have to flash manually - first microg.lineageos and magisk afterwards.

For OTA-Updates it would be great if I just could use the updater that comes with lineageos, but therefore I'd need to somehow merge the magisk.zip into my lineageos build. 

Is that possible and if yes, can you provide any advice how to do so?

Many thanks in advance!

**Comment by asafniv** [comment]
You don't need to reflash magisk, it has an addon.d script

**Comment by githtz** [comment]
Damn, I didn't know about that. Thank you! But what about other stuff, for example a custom kernel?
