### ISSUE TITLE
Add option to manually change the number of jobs of build proccess

### ISSUE THREAD

**Issue by tchici** [lineageos4microg/docker-lineage-cicd#190]
I've noticed that the build process calls `ninja` with 10 jobs, then `ninja` sometimes calls `make` with 8 jobs, at least on my machine. This means that there are effectively 17 jobs running at the same time! I would like to be able to control the number of jobs (at least the top-level `ninja` one, but if it is possible to control both number of `ninja` jobs and `make` separately would be preferred).

Reasons:
1. Ability to build on desktop PC and still have a responsive desktop experience.
1. Possibly reducing the peak memory or RAM usage, allowing computers with less memory to complete the build faster (swap might be extremely slow depending on where it is).
1. Ability to increase the number of jobs for a server with a billion threads or something...

**Comment by bananer** [comment]
For the actual build, we are calling LineageOS' [brunch](https://github.com/LineageOS/android_vendor_lineage/blob/lineage-18.1/build/envsetup.sh#L55), which does not support e.g. passing options like `-j` further down to `ninja`.

I've head some success throttling the cpu usage using docker's `--cpus` [option](https://docs.docker.com/config/containers/resource_constraints/).

**Comment by tchici** [comment]
> For the actual build, we are calling LineageOS' [brunch](https://github.com/LineageOS/android_vendor_lineage/blob/lineage-18.1/build/envsetup.sh#L55), which does not support e.g. passing options like `-j` further down to `ninja`.

I just looked into it. It looks like `brunch` calls `breakfast` for some setup, then `mka bacon`, and, I think, here is the problem. `mka` is a simple wrapper to `m` with the option `-j` empty (which makes it default to all processors---again, I think). Also, `m` is another wrapper to `_triger_build "all-modules" "$@"`, etc..

So, I think it is possible to do something like this: call `breakfast $codename` manually, then `m -j$JOBS bacon`. I haven't tried it, and I am not sure how I would try (new to docker).

There might be an "official" way to do this, but I cannot find the documentation on the LineageOS build instructions wiki page.

> I've head some success throttling the cpu usage using docker's `--cpus` [option](https://docs.docker.com/config/containers/resource_constraints/).

`--cpus` might throttle cpu usage, but I think it will still expose the host system's cpu count, and `mka` creates that number of jobs, so the peak memory usage doesn't change. Reading through `docker-run` `man` page, I think `--cpuset-cpus` might work better, as it actually changes the number of processors the container sees.

If `--cpuset-cpus` works, then I think I can close this issue. I will try it later and come back (maybe a week or two or more).

**Comment by tchici** [comment]
Using the `--cpuset-cpus 0-3` docker option does indeed work. The build system seems to use the number of processors plus 2 for the `ninja` invocation, and it uses just the number of processors for the `make` invocation. I would assume if we wanted more precise control then the issue should be raised to LineageOS, not here (or maybe the method already exists but I'm not sure how).

Here is some documentation from the man page: <https://www.mankier.com/1/docker-run#--cpuset-cpus>.
