### ISSUE TITLE
Build failing "ext2fs_check_mount_point: Can't check if filesystem is mounted due to missing mtab file"

### ISSUE THREAD

**Issue by Kranzes** [lineageos4microg/docker-lineage-cicd#193]
Ive tried building for a couple of devices already, supported and unsupported (officially).
They all seem to fail at about the same point with the same error.
I am getting this error on both 17.1 and 18.1.
The error is *see picture*
![image](https://user-images.githubusercontent.com/56614642/123292154-70e7ba00-d51b-11eb-9bbc-9dafddb9ff95.png)

**Comment by bananer** [comment]
What's the exact command you use to run the build? Does your computer have enough disk space and RAM?

**Comment by Kranzes** [comment]
```
podman run \
    -e "BRANCH_NAME=lineage-18.1" \
    -e "DEVICE_LIST=miatoll" \
    -e "SIGN_BUILDS=true" \
    -e "INCLUDE_PROPRIETARY=false" \
    -e "CCACHE_SIZE=200G" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore" \
    -e "TARGET_FLOS=true" \
    -v "/home/4TB-HDD/android/lineage:/srv/src" \
    -v "/home/4TB-HDD/android/zips:/srv/zips" \
    -v "/home/4TB-HDD/android/logs:/srv/logs" \
    -v "/home/4TB-HDD/android/keys:/srv/keys" \
    -v "/home/4TB-HDD/android/manifests:/srv/local_manifests" \
    -v "/home/4TB-HDD/android/ccache:/srv/ccache" \
    localhost/forklineageos:latest
```
 I also have 16 gigs of ram, which i know for a fact that its enough to build successfully because i have managed to build this before without the container image.
 btw this custom forklineageos image is the same as the stock one without one but it uses a different manifest, though i got this error when building an official device with the official image.
