### ISSUE TITLE
OTA information missing

### ISSUE THREAD

**Issue by tduboys** [lineageos4microg/docker-lineage-cicd#198]
Hi all,

First, thanks for all works, this ROM is working great on my case.

I'm building my own ROM (to add custom packages…) and I've some issues with OTA servers.
I wanted to discuss, for each, where is the best place to fix (documentation, PR here, PR on other git repo…)

- Lineage 18.1 only works with https ota url 
-> I dont know if it's related to 18.1, I suppose that the best place is to add an information in the README here
-> I didnt see any infos about that, but it's the error I got on `adb logcat` during an OTA update when I didnt use https

- LineageOTA docker image does not read ro.lineage.releasetype on build.prop file, it detects the release type by parsing zip file name. But if your release type includes `-`, it does not works as your device will get `/api/v1/{model_name}/{type}/{incremental version}`

For example, my release type was `microg-tduboys`, on my akari, so my phone tries `/api/v1/akari/microg-tduboys/eng.root.20210626.133439`, but LineageOTA docker image need `/api/v1/akari/microg/eng.root.20210626.133439` to work.

I suppose there is 3 way to help on this second issue : 
- adding documentation to do not use `-` on release type
- forcing this docker image to replace `-` by `_` (as an example) with a warning
- fix lineageOTA docker image to read `ro.lineage.releasetype` properties if exists

As I dont know if the `ro.lineage.releasetype` property is an official lineage property or not, I dont know what is the best way to help users.

Thanks

**Comment by antoinevth** [comment]
Hi !

I guess your issues are more related to this repo : https://github.com/julianxhokaxhiu/LineageOTA

**Comment by tduboys** [comment]
Hi,
I just added it on LineageOTA repository, PR is now merged (about reading `ro.lineage.releasetype`)

Maybe we can add a note in README regarding https restriction ? But I dont know when Lineage added this restriction (Updater does not work on http, he needs an https link).
Thanks

**Comment by FintasticMan** [comment]
> Make always sure to provide a HTTPS based uri, otherwise the updater will reject to connect with your server! This is caused by the security policies newer versions of Android (at least 10+) include, as any app wanting to use non-secured connections must explicitly enable this during the compilation. The LineageOS Updater does not support that.

It says this in the LineageOTA readme

**Comment by JuniorJPDJ** [comment]
I suspect it can be closed as it has been resolved in upstream

**Comment by bananer** [comment]
If you would like to add something about https requirement to this repo's readme, feel free to create a pull request!
