### ISSUE TITLE
Boot images

### ISSUE THREAD

**Issue by Iey4iej3** [lineageos4microg/docker-lineage-cicd#200]
To install `magisk`, it is recommended to patch the boot image.

Currently, we can download the build, extract the boot image and do the patch. However, it might be a bit cumbersome to do so if I download the package from Lineage OS. It seems better if

1. The built boot image is directly downloadable.
2. Or, there is an app to extract the boot image from the downloaded build.

**Comment by kurt-by** [comment]
Most lineageOS devices work well with recovery method
https://topjohnwu.github.io/Magisk/install.html#custom-recovery

**Comment by AreYouLoco** [comment]
What about patching the boot image on pc and then signing it to be able to relock the bootloader? Is it doable?

**Comment by kurt-by** [comment]
@AreYouLoco no

**Comment by AreYouLoco** [comment]
May I adk why not?

**Comment by Iey4iej3** [comment]
The reason to patch on the Android device is that Magisk collects the necessary information on the running Android to decide how to patch the boot image. Some of these information might not be easily obtained (or even lacking) from the boot image.

**Comment by AreYouLoco** [comment]
What about this: https://github.com/topjohnwu/Magisk/issues/2859
