### ISSUE TITLE
Devices build in multiple versions

### ISSUE THREAD

**Issue by antoinevth** [lineageos4microg/docker-lineage-cicd#203]
Actually, there are many devices that are build in multiple versions:

Devices | `18.1` | `17.1` | `unofficial 17.1` | `unofficial 18.1`
----------- | ----------- | ----------- | ----------- | -----------
`ahannah` | :heavy_check_mark: | :heavy_check_mark:
`akari` | :heavy_check_mark: | :heavy_check_mark:
`blueline` | :heavy_check_mark: | :heavy_check_mark:
`cedric` | :heavy_check_mark: | :heavy_check_mark:
`chiron` | :heavy_check_mark: | :heavy_check_mark:
`crosshatch` | :heavy_check_mark: | :heavy_check_mark:
`d850` | :heavy_check_mark: | :heavy_check_mark:
`d851` | :heavy_check_mark: | :heavy_check_mark:
`d852` | :heavy_check_mark: | :heavy_check_mark:
`d855` | :heavy_check_mark: | :heavy_check_mark:
`enchilada` | :heavy_check_mark: | :heavy_check_mark:
`f400` | :heavy_check_mark: | :heavy_check_mark:
`fajita` | :heavy_check_mark: | :heavy_check_mark:
`hannah` | :heavy_check_mark: | :heavy_check_mark:
`hlte` | :heavy_check_mark: | :heavy_check_mark:
`hltechn` | :heavy_check_mark: | :heavy_check_mark:
`hltekor` | :heavy_check_mark: | :heavy_check_mark:
`hltetmo` | :heavy_check_mark: | :heavy_check_mark:
`jason` | :heavy_check_mark: | :heavy_check_mark:
`klte` | :heavy_check_mark: | :heavy_check_mark:
`klteactivexx` | :heavy_check_mark: | :heavy_check_mark:
`kltechn` | :heavy_check_mark: | :heavy_check_mark:
`kltechnduo` | :heavy_check_mark: | :heavy_check_mark:
`klteduos` | :heavy_check_mark: | :heavy_check_mark:
`kltedv` | :heavy_check_mark: | :heavy_check_mark:
`kltekdi` | :heavy_check_mark: | :heavy_check_mark:
`kltekor` | :heavy_check_mark: | :heavy_check_mark:
`kuntao` | :heavy_check_mark: | :heavy_check_mark:
`lavender` | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
`ls990` | :heavy_check_mark: | :heavy_check_mark:
`montana` | :heavy_check_mark: | :heavy_check_mark:
`rhannah` | :heavy_check_mark: | :heavy_check_mark:
`sagit` | :heavy_check_mark: | :heavy_check_mark:
`vs985` | :heavy_check_mark: | :heavy_check_mark:
`X00TD` | :heavy_check_mark: | | | :heavy_check_mark:
`X01BD` | :heavy_check_mark: | | | :heavy_check_mark:
`xz2c` | :heavy_check_mark: | :heavy_check_mark:
`YTX703F` | :heavy_check_mark: | | | :heavy_check_mark:
`YTX703L` | :heavy_check_mark: | | | :heavy_check_mark:
`Z01R` | :heavy_check_mark: | :heavy_check_mark:

This table is based on https://github.com/lineageos4microg/docker-lineage-cicd/issues/166#issuecomment-869768562

I don't think supporting lower or unofficial versions is necessary when higher or official versions are available.
Reducing the number of versions to build will help us in the goal of weekly updates.

**Comment by Ammako** [comment]
I think there are valid reasons to have both 17.1 and 18.1 builds for the same devices, due to certain things not quite working yet on Android 11 it's good for users to be able to stick with 10 until things that they need are functional on 11. Unofficial builds are totally unnecessary though when official builds for the same version exist.

Besides, 17.1 is still supported and maintained, so I think it's worth keeping it around at least until support ends.

**Comment by bananer** [comment]
I've updated the list of devices to build from [LineageOS' build configuration](https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets), which means devices where 18.1 is supported are no longer build for 17.1

As you said, this should reduce the overall build time.

If there are good reasons to keep 17.1 builds for a device please create a new issue and I will consider it.
