### ISSUE TITLE
LOS 18.1 build with com.android.email possible?

### ISSUE THREAD

**Issue by michaelschefczyk** [lineageos4microg/docker-lineage-cicd#204]
Dear All,

I would very much to include the AOSP email app in my LOS 18.1 build because this should bring back activesync ("Exchange") mail, calendar, and contact sync with an open source app.

The following does not work:

1) Build with docker run -e "BRANCH_NAME=lineage-18.1" -e "DEVICE_LIST=flox" -e "SIGN_BUILDS=true" -e "SIGNATURE_SPOOFING=restricted" -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension com.android.email " -v "/mnt/lineage:/srv/src" -v "/mnt/zips:/srv/zips" -v "/mnt/logs:/srv/logs" -v "/mnt/cache:/srv/ccache" -v "/mnt/keys:/srv/keys" -v "/mnt/manifests:/srv/local_manifests" lineageos4microg/docker-lineage-cicd

2) Add the following to the manifests folder (could not find an Android 11 version): https://android.googlesource.com/platform/packages/apps/Email/+/refs/heads/android10-release/AndroidManifest.xml

When building that way, no e-mail app is visible - just like in the regular LOS 18.1 build.

Regards,

Michael Schefczyk

**Comment by bananer** [comment]
AOSP email app was dropped from upstream LineageOS in 18.1.

Totally unsupported by lineageos4microg or me: You can add the version from 17.1 branch to your build with a local manifest file like this: https://github.com/bananer/android_manifests/blob/master/apps_from_17.1.xml

**Comment by michaelschefczyk** [comment]
As far as I could try so far with an old jfltexx device (increasing BOARD_SYSTEMIMAGE_PARTITION_SIZE was required), this does lead to a build of LOS 18.1 with full email and activesync/exchange functionality as it did exist in LOS 17.1.

This should at least be mentioned under Examples/README.md

LOS 18.1 users wanting to use activesync would otherwise have to use nonfree apps or move to GAAPS altogether!

Thanks to Philip Nagler-Frank!!

**Comment by lp35** [comment]
Hi, 

Same probleme here, exchange vanished from 18.1.

We badly need it!
