### ISSUE TITLE
No LineageOS for MicroG 18.1 builds for apollon (Xiaomi Mi 10T / Mi 10T Pro / Redmi K30S Ultra)

### ISSUE THREAD

**Issue by Sotcitt** [lineageos4microg/docker-lineage-cicd#207]
My device is apollon, it is officially supported by LineageOS, but I did not find the build in the downloads page.

**Comment by Diapolo** [comment]
That's also the case for FP2 (https://download.lineageos.org/FP2/changes).

**Comment by bananer** [comment]
I've updated the list of devices to build and started a new round of builds. If all goes well, downloads should be available in 3-10 days. Otherwise, please reopen this issue.
