### ISSUE TITLE
Rebuild to eliminate touch input issues

### ISSUE THREAD

**Issue by parcelcat** [lineageos4microg/docker-lineage-cicd#209]
Is it possible to immediately rebuild the images to eliminate the LineageOS touch input bugs that were recently fixed?

During the week of the most recent build (starting July 26), upstream LineageOS made a change that caused input lag. This bug makes it extremely difficult to type or even tap accurately. Screen taps sometimes do not register and sometimes register repeatedly.

The edit that introduced the bug was later reversed.

Details:

- https://www.reddit.com/r/LineageOS/comments/owdj14/los_181_july_27th_build_removed_for_oneplus_6/

- https://www.reddit.com/r/LineageOS/comments/ox4eik/touch_issues_from_the_previous_week_enchilada_and/

Unfortunately, many of the recent batch of LineageOS for microG builds are stuck with the bug until the next rebuild.

**Comment by bananer** [comment]
New round of builds starting today.

**Comment by parcelcat** [comment]
Thank you!
