### ISSUE TITLE
kltedv 15.1 Zip is Not Signed

### ISSUE THREAD

**Issue by eviljoel** [lineageos4microg/docker-lineage-cicd#21]
According to https://lineage.microg.org/#instructions , we are suppose to be able to verify installation zips by running "keytool -list -printcert -jarfile lineage-microG.zip" and checking the certificate fingerprints. (Which isn't exactly true because Ubuntu 18.04's keytool complains about the user supplying both -list and -printcert at the same time.) However when I run "keytool -printcert -jarfile lineage-15.1-20180813-microG-kltedv.zip" I receive "Not a signed jar file" and no fingerprint to verify against. I have every kltedv 15.1 installation zip downloaded, and they all have this problem.

To verify there isn't something wrong with my setup, I have ran this command against lineage-14.1-20180706-microG-kltedv.zip and received a certificate fingerprint.

Please either remove the instructions about verifying the signature on the zip or start signing the zip. (I prefer you sign the zip.)

Thank you.

**Comment by pschyska** [comment]
They changed the signing upstream, see #4 for a tool to verify the new theme (or use the shasum).

**Comment by corna** [comment]
Website updated
