### ISSUE TITLE
Seedvault is being incorrectly build as userdebug leading to unintended debug behaviour

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/docker-lineage-cicd#218]
## STR

On any device build, setup a backup with Seedvault in the LineageOS settings.

## Expected Behavior

As far as I understood it, this is how it should work when setting up the backup:
* you see a screen with your passwords and write them down
* the next screen forces you to enter these passwords again to verify that you've _really_ written them down/saved them

## Current Behavior

The second screen you get to verify the passwords you enter is prefilled with the values from your first screen.

## Possible Solution

According to upstream (Seedvault), this happens…
> because Lineage makes userdebug builds, so Seedvault thinks this is a debug build.

As such, the solution would be to make non-userdebug builds.

## Steps to Reproduce

1. Use a new LineageOS ROM.
2. Setup the 

(all not relevant as I could reproduce it on multiple devices, but here is one example device:)

/device FP3
/version lineage-18.1
/date 2021-08-11
/kernel 4.9.218+
/baseband 953_GEN_PACK-1[…]
/mods F-Droid

Seedvault v11-1.1
upstream issue: https://github.com/seedvault-app/seedvault/issues/306

--- 

copied/cross-posted from/to https://gitlab.com/LineageOS/issues/android/-/issues/3897 as I assume it is also an upstream LineageOS issue 8correct me if I'm wrong), but now thought you can influence how you build/bundle Seedvault, too here, so maybe it is an issue for you, too.
Again, correct me if I'm wrong and upstream should fix it.

I have read the directions.

**Comment by bananer** [comment]
As long as upstream LineageOS is doing their builds with `userdebug`, I don't want to change this for our builds.

https://gitlab.com/LineageOS/hudson/-/blob/master/lineage-build-targets

**Comment by rugk** [comment]
Understandable, okay.

**Comment by bananer** [comment]
It seems Seedvault has changed this behaviour: https://github.com/LineageOS/android_packages_apps_Seedvault/commit/ec1120d37d870424b49a87914e7724bf87e7cc5d

**Comment by rugk** [comment]
Thanks a lot for that link. However, not Seedvault, but LineageOS's fork of Seedvault "fork"(?) seem to have changed the behavior (according to that commit you link to). Anyway this is good news (at least if you use that in your build, too, which seems to be the case, however.)
