### ISSUE TITLE
Google Pixel 4/5: WiFi not working, Failed to start legacy HAL: TIMED_OUT

### ISSUE THREAD

**Issue by RealJTG** [lineageos4microg/docker-lineage-cicd#222]
Not sure where to report bug.

WiFi not working after installing LineageOS MicroG, but works with official LineageOS. My device is Google Pixel 4a 5G, I'm following this guide https://wiki.lineageos.org/devices/bramble/install.

Official LineageOS image works https://mirrorbits.lineageos.org/full/bramble/20210912/lineage-18.1-20210912-nightly-bramble-signed.zip
With LineageOS-microG https://download.lineage.microg.org/bramble/lineage-18.1-20210914-microG-bramble.zip (and any other version from https://download.lineage.microg.org/bramble/) I'm getting an error when enabling WiFi:

```
09-25 19:15:36.920   894   894 E WifiHAL : Timed out wating on Driver ready ... 
09-25 19:15:36.921   894   894 E vendor.google.wifi_ext@1.0-service-vendor: Failed or timed out awaiting driver ready
09-25 19:15:36.921   894   894 E vendor.google.wifi_ext@1.0-service-vendor: Failed to start legacy HAL: TIMED_OUT
09-25 19:15:36.929  1307  3910 E HalDevMgr: executeChipReconfiguration: configureChip error: 9 (, timed out)
09-25 19:15:36.929  1307  3910 E WifiVendorHal: Failed to create STA iface
09-25 19:15:36.929  1307  3910 E WifiNative: Failed to create iface in vendor HAL
09-25 19:15:36.930  1307  3910 E WifiClientModeManager: Failed to create ClientInterface. Sit in Idle
```

IDK maybe there are some blobs or something missing in these builds.

**Comment by RealJTG** [comment]
payload.bin content seems to have notable differences. Is it supposed to be like this?

LineageOS-microG payload.bin:
```
4,0K	./vbmeta_system.img
8,0K	./vbmeta.img
16M	./dtbo.img
96M	./boot.img
96M	./vendor_boot.img
280M	./system_ext.img
553M	./product.img
710M	./vendor.img
1,1G	./system.img
2,8G	.
```
LineageOS payload.bin:
```
4,0K	./vbmeta_system.img
8,0K	./vbmeta.img
44K	./devcfg.img
56K	./qupfw.img
80K	./xbl_config.img
88K	./featenabler.img
124K	./uefisecapp.img
192K	./aop.img
236K	./keymaster.img
404K	./hyp.img
1,0M	./abl.img
2,9M	./tz.img
3,5M	./xbl.img
16M	./dtbo.img
96M	./boot.img
96M	./vendor_boot.img
147M	./modem.img
280M	./system_ext.img
710M	./vendor.img
948M	./product.img
2,6G	./system.img
4,9G	.
```

**Comment by bananer** [comment]
This is the right place to report, but I'm afraid I don't know how to troubleshoot your problem. We're using firmware blobs from [TheMuppets](https://github.com/TheMuppets/proprietary_vendor_google/tree/lineage-18.1/bramble), can't really tell if something is missing there.

**Comment by Gigadoc2** [comment]
I can confirm this happening with a manual build (following the LineageOS instructions and not using the build system from this repo) as well. I did not encounter this problem three months ago when I last built a new image (yes, I waited way too long).

I was able to work around this by flashing the official Lineageos OTA just before my own build, which is interesting as I have enabled AVB on my build. My guess is that all the extra partitions flashed by the official build are too low-level to be verified by AVB (and are probably verified by the CPU and modem themselves?).

> We're using firmware blobs from [TheMuppets](https://github.com/TheMuppets/proprietary_vendor_google/tree/lineage-18.1/bramble), can't really tell if something is missing there.

From the looks of it I _think_ that the muppet repos are only containing files that are relevant for the building process, e.g. stuff that ends up in vendor or system one way or another. So those images for partions like `modem` are introduced somewhere else in the build process?

**Comment by XDjackieXD** [comment]
Hi! I can confirm that this is still an issue with the current image (25.05.2022 Lineage19) and that Factory Reset -> Flash "normal" LineageOS image -> Flash Lineage4MicroG solves this problem.
If I can help with debugging in any way please let me know

**Comment by petefoth** [comment]
@RealJTG @Gigadoc2 @XDjackieXD Is this still a problem for you on these devices, or is it OK for this issue to be closed?

Thanks for your response

**Comment by RealJTG** [comment]
@petefoth It's an old issue, I guess it could be closed.

I ended up installing ProtonAOSP back then, will return to the LineageOS with my next phone (if Google won't kill the custom ROMs ecosystem with their brand new Integrity API :)

**Comment by petefoth** [comment]
Thanks. Closing

**Comment by Gigadoc2** [comment]
Sorry, I was not fast enough. I can't tell for sure that this is still an issue with the pipeline in this project, but it is still an issue building manually, so I am going to suspect that this is also still happening for this project.

**Comment by Gigadoc2** [comment]
Good news, with LineageOS 21, the build process is now properly fixed and self-built images include the firmware partitions now too: https://github.com/LineageOS/android_device_google_bramble/commit/e83db3f96dedad1ecfbd34595231d8a33fa34ed5#diff-3173213a657d3b07f9f97bbf9e908b286808ee9be0f357cd20a5378603882d3eR37
