### ISSUE TITLE
Sync OTA releases with Android patchday (LOS side)?

### ISSUE THREAD

**Issue by Diapolo** [lineageos4microg/docker-lineage-cicd#229]
Is there any way to sync the release of new builds and OTA updates with Android patchday merges on the LOS side? In terms of security it would be nice to get the updates ASAP :).

**Comment by bananer** [comment]
Do these merges occur in a specific interval, like on a certain day of the month? Is this publicly documented?

**Comment by FintasticMan** [comment]
I know that the security patches are released on the 1st or 5th of each month, but I haven't found any patterns in when they are merged into LOS.  
Based on [the Gerrit](https://review.lineageos.org/q/status:merged+Bump+Security+String) they seem to be merged within 2 weeks of being released.

**Comment by bananer** [comment]
I don't see how we can fulfill this request.
