### ISSUE TITLE
Building on Fedora

### ISSUE THREAD

**Issue by pschyska** [lineageos4microg/docker-lineage-cicd#23]
Due to SELinux and the docker installation being secure by default the docker commandline should look like:

```
sudo docker run \
    ...
    -v "/path/to/sauce/lineage:/srv/src:Z" \
    ...
    lineageos4microg/docker-lineage-cicd
```

N.B. the Z option in the volume mounts. Maybe this should be added to README.md?

**Comment by spolack** [comment]
Feel free to provide a pull request. Closing as its not a real issue.
