### ISSUE TITLE
microg is not available - as if it was not installed

### ISSUE THREAD

**Issue by dyeray** [lineageos4microg/docker-lineage-cicd#230]
Hi! In LineageOS for microg, there does not seem to be available any microg package. This happened after updating the OTA, months ago, so it seems like it worked at some point. There are 0 apps on the "add/remove apps" section, and also the microg settings app is missing.

It basically looks like a regular LineageOS installation.

I'm using the builds for Xiaomi Mi A1 (tissot).

On logcat I see a lot of errors like:
```
11-11 23:13:14.617  1481  2360 W PackageManagerService.FAKE_PACKAGE_SIGNATURE: java.lang.NullPointerException: Attempt to write to field 'android.content.pm.Signature[] android.content.pm.PackageInfo.signatures' on a null object reference
11-11 23:13:14.617  1481  2360 W PackageManagerService.FAKE_PACKAGE_SIGNATURE: 	at com.android.server.pm.PackageManagerService.mayFakeSignature(PackageManagerService.java:4252)
11-11 23:13:14.617  1481  2360 W PackageManagerService.FAKE_PACKAGE_SIGNATURE: 	at com.android.server.pm.PackageManagerService.generatePackageInfo(PackageManagerService.java:4206)
11-11 23:13:14.617  1481  2360 W PackageManagerService.FAKE_PACKAGE_SIGNATURE: 	at com.android.server.pm.PackageManagerService.getPackageInfoInternal(PackageManagerService.java:4382)
11-11 23:13:14.617  1481  2360 W PackageManagerService.FAKE_PACKAGE_SIGNATURE: 	at com.android.server.pm.PackageManagerService.getPackageInfo(PackageManagerService.java:4320)
11-11 23:13:14.617  1481  2360 W PackageManagerService.FAKE_PACKAGE_SIGNATURE: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1957)
11-11 23:13:14.617  1481  2360 W PackageManagerService.FAKE_PACKAGE_SIGNATURE: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4110)
11-11 23:13:14.617  1481  2360 W PackageManagerService.FAKE_PACKAGE_SIGNATURE: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
11-11 23:13:14.617  1481  2360 W PackageManagerService.FAKE_PACKAGE_SIGNATURE: 	at android.os.Binder.execTransact(Binder.java:994)
11-11 23:13:14.618  3340  4968 W FirebaseInstanceId: Failed to find package android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
```

There is a privapp-permissions-com.google.android.gms.xml on /etc/permissions. /system/priv-app/GmsCore contains GmsCore.apk and a directory oat. Not sure where else can be looked for anything out of order.

**Comment by TheHighGroundWins** [comment]
I had the exact same problem and had to wipe my device to fix it.

Lineage OS 20 minor update one OnePlus 7 pro guacamole.

It is no longer available now but used to be there as it was just one update after the first release of lineage OS 20

**Comment by petefoth** [comment]
@dyeray Is this still a problem for you with recent builds? If not, I will close the issue (or you can do it yourself)

Assigning back to you for a response

**Comment by dyeray** [comment]
Hi. I don't know if it happens with current builds. Never managed to fix this, so I switched to another rom. I guess this was something specific to Mi A1 builds anyways so probably less relevant nowadays.
