### ISSUE TITLE
Lineage 17.1 build stopped updating for "lavender" on September 9th.

### ISSUE THREAD

**Issue by filledfield** [lineageos4microg/docker-lineage-cicd#232]
As all users of "lavender" including myself claim that there is a bunch of camera and interface related bugs in 18.1 build, and current official LOS maintainer seems not to be quite active for some time, Lineage OS 17.1 is the only way to have a fully usable daily driven device.

**Comment by bananer** [comment]
I added `lavender` to the list of additional devices to build for 17.1, starting with the next round on Dec 1st.

Though this sounds like something that should be handled by upstream LineageOS. Any place where this was reported and we could find reactions?

**Comment by filledfield** [comment]
We've reported about camera issues for many times at Gitlab and many users tried to find a solution in our telegram support chat of LineageOS for Redmi Note 7/7S, but there was no any official answer from developer. 

Users made some "workarounds" to get camera working without freezing in 18.1 build, but those methods are not permanent and need to be re-flashed after every single OTA update. Actually, camera was working good in 17.1, but the video quality was worse than in other roms like ArrowOS, CrDroid, and I think its because of the proprietary blobs. While LOS uses newcam blobs, other AOSP-based rom projects implement oldcam blobs, that work better than newcam.

Here are some of the issues opened:
https://gitlab.com/LineageOS/issues/android/-/issues/3564
https://gitlab.com/LineageOS/issues/android/-/issues/3861

**Comment by filledfield** [comment]
Thank you very much for the update!
