### ISSUE TITLE
Builds for lake not updated

### ISSUE THREAD

**Issue by BentiGorlich** [lineageos4microg/docker-lineage-cicd#236]
The build for lake have not been updated since the 20th of October. There have been at least 4 newer builds that did not make it to the lineageos4microg builds:
- 2021-11-30
- 2021-11-23
- 2021-11-16
- 2021-11-09

It seems like they get a weekly build, so there will be more missed builds I guess.
This would not have been a major problem, but I do have a GPS problem with my build, so I am hoping newer builds would fix that, but they didn't make it to my phone yet.

**Comment by bananer** [comment]
See #228 

Hoping I can find the time to fix these devices for the next round of builds starting Dec 15.

**Comment by BentiGorlich** [comment]
Ok, thanks for making all of this possible :)
Looking forward to it
