### ISSUE TITLE
Verification failing?

### ISSUE THREAD

**Issue by jedahan** [lineageos4microg/docker-lineage-cicd#24]
I installed update_verifier (with a little build tweak to work on macOS), and the latest build is failing verification.
```zsh
./verifier ~/Downloads/lineage-15.1-20181030-microG-sailfish.zip ../lineageos-key
read key e=65537 hash=20
comment is 1310 bytes; signature is 1292 bytes from end
signature (offset: 1c36f561, length: 506): 308205020609...SNIP...ce8cca70b09a3662136ee41eebbb9
failed to verify against RSA key 0
SHA-1 digest: 64693edda46c2febdae261c9492531379e172ed2
failed to verify whole-file signature
```

The shasums seem fine:
```zsh
▲ ls                                                                                                                 ~/Downloads
lineage-15.1-20181030-microG-sailfish.zip         lineage-15.1-20181030-microG-sailfish.zip.sha256sum
lineage-15.1-20181030-microG-sailfish.zip.md5sum  Patchwork-3.11.3-mac.dmg
▲ md5 lineage-15.1-20181030-microG-sailfish.zip                                                                      ~/Downloads
MD5 (lineage-15.1-20181030-microG-sailfish.zip) = 91fefe7ff246e319fed5a2c31592d655
▲ \cat lineage-15.1-20181030-microG-sailfish.zip.md5sum                                                              ~/Downloads
91fefe7ff246e319fed5a2c31592d655  lineage-15.1-20181030-microG-sailfish.zip
▲ shasum -a 256 lineage-15.1-20181030-microG-sailfish.zip                                                            ~/Downloads
2d304ae088ab0be93eb799b6ab1d28a1b8e58e5a7580e9624450234717020d7c  lineage-15.1-20181030-microG-sailfish.zip
▲ \cat lineage-15.1-20181030-microG-sailfish.zip.sha256sum                                                           ~/Downloads
2d304ae088ab0be93eb799b6ab1d28a1b8e58e5a7580e9624450234717020d7c  lineage-15.1-20181030-microG-sailfish.zip
```

What am I misunderstanding?

**Comment by corna** [comment]
Which key are you using for the verification? We use a different signing key from the official LineageOS builds, you can find ours [here](https://github.com/corna/update_verifier/).

```
>>> python3 update_verifier.py lineageos_pubkey lineage-15.1-20181030-microG-sailfish.zip 
failed verification
>>> python3 update_verifier.py lineageos4microg_pubkey lineage-15.1-20181030-microG-sailfish.zip
verified successfully
```

I will PGP-sign that repo and publish it under [https://github.com/lineageos4microg](https://github.com/lineageos4microg) soon.

Btw, which tweak was needed on Mac OS?

**Comment by jedahan** [comment]
Ahh great, I didn't dig deep enough to find that fork. Maybe the website can point towards using that key for now and update it when the other repos get updated?

I was using this https://github.com/gmrt/update_verifier , which was linked from a closed github issue somewhere. Now that I know the right place to look for the lineageos4microg update_verifier (corna/update_verifier) this all makes more sense, and I'm glad to see it will be republished under the main organization. Once that is done I'll close the issue.

**Comment by alastair-dm** [comment]
I'd suggest using https://gitlab.com/iain/otasig from #4 as it prints certificate fingerprints in a similar format to keytool. That means you can just update the installation instructions to use keytool for 14.1 and otasig for 15.1, and keep the existing fingerprint block.
