### ISSUE TITLE
Building User Instead of UserDebug

### ISSUE THREAD

**Issue by KuzonCode** [lineageos4microg/docker-lineage-cicd#242]
Is there a way to build user instead of userdebug. I think it can just be passed through to the breakfast command. Is there an easy way of doing that?

**Comment by bananer** [comment]
See #182

**Comment by KuzonCode** [comment]
@bananer  thanks for the reply I did do a search and find that comment, but I am unsure how our where to modify the second parameter. Do I need to make changes to the Docker image to pass it in?

**Comment by bananer** [comment]
Yes, I think you need to modify the Docker image. Changing the build type is not supported currently, but if you can figure it out a Pull Request offering the option through an environment variable would be appreciated.

**Comment by KuzonCode** [comment]
@bananer Thanks for the info, and here is the requested PR. Here is an example of the param being set and recognised by the build. Sorry about the delay had some issue with my build server. Appreciate your work on this project!

![image](https://user-images.githubusercontent.com/8284579/149069363-8d79c37c-a92e-4ecc-a0eb-90283afb64ae.png)
