### ISSUE TITLE
kccat6: boot loop on encrypted storage (Samsung Galaxy S5 Plus G901F - continuing #94)

### ISSUE THREAD

**Issue by kolAflash** [lineageos4microg/docker-lineage-cicd#245]
_This is a continuation for: #94 Build for "kccat6" broken  
The problem still exists with the current [lineage-16.0-20211225-microG-kccat6.zip](https://download.lineage.microg.org/kccat6/lineage-16.0-20211225-microG-kccat6.zip)_

&nbsp;

When updating to any ROM >= lineage-16.0-20200816-microG-kccat6.zip with encrypted storage enabled, the phone will get into a boot loop.  
Workarounds (CHOOSE ONE):
- Downgrade to an older ROM. (if you don't wipe, downgrading should get you simply back your old system without problems)
- Use an old `boot.img`, e.g. extracted from `lineage-16.0-20200424-microG-kccat6.zip` (see [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/94#issue-681023433))
- Wipe device.

&nbsp;
Device: kccat6 (Samsung Galaxy S5 Plus G901F)
Last known working version:  
https://misc.kolahilft.de/other/lineage-16.0-20200424-microG-kccat6.zip  
SHA256: 59bf682677f46cda86057b8a21688c921a61da8aed78920744059b3034be60f6

The problem also happens if you enable encryption on a freshly wiped device with a ROM >= lineage-16.0-20200816-microG-kccat6.zip.

**I don't know how to debug such early boot problems before I can adb to the device. If you give me a hint how to get logs, I'll happily upload them.**

&nbsp;

The [e-Foundation](https://e.foundation/) also provides a recent ROM for kccat6 based on LineageOS and they seem to have the same problem.
- https://gitlab.e.foundation/e/backlog/-/issues/2580 _Samsung S5 Plus with kccat6 going into infinite reboot loop_
- https://gitlab.e.foundation/e/backlog/-/issues/1908 _Encryption on kccat6 going into infinite reboot loop_

**Comment by petefoth** [comment]
Closing. This device is no longer on our build target list https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets
