### ISSUE TITLE
Android TV - No launcher?

### ISSUE THREAD

**Issue by kantlivelong** [lineageos4microg/docker-lineage-cicd#246]
Hello,

Tried flashing LineageOS For MicroG on an Android Shield Pro 2019 and can get through the wizard but no shell launches. It just sits at a black screen. Upstream LineageOS builds work without an issue. Perhaps some dependency is missing?

I tried:
lineage-17.1-20211124-microG-mdarcy.zip - black screen after wizard
lineage-17.1-20211210-microG-mdarcy.zip - black screen after wizard
lineage-17.1-20211224-microG-mdarcy.zip - wouldn't get past nvidia boot logo (before lineage logo)

Let me know if you need anything to troubleshoot.

**Comment by petefoth** [comment]
The current position is that  - sadly - we cannot make official lineageos4microg builds for minimal and Android TV devices.

See [this comment](https://github.com/lineageos4microg/docker-lineage-cicd/issues/436#issuecomment-1613825491) for details

See  Builds for Minimal devices and TV boxes failed #436
