### ISSUE TITLE
Missing binary blobs on Pixel 5 builds - WiFi does not work

### ISSUE THREAD

**Issue by johnjacob10** [lineageos4microg/docker-lineage-cicd#247]
I got a new Pixel 5 to replace my Essential PH-1. I build my own Lineage OS builds with MicroG using docker-lineage-cicd, but when I booted my build on the Pixel, Wifi did not work. It worked fine with stock, so this was not a hardware issue.

I tried with the official Lineage MicroG build from https://download.lineage.microg.org/redfin/ and I had the same issue.

However, the official Lineage OS builds from https://download.lineageos.org/redfin/ did not have the issue.

When I investigated further, the MicroG builds are smaller and missing some image files in the payload. When I unzip payload.bin from the image zip file, and extract the payload.bin using payload_dumper, these are the results:

MicroG build:
```
boot.img  product.img     system.img  vbmeta_system.img  vendor.img
dtbo.img  system_ext.img  vbmeta.img  vendor_boot.img
```
Lineage build:
```
abl.img     featenabler.img  qupfw.img       vbmeta.img         xbl.img
aop.img     hyp.img          system_ext.img  vbmeta_system.img
boot.img    keymaster.img    system.img      vendor_boot.img
devcfg.img  modem.img        tz.img          vendor.img
dtbo.img    product.img      uefisecapp.img  xbl_config.img
```
I do not have the expertise to fix this myself. Could you please fix this?

**Comment by bananer** [comment]
Might be same issue as #222

**Comment by johnjacob10** [comment]
Yeah, you're right - it's the same issue as #222 . I'll close this one.
