### ISSUE TITLE
LineageOS for MicroG 16.0 - Security Patch Level stuck at 5 Nov 2020

### ISSUE THREAD

**Issue by SekDev** [lineageos4microg/docker-lineage-cicd#248]
Hello, I have been successfully compiling LineageOS v16 for MicroG for several years.

I noticed last year, the security patch level was no longer incrementing, this is still the case, I just compiled a nightly 2022 build.

My LOS v16 (microG) nightly build is stuck at "Android Security Patch Level" = 5 Nov 2020

The Android security bulletin notes for v9 still appear to be integrating critical hotfixes into AOSP v9

https://source.android.com/security/bulletin/2021-12-01

In the LineageOS v16 changelog, it says from December 2021, "Bump Security String to 2021-12-05", so it appears they are still maintaining it and so I am just really confused why my MicroG builds arent showing a recent security level.

https://www.lineageoslog.com/16.0
https://review.lineageos.org/c/LineageOS/android_build/+/320434/

The file that was upgraded seems to be: **core/version_defaults.mk**  is it possible MicroG is not sync'ing this code ?

Are security fixes still being integrated to LOS v16 MicroG ? Could this be specific to my device, sorry but im not sure where to turn to at this point.

I have had a lot of trouble getting v17 to compile which is why I didnt just upgrade already.

Thank you !

**Comment by Exodusnick** [comment]
Delete the repo and sync again.

**Comment by Exodusnick** [comment]
please show me the output .
To do this go to the build/make folder inside lineage source and then type git log in terminal . 

![Bildschirmfoto vom 2022-01-13 23-22-59](https://user-images.githubusercontent.com/24758741/149418503-1c11fe3c-d922-40d7-b87a-4ab6b2baed17.png)

see my rom has Bump Security String to 2021-12-05

![photo_2022-01-14_00-23-03](https://user-images.githubusercontent.com/24758741/149424359-9d5b73b0-eacb-4f2a-83e7-05d7a664c17b.jpg)

**Comment by petefoth** [comment]
Closing. We are no longer building 16.1 devices, and security patches are up to date in the branches we are building
