### ISSUE TITLE
Replace Android System WebView with Bromite WebView

### ISSUE THREAD

**Issue by Sarkasper** [lineageos4microg/docker-lineage-cicd#25]
Is it possible to include Bromite WebView[0] instead of the default one?

[0] https://www.bromite.org/system_web_view

**Comment by cssr45** [comment]
I want to second this idea! I use Bromite webview and browser. I think replacing "stock" webview and browser with Bromite would be a privacy plus for microG.

**Comment by cssr45** [comment]
I have made the prebuilts/prebuiltapks folders for Bromite browser and webview. The folders include the needed permission.xml and/or .mk files. I would like to add them to microG's prebuilts/prebuiltapks source so anyone wishing to can use them in there builds. I'm using a build with these added and have had no problems.

**Comment by Partagas150** [comment]
Awesome! After stumbling across this, for my Devise ... After Playing with it, for the past week, I Have been wondering the same!  
Thank you

**Comment by cssr45** [comment]
I have run 4 builds with these files added, no problems at all. Just add them to  prebuilts/prebuiltapks folder and then add there folder names to the "CUSTOM_PACKAGES" list in the build script.
Link to a zip with the Bromite folders and a folder for Deja Vu location service. https://www.androidfilehost.com/?fid=11410963190603864054

**Comment by corna** [comment]
I prefer not to replace the Android System WebView with another one. However, we can consider adding it if it can installed alongside the Android one.
However it seems that [is uses the same name as the Android one](https://github.com/bromite/bromite/wiki/Installing-SystemWebView#about-the-package-name), so I don't know if it is doable. Let me know if you find something.

**Comment by Iolaum** [comment]
@cssr45 Do you have available the android.mk and permissions.xml for the prebuilt apk as well as the custom manifest that needs to remove the project describing the official android system webview that you used for your builds? I 'd be willing to try adding bromite webview in my [s5neolte microg+lineage rom/builds](https://forum.xda-developers.com/galaxy-s5-neo/development/lineageos15-1-microg-t3868809). Given time I may be able to figure it out on my own but if you can help I 'd appreciate it.

**Comment by chilliger** [comment]
I want to remove the chromium webview from my custom build and install the bromite webview as a user app. Will removing the "webview" line from build/make/target/product/core_minimal.mk (LOS 15.1) solve this?

**Comment by alistairporter** [comment]
@Sarkasper Here is what i do for my builds: https://gist.github.com/alistairporter/67cca7019dbc1a3d63054cedf656536d

**Comment by chilliger** [comment]
@alistairporter where do you put that xml file?

**Comment by Iolaum** [comment]
@chilliger 
In the `/srv/local_manifests` volume fot the docker image which is for custom manifests.

**Comment by alistairporter** [comment]
@chilliger you also need to add the apps to the build using the Custom packages env var for the docker image eg: -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension ThemeInterfacer Substratum SubstratumDefaultDarkTheme Amaze Firefox KISS YalpStore Etar Nextcloud NextcloudNotes OpenTasks Vinyl QKSMS DavDroid Newpipe Redreader CameraRoll OpenCamera OSMand VLC ClockPlus ExactCalculator Adaway AndOTP Keepass Keychain uFirewall Klar HackerSKB Termux TermuxWidget TermuxStyling TermuxAPI AnysoftSKB K9 Barcode Bromite" \

**Comment by spolack** [comment]
> I prefer not to replace the Android System WebView with another one. However, we can consider adding it if it can installed alongside the Android one.
> However it seems that [is uses the same name as the Android one](https://github.com/bromite/bromite/wiki/Installing-SystemWebView#about-the-package-name), so I don't know if it is doable. Let me know if you find something.

What @ncorna says.

**Comment by muranava** [comment]
> @Sarkasper Here is what i do for my builds: https://gist.github.com/alistairporter/67cca7019dbc1a3d63054cedf656536d

hi thanks for the bromite manifest, what is the best way to update the webview apk?

**Comment by muranava** [comment]
> @Sarkasper Here is what i do for my builds: https://gist.github.com/alistairporter/67cca7019dbc1a3d63054cedf656536d

@alistairporter thanks for the bromite manifest, i have a question about best way to get the latest webview apk using the manifest method?
thanks for any help!

**Comment by alistairporter** [comment]
@muranava I haven't used (or updated for that matter) the apk referenced in the manifest in over a year, having moved to the use of a magisk module to accomplish the same result.

However if you were wanting to update the apk I would suggest forking the repository I use in the manifest and replacing the apk with an updated version.
If this fails, you could attempt to modify the LineageOS webview repository to suit your needs.
I hope this is of some help!

**Comment by muranava** [comment]
> @muranava I haven't used (or updated for that matter) the apk referenced in the manifest in over a year, having moved to the use of a magisk module to accomplish the same result.
> 
> However if you were wanting to update the apk I would suggest forking the repository I use in the manifest and replacing the apk with an updated version.
> If this fails, you could attempt to modify the LineageOS webview repository to suit your needs.
> I hope this is of some help!

@alistairporter ah okay thanks, what magisk module do you use?
regards

**Comment by alistairporter** [comment]
This one: https://github.com/Magisk-Modules-Repo/bromitewebview

**Comment by muranava** [comment]
> This one: https://github.com/Magisk-Modules-Repo/bromitewebview
> […](#)
> On 26 January 2021 16:35:35 GMT, muranava ***@***.***> wrote: > @muranava I haven't used (or updated for that matter) the apk referenced in the manifest in over a year, having moved to the use of a magisk module to accomplish the same result. > > However if you were wanting to update the apk I would suggest forking the repository I use in the manifest and replacing the apk with an updated version. > If this fails, you could attempt to modify the LineageOS webview repository to suit your needs. > I hope this is of some help! @alistairporter ah okay thanks, what magisk module do you use? regards -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#25 (comment)](https://github.com/lineageos4microg/docker-lineage-cicd/issues/25#issuecomment-767666770)

right i think i tried that module before and had a problem with it, will try again, thanks

**Comment by muranava** [comment]
followiing up on my query and for others may be of use , there is a repo here https://github.com/MSe1969/android_external_bromite-webview that has latest bromite webview, you can simply add a manifest and then use custom packages to select bromite-webview; if interested person also has up to date microg core and frdoif prebuilts repo - https://github.com/MSe1969/android_prebuilts_prebuiltapks

**Comment by JuniorJPDJ** [comment]
Maybe someone could provide some dockerfiles for building this prebuild apps?
Or just downloading latest versions from upstreams?

**Comment by Ammako** [comment]
F-Droid repository to keep Bromite Webview up-to-date:

https://www.bromite.org/fdroid
