### ISSUE TITLE
Couldn't locate the top of the tree. Try setting TOP

### ISSUE THREAD

**Issue by KuzonCode** [lineageos4microg/docker-lineage-cicd#259]
Ever since the latest update I have been unable to build, I have not changed anything in my setup.

Any ideas?

```
>> [Sun Jan 30 03:25:51 UTC 2022] Starting build for enchilada, lineage-18.1 branch
build/envsetup.sh: line 793: TOP: unbound variable
Couldn't locate the top of the tree. Try setting TOP.
>> [Sun Jan 30 03:25:51 UTC 2022] Moving build artifacts for enchilada to '/srv/zips/enchilada'
```

**Comment by bananer** [comment]
Thanks for reporting. I made a small mistake when copying from my test environment with the last merge. https://github.com/lineageos4microg/docker-lineage-cicd/commit/0d681332309dfd26cb653629761fb9ae4377a5d8 should fix this.

Would be great if you could test again with the latest image. and close this issue if it's resolved.

**Comment by KuzonCode** [comment]
@bananer Appreciate the fast reply. All good. It's up and going

**Comment by KuzonCode** [comment]
@bananer Sorry to bother you again about this, but I have notice this at the end of my logs on Latest

![image](https://user-images.githubusercontent.com/8284579/151903634-225c7f7d-0fcb-4027-8721-c0024060afb6.png)

Just thought I would confirm with you if there could be another stop that was affected by the issue above?

**Comment by bananer** [comment]
@KuzonCode seems like the build succeeded, right? Then I can't quite explain where that message came from, it might be a relic from the last build and the way you read your logs...

**Comment by KuzonCode** [comment]
@bananer Yes, it is building okay. I couldn't work it out either was having a look at the script. I will close out for now and raise in the future if it causes and issues.
