### ISSUE TITLE
LOS 14.1 not working

### ISSUE THREAD

**Issue by timmithan** [lineageos4microg/docker-lineage-cicd#262]
Not able to build LOS 14.1.
I think the proprietary vendor files for LOS 14.1 are not on gitlab available, only on github.

I get an error after "Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'"
Seems like the "build_manifest.py" isnt able to fetch the manifest correctly from this link.

I think the error is in [Line 74-76](https://github.com/lineageos4microg/docker-lineage-cicd/blob/71cb0d817043e1c26a079ecf75a341c1c1742c12/src/build.sh#L74) in "build.sh", it tries to fetch from gitlab but this repo doesnt have version 14.1

Is there a way to fetch this manifest from the github "TheMuppets" repo and continue the build?

Does someone know how to fix this?

![Screenshot 2022-02-03 220944](https://user-images.githubusercontent.com/23740660/152429230-19b9d040-293e-4102-a34e-51d43eeca412.jpg)

**Comment by timmithan** [comment]
I have tried:
`wget -q -O .repo/local_manifests/proprietary.xml "https://raw.githubusercontent.com/TheMuppets/manifests/$themuppets_branch/muppets.xml" 
      /root/build_manifest.py --remote "https://github.com" --remotename "github_https" \
        "https://raw.githubusercontent.com/TheMuppets/manifests/$themuppets_branch/muppets.xml" .repo/local_manifests/proprietary_github.xml`

instead of:
`wget -q -O .repo/local_manifests/proprietary.xml "https://raw.githubusercontent.com/TheMuppets/manifests/$themuppets_branch/muppets.xml"
    /root/build_manifest.py --remote "https://gitlab.com" --remotename "gitlab_https" \
    "https://gitlab.com/the-muppets/manifest/raw/$themuppets_branch/muppets.xml" .repo/local_manifests/proprietary_gitlab.xml`

then it builds the manifest but but instantly exits after printing "**Syncing branch repository**"

**Comment by timmithan** [comment]
Output of `echo repo sync -c --force-sync &>> "$repo_log"` is:
Missing "vendor/cm", aborting

**Comment by bananer** [comment]
Seems like TheMuppets dropped support for 14.1, since there is no more `cm-14.1` branch there: https://gitlab.com/the-muppets/manifest/

**Comment by timmithan** [comment]
Thx for your response. Yes i saw this too.
But on Github there still is the cm-14.1 branch. 
https://github.com/TheMuppets/manifests/  (+ proprietary vendor stuff)

Thats why i was altering the link above from gitlab into github, but i still get the `Missing "vendor/cm", aborting` Error.
Does someone know a fix for this?

**Comment by bananer** [comment]
I see you had already figured out what I wrote... Sorry, I was not paying enough attention this morning.

[This line](https://github.com/lineageos4microg/docker-lineage-cicd/blob/71cb0d817043e1c26a079ecf75a341c1c1742c12/src/build.sh#L158) loads the manifest for GitHub and [these lines](https://github.com/lineageos4microg/docker-lineage-cicd/blob/71cb0d817043e1c26a079ecf75a341c1c1742c12/src/build.sh#L159-L160) create a manifest for GitLab, so with your changes you would actually have the entries for GitHub twice. You might actually want to remove the second part, since the repo on GitLab only seems to contain files for xiaomi devices.

**Comment by timmithan** [comment]
I have deleted the lines but it still says `Missing "vendor/cm", aborting` after `Syncing branch repository`. 
I dont really understand because i think the needed branch is still available on github.

btw the first line gives:
`<manifest>
  <project name="TheMuppets/proprietary_vendor_alcatel" path="vendor/alcatel"/>
   ....`

the lines that i have deleted give:
`  <manifest>
  <remote fetch="https://github.com" name="github_https"/>
  <project name="TheMuppets/proprietary_vendor_alcatel" path="vendor/alcatel" remote="github_https"/>
  ...`

I think it should be possible to build cm-14.1 because the branch is still on github but i dont really know what the problem is

**Comment by bananer** [comment]
You could check whether there is anything in `vendor/cm` in your source directory

**Comment by petefoth** [comment]
@timmithan Is this still a problem for you? Are you still trying to build 14.1?

If not, can this issue be closed

Assigning back to you for a response

**Comment by petefoth** [comment]
Closing
