### ISSUE TITLE
No February built for appolon

### ISSUE THREAD

**Issue by Iey4iej3** [lineageos4microg/docker-lineage-cicd#263]
I don't know what's not working properly. The February built for appolon does not seem to be available yet.

**Comment by bananer** [comment]
There was a problem in the build script, most 18.1 builds were skipped unfortunately. It should be fixed for the next round starting on Feb 15th.

**Comment by bananer** [comment]
New build today: https://download.lineage.microg.org/apollon/lineage-18.1-20220215-microG-apollon.zip
