### ISSUE TITLE
Build fail for beyojnd0lte

### ISSUE THREAD

**Issue by palight** [lineageos4microg/docker-lineage-cicd#265]
Hi, 
I'm trying to build lineage 18.1 for beyond0lte on a computer with 4 cores, 4 GB of RAM et 16 GB of Swap. Disk space is about 700 GB. I built without specific option and got the following output. Can someone help me to solve it. I already tried to start from scratch (erasing all containers, images and folders), but the error is still the same. 

21:37:50 Build sandboxing disabled due to nsjail error.
sched_setaffinity: Invalid argument
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "lineage_beyond0lte".
21:37:53 dumpvars failed with: exit status 1
repo sync has finished successfully.
repo sync has finished successfully.
Updating files: 100% (69719/69719), done.
repo sync has finished successfully.
Device beyond0lte not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_samsung_beyond0lte
Default revision: lineage-18.1
Checking branch info
Checking if device/samsung/beyond0lte is fetched from android_device_samsung_beyond0lte
Adding dependency: LineageOS/android_device_samsung_beyond0lte -> device/samsung/beyond0lte
Using default branch for android_device_samsung_beyond0lte
Syncing repository to retrieve project.
Repository synced!
Looking for dependencies in device/samsung/beyond0lte
Adding dependencies to manifest
Checking if device/samsung/exynos9820-common is fetched from android_device_samsung_exynos9820-common
Adding dependency: LineageOS/android_device_samsung_exynos9820-common -> device/samsung/exynos9820-common
Using default branch for android_device_samsung_exynos9820-common
Syncing dependencies
Looking for dependencies in device/samsung/exynos9820-common
Adding dependencies to manifest
Checking if device/samsung_slsi/sepolicy is fetched from android_device_samsung_slsi_sepolicy
Adding dependency: LineageOS/android_device_samsung_slsi_sepolicy -> device/samsung_slsi/sepolicy
Using default branch for android_device_samsung_slsi_sepolicy
Checking if hardware/samsung is fetched from android_hardware_samsung
Adding dependency: LineageOS/android_hardware_samsung -> hardware/samsung
Using default branch for android_hardware_samsung
Checking if hardware/samsung/nfc is fetched from android_hardware_samsung_nfc
Adding dependency: LineageOS/android_hardware_samsung_nfc -> hardware/samsung/nfc
Using default branch for android_hardware_samsung_nfc
Checking if kernel/samsung/exynos9820 is fetched from android_kernel_samsung_exynos9820
Adding dependency: LineageOS/android_kernel_samsung_exynos9820 -> kernel/samsung/exynos9820
Using default branch for android_kernel_samsung_exynos9820
Syncing dependencies
Looking for dependencies in device/samsung_slsi/sepolicy
device/samsung_slsi/sepolicy has no additional dependencies.
Looking for dependencies in hardware/samsung
hardware/samsung has no additional dependencies.
Looking for dependencies in hardware/samsung/nfc
hardware/samsung/nfc has no additional dependencies.
Looking for dependencies in kernel/samsung/exynos9820
kernel/samsung/exynos9820 has no additional dependencies.
Done
21:38:31 Build sandboxing disabled due to nsjail error.
21:38:34 Build sandboxing disabled due to nsjail error.

 ============================================
 PLATFORM_VERSION_CODENAME=REL
 PLATFORM_VERSION=11
 LINEAGE_VERSION=18.1-20220210-UNOFFICIAL-beyond0lte
 TARGET_PRODUCT=lineage_beyond0lte
 TARGET_BUILD_VARIANT=userdebug
 TARGET_BUILD_TYPE=release
 TARGET_ARCH=arm64
 TARGET_ARCH_VARIANT=armv8-2a
 TARGET_CPU_VARIANT=cortex-a75
 TARGET_2ND_ARCH=arm
 TARGET_2ND_ARCH_VARIANT=armv8-2a
 TARGET_2ND_CPU_VARIANT=cortex-a55
 HOST_ARCH=x86_64
 HOST_2ND_ARCH=x86
 HOST_OS=linux
 HOST_OS_EXTRA=Linux-5.13.19-2-pve-x86_64-Ubuntu-20.04.3-LTS
 HOST_CROSS_OS=windows
 HOST_CROSS_ARCH=x86
 HOST_CROSS_2ND_ARCH=x86_64
 HOST_BUILD_TYPE=release
 BUILD_ID=RQ3A.211001.001
 OUT_DIR=out
 PRODUCT_SOONG_NAMESPACES=vendor/samsung/exynos9820-common device/samsung/exynos9820-common hardware/google/interfaces hardware/google/pixel hardware/samsung/aidl/power-libperfmgr vendor/samsung/beyond0lte packages/apps/Bluetooth
 WITH_SU=false
 ============================================

>> [Thu Feb 10 21:38:35 UTC 2022] Starting build for beyond0lte, lineage-18.1 branch
21:38:37 Build sandboxing disabled due to nsjail error.
sched_setaffinity: Invalid argument
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
LINEAGE_VERSION=18.1-20220210-UNOFFICIAL-beyond0lte
TARGET_PRODUCT=lineage_beyond0lte
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-2a
TARGET_CPU_VARIANT=cortex-a75
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-2a
TARGET_2ND_CPU_VARIANT=cortex-a55
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.13.19-2-pve-x86_64-Ubuntu-20.04.3-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RQ3A.211001.001
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=vendor/samsung/exynos9820-common device/samsung/exynos9820-common hardware/google/interfaces hardware/google/pixel hardware/samsung/aidl/power-libperfmgr vendor/samsung/beyond0lte packages/apps/Bluetooth
WITH_SU=false
============================================
[100% 1/1] out/soong/.minibootstrap/minibp out/soong/.bootstrap/build.ninja
[  1% 2/182] compile out/soong/.bootstrap/blueprint-deptools/pkg/github.com/google/blueprint/deptools.a
[  1% 3/182] compile out/soong/.bootstrap/blueprint-parser/pkg/github.com/google/blueprint/parser.a
[  2% 4/182] compile out/soong/.bootstrap/blueprint-pathtools/pkg/github.com/google/blueprint/pathtools.a
[  2% 5/182] compile out/soong/.bootstrap/loadplugins/obj/loadplugins.a
[  3% 6/182] compile out/soong/.bootstrap/gotestrunner/obj/gotestrunner.a
[  3% 7/182] compile out/soong/.bootstrap/blueprint-proptools/pkg/github.com/google/blueprint/proptools.a
[  4% 8/182] compile out/soong/.bootstrap/gotestmain/obj/gotestmain.a
[  4% 9/182] compile out/soong/.bootstrap/blueprint-pathtools/test/github.com/google/blueprint/pathtools.a
[  5% 10/182] compile out/soong/.bootstrap/blueprint-parser/test/github.com/google/blueprint/parser.a
[  6% 11/182] link out/soong/.bootstrap/gotestrunner/obj/a.out
[  6% 12/182] cp out/soong/.bootstrap/bin/gotestrunner
[  7% 13/182] compile out/soong/.bootstrap/soong-env/pkg/android/soong/env.a
[  7% 14/182] compile out/soong/.bootstrap/soong-shared/pkg/android/soong/shared.a
[  8% 15/182] compile out/soong/.bootstrap/blueprint-proptools/test/github.com/google/blueprint/proptools.a
[  8% 16/182] compile out/soong/.bootstrap/soong_env/obj/soong_env.a
[  9% 17/182] compile out/soong/.bootstrap/blueprint/pkg/github.com/google/blueprint.a
[  9% 18/182] compile out/soong/.bootstrap/blueprint/test/github.com/google/blueprint.a
[ 10% 19/182] compile out/soong/.bootstrap/blueprint-bootstrap-bpdoc/pkg/github.com/google/blueprint/bootstrap/bpdoc.a
[ 10% 20/182] compile out/soong/.bootstrap/soong/pkg/android/soong.a
[ 11% 21/182] compile out/soong/.bootstrap/blueprint-bootstrap-bpdoc/test/github.com/google/blueprint/bootstrap/bpdoc.a
[ 12% 22/182] compile out/soong/.bootstrap/blueprint-bootstrap/pkg/github.com/google/blueprint/bootstrap.a
[ 12% 23/182] compile out/soong/.bootstrap/soong-android-soongconfig/pkg/android/soong/android/soongconfig.a
[ 13% 24/182] link out/soong/.bootstrap/soong_env/obj/a.out
[ 13% 25/182] link out/soong/.bootstrap/loadplugins/obj/a.out
[ 14% 26/182] link out/soong/.bootstrap/gotestmain/obj/a.out
[ 14% 27/182] cp out/soong/.bootstrap/bin/soong_env
[ 15% 28/182] cp out/soong/.bootstrap/bin/loadplugins
[ 15% 29/182] cp out/soong/.bootstrap/bin/gotestmain
[ 16% 30/182] create out/soong/.bootstrap/soong_build/gen/plugin.go
[ 17% 31/182] gotestmain out/soong/.bootstrap/blueprint/test/test.go
[ 17% 32/182] gotestmain out/soong/.bootstrap/blueprint-parser/test/test.go
[ 18% 33/182] gotestmain out/soong/.bootstrap/blueprint-bootstrap-bpdoc/test/test.go
[ 18% 34/182] gotestmain out/soong/.bootstrap/aidl-soong-rules/test/test.go
[ 19% 35/182] compile out/soong/.bootstrap/blueprint-bootstrap-bpdoc/test/test.a
[ 19% 36/182] compile out/soong/.bootstrap/blueprint-parser/test/test.a
[ 20% 37/182] compile out/soong/.bootstrap/blueprint/test/test.a
[ 20% 38/182] gotestmain out/soong/.bootstrap/blueprint-pathtools/test/test.go
[ 21% 39/182] compile out/soong/.bootstrap/blueprint-pathtools/test/test.a
[ 21% 40/182] link out/soong/.bootstrap/blueprint-parser/test/test
[ 22% 41/182] test github.com/google/blueprint/parser
[ 23% 42/182] gotestmain out/soong/.bootstrap/blueprint-proptools/test/test.go
[ 23% 43/182] link out/soong/.bootstrap/blueprint-pathtools/test/test
[ 24% 44/182] test github.com/google/blueprint/pathtools
[ 24% 45/182] compile out/soong/.bootstrap/blueprint-proptools/test/test.a
[ 25% 46/182] gotestmain out/soong/.bootstrap/soong-android/test/test.go
[ 25% 47/182] link out/soong/.bootstrap/blueprint/test/test
[ 26% 48/182] link out/soong/.bootstrap/blueprint-bootstrap-bpdoc/test/test
[ 26% 49/182] gotestmain out/soong/.bootstrap/soong-bpf/test/test.go
[ 27% 50/182] gotestmain out/soong/.bootstrap/soong-apex/test/test.go
[ 28% 51/182] gotestmain out/soong/.bootstrap/soong-cc-config/test/test.go
[ 28% 52/182] gotestmain out/soong/.bootstrap/soong-dexpreopt/test/test.go
[ 29% 53/182] gotestmain out/soong/.bootstrap/soong-etc/test/test.go
[ 29% 54/182] gotestmain out/soong/.bootstrap/soong-genrule/test/test.go
[ 30% 55/182] gotestmain out/soong/.bootstrap/soong-cc/test/test.go
[ 30% 56/182] gotestmain out/soong/.bootstrap/soong-python/test/test.go
[ 31% 57/182] gotestmain out/soong/.bootstrap/soong-java/test/test.go
[ 31% 58/182] gotestmain out/soong/.bootstrap/soong-remoteexec/test/test.go
[ 32% 59/182] gotestmain out/soong/.bootstrap/soong-rust/test/test.go
[ 32% 60/182] gotestmain out/soong/.bootstrap/soong-sh/test/test.go
[ 33% 61/182] gotestmain out/soong/.bootstrap/soong-sdk/test/test.go
[ 34% 62/182] gotestmain out/soong/.bootstrap/soong-xml/test/test.go
[ 34% 63/182] gotestmain out/soong/.bootstrap/soong-sysprop/test/test.go
[ 35% 64/182] link out/soong/.bootstrap/blueprint-proptools/test/test
[ 35% 65/182] test github.com/google/blueprint/proptools
[ 36% 66/182] test github.com/google/blueprint
[ 36% 67/182] test github.com/google/blueprint/bootstrap/bpdoc
[ 37% 68/182] compile out/soong/.bootstrap/soong-android/pkg/android/soong/android.a
[ 37% 69/182] compile out/soong/.bootstrap/kernel-config-soong-rules/pkg/android/soong/kernel/configs.a
[ 38% 70/182] compile out/soong/.bootstrap/soong-etc/pkg/android/soong/etc.a
[ 39% 71/182] compile out/soong/.bootstrap/soong-etc/test/android/soong/etc.a
[ 39% 72/182] compile out/soong/.bootstrap/soong-dexpreopt/pkg/android/soong/dexpreopt.a
[ 40% 73/182] compile out/soong/.bootstrap/soong-etc/test/test.a
[ 40% 74/182] compile out/soong/.bootstrap/soong-dexpreopt/test/android/soong/dexpreopt.a
[ 41% 75/182] compile out/soong/.bootstrap/soong-dexpreopt/test/test.a
[ 41% 76/182] compile out/soong/.bootstrap/soong-icu/pkg/android/soong/icu.a
[ 42% 77/182] compile out/soong/.bootstrap/soong-genrule/test/android/soong/genrule.a
[ 42% 78/182] compile out/soong/.bootstrap/soong-genrule/pkg/android/soong/genrule.a
[ 43% 79/182] compile out/soong/.bootstrap/soong-genrule/test/test.a
[ 43% 80/182] compile out/soong/.bootstrap/soong-fs_config/pkg/android/soong/fs_config.a
[ 44% 81/182] compile out/soong/.bootstrap/soong-lineage-generator/pkg/lineage/soong/generator.a
[ 45% 82/182] compile out/soong/.bootstrap/soong-phony/pkg/android/soong/phony.a
[ 45% 83/182] compile out/soong/.bootstrap/soong-android/test/android/soong/android.a
[ 46% 84/182] compile out/soong/.bootstrap/soong-libchrome/pkg/android/soong/external/libchrome.a
[ 46% 85/182] compile out/soong/.bootstrap/soong-ca-certificates/pkg/android/soong/system/ca-certificates.a
[ 47% 86/182] compile out/soong/.bootstrap/soong-android/test/test.a
[ 47% 87/182] compile out/soong/.bootstrap/soong-remoteexec/pkg/android/soong/remoteexec.a
[ 48% 88/182] compile out/soong/.bootstrap/soong-remoteexec/test/android/soong/remoteexec.a
[ 48% 89/182] compile out/soong/.bootstrap/soong-cc-config/test/android/soong/cc/config.a
[ 49% 90/182] compile out/soong/.bootstrap/soong-cc-config/pkg/android/soong/cc/config.a
[ 50% 91/182] compile out/soong/.bootstrap/soong-cc-config/test/test.a
[ 50% 92/182] compile out/soong/.bootstrap/soong-java-config/pkg/android/soong/java/config.a
[ 51% 93/182] compile out/soong/.bootstrap/soong-java-config-error_prone/pkg/android/soong/java/config/error_prone.a
[ 51% 94/182] compile out/soong/.bootstrap/soong-remoteexec/test/test.a
[ 52% 95/182] link out/soong/.bootstrap/soong-dexpreopt/test/test
[ 52% 96/182] link out/soong/.bootstrap/soong-android/test/test
[ 53% 97/182] link out/soong/.bootstrap/soong-etc/test/test
[ 53% 98/182] link out/soong/.bootstrap/soong-genrule/test/test
[ 54% 99/182] compile out/soong/.bootstrap/soong-robolectric/pkg/android/soong/robolectric.a
[ 54% 100/182] test android/soong/android
[ 55% 101/182] compile out/soong/.bootstrap/soong-rust-config/pkg/android/soong/rust/config.a
[ 56% 102/182] test android/soong/dexpreopt
[ 56% 103/182] test android/soong/etc
[ 57% 104/182] compile out/soong/.bootstrap/soong-selinux/pkg/android/soong/selinux.a
[ 57% 105/182] test android/soong/genrule
[ 58% 106/182] compile out/soong/.bootstrap/soong-tradefed/pkg/android/soong/tradefed.a
[ 58% 107/182] compile out/soong/.bootstrap/soong-xml/pkg/android/soong/xml.a
[ 59% 108/182] compile out/soong/.bootstrap/soong-wayland-protocol-codegen/pkg/android/soong/external/wayland-protocol.a
[ 59% 109/182] compile out/soong/.bootstrap/soong-xml/test/android/soong/xml.a
[ 60% 110/182] link out/soong/.bootstrap/soong-cc-config/test/test
[ 60% 111/182] link out/soong/.bootstrap/soong-remoteexec/test/test
[ 61% 112/182] compile out/soong/.bootstrap/soong-xml/test/test.a
[ 62% 113/182] test android/soong/remoteexec
[ 62% 114/182] compile out/soong/.bootstrap/soong-python/pkg/android/soong/python.a
[ 63% 115/182] test android/soong/cc/config
[ 63% 116/182] compile out/soong/.bootstrap/soong-python/test/android/soong/python.a
[ 64% 117/182] compile out/soong/.bootstrap/soong-python/test/test.a
[ 64% 118/182] compile out/soong/.bootstrap/vintf-compatibility-matrix-soong-rules/pkg/android/soong/vintf-compatibility-matrix.a
[ 65% 119/182] link out/soong/.bootstrap/soong-xml/test/test
[ 65% 120/182] test android/soong/xml
[ 66% 121/182] link out/soong/.bootstrap/soong-python/test/test
[ 67% 122/182] test android/soong/python
[ 67% 123/182] compile out/soong/.bootstrap/soong-cc/pkg/android/soong/cc.a
[ 68% 124/182] compile out/soong/.bootstrap/soong-cc/test/android/soong/cc.a
[ 68% 125/182] compile out/soong/.bootstrap/soong-bpf/pkg/android/soong/bpf.a
[ 69% 126/182] compile out/soong/.bootstrap/soong-bpf/test/android/soong/bpf.a
[ 69% 127/182] compile out/soong/.bootstrap/soong-cc/test/test.a
[ 70% 128/182] compile out/soong/.bootstrap/soong-bpf/test/test.a
[ 70% 129/182] compile out/soong/.bootstrap/soong-fluoride/pkg/android/soong/fluoride.a
[ 71% 130/182] compile out/soong/.bootstrap/soong-clang/pkg/android/soong/external/clang.a
[ 71% 131/182] compile out/soong/.bootstrap/soong-display_defaults_sm7250/pkg/android/soong/hardware/qcom/sm7250/display.a
[ 72% 132/182] compile out/soong/.bootstrap/soong-clang-prebuilts/pkg/android/soong/prebuilts/clang/host/linux-x86/clangprebuilts.a
[ 73% 133/182] compile out/soong/.bootstrap/soong-fluoride_qti/pkg/android/soong/fluoride_qti.a
[ 73% 134/182] compile out/soong/.bootstrap/soong-llvm/pkg/android/soong/external/llvm.a
[ 74% 135/182] compile out/soong/.bootstrap/soong-rust/test/android/soong/rust.a
[ 74% 136/182] compile out/soong/.bootstrap/soong-rust/test/test.a
[ 75% 137/182] compile out/soong/.bootstrap/soong-rust/pkg/android/soong/rust.a
[ 75% 138/182] compile out/soong/.bootstrap/soong-sanitizer_status/pkg/android/soong/security/santizers_status.a
[ 76% 139/182] compile out/soong/.bootstrap/soong-sh/test/android/soong/sh.a
[ 76% 140/182] compile out/soong/.bootstrap/soong-sh/test/test.a
[ 77% 141/182] link out/soong/.bootstrap/soong-cc/test/test
[ 78% 142/182] link out/soong/.bootstrap/soong-bpf/test/test
[ 78% 143/182] compile out/soong/.bootstrap/soong-sh/pkg/android/soong/sh.a
[ 79% 144/182] link out/soong/.bootstrap/soong-rust/test/test
[ 79% 145/182] compile out/soong/.bootstrap/soong-java/pkg/android/soong/java.a
[ 80% 146/182] link out/soong/.bootstrap/soong-sh/test/test
[ 80% 147/182] compile out/soong/.bootstrap/aidl-soong-rules/test/android/soong/aidl.a
[ 81% 148/182] compile out/soong/.bootstrap/aidl-soong-rules/pkg/android/soong/aidl.a
[ 81% 149/182] compile out/soong/.bootstrap/aidl-soong-rules/test/test.a
[ 82% 150/182] compile out/soong/.bootstrap/hidl-soong-rules/pkg/android/soong/hidl.a
[ 82% 151/182] compile out/soong/.bootstrap/soong-java/test/android/soong/java.a
[ 83% 152/182] compile out/soong/.bootstrap/soong-java/test/test.a
[ 84% 153/182] compile out/soong/.bootstrap/soong-suite-harness/pkg/android/soong/suite_harness.a
[ 84% 154/182] compile out/soong/.bootstrap/soong-sysprop/test/android/soong/sysprop.a
[ 85% 155/182] compile out/soong/.bootstrap/soong-sysprop/test/test.a
[ 85% 156/182] compile out/soong/.bootstrap/soong-apex/test/android/soong/apex.a
[ 86% 157/182] compile out/soong/.bootstrap/soong-apex/test/test.a
[ 86% 158/182] compile out/soong/.bootstrap/soong-apex/pkg/android/soong/apex.a
[ 87% 159/182] compile out/soong/.bootstrap/soong-art/pkg/android/soong/art.a
[ 87% 160/182] compile out/soong/.bootstrap/soong-sdk/test/android/soong/sdk.a
[ 88% 161/182] compile out/soong/.bootstrap/soong-sdk/test/test.a
[ 89% 162/182] link out/soong/.bootstrap/soong-java/test/test
[ 89% 163/182] link out/soong/.bootstrap/aidl-soong-rules/test/test
[ 90% 164/182] compile out/soong/.bootstrap/soong-sdk/pkg/android/soong/sdk.a
[ 90% 165/182] compile out/soong/.bootstrap/soong-sysprop/pkg/android/soong/sysprop.a
[ 91% 166/182] link out/soong/.bootstrap/soong-sysprop/test/test
[ 91% 167/182] compile out/soong/.bootstrap/xsdc-soong-rules/pkg/android/soong/xsdc.a
[ 92% 168/182] compile out/soong/.bootstrap/soong_build/obj/soong_build.a
[ 92% 169/182] link out/soong/.bootstrap/soong-apex/test/test
[ 93% 170/182] link out/soong/.bootstrap/soong-sdk/test/test
[ 93% 171/182] link out/soong/.bootstrap/soong_build/obj/a.out
[ 94% 172/182] test android/soong/cc
[ 95% 173/182] test android/soong/sh
[ 95% 174/182] test android/soong/bpf
[ 96% 175/182] test android/soong/rust
[ 96% 176/182] test android/soong/java
[ 97% 177/182] test android/soong/sysprop
[ 97% 178/182] test android/soong/aidl
[ 98% 179/182] test android/soong/apex
[ 98% 180/182] test android/soong/sdk
[ 99% 181/182] cp out/soong/.bootstrap/bin/soong_build
21:41:04 soong bootstrap failed with: exit status 1
[100% 182/182] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
Killed
ninja: build stopped: subcommand failed.

#### failed to build some targets (02:29 (mm:ss)) ####

>> [Thu Feb 10 21:41:04 UTC 2022] Failed build for beyond0lte
>> [Thu Feb 10 21:41:04 UTC 2022] Finishing build for beyond0lte
>> [Thu Feb 10 21:41:04 UTC 2022] Cleaning source dir for device beyond0lte
21:41:12 Entire build directory removed.

**Comment by RealStickman** [comment]
I've also got issues with building. In my case for oneplus3 with LOS branches 17.1 and 18.1.  
After the container process has finished, I only have an empty "oneplus3" directory in my zip output folder.  

Here's the full command I used to run the container:  
```
podman run \
    -e "BRANCH_NAME=lineage-17.1,lineage-18.1" \
    -e "DEVICE_LIST_LINEAGE_17_1=oneplus3" \
    -e "DEVICE_LIST_LINEAGE_18_1=oneplus3" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "WITH_GMS=true" \
    -v "/mnt/storage/lineagebuild/lineageos4microg/src:/srv/src" \
    -v "/mnt/storage/lineagebuild/lineageos4microg/zips:/srv/zips" \
    -v "/mnt/storage/lineagebuild/lineageos4microg/logs:/srv/logs" \
    -v "/mnt/storage/lineagebuild/lineageos4microg/ccache:/srv/ccache" \
    -v "/mnt/storage/lineagebuild/lineageos4microg/manifests:/srv/local_manifests" \
    docker.io/lineageos4microg/docker-lineage-cicd
```

**Comment by palight** [comment]
> I've also got issues with building. In my case for oneplus3 with LOS branches 17.1 and 18.1. After the container process has finished, I only have an empty "oneplus3" directory in my zip output folder.
> 
> Here's the full command I used to run the container:
> 
> ```
> podman run \
>     -e "BRANCH_NAME=lineage-17.1,lineage-18.1" \
>     -e "DEVICE_LIST_LINEAGE_17_1=oneplus3" \
>     -e "DEVICE_LIST_LINEAGE_18_1=oneplus3" \
>     -e "SIGNATURE_SPOOFING=restricted" \
>     -e "WITH_GMS=true" \
>     -v "/mnt/storage/lineagebuild/lineageos4microg/src:/srv/src" \
>     -v "/mnt/storage/lineagebuild/lineageos4microg/zips:/srv/zips" \
>     -v "/mnt/storage/lineagebuild/lineageos4microg/logs:/srv/logs" \
>     -v "/mnt/storage/lineagebuild/lineageos4microg/ccache:/srv/ccache" \
>     -v "/mnt/storage/lineagebuild/lineageos4microg/manifests:/srv/local_manifests" \
>     docker.io/lineageos4microg/docker-lineage-cicd
> ```

Hi, in my case, it was ram amount wich wasn't enough. At least 16gb are needed.
