### ISSUE TITLE
SU not working

### ISSUE THREAD

**Issue by KuzonCode** [lineageos4microg/docker-lineage-cicd#273]
I am really confused here. I have set WITH_SU to true. And I had one build work. I was able to access SU from adb shell. 
![image](https://user-images.githubusercontent.com/8284579/156266778-6c5b2773-6dfa-4719-9de6-146259942221.png)

However, I ran a few more builds and I am no longer able to access SU. 
![image](https://user-images.githubusercontent.com/8284579/156266881-d4d1aedf-5fbe-47b0-a8ee-fb6ec212f272.png)

I can't work out why it would work on one build, but not on another when I didn't change anything. Just wondering if I have missed something super obvious?
![image](https://user-images.githubusercontent.com/8284579/156267830-4f3381a2-6306-49bb-8a58-ecb63083e0b4.png)

**Comment by bananer** [comment]
I don't think `WITH_SU` does anything anymore in recent LineageOS versions.

Root over `adb` can be enabled in developer settings, maybe you did not turn that on in your second build?

**Comment by KuzonCode** [comment]
@bananer I did read that they didn't support it after 16. Just had a look and couldn't see the option in settings. Maybe because I am running a build with the SU flag set? I could also just be going blind...

Oh wait! I am running a user build. Let me try if I change tat to userdebug. I'll give that a crack.

**Comment by petefoth** [comment]
@KuzonCode is it OK to close this issue now?

Assigning back to you for a response
