### ISSUE TITLE
Android S restricted patch breaks Wifi and cellular data in 19.0

### ISSUE THREAD

**Issue by poshul** [lineageos4microg/docker-lineage-cicd#278]
Application of the restricted [android_frameworks_base-S.patch](https://github.com/lineageos4microg/docker-lineage-cicd/blob/lineage-19.0/src/signature_spoofing_patches/android_frameworks_base-S.patch) in 19.0 breaks both Wifi connectivity (fails after authentication) and cellular data connectivity (hangs at connecting). Crucially the equivalent Calyx patch (https://review.calyxos.org/c/CalyxOS/platform_frameworks_base/+/6178) does not introduce such behavior.

**Comment by bananer** [comment]
Thanks for reporting! I compared with the calyx patch again and it seems I actually messed up permission handling for all apps other than microG. This could explain wifi and cellular not working, besides many other potential problems.

Pushed a fix but I don't have a device I can test on right now. Would be great if you could retry an report back.

**Comment by poshul** [comment]
Running the updated patch on its own works. I'll update after rebuilding with Docker.

**Comment by poshul** [comment]
Rebuilding with the changes works and gives a fully* functional image.


*at least as far as my testing has shown so far.
