### ISSUE TITLE
No new builds for whyred? Build at least every time security patch is out?

### ISSUE THREAD

**Issue by flawedworld** [lineageos4microg/docker-lineage-cicd#28]
So I last updated in November, and there hasn't been any builds for whyred. I'm asking as theres now been 2 security patches released. Is this a bug? A very quick and dirty fix would be running the builds on the 5th of every month.

**Comment by corna** [comment]
Unfortunately whyred [has been dropped by LineageOS](https://github.com/LineageOS/hudson/commit/a8286e7fe3d9b46658d8807d3aa132e6f6cc8315#diff-6e2d6eaccc424d5936d22f65ce8b37bdL72), so no new builds will be done :(
