### ISSUE TITLE
add option to limit number of parallel jobs ?????

### ISSUE THREAD

**Issue by Exodusnick** [lineageos4microg/docker-lineage-cicd#286]
set cache size limit to 50.0 GB
/root/build.sh: line 60: PARALLEL_JOBS: unbound variable ??
nick:~/lineageos_microG/18.1_microG/docker-lineage-cicd$

since you put this I can't create a build anymore
https://github.com/lineageos4microg/docker-lineage-cicd/commit/15ba459d3c6482a868bcd4ffda3be19d0309a064#diff-02f64ab7fe6df7a34979c489dccf70a9902438ab964f4fe9471534d6b7b74a76R60

docker run
-e "BRANCH_NAME=lineage-18.1"
-e "DEVICE_LIST=dumpling,cheeseburger"
-e "SIGN_BUILDS=true"
-e "WITH_SU=false"
-e "SIGNATURE_SPOOFING=yes"
-e "UNIFIEDNLP_SUPPORT=true"
-e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension"
-e "RELEASE_TYPE=microG-signed"
-e "INCLUDE_PROPRIETARY=false"
-v "/home/nick/lineageos_microG/18.1_microG/lineage:/srv/src"
-v "/home/nick/lineageos_microG/18.1_microG/zips:/srv/zips"
-v "/home/snick/lineageos_microG/18.1_microG/logs:/srv/logs"
-v "/home/nick/lineageos_microG/18.1_microG/cache:/srv/ccache"
-v "/home/snick/lineageos_microG/18.1_microG/keys:/srv/keys"
-v "/home/snick/lineageos_microG/18.1_microG/manifests:/srv/local_manifests"
lineageos4microg/docker-lineage-cicd

**Comment by bananer** [comment]
Thanks for reporting, should be fixed now.

**Comment by Exodusnick** [comment]
now it works again 
thanks a lot
