### ISSUE TITLE
Almost libre galaxy S3 builds

### ISSUE THREAD

**Issue by tlaurion** [lineageos4microg/docker-lineage-cicd#29]
Can this work be included in separate builds? S3 and  Note 2 would benefit from it.
 https://blog.forkwhiletrue.me/posts/an-almost-fully-libre-galaxy-s3/

**Comment by corna** [comment]
While I'd like to see more builds on this project, we currently just don't have both the resources and the manpower to add "unofficial" builds, I'm sorry.
