### ISSUE TITLE
Lineage-15.1 Failed

### ISSUE THREAD

**Issue by heldrosil** [lineageos4microg/docker-lineage-cicd#298]
`FAILED: /srv/src/LINEAGE_15_1/out/target/common/obj/all-event-log-tags.txt 
/bin/bash -c "build/tools/merge-event-log-tags.py -o /srv/src/LINEAGE_15_1/out/target/common/obj/all-event-log-tags.txt frameworks/base/core/java/android/app/admin/SecurityLogTags.logtags frameworks/base/core/java/android/content/EventLogTags.logtags frameworks/base/core/java/android/net/EventLogTags.logtags frameworks/base/core/java/android/speech/tts/EventLogTags.logtags frameworks/base/core/java/android/webkit/EventLogTags.logtags frameworks/base/core/java/com/android/internal/logging/EventLogTags.logtags frameworks/base/packages/SettingsProvider/src/com/android/providers/settings/EventLogTags.logtags frameworks/base/packages/SystemUI/src/com/android/systemui/EventLogTags.logtags frameworks/base/services/core/java/com/android/server/EventLogTags.logtags frameworks/base/services/core/java/com/android/server/am/EventLogTags.logtags frameworks/ex/common/java/com/android/common/GoogleLogTags.logtags frameworks/native/services/surfaceflinger/EventLog/EventLogTags.logtags frameworks/opt/telephony/src/java/com/android/internal/telephony/EventLogTags.logtags packages/apps/Settings/src/com/android/settings/EventLogTags.logtags packages/providers/CalendarProvider/src/com/android/providers/calendar/EventLogTags.logtags packages/providers/ContactsProvider/src/com/android/providers/contacts/EventLogTags.logtags packages/services/Telephony/src/com/android/phone/EventLogTags.logtags system/bt/main/../EventLogTags.logtags system/core/liblog/event.logtags system/core/libsysutils/EventLogTags.logtags system/core/logcat/event.logtags system/core/logd/event.logtags system/core/storaged/EventLogTags.logtags"
  File "/srv/src/LINEAGE_15_1/build/tools/merge-event-log-tags.py", line 51
    except getopt.GetoptError, err:
           ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
[  0% 177/94792] Check module type: /srv/src/LINEAGE_15_1/out/host/linux-x86/obj/SHARED_LIBRARIES/libhidl-gen_intermediates/link_type
[  0% 178/94792] Notice file: system/tools/hidl/NOTICE -- /srv/src/LINEAGE_15_1/out/host/linux-x86/obj/NOTICE_FILES/src/lib64/libhidl-gen-hash.so.txt
[  0% 179/94792] target Prebuilt: sdk_v21 (/srv/src/LINEAGE_15_1/out/target/common/obj/JAVA_LIBRARIES/sdk_v21_intermediates/classes.jar)
[  0% 180/94792] Merge android manifest files: /srv/src/LINEAGE_15_1/out/target/common/obj/APPS/framework-res_intermediates/AndroidManifest.xml <-- frameworks/base/core/res/AndroidManifest.xml frameworks/base/core/res/LineageManifest.xml
[  0% 181/94792] host C++: conscrypt_generate_constants <= external/conscrypt/constants/src/gen/cpp/generate_constants.cpp
ninja: build stopped: subcommand failed.
10:50:36 ninja failed with: exit status 1

#### failed to build some targets (01:01 (mm:ss)) ####

>> [Tue May 10 10:50:36 UTC 2022] Failed build for bullhead
>> [Tue May 10 10:50:36 UTC 2022] Finishing build for bullhead
>> [Tue May 10 10:50:36 UTC 2022] Cleaning source dir for device bullhead
10:50:36 Entire build directory removed.

#### build completed successfully  ####`

**Comment by bananer** [comment]
Seems like 15.1 expects to be built with python2, but we updated the image to ubuntu 22.04 with python3 [recently](https://github.com/lineageos4microg/docker-lineage-cicd/pull/291).

This might just be the end of 15.1 support from this project. Python2 is unsupported for ages and I don't have the time to support this case.

You could try building the Dockerfile with commit 9a588acc2f5ea257afbafd78300ee29fca0091f7 or before.

**Comment by muranava** [comment]
hi
I have same issue with building 14.1 and i tried using build.sh with the commit suggested (https://github.com/lineageos4microg/docker-lineage-cicd/commit/9a588acc2f5ea257afbafd78300ee29fca0091f7) but no luck.
is there anything else needs to be done regarding building with python2?
thanks for any hints

**Comment by heldrosil** [comment]
I haven't tried. I ended up compiling the normal version without microg.

**Comment by muranava** [comment]
ah I see ok thanks for info

    On Monday, 16 May 2022, 09:41:25 CEST, heldrosil ***@***.***> wrote:  
 
 


I haven't tried. I ended up compiling the normal version without microg.

**Comment by FintasticMan** [comment]
There might be, but this docker image can be used to build a stock version of Lineage.

**Comment by heldrosil** [comment]
> @heldrosil hi i forgot to ask, is there a docker for lineageos without microg? thanks

I have forked and create new branch lineage-15.1, you can use that to build los-14.1, yes you can build without microg, check examples in README.

**Comment by muranava** [comment]
> There might be, but this docker image can be used to build a stock version of Lineage.

hi thanks yes actually i want to build with microg, problem is lineageos 14.1 (and 15.1) can't be built anymore  due to the python change.

**Comment by heldrosil** [comment]
mkdir lineage-docker-muranava
cd lineage-docker-muranava
git clone -b lineage-15.1 https://github.com/heldrosil/docker-lineage-cicd.git .

docker build --tag muranava/docker-lineage-cicd .
