### ISSUE TITLE
Missing builds for kiev (Moto G 5G) and nairo (Moto G 5G Plus)

### ISSUE THREAD

**Issue by UncreativeCreation** [lineageos4microg/docker-lineage-cicd#299]
Hello,

I have looked for kiev and nairo builds on your official download [website](https://download.lineage.microg.org/) but I was unable to find them.

From my search I have found out that both kiev and nairo became officially supported on April 4, 2022:
https://github.com/LineageOS/hudson/commit/d7bc68304ef8f5c43c7e45fa3829d88494c58a99
https://github.com/LineageOS/hudson/commit/c5e1fc7f62a82908cdd6516568f639a68d8ac570
https://www.xda-developers.com/lineageos-18-1-moto-g-5g-plus-motorola-edge/

Official LineageOS builds for these devices can be found here:
https://download.lineageos.org/kiev
https://download.lineageos.org/nairo

From my understanding, builds are supposed to be generated twice a month, and on your download [website](https://download.lineage.microg.org/?sort=time&order=desc) I see that latest builds for some devices were generated between 2022-05-02 and 2022-05-07.
However, there are no builds for kiev and nairo even though it has been almost month and a half since first LineageOS builds for these devices were generated.

Will you please generate builds for these devices or write about encountered problems?
If everything is going according to schedule, I apologize for taking your time.
Thank you in advance.

**Comment by bananer** [comment]
There was one attempt to build these devices. Failure from logs:

```
[ 36% 235/651] including hardware/xiaomi/Android.mk ...
[ 36% 236/651] including kernel/bq/msm8953/drivers/staging/greybus/tools/Android.mk ...
[ 36% 237/651] including kernel/bq/msm8953/drivers/staging/prima/Android.mk ...
[ 36% 238/651] including kernel/bq/msm8953/techpack/audio/Android.mk ...
[ 36% 239/651] including kernel/fairphone/msm8974/drivers/staging/prima/Android.mk ...
[ 36% 240/651] including kernel/fairphone/sdm632/drivers/staging/greybus/tools/Android.mk ...
FAILED:
In file included from kernel/fairphone/msm8974/drivers/staging/prima/Android.mk:20:
In file included from kernel/fairphone/sdm632/drivers/staging/greybus/tools/Android.mk:9:
In file included from build/make/core/executable.mk:58:
In file included from build/make/core/executable_internal.mk:29:
In file included from build/make/core/dynamic_binary.mk:39:
In file included from build/make/core/binary.mk:9:
build/make/core/base_rules.mk:325: error: kernel/fairphone/sdm632/drivers/staging/greybus/tools: MODULE.TARGET.EXECUTABLES.gb_loopback_test already defined by kernel/bq/msm8953/drivers/staging/greybus/tools.
21:54:52 ckati failed with: exit status 1
```

Next round starts tomorrow, maybe the issue was resolved upstream.
