### ISSUE TITLE
repo sync from container on Docker 18.09 - getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by bananer** [lineageos4microg/docker-lineage-cicd#300]
Since we update the container to be based on Ubuntu 22.04, it can no longer `repo sync`, fails with `getaddrinfo() thread failed to start` in the repo logfile. Root cause is the `clone3` syscall not being permitted by Docker.

https://github.com/moby/moby/issues/42680
https://github.com/moby/moby/pull/42681

Docker 18.09 is EOL but it's the latest version in Debian buster

Workaround is to add `--security-opt seccomp=unconfined` when running

**Comment by FintasticMan** [comment]
Maybe podman does allow it? podman should be interchangeable with docker.

**Comment by petefoth** [comment]
@bananer Is it OK to close this issue now or is it still an issue?

Assigning back to you for a response

**Comment by petefoth** [comment]
Closing. If anyone is still seeing this problem, the 'fix' seems to be to use an up-to-date version of Docker
