### ISSUE TITLE
no instantnoodle builds

### ISSUE THREAD

**Issue by paulhersch** [lineageos4microg/docker-lineage-cicd#302]
Hey,
There have been no instantnoodle builds since 4th of April, stock Lineage is still updated. Any reason why there are no builds with microg?

**Comment by bananer** [comment]
Latest build is 20220517 https://download.lineage.microg.org/instantnoodle/

**Comment by paulhersch** [comment]
ah saw it
before that was a period of one month where no updates came and i was starting to worry that something in the build pipeline is broken
