### ISSUE TITLE
no new nio builds

### ISSUE THREAD

**Issue by red-black-bonsai** [lineageos4microg/docker-lineage-cicd#303]
The [last nio build](https://download.lineage.microg.org/nio/) seems to be from 2022-04-06. The [recommendation here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/272#issuecomment-1105327463) was to wait for a build at around 05-01 and apparently that didn't happen. Now it's three weeks later - will nio receive a build during the current build round or is that also already over?

**Comment by red-black-bonsai** [comment]
Ah, a day to early, now there is a build :)
I assume builds for LOS 18 are history because upstream LOS also doesn't have nio builds with 18 anymore?

**Comment by FintasticMan** [comment]
Lineageos4microg only builds the versions specified in the LineageOS/hudson repository, and some older versions for previously supported devices. So that means that there won't be any more 18 builds for `nio`.

**Comment by red-black-bonsai** [comment]
OK, thanks for the info :)
The 19 build works fine for me :+1:
