### ISSUE TITLE
MicroG missing after build

### ISSUE THREAD

**Issue by SyboidGit** [lineageos4microg/docker-lineage-cicd#304]
Hello,

I tried to build Lineage 18.1 with microG included in the roomservice.xml in the local_manifest directory
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    <project path="vendor/partner_gms" name="lineageos4microg/android_vendor_partner_gms" remote="github" revision="master" />
</manifest>
```
Regarding the build command-line:
```
sudo docker run     
-e "BRANCH_NAME=lineage-18.1"     
-e "DEVICE_LIST=sunfish"     
-e "SIGN_BUILDS=true"     
-e "SIGNATURE_SPOOFING=restricted"     
-e "WITH_GMS=true"     
-v "/home/build/Lineageos/lineage:/srv/src"     
-v "/home/build/Lineageos/zips:/srv/zips"     
-v "/home/build/Lineageos/logs:/srv/logs"     
-v "/home/build/Lineageos/cache:/srv/ccache"     
-v "/home/build/Lineageos/keys:/srv/keys"     
-v "/home/build/Lineageos/manifests:/srv/local_manifests"     
lineageos4microg/docker-lineage-cicd
```

It succeeds but I have no MicroG installed or Fdroid.

Any advices ?

Thank you

**Comment by SyboidGit** [comment]
Hi all,

I wonder, does CUSTOM_PACKAGES have still to be used to get MicroG then ? 
_(Maybe have I mistranslated something ?)_

**Comment by michaelschefczyk** [comment]
I find similar results based on the latest docker image (ID 548845b09b0d):

- Building 18.1 does work WITH CUSTOM_PACKAGES
- Building 19.1 does not work WITH CUSTOM_PACKAGES (errors here: https://github.com/lineageos4microg/docker-lineage-cicd/issues/307)
- Building 19.1 does work WITHOUT CUSTOM_PACKAGES, but the ZIP lacks MicroG and Fdroid

**Comment by SyboidGit** [comment]
Hi everybody, 

Please accept my apologies for the late reply,

I've taken a look in the build log and find no errors regarding the apk creation (fdroid), I will try using custom_packages and will tell you if it's better with this trigger,

**Comment by SyboidGit** [comment]
Hello there, I've tried many build

Old way
```
sudo docker run -e "BRANCH_NAME=lineage-18.1" \
-e "DEVICE_LIST=sunfish" -e "SIGN_BUILDS=true" \
-e "SIGNATURE_SPOOFING=restricted" \
-e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend FDroid FDroidPrivilegedExtension" \
-v "/home/build/Lineageos/lineage:/srv/src" \
-v "/home/build/Lineageos/zips:/srv/zips" \
-v "/home/build/Lineageos/logs:/srv/logs" \
-v "/home/build/Lineageos/cache:/srv/ccache" \
-v "/home/build/Lineageos/keys:/srv/keys" \
-v "/home/build/Lineageos/manifests:/srv/local_manifests" \
lineageos4microg/docker-lineage-cicd
```

New way
```
 sudo docker run 
 -e "BRANCH_NAME=lineage-18.1" \
 -e "DEVICE_LIST=sunfish" \
 -e "SIGN_BUILDS=true" \
 -e "SIGNATURE_SPOOFING=restricted" \
 -e "WITH_GMS=true" \
 -v "/home/build/Lineageos/lineage:/srv/src" \
 -v "/home/build/Lineageos/zips:/srv/zips" \
 -v "/home/build/Lineageos/logs:/srv/logs" \
 -v "/home/build/Lineageos/cache:/srv/ccache" \
 -v "/home/build/Lineageos/keys:/srv/keys" \
 -v "/home/build/Lineageos/manifests:/srv/local_manifests" \
 lineageos4microg/docker-lineage-cicd
```
Same issue: no MicroG installed, I didn't see any errors in the logs either,

Any idea ? Am I missing something ?

**Comment by SyboidGit** [comment]
Good Morning,

Does anyone can built it with the 18.1 version ?
I can get any error in the logs, I will increase the verbose

**Comment by pswilde** [comment]
Same here with me, but version 19.1 on Fairphone3+ **without** CUSTOM_PACKAGES.
No errors in logs, in fact I get the below logs
```sh
[ 85% 538/629] including vendor/partner_gms/FDroid/Android.mk ...
[ 85% 539/629] including vendor/partner_gms/FDroidPrivilegedExtension/Android.mk ..
...
[ 86% 541/629] including vendor/partner_gms/GmsCore/Android.mk ...
```

I'm trying **with** CUSTOM_PACKAGES now, we'll see I guess

**Comment by pswilde** [comment]
Further update from me (sorry!), compiling **with** `CUSTOM_PACKAGES` works, even without `WITH_GMS=true` set
I'm running another compile overnight now **without** `CUSTOM_PACKAGES` and **with** `WITH_GMS=true` to check and will update accordingly

**Comment by pswilde** [comment]
So, yep, sorry for my last few comments, but setting `WITH_GMS=true` correctly (i.e. not `GMX`) has worked fine.

Thanks all!

**Comment by SyboidGit** [comment]
Okay; I'm still using the 18.1 (I prefer the UI), but I will retry with the 19.1, maybe it is an issue with the 18.1 ?

Thanks for you reply
