### ISSUE TITLE
Plan for building for LineageOS <= 17.1

### ISSUE THREAD

**Issue by martinknl** [lineageos4microg/docker-lineage-cicd#305]
I currently only see new builds for devices officially supported by LineageOS (so version >= 18.1). Are there plans to support devices again which are stuck on an older LineageOS version?

**Comment by FintasticMan** [comment]
I believe so, see #90.

**Comment by martinknl** [comment]
I also see #298. So clarity on which versions will renain supported going forward would be appreciated.

**Comment by Kommprog** [comment]
I also [interested](https://github.com/lineageos4microg/lineageos4microg.github.io/issues/101#issue-1243922761) about, but there isn't any official answer yet.

**Comment by bananer** [comment]
Right now we're lacking time and resources to support other versions. 

If you want to help, build it yourself and report whether it's working or not.

**Comment by martinknl** [comment]
I did not mean to reopen
