### ISSUE TITLE
Building LOS 19.1 with latest docker file fails

### ISSUE THREAD

**Issue by michaelschefczyk** [lineageos4microg/docker-lineage-cicd#307]
Dear All,

Building LOS 18.1 with a five weeks old docker image (ID 8df1dfa2e8fa) does work. However, trying to build LOS 19.1 with the current image (ID 548845b09b0d) fails early during the repo sync. The error I am getting in the log is:

repo: error: "git" failed with exit status 1
  cwd: /srv/src/LINEAGE_19_1/.repo/repo
  cmd: ['git', 'fetch', '--quiet', '/srv/src/LINEAGE_19_1/.repo/repo/.git/clone.bundle', '+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*']
  stderr:
  >> fatal: unable to create thread: Operation not permitted
  >> error: index-pack died
fatal: double check your --repo-rev setting.
fatal: cloning the git-repo repository failed, will remove '.repo/repo' 

Can someone please be so kind to indicate what that may mean?

Regards,

Michael Schefczyk

**Comment by bananer** [comment]
Could be this issue https://github.com/lineageos4microg/docker-lineage-cicd/issues/300

What version of docker are you using?

**Comment by michaelschefczyk** [comment]
The workaround did not help, but upgrading Docker to 20.10.16 did solve the issue.

However, the build does still not complete, and I am still seeking advice on this.

My command is:

docker run -e "BRANCH_NAME=lineage-19.1" -e "DEVICE_LIST=enchilada" -e "SIGN_BUILDS=true" -e "SIGNATURE_SPOOFING=restricted" -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension com.android.email " -v "/mnt/lineage:/srv/src" -v "/mnt/zips:/srv/zips" -v "/mnt/logs:/srv/logs" -v "/mnt/cache:/srv/ccache" -v "/mnt/keys:/srv/keys" -v "/mnt/manifests:/srv/local_manifests" lineageos4microg/docker-lineage-cicd

I intend to include email (no problem in 18.1) like this: https://github.com/lineageos4microg/docker-lineage-cicd/issues/204

My additional manifest file is:

<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    
    <project path="packages/apps/Email" name="LineageOS/android_packages_apps_Email" revision="lineage-17.1" />
    <project path="packages/apps/Exchange" name="LineageOS/android_packages_apps_Exchange" revision="lineage-17.1" />
    <project path="packages/apps/UnifiedEmail" name="LineageOS/android_packages_apps_UnifiedEmail" revision="lineage-17.1" />
</manifest>

The errors logged are:

[ 65% 93128/141196] //system/tools/sysprop:sysprop_api_dump clang++ CodeWriter.cpp [linux_glibc]
[ 65% 93129/141196] Verifying uses-libraries: prebuilts/prebuiltapks/NominatimNlpBackend/org.microg.nlp.backend.nominatim_20042.apk
[ 65% 93130/141196] Verifying uses-libraries: prebuilts/prebuiltapks/com.google.android.maps/com.google.android.maps.jar
FAILED: out/target/common/obj/JAVA_LIBRARIES/com.google.android.maps.jar_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/JAVA_LIBRARIES/com.google.android.maps.jar_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/common/obj/JAVA_LIBRARIES/com.google.android.maps.jar_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bin/aapt 	   	   	   	   	  prebuilts/prebuiltapks/com.google.android.maps/com.google.android.maps.jar )"
error: not well-formed (invalid token): line 1, column 2
[ 65% 93131/141196] Verifying uses-libraries: prebuilts/prebuiltapks/FDroidPrivilegedExtension/org.fdroid.fdroid.privileged_2120.apk
[ 65% 93132/141196] Verifying uses-libraries: prebuilts/prebuiltapks/FakeStore/com.android.vending-22.apk
[ 65% 93133/141196] Verifying uses-libraries: prebuilts/prebuiltapks/GmsCore/com.google.android.gms-212658044.apk
FAILED: out/target/common/obj/APPS/GmsCore_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/APPS/GmsCore_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/common/obj/APPS/GmsCore_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bin/aapt 	   	   	   	   	  prebuilts/prebuiltapks/GmsCore/com.google.android.gms-212658044.apk )"
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: [com.android.location.provider]
	- optional libraries in build system: []
	                 vs. in the manifest: []
	- tags in the manifest (prebuilts/prebuiltapks/GmsCore/com.google.android.gms-212658044.apk):
		uses-library:'com.android.location.provider'
note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- see build/make/Changes.md for details

[ 65% 93134/141196] Verifying uses-libraries: out/target/common/obj/APPS/OnePlusPocketMode_intermediates/manifest/AndroidManifest.xml
[ 65% 93135/141196] Verifying uses-libraries: out/target/common/obj/APPS/Camera2_intermediates/manifest/AndroidManifest.xml
[ 65% 93136/141196] //system/tools/sysprop:sysprop_api_checker clang++ ApiCheckerMain.cpp [linux_glibc]
[ 65% 93137/141196] //system/tools/sysprop:sysprop_api_checker clang++ proto/system/tools/sysprop/sysprop.pb.cc [linux_glibc]
[ 65% 93138/141196] //system/tools/sysprop:sysprop_api_dump clang++ ApiDumpMain.cpp [linux_glibc]
[ 65% 93139/141196] //system/tools/sysprop:sysprop_api_dump clang++ proto/system/tools/sysprop/sysprop.pb.cc [linux_glibc]
[ 65% 93140/141196] //system/tools/sysprop:sysprop_cpp clang++ proto/system/tools/sysprop/sysprop.pb.cc [linux_glibc]
[ 65% 93141/141196] //packages/modules/DnsResolver:libnetd_resolv clang-tidy DnsTlsSocket.cpp [com.android.resolv]
[ 65% 93142/141196] //system/tools/sysprop:sysprop_api_checker clang++ ApiChecker.cpp [linux_glibc]
[ 65% 93143/141196] //system/tools/sysprop:sysprop_api_checker clang++ Common.cpp [linux_glibc]
[ 65% 93144/141196] //system/tools/sysprop:sysprop_cpp clang++ Common.cpp [linux_glibc]
[ 65% 93145/141196] //system/tools/sysprop:sysprop_api_dump clang++ Common.cpp [linux_glibc]
[ 65% 93146/141196] //frameworks/av/services/mediametrics:libmediametricsservice clang-tidy AudioAnalytics.cpp
[ 65% 93147/141196] //external/rust/crates/libsqlite3-sys/android:sqlite3_bindgen_build rustc build.rs [linux_glibc]
ninja: build stopped: subcommand failed.
18:20:06 ninja failed with: exit status 1

#### failed to build some targets (01:11:12 (hh:mm:ss)) ####

**Comment by petefoth** [comment]
@michaelschefczyk Is this still a problem for you or have you been able to build OK with the latest image. If you have it would nice to be able to close this issue.

Assigning back to you for comment

**Comment by michaelschefczyk** [comment]
I have given up building myself.
