### ISSUE TITLE
rebuild instructions

### ISSUE THREAD

**Issue by 532910** [lineageos4microg/docker-lineage-cicd#308]
I'm trying to use this docker env with crdroid oneplus repos and found it's not enough just to edit a manifest file placed in a directory bind-mounted to `/srv/local_manifests`. But also you need to remove `src/LINEAGE_19_1/.repo/local_manifests` as it isn't updated.

Is this a `build.sh` issue or what should the rebuild process look like?

**Comment by petefoth** [comment]
@532910 Please can you let us know if this is till a problem for you?

Thanks

**Comment by petefoth** [comment]
Closing due to no response
