### ISSUE TITLE
[alioth] Failed to build LineageOS 19.1

### ISSUE THREAD

**Issue by flame-0** [lineageos4microg/docker-lineage-cicd#309]
**Device**
[`alioth`](https://wiki.lineageos.org/devices/alioth/)

**Logs**
[`repo-20220605.log`](https://github.com/lineageos4microg/docker-lineage-cicd/files/8843412/repo-20220605.log)
[`lineage-19.1-20220605-AMOGUS-alioth.log`](https://github.com/lineageos4microg/docker-lineage-cicd/files/8843416/lineage-19.1-20220605-AMOGUS-alioth.log)

**Additional Context**
> Personal Android keys with password are generated from unmodified forked [`make_key`](https://github.com/flame-0/docker-lineage-cicd/blob/master/src/make_key) shell script.

> **Modification in [`flame-0: android_vendor_partner_gms`](https://github.com/flame-0/android_vendor_partner_gms)**
> Removed [`F-Droid and Updater`](https://github.com/flame-0/android_vendor_partner_gms/commit/b7871ac07587b265ff4d8b153a718ed599e672e0)

> **Tree of `/home/user/manifests` and the content of `amogus.xml`**
> ```
> amogus.xml
> ```
> ```xml
> <?xml version="1.0" encoding="UTF-8"?>
> <manifest>
>     <project path="vendor/partner_gms" name="flame-0/android_vendor_partner_gms" remote="github" revision="master" />
> </manifest>
> ```

> **Modification in `Dockerfile`**
> ```
> RELEASE_TYPE 'AMOGUS'
> ```

> **Executed docker command**
> ```
> sudo docker run \
>     -e "BRANCH_NAME=lineage-19.1" \
>     -e "DEVICE_LIST=alioth" \
>     -e "SIGN_BUILDS=true" \
>     -e "SIGNATURE_SPOOFING=restricted" \
>     -e "WITH_GMS=true" \
>     -v "/home/user/lineage:/srv/src" \
>     -v "/home/user/zips:/srv/zips" \
>     -v "/home/user/logs:/srv/logs" \
>     -v "/home/user/cache:/srv/ccache" \
>     -v "/home/user/keys:/srv/keys" \
>     -v "/home/user/manifests:/srv/local_manifests" \
>     c4797eb5c6a1
> ```

**Comment by flame-0** [comment]
I think it's similar issue here, https://github.com/AndroidHardeningArchive/legacy_bugtracker/issues/126.

**Comment by bananer** [comment]
from https://github.com/AndroidHardeningArchive/legacy_bugtracker/issues/126#issuecomment-309924257

> The keys should not be given passwords due to limitations in the upstream scripts. If you want to secure them at rest, you should take a different approach where they can still be available to the signing scripts as a directory of unencrypted keys. The sample certificate subject can be replaced with your own information or simply left as-is.
