### ISSUE TITLE
can't flash recovery on Pixel 4a 5G (bramble)

### ISSUE THREAD

**Issue by widener-physics** [lineageos4microg/docker-lineage-cicd#313]
The recovery image for bramble doesn't seem to work.  I've tried using both the one on the site and compiling one myself.  Both flash without error, but when booting into recovery I get dumped back to fastboot with the error message "error boot prepare"

The stock Lineage recovery loads fine, and I can load Lineage w/ MicroG using that, but then I lose OTA updates.

I think Lineage recently updated their recovery installation instructions, since now you have to flash vendor_boot instead of the boot or recovery partitions.

Any advice is appreciated.

**Comment by stephan-herrmann** [comment]
> I think Lineage recently updated their recovery installation instructions, since now you have to flash vendor_boot instead of the boot or recovery partitions.

Where did you find that? Any details?

**Comment by hansjuergenmay** [comment]
I have the same problem, I downloaded the latest recovery from 
https://download.lineage.microg.org/bramble/lineage-20.0-20230122-microG-bramble-boot.img
, but this recovery doesn't boot (error boot prepare).

**Comment by bananer** [comment]
Installation instructions indeed tell you to flash `vendor_boot` for this device: https://wiki.lineageos.org/devices/bramble/install

I changed the script so it should also copy that partition image, if it exists: https://github.com/lineageos4microg/docker-lineage-cicd/commit/ba58e6bd8f36222c8f8ad975c4abad9bafbf236d

Could not test it yet, but hopefully during the next run of builds `vendor_boot` images should also turn up so you can follow the instructions properly.

**Comment by petefoth** [comment]
This problem should be fixed when #467 is merged to fix #405. If all goes according to plan, our built `vendor-boot.img` should be made available with the September builds.

Until then you could try using the latest LineageOS `vendor_boot.img' from [here](https://download.lineageos.org/devices/bramble/builds)

@widener-physics @mennerausr If you have time to try that, I would be very interested in the outcome. Thanks

**Comment by petefoth** [comment]
New `boot.img` and `vendor_boot.img` files are now available for download at https://download.lineage.microg.org/barbet/

**Comment by petefoth** [comment]
All needed images for bramble are available at https://download.lineage.microg.org/bramble/
