### ISSUE TITLE
Build LOS 18.1 for Gauguin fails : proprietary/vendor/etc/camera/megviifacepp_0_5_2_model missing

### ISSUE THREAD

**Issue by ElCorzo** [lineageos4microg/docker-lineage-cicd#317]
Ubuntu Linux 20.04. Docker version : 20.10.14, build a224086
Please see the build configuration in TXT file and the two LOG files attached.

[lineage-18.1-20220704-UNOFFICIAL-gauguin.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/9042172/lineage-18.1-20220704-UNOFFICIAL-gauguin.log)
[repo-20220704.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/9042173/repo-20220704.log)
[build.config.txt](https://github.com/lineageos4microg/docker-lineage-cicd/files/9042178/build.config.txt)

**Comment by ElCorzo** [comment]
LOS 19.1 build was successful (7 hours from docker run to the end!). So this issue may be not so important if you have limited resources and want to focus on most actual ...

**Comment by petefoth** [comment]
I'm going to close this issue, as latest 19.1 builds for `gauguin` are building with no problem
