### ISSUE TITLE
[FP3] 19.1 builds still missing

### ISSUE THREAD

**Issue by EmanuelLoos** [lineageos4microg/docker-lineage-cicd#318]
LineageOS 19.1 is already available for quite some time without a corresponding L4M build. I suspect the build might have failed.
If I'm just being impatient, I apologise for that.

**Comment by FintasticMan** [comment]
L4M builds are done 2 times a month, and there just hasn't been a build since it was bumped to Lineage 19.

**Comment by EmanuelLoos** [comment]
> L4M builds are done 2 times a month, and there just hasn't been a build since it was bumped to Lineage 19.
The [last build](https://download.lineage.microg.org/FP3) is from 20220616. The first official LinageOS 19.1 build is from 20220627. Today would be 20220707. That is longer than half a month. Therefore I suspected the build might have failed. But maybe the build server is just busy.

**Comment by Iey4iej3** [comment]
It seems that the last build of this around is 07/07 morning (according to the modified date shown on the download server). @bananer Is there any issue on the server side?

**Comment by bananer** [comment]
Last round of 19.1 build failed due to a repo sync error:

```
error.GitError: Cannot checkout LineageOS/android_hardware_qcom_display: LineageOS/android_hardware_qcom_display rev-list ('^d6d038f5b936a5432b9fbf778beb6934b8a29b1f', 'HEAD', '--'): fatal: bad object d6d038f5b936a5432b9fbf778beb6934b8a29b1f

error: Cannot checkout LineageOS/android_hardware_qcom_display
error.GitError: Cannot checkout LineageOS/android_hardware_qcom_media: LineageOS/android_hardware_qcom_media rev-list ('^900fdc81a13e8fe1ab495aab58b160a3777bf075', 'HEAD', '--'): fatal: bad object 900fdc81a13e8fe1ab495aab58b160a3777bf075
```

Don't have a lot of time to look into this right now. I deleted the source directory so it will re-download on the next build. Hopefully that fixes it. Check back for a FP3 build approximately around 07/25.

**Comment by marek22k** [comment]
Is there any new information?

**Comment by EmanuelLoos** [comment]
@bananer
Is it still building or did it fail again?

**Comment by Iey4iej3** [comment]
@bananer It seems that there were still some errors. For example, there is no build of [gta4xlwifi](https://download.lineage.microg.org/gta4xlwifi/) in July.

**Comment by htsr** [comment]
The 19.1 build is out ! 🎉

**Comment by D3SOX** [comment]
Maybe a bit off-topic here, but does anybody know if there's an ETA for 19.1 on the OnePlus 8T (kebab)

**Comment by ThaChillera** [comment]
> The 19.1 build is out !

For anyone following this thread, be warned that for me the 19.1 update had a pretty big performance impact.

**Comment by marek22k** [comment]
After updating the F-Droid Extensions does not work anymore.

**Comment by EmanuelLoos** [comment]
Closing this issue since there is now a build.

> After updating the F-Droid Extensions does not work anymore.
> Should I open a Issue for it?

I did a fresh install and it worked fine, but go ahead.

**Comment by olegtishin** [comment]
Yay, the new build came for my lemonade :) Thank you developers!

I know it's a bit of a strange question, but still, can I expect timely updates from now on? (twice a month, as stated on the site)

**Comment by Iey4iej3** [comment]
> I know it's a bit of a strange question, but still, can I expect timely updates from now on? (twice a month, as stated on the site)

One of the inconvenience is that, once the build of a device fails, then the building procedure stops, so the devices ordered after this device won't build in the same round.

**Comment by olegtishin** [comment]
> so the devices ordered after this device won't build in the same round.

Sorry for my possible incompetence, but how long, in this case, do we have to wait for the next round?

> once the build of a device fails

And do I understand correctly that the device, the build for which fails, can be absolutely any device? 

> then the building procedure stops

If the build fails for a certain device, the next builds for the other devices in the queue will not be built? 
And how long do we need to wait for builds for devices that are in the queue after a failed build device? 

Thank you and sorry for the questions.

**Comment by remi-dupre** [comment]
Hi!

Builds for the [FP3](https://download.lineage.microg.org/FP3/) have not been updated for about 6 weeks, it seems that it is very similar to the issue discussed above. Should I report this in a separate issue? (Is there any way to help, investigating some logs for example?)

**Comment by SecT0uch** [comment]
Maybe a new issue would be more appropriate, since we had a release since then.
