### ISSUE TITLE
Issues with latest beyond2lte build

### ISSUE THREAD

**Issue by danboid** [lineageos4microg/docker-lineage-cicd#320]
Yesterday I installed https://download.lineage.microg.org/beyond2lte/lineage-19.1-20220622-microG-beyond2lte.zip on my SGS 10+ (SM-G975F)

The first issue I encountered after installing was that the microG settings and services didn't seem to be installed. I couldn't see a link to the microG settings app and nor could I open gcam / zgcam. That seemed very odd but they're easy enough to install so I did that, opened microG settings and ran the Self-Check but it told me that the ROM has no native support for signature spoofing and I thought this was the whole purpose of the LOS4microg ROMs?

Also, is there any functional difference between the the LOS4microg recovery images versus the regular LOS recovery images for the same major/minor version and platform?

**Comment by petefoth** [comment]
@danboid Is this still a problem for you. Are you running an up-to-date LOS4microg build?

**Comment by petefoth** [comment]
Closing.
