### ISSUE TITLE
[Pixel 4(flame)] Builds fall behind the official repo

### ISSUE THREAD

**Issue by Bob0111** [lineageos4microg/docker-lineage-cicd#321]
You said it will update it twice a month，but the previous build was 20220624, and today is 20220724, a month has passed without any update. I hope I will get updates soon as it contains both for system and vendor security patch.

**Comment by real-or-random** [comment]
I suspect the reason is the same as in #323

**Comment by Iey4iej3** [comment]
Related: https://github.com/lineageos4microg/docker-lineage-cicd/issues/318#issuecomment-1179102517

**Comment by real-or-random** [comment]
A new build appeared yesterday, so I believe the server is doing its job again.

**Comment by petefoth** [comment]
Closing this issue: `flame` builds are up-to-date as of this month
