### ISSUE TITLE
July build missing for sunfish

### ISSUE THREAD

**Issue by ghost573** [lineageos4microg/docker-lineage-cicd#322]
Not sure if there was a problem but sunfish didn't get a July build.

**Comment by christophehenry** [comment]
Same for dumpling. [There was 4 builds in july](https://download.lineageos.org/dumpling) last update from L4M is from 23 june. There are several annoying bugs in 19.1 I expect fixes for in these updates.

**Comment by Danacus** [comment]
Same for X00TD. Should've been built at 20th of July, like other ASUS devices, but it appears to have been skipped. Perhaps the build failed?

**Comment by RizzoV** [comment]
Same for dipper and lemonade sadly.

**Comment by Dperrigo18** [comment]
I would like to add lake to the list as well.

**Comment by Iey4iej3** [comment]
Related: https://github.com/lineageos4microg/docker-lineage-cicd/issues/318#issuecomment-1179102517

**Comment by timethy96** [comment]
Same for sargo.

**Comment by Danacus** [comment]
Looks like the new "wave" of builds is succeeding, judging from the downloads page. dumpling, dipper, lemonade and lake have new builds. sunfish, X00TD and sargo will probably receive an update soon (I predict within the next few days).
