### ISSUE TITLE
No timely updates for OnePlus 9 (lemonade)

### ISSUE THREAD

**Issue by olegtishin** [lineageos4microg/docker-lineage-cicd#323]
At the time of writing this post, the latest nightly version of the [official LOS](https://download.lineageos.org/lemonade) for my device was released on 2022-07-24

But if you check when the last version of [LOS for microG](https://download.lineage.microg.org/lemonade/) for my device was released, it turns out to be 2022-06-10

It turns out that LOS for microG has not been updated for my device for almost two months.
 But the official LOS for microG page says that OTA updates come twice a month.

Should I be worried? Is it normal?

**Comment by Danacus** [comment]
Possibly related to #322.

**Comment by Iey4iej3** [comment]
Related: https://github.com/lineageos4microg/docker-lineage-cicd/issues/318#issuecomment-1179102517

**Comment by olegtishin** [comment]
Yay, the new build came for my lemonade :) Thank you developers!

I know it's a bit of a strange question, but still, can I expect timely updates from now on? (twice a month, as stated on the site)

**Comment by levinuss** [comment]
19.1 builds seem to have failed again after bramble on 07.09 :c So no new builds for 19.1 devices after bramble.
Hope the build round starting on Thursday will go through..

**Comment by FintasticMan** [comment]
And it seems this build round has failed after `dipper`, so I assume that `discovery` is the device whose build failed.
