### ISSUE TITLE
missing .img files for lemonade

### ISSUE THREAD

**Issue by tieu1991** [lineageos4microg/docker-lineage-cicd#324]
Starting on 2022-07-24 the lineageos team started including some new .img file in the release. The build with this docker image does not include those .img files. This result in an update that does not work properly because these files were not updated. Here is a list of those missing files:

abl.img
aop.img
bluetooth.img
cpucp.img
devcfg.img
dsp.img
engineering_cdt.img
featenabler.img
hyp.img
imagefv.img
keymaster.img
modem.img
multiimgoem.img
oplus_sec.img
oplusstanvbk.img
qupfw.img
qweslicstore.img
shrm.img
splash.img
tz.img
uefisecapp.img
xbl_config.img
xbl.img

I don't know if something is missing in the docker image or something is missing in the official LineageOS git repo. For now I manually flashed the missing .img files that I extracted from the official release, and it works.

**Comment by fx880p** [comment]
> 

you extracted the files from the official lineage release (without microg) or from the stock rom (which version?)? Do you have the newest update?

**Comment by tieu1991** [comment]
I extracted from the latest release of the official LineageOS (without microg). After that you apply these operations. 

https://wiki.lineageos.org/devices/lemonade/fw_update

With the exeption of vm-bootsys which was not included the latest release at that moment.

**Comment by fx880p** [comment]
I have now downgraded to lineage-19.1-20220611. It cost me a lot of time. :(
I hope the next update (with microg) includes the updatet files and i can upgrade without any errors.

**Comment by gwstorm** [comment]
Issue still persists. 🙁 Time to rebuild.

**Comment by tieu1991** [comment]
FYI, I tried building the official LineageOS according to their instructions. The firmware files are still missing. They must do something in post build to add these files.
