### ISSUE TITLE
Intent filter verification service / com.android.statementservice regularly crashing on LineageOS for microg

### ISSUE THREAD

**Issue by ale5000-git** [lineageos4microg/docker-lineage-cicd#325]
See this: https://github.com/microg/GmsCore/issues/1740

I currently cannot test it but it may be fixed by this:

Quote from [flipreverse](https://github.com/flipreverse):
> This seems to be a bug in AOSP: https://android.googlesource.com/platform/frameworks/base/+/4978d1ad10293900e9b5feea349abd09ceb6e710
> The LOS repo android_frameworks_base does not have this commit at the moment. I'll cherry-pick that one, and give it a try.

**Comment by st3rox** [comment]
Clearing app data for it and force stopping it stops it from crashing repeatedly

Still crashes every reboot

**Comment by gonciarz** [comment]
Confirmed (on vayu / Xiaomi Poco X3 Pro)

**Comment by ale5000-git** [comment]
This is now also in the LOS repo: https://github.com/LineageOS/android_frameworks_base/commit/fce1b15db00aae4447456359ac1c16bf773bbb26

**Comment by bananer** [comment]
I've also experienced this in the past and it went away some time ago. Seems like that is resolved.
