### ISSUE TITLE
lemonadep 06.08.2022 Update - Touchscreen is not working

### ISSUE THREAD

**Issue by fx880p** [lineageos4microg/docker-lineage-cicd#326]
The update took a long time und after the restart i've seen the login screen for seconds and the screen went black.
i made a hard reboot. Now i see the login screen, but the touchscreen is not working and i can't login. :(

updating 
lineage-19.1-20220611-microG-lemonadep to lineage-19.1-20220806-microG-lemonadep

**Comment by tieu1991** [comment]
This problem is the same as I had with lemonade. This issue is the thing.
 https://github.com/lineageos4microg/docker-lineage-cicd/issues/324

**Comment by skunkfox** [comment]
The flowchart on the website really needs to be updated, I had no idea where to go to even report this bug.

**Comment by Context0486** [comment]
I had the same issue.  Using payload dumper to extract from the latest LineageOS release for lemonadep the files you need to flash, then following https://wiki.lineageos.org/devices/lemonadep/fw_update instructions while in fastbootd fixed it for me

**Comment by fx880p** [comment]
Has anyone tested the new update?

**Comment by Context0486** [comment]
I'm going to try it later on when I have my computer set up in case it requires the missing .img flashing again, will update with results

**Comment by fx880p** [comment]
the new update works great.
