### ISSUE TITLE
[OTA_URL] unescaped apostrophe in string

### ISSUE THREAD

**Issue by TheLastGimbus** [lineageos4microg/docker-lineage-cicd#329]
Hi there!
I was building my image, and after 20 minutes, it failed because of the stupid error:

```
FAILED: out/target/common/obj/APPS/Updater_intermediates/flat-res/vendor/lineage/overlay/microg/packages/apps/Updater/res/values_strings.arsc.flat
/bin/bash -c "out/soong/host/linux-x86/bin/aapt2 compile -o out/target/common/obj/APPS/Updater_intermediates/flat-res/vendor/lineage/overlay/microg/packages/apps/Updater/res/ --pseudo-locali
ze  vendor/lineage/overlay/microg/packages/apps/Updater/res/values/strings.xml"
vendor/lineage/overlay/microg/packages/apps/Updater/res/values/strings.xml:5: error: unescaped apostrophe in string
"'https://ota.lineage4microg.lastgimbus.com/api'/v1/{device}/{type}/{incr}".
```

i passed it like that:
```
...
-e "OTA_URL='https://ota.lineage4microg.lastgimbus.com/api'" \
...
```

I thought the apostrophe is needed there... i passed few other things with apostrophes and they went fine...

Maybe there should be a function somewhere to parse those env vars to avoid errors like this...

**Comment by petefoth** [comment]
The ['Examples' section of the README](https://github.com/lineageos4microg/docker-lineage-cicd#build-for-four-devices-on-lineage-171-and-lineage-181-officially-supported-custom-keys-restricted-signature-spoofing-with-integrated-microg-and-fdroid-custom-ota-server) clearly shows `OTA_URL` being set ***without*** an apostrophe
>     -e "OTA_URL=https://api.myserver.com/" \
 
The parsing is done by Docker, not by any of our scripts so there's nothing we can do

Closing
