### ISSUE TITLE
M4L builds aren't signed? 

### ISSUE THREAD

**Issue by christophehenry** [lineageos4microg/docker-lineage-cicd#332]
Since I flashed microg for Lineage on my Nexus 7 2013 repartitionned (flox), I can't apply any update using Lineage's recovery for it claims the signature verification fails.

On other devices, I usually use TWRP, but TWRP is not available for the flox variant (only flo) so TWRP won't install update either claiming it's not suitable.

**Comment by LuccoJ** [comment]
The signature is different from the one of official LineageOS, so you need to get the LineageOS for microG *recovery* too, not use LineageOS's standard one.

**Comment by petefoth** [comment]
> you need to get the LineageOS for microG _recovery_ too, not use LineageOS's standard one.

Our recovery image for `flox` is now made available at https://download.lineage.microg.org/flox/, so I'm going to close this issue. Please feel free to reopen it, or create a new issue if you still have problems applying updates.
