### ISSUE TITLE
seccomp Settings prevent curl from working

### ISSUE THREAD

**Issue by tfbb-bb** [lineageos4microg/docker-lineage-cicd#333]
hi there -

thank you for your work, I've been using lineageos4microg to build roms for a moto g5 for quite some time now :)

However, after pulling the latest image, the container exited immediately after writing this to the logfile:
> [Mon Aug 22 09:11:51 UTC 2022] (Re)initializing branch repository
fatal: unable to access 'https://github.com/LineageOS/android.git/': getaddrinfo() thread failed to start
fatal: unable to access 'https://github.com/LineageOS/android.git/': getaddrinfo() thread failed to start
fatal: cannot obtain manifest https://github.com/LineageOS/android.git
manifests: sleeping 4.0 seconds before retrying

Digging around in the container revealed that `curl` doesn't seem to be able to resolve hostnames anymore:
> root@059af0f376f8:/srv/src# curl https://github.com/LineageOS/android.git/                                                                                       
curl: (6) getaddrinfo() thread failed to start                                                               
root@059af0f376f8:/srv/src#

… which seems due to it using the clone-syscall, which won't be allowed by seccomp. See [here](https://openforums.blog/2021/12/15/tracing-curl-error-6-getaddrinfo-thread-failed-to-start-error-with-systemd-seccomp-filters/) for a similar issue.

Starting the container with `--security-opt seccomp=unconfined` works around the issue - however, it might be a good idea to fix this in the image.

**Comment by bananer** [comment]
See #300 - update your Docker

**Comment by tfbb-bb** [comment]
thank you, that fixed it: docker-ce in debian buster is now  20.10.
