### ISSUE TITLE
Did build have errors, seems to have stopped at 17/09/2022

### ISSUE THREAD

**Issue by ghost573** [lineageos4microg/docker-lineage-cicd#338]
New round of builds seem to have started on 15/09/2022 but seems to have gotten stuck with the last build for dipper on 17/09/2022, just checking to make sure everything is fine.

**Comment by D3SOX** [comment]
Is there a technical reason why all subsequent builds are stopped when one fails?

**Comment by bananer** [comment]
unfortunately there are still some error conditions which cause all the following builds to fail. we ran into one of them in the last round. [I think I fixed that one now](https://github.com/lineageos4microg/docker-lineage-cicd/commit/6280708eae7e9cf1991465270b856b0c5b19fa0b), let's hope in the next round on oct 1st all will go well.
