### ISSUE TITLE
19.1 for instantnoodlep

### ISSUE THREAD

**Issue by C0D3D3V** [lineageos4microg/docker-lineage-cicd#339]
I'm just wondering if there will be a 19.1 build for instantnoodlep this month. I expected it to be build at the 17.09, because the last two builds were done at the 17th.
Can someone tell me if there will be one this month?

**Comment by subterfugium** [comment]
I was wondering the same. Offtopic: Downgrading oxygenos 12 to lineage-microg-18.1 did not go smoothly.

**Comment by C0D3D3V** [comment]
Would it be possible to publish some status informations about the builds per device (only theoreticly)? So that answers to such questions would be visible on the status page.

**Comment by Nan123721** [comment]
My daily driver as well. Hoping for a build soon!

**Comment by subterfugium** [comment]
From Telegram:
There's currently some sort of build issue, the guy who does the builds mentioned it on their Github on 9/22, and it should be fixed now.

Apparently they will start a new round of builds on 10/1.

Device roms are built in alphabetical order by device codename.

If you periodically check the timestamps of the builds on their download page, starting at the top of the alphabet, you can check the progress.

https://github.com/lineageos4microg/docker-lineage-cicd/issues/338#issuecomment-1255484784

**Comment by Nan123721** [comment]
Any updates? It seems to have skipped instantnoodle and instantnoodlep.

**Comment by D3SOX** [comment]
> 

See https://github.com/lineageos4microg/docker-lineage-cicd/issues/341#issuecomment-1265745068

**Comment by Nan123721** [comment]
I'm confused as to what you're saying. Are you saying that it's doing all 18.1 builds first, or that instantnoodlep doesn't have an Lineage 19 build?

**Comment by subterfugium** [comment]
Build is now available!

**Comment by C0D3D3V** [comment]
¡Fantastico!
