### ISSUE TITLE
Infinite startup when tried to unlock with fingerprint first

### ISSUE THREAD

**Issue by Booteille** [lineageos4microg/docker-lineage-cicd#34]
When I try to unlock my phone, at boot, with fingerprint instead of schema first, I get an infinite loop where I can't unlock the phone. It states "démarrage du téléphone" (booting) for a while then go back on the lock screen.

I am using 16.0-20190311-microG-oneplus3 build.

**Comment by JustMeErazem** [comment]
This is probably a LineageOS-related issue and doesn't have much to do with MicroG, especially with this docker image. Post it in reddit or the LineageOS bug reporter.

**Comment by corna** [comment]
As @JustMeErazem said, this is probably a LineageOS-related bug.
