### ISSUE TITLE
Build Server Issues for version 19.1?

### ISSUE THREAD

**Issue by mddvul22** [lineageos4microg/docker-lineage-cicd#341]
I don't know how the build server works, but it would appear that there is an issue with the build server and version 19.1. It appears that perhaps a build for one device (discovery, perhaps?) is failing and causing all builds after that to not get built? Perhaps the builds occur in alphabetical order? Some devices, like blueline are getting built every few weeks. However, many other devices, like fajita and flame, haven't been built in over a month.

**Comment by levinuss** [comment]
See https://github.com/lineageos4microg/docker-lineage-cicd/issues/338#issuecomment-1255484784

**Comment by subterfugium** [comment]
It seems 18 builds are working today but I don't see any successful 19.1 builds (assuming builds are done aplhabetically). 

@bananer could you check?

**Comment by D3SOX** [comment]
Hm, still no new (19.1) build for kebab today. This is my only annoyance with this ROM. If the build fails two times you don't get updates for months.

**Comment by subterfugium** [comment]
> Hm, still no new (19.1) build for kebab today. This is my only annoyance with this ROM. If the build fails two times you don't get updates for months.

As said before 18 builds are going now (somewhere around D*) and 19 will follow later.

**Comment by D3SOX** [comment]
Hm now it's the 2nd and there is still no build. Is there an easy way to migrate to a self-compiled build? I think I'd need to swap the keys or something like that.

**Comment by FintasticMan** [comment]
There are a lot of devices to build, and building each usually seems to take between 20 minutes and an hour, so you can imagine that it takes more than 2 days to build all of the devices.

You can check the progress at <https://download.lineage.microg.org/?sort=time&order=desc>.

**Comment by D3SOX** [comment]
> There are a lot of devices to build, and building each usually seems to take between 20 minutes and an hour, so you can imagine that it takes more than 2 days to build all of the devices.
> 
> You can check the progress at <https://download.lineage.microg.org/?sort=time&order=desc>.

It would be better if the build server was publicly viewable but thanks for that link!

**Comment by mddvul22** [comment]
klte is an 18.1 build.  It hasn't gotten to the 19.1 builds, yet.

**Comment by D3SOX** [comment]
Ok, thanks for the heads-up. I was about to try building it myself, but then I guess I'll wait a bit longer

**Comment by EnnoxHD** [comment]
The build server seem to have stopped again? The last 18.1 build was for device `x2`. Since then there are no new builds for the last 14 hours.

**Comment by mddvul22** [comment]
Hopefully they can get this started again.  It would be nice if they could also start with the 19.1 devices since those seem to have the most current state of support.  Is the core problem the quality of the build server hardware?  Or is this a software bug?  If it is hardware and if there is a way to make donations toward purchasing hardware, I'd be willing to donate to that.

**Comment by D3SOX** [comment]
Still no new builds. Is there no one here who can trigger the 19.1 builds?

I'm building it myself right now. I hope it works installing it on top without data loss.
Furthermore, I'm also thinking about switching to upstream Lineage and install microG via Magisk or NanoDroid, but I'm not sure what's the best way.

**Comment by TinfoilSubmarine** [comment]
> Still no new builds. Is there no one here who can trigger the 19.1 builds?
> 
> I'm building it myself right now. I hope it works installing it on top without data loss. Furthermore, I'm also thinking about switching to upstream Lineage and install microG via Magisk or NanoDroid, but I'm not sure what's the best way.

Hey, just chiming in to say that this is possible (I've done it multiple times), but you'll have to make sure to patch the keys on your live system **before** you flash the ZIP you built. See https://wiki.lineageos.org/signing_builds#using-a-script and https://download.lineage.microg.org/extra/lineageos-for-microg-keys-migration.zip for the lineageos4microg keys.

**Comment by D3SOX** [comment]
@TinfoilSubmarine Thanks for the reply. I've read on the site
> Lineage recovery: Flash the LineageOS for microG ZIP and confirm flash despite signature mismatch.

So my first try (when the repo sync + build is finally done) would be to first [Upgrade the firmware](https://wiki.lineageos.org/devices/kebab/fw_update) and then flash my build in LOS recovery

**Comment by Yannik** [comment]
@bananer looks like the build process crashed again. The last finished build is for x2 (which is a 18.1 build) on the 5th of october. No 19.1 builds were done as far as I can see.

**Comment by mddvul22** [comment]
Yay!  Looks like the 19.1 builds have started.

**Comment by D3SOX** [comment]
Build for `kebab` is now available and works fine! I think this issue can be closed btw

**Comment by ghost573** [comment]
> Build for `kebab` is now available and works fine! I think this issue can be closed btw
Some devices haven't gotten a new build yet but lets close the issue now that your device has gotten its.

**Comment by mddvul22** [comment]
My devices are fajita and flame.  I now have updates for those devices.  Since I opened this ticket, I will now close it.  Thanks!
