### ISSUE TITLE
[FP3] Target for 19.1 not update since 23 of August

### ISSUE THREAD

**Issue by remi-dupre** [lineageos4microg/docker-lineage-cicd#343]
The builds for Fairphone 3 have not been updated since the 23 of August ([FP3](https://download.lineage.microg.org/FP3/)).

There are several issues that may be related:

 - the builds of LineageOS 19.1 were initially failing for FP3 : https://github.com/lineageos4microg/docker-lineage-cicd/issues/318#issuecomment-1267148373
 - someone reported that Asus Zenfone 8 are also not getting updates since a similar date : https://github.com/lineageos4microg/docker-lineage-cicd/issues/340
 
 Also, is there any way to help as a non-android developer ? I've just started using Lineage+MicroG (coming from /e/OS) and I think it will be my go-to ROM for a while :)

**Comment by D3SOX** [comment]
See https://github.com/lineageos4microg/docker-lineage-cicd/issues/341#issuecomment-1265745068, 19.1 builds will start in a few days

**Comment by remi-dupre** [comment]
Oh OK, thanks for the link, I'll close this in favor of the other issue.
