### ISSUE TITLE
New 19.1 build for polaris please?

### ISSUE THREAD

**Issue by SpaceAgeHero** [lineageos4microg/docker-lineage-cicd#346]
polaris was promoted to LineageOS 19.1.
Can you please trigger an unscheduled build?

**Comment by D3SOX** [comment]
Builds are done alphabetically and are still running. `polaris` has not yet had its turn.
You can check the status here: https://download.lineage.microg.org/?sort=time&order=desc

**Comment by SpaceAgeHero** [comment]
Yes I've looked there and saw that it was built before the major version upgrade.
Was hoping to get a prioritized build.

**Comment by SpaceAgeHero** [comment]
Build is up. Dirty flashed over 18.1 from TWRP. Everything seems to work fine.
