### ISSUE TITLE
I9300 14.1 last built March 02 2019

### ISSUE THREAD

**Issue by tlaurion** [lineageos4microg/docker-lineage-cicd#35]

**Comment by corna** [comment]
14.1 builds have been dropped, see [here](https://github.com/LineageOS/hudson/commit/b8cf20218fd7676d7904152531e0f1cacead740f)

**Comment by tlaurion** [comment]
@corna no transition?!

**Comment by corna** [comment]
LineageOS decided to drop all the 14.1 phones without a 15.1 port, it doesn't depend on us.
