### ISSUE TITLE
Unofficial builds for devices that used to be supported upstream but no longer are is not possible

### ISSUE THREAD

**Issue by wiryfuture** [lineageos4microg/docker-lineage-cicd#352]
I am trying to make a build for chagallwifi, which used to be supported upstream many versions ago but no longer is.
As it is no longer upstream, I want to compile with the same method as [the a6000 example, using my own manifests](https://github.com/lineageos4microg/docker-lineage-cicd#build-for-a6000-not-officially-supported-custom-keys-restricted-signature-spoofing-with-integrated-microg-and-fdroid), but the image finds the old lineage repo, which has the cm12-14 branches, and tries to find an upstream branch for the newer version I want to try build that don't exist, rather than using my manifests

the log:
```
01:20:52 Build sandboxing disabled due to nsjail error.
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
[1mbuild/make/target/product/product_launched_with_k.mk:2: [31merror: [0m[1m_nic.PRODUCTS.[[device/samsung/chagallwifi/lineage_chagallwifi.mk]]: "device/samsung/universal5420-common/device-common.mk" does not exist.[0m
01:20:52 dumpvars failed with: exit status 1
Device chagallwifi not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_samsung_chagallwifi
Default revision: lineage-19.1
Checking branch info
Default revision lineage-19.1 not found in android_device_samsung_chagallwifi. Bailing.
Branches found:
cm-12.1
cm-13.0
cm-14.1
Use the ROOMSERVICE_BRANCHES environment variable to specify a list of fallback branches.
01:20:53 Build sandboxing disabled due to nsjail error.
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
[1mbuild/make/target/product/product_launched_with_k.mk:2: [31merror: [0m[1m_nic.PRODUCTS.[[device/samsung/chagallwifi/lineage_chagallwifi.mk]]: "device/samsung/universal5420-common/device-common.mk" does not exist.[0m
01:20:53 dumpvars failed with: exit status 1
01:20:54 Build sandboxing disabled due to nsjail error.
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
[1mbuild/make/target/product/product_launched_with_k.mk:2: [31merror: [0m[1m_nic.PRODUCTS.[[device/samsung/chagallwifi/lineage_chagallwifi.mk]]: "device/samsung/universal5420-common/device-common.mk" does not exist.[0m
01:20:54 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_chagallwifi'
** Do you have the right repo manifest?

>> [Tue Oct 25 01:20:54 UTC 2022] breakfast failed for chagallwifi, lineage-19.1 branch
```
My envfile
```
BRANCH_NAME=lineage-19.1
DEVICE_LIST=chagallwifi
SIGN_BUILDS=true
SIGNATURE_SPOOFING=yes
WITH_GMS=true
INCLUDE_PROPRIETARY=false
RELEASE_TYPE=UNOFFICIAL
ZIP_SUBDIR=true
```

**Comment by wiryfuture** [comment]
This is the device manifest ive made right how, probably not gonna compile properly but i gotta start with something
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project path="device/samsung/chagallwifi" remote="github" name="exynos5420/android_device_samsung_chagallwifi" revision="lineage-17.1" />
  <!-- firmware exynos; appears to have some additional camera patches? -->
    <project path="device/samsung/exynos5420-common" remote="github" name="exynos5420/android_device_samsung_exynos5420-common" revision="lineage-16.0" />
  <project path="hardware/samsung" remote="github" name="LineageOS/android_hardware_samsung" revision="lineage-19.1" />
  <project path="device/samsung/chagall-common" remote="github" name="exynos5420/android_device_samsung_chagall-common" revision="lineage-17.1" />
  <project path="device/samsung_slsi/sepolicy" remote="github" name="LineageOS/android_device_samsung_slsi_sepolicy" revision="lineage-19.1" />
  <project path="hardware/samsung_slsi/exynos5" remote="github" name="LineageOS/android_hardware_samsung_slsi_exynos5" revision="lineage-19.1" />
  <project path="hardware/samsung_slsi/exynos5420" remote="github" name="exynos5420/android_hardware_samsung_slsi_exynos5420" revision="lineage-17.1" />
  <!-- firmware universal ? Idk what difference there is meant to be between these two -->
  <!-- <project path="device/samsung/universal5420-common" remote="github" name="exynos5420/android_device_samsung_universal5420-common" revision="lineage-17.1" /> -->
  <project path="hardware/samsung_slsi-cm/exynos5" remote="github" name="LineageOS/android_hardware_samsung_slsi-cm_exynos5" revision="lineage-16.0" />
  <project path="hardware/samsung_slsi-cm/exynos5420" remote="github" name="LineageOS/android_hardware_samsung_slsi-cm_exynos5420" revision="lineage-16.0" />
  <project path="hardware/samsung_slsi-cm/openmax" remote="github" name="LineageOS/android_hardware_samsung_slsi-cm_openmax" revision="lineage-16.0" />
  <project path="kernel/samsung/exynos5420" remote="github" name="exynos5420/android_kernel_samsung_exynos5420" revision="lineage-17.1" />
  <project path="external/stlport" remote="github" name="LineageOS/android_external_stlport" revision="lineage-15.1" />
  <project path="vendor/samsung" remote="github" name="TheMuppets/proprietary_vendor_samsung" revision="lineage-19.1" />
  <project path="hardware/samsung_slsi/exynos" remote="github" name="LineageOS/android_hardware_samsung_slsi_exynos" revision="lineage-19.1" />
  <project path="hardware/samsung_slsi/openmax" remote="github" name="LineageOS/android_hardware_samsung_slsi_openmax" revision="lineage-19.1" />
</manifest>
```
Also I have a separate manifest for the gms microg stuff i havent forgotten that.

**Comment by petefoth** [comment]
The key error in that build log is
```
Default revision lineage-19.1 not found in android_device_samsung_chagallwifi. Bailing.
```
You are trying to build **`lineage-19.1`**, so the build tool / image will search all the repos it knows about to find a branch that corresponds to that Android version.

Your manifest is pointing to the **`lineage-17.1`** branch of the `exynos5420/android_device_samsung_chagallwifi` github repo, which is the latest (and the default) branch in that repo, so there is no suitable branch there. 
```
Device chagallwifi not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).`
```
The image then searches the remaining repos in its manifest, including the official LineageOS repos. It finds the [LineageOS/android_device_samsung_chagallwifi](https://github.com/LineageOS/android_device_samsung_chagallwifi) repo, but there is no `lineage-19.1` branch there either, so it fails to find a branch it can use to build.
```
Found repository: android_device_samsung_chagallwifi
Default revision: lineage-19.1
Checking branch info
Default revision lineage-19.1 not found in android_device_samsung_chagallwifi. Bailing.
Branches found:
cm-12.1
cm-13.0
cm-14.1
Use the ROOMSERVICE_BRANCHES environment variable to specify a list of fallback branches.
```
So, there is no suitable version of the file `lineage_chagallwifi.mk` to be found, and the image gives up.
```
** Don't have a product spec for: 'lineage_chagallwifi'
```

For the build to succeed, you need to provide a suitable branch (i.e. `lineage-19.1`) for all of the component parts of the build. The earlier revisions (`15.1`, `16.0`, `17.1`) listed in your manifest won't do. You would therefore need to fork those repos, and create a `lineage-19.1` branch in each of them, and point to that branch in your manifest (or don't specify the `revision` field - the tool will use the `lineage-19.1` branch  by default).

Or you could do as suggested by the build log
```
Use the ROOMSERVICE_BRANCHES environment variable to specify a list of fallback branches.
```
But that probably won't work, because you are probably going to need to make changes to the components in these repos (to get your build to succeed, and the code to work properly) and you won't have write access to those repos. 

When you've made a suitable branch, and changed your manifest so the image can find it, the build should start, and you can make progress by fixing any further build errors that occur when the image tries to build these components. Good luck.

**Comment by wiryfuture** [comment]
> The key error in that build log is
> 
> ```
> Default revision lineage-19.1 not found in android_device_samsung_chagallwifi. Bailing.
> ```
> 
> You are trying to build **`lineage-19.1`**, so the build tool / image will search all the repos it knows about to find a branch that corresponds to that Android version.
> 
> Your manifest is pointing to the **`lineage-17.1`** branch of the `exynos5420/android_device_samsung_chagallwifi` github repo, which is the latest (and the default) branch in that repo, so there is no suitable branch there.
> 
> ```
> Device chagallwifi not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).`
> ```
> 
> The image then searches the remaining repos in its manifest, including the official LineageOS repos. It finds the [LineageOS/android_device_samsung_chagallwifi](https://github.com/LineageOS/android_device_samsung_chagallwifi) repo, but there is no `lineage-19.1` branch there either, so it fails to find a branch it can use to build.
> 
> ```
> Found repository: android_device_samsung_chagallwifi
> Default revision: lineage-19.1
> Checking branch info
> Default revision lineage-19.1 not found in android_device_samsung_chagallwifi. Bailing.
> Branches found:
> cm-12.1
> cm-13.0
> cm-14.1
> Use the ROOMSERVICE_BRANCHES environment variable to specify a list of fallback branches.
> ```
> 
> So, there is no suitable version of the file `lineage_chagallwifi.mk` to be found, and the image gives up.
> 
> ```
> ** Don't have a product spec for: 'lineage_chagallwifi'
> ```
> 
> For the build to succeed, you need to provide a suitable branch (i.e. `lineage-19.1`) for all of the component parts of the build. The earlier revisions (`15.1`, `16.0`, `17.1`) listed in your manifest won't do. You would therefore need to fork those repos, and create a `lineage-19.1` branch in each of them, and point to that branch in your manifest (or don't specify the `revision` field - the tool will use the `lineage-19.1` branch by default).
> 
> Or you could do as suggested by the build log
> 
> ```
> Use the ROOMSERVICE_BRANCHES environment variable to specify a list of fallback branches.
> ```
> 
> But that probably won't work, because you are probably going to need to make changes to the components in these repos (to get your build to succeed, and the code to work properly) and you won't have write access to those repos.
> 
> When you've made a suitable branch, and changed your manifest so the image can find it, the build should start, and you can make progress by fixing any further build errors that occur when the image tries to build these components. Good luck.

Ah, not sure what the revision tag is meant to be used for now, but I see what you mean.
