### ISSUE TITLE
Lineage 19.1 Guacamole has been failing

### ISSUE THREAD

**Issue by rei-zero246** [lineageos4microg/docker-lineage-cicd#356]
Since my last build of lineage-19.1-20221016-UNOFFICIAL-guacamole, building the OS has been failing.

[ 65% 90294/138434] Verifying uses-libraries: vendor/partner_gms/GmsCore/GmsCore.apk
FAILED: out/target/common/obj/APPS/GmsCore_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/APPS/GmsCore_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enforce-uses-libraries 	  --enforce-uses-libraries-status out/target/common/obj/APPS/GmsCore_intermediates/enforce_uses_libraries.status 	  --aapt out/host/linux-x86/bin/aapt 	  --uses-library com.android.location.provider 	   	  --dexpreopt-config out/target/product/guacamole/obj/JAVA_LIBRARIES/com.android.location.provider_intermediates/dexpreopt.config 	   	  vendor/partner_gms/GmsCore/GmsCore.apk )"
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: [com.android.location.provider]
	                 vs. in the manifest: [com.android.location.provider]
	- optional libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- tags in the manifest (vendor/partner_gms/GmsCore/GmsCore.apk):
		uses-library:'com.android.location.provider'		uses-library-not-required:'androidx.window.extensions'		uses-library-not-required:'androidx.window.sidecar'
note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- see build/make/Changes.md for details

[ 65% 90295/138434] Verifying uses-libraries: out/target/common/obj/APPS/TrebuchetQuickStep_intermediates/manifest/AndroidManifest.xml
[ 65% 90296/138434] //vendor/qcom/opensource/commonsys/packages/apps/Bluetooth:Bluetooth verify <uses-library> [common]
[ 65% 90297/138434] //packages/apps/AudioFX:AudioFX verify <uses-library> [common]
[ 65% 90298/138434] //external/ant-wireless/ant_client:AntHalService-Soong verify <uses-library> [common]
[ 65% 90299/138434] //frameworks/base/packages/BackupRestoreConfirmation:BackupRestoreConfirmation verify <uses-library> [common]
[ 65% 90300/138434] //packages/modules/DnsResolver:libnetd_resolv clang-tidy ResolverEventReporter.cpp [com.android.resolv]
[ 65% 90301/138434] //packages/modules/DnsResolver:libnetd_resolv clang-tidy DnsTlsTransport.cpp [com.android.resolv]
[ 65% 90302/138434] //packages/modules/DnsResolver:libnetd_resolv clang-tidy res_cache.cpp [com.android.resolv]
[ 65% 90303/138434] //packages/modules/DnsResolver:libnetd_resolv clang-tidy ResolverController.cpp [com.android.resolv]
[ 65% 90304/138434] //packages/modules/DnsResolver:libnetd_resolv clang-tidy DnsProxyListener.cpp [com.android.resolv]
[ 65% 90305/138434] //packages/modules/DnsResolver:libnetd_resolv clang-tidy PrivateDnsConfiguration.cpp [com.android.resolv]
[ 65% 90306/138434] //packages/modules/DnsResolver:libnetd_resolv clang-tidy DnsTlsSocket.cpp [com.android.resolv]
[ 65% 90307/138434] //frameworks/av/services/mediametrics:libmediametricsservice clang-tidy AudioAnalytics.cpp
[ 65% 90308/138434] Building bootanimation.zip
[ 65% 90309/138434] //system/bt/gd:libbt_packets rustc rust/packets/lib.rs [arm]
[ 65% 90310/138434] //system/bt/gd:libbt_packets rustc rust/packets/lib.rs
[ 65% 90311/138434] //external/rust/crates/libsqlite3-sys/android:sqlite3_bindgen_build rustc build.rs [linux_glibc]
ninja: build stopped: subcommand failed.
13:24:11 ninja failed with: exit status 1

#### failed to build some targets (27:56 (mm:ss)) ####

>> [Sun Nov 13 13:24:11 UTC 2022] Failed build for guacamole
>> [Sun Nov 13 13:24:11 UTC 2022] Finishing build for guacamole
>> [Sun Nov 13 13:24:11 UTC 2022] Cleaning source dir for device guacamole
13:24:20 Entire build directory removed.

Windows 11
Docker 4.13.1
Ubuntu 22.04.1 LTS WSL

**Comment by petefoth** [comment]
When I bumped into this problem, I worked round it be setting `RELAX_USES_LIBRARY_CHECK=true` in my Docker build command (or just EXPORTING it in my environment when building from the command line with `lunch`, `mka`

A proper fix needs to be made (either in the Docker file or the `Android.mk` files in the `partner_gms` repo, but this workaround should help until that is done

**Comment by fwg-cag** [comment]
I bumped into the same problem and submitted [https://github.com/lineageos4microg/android_vendor_partner_gms/pull/15](url). Fixing the build process wasn't enough for me since the device wouldn't come up with the new image without the additional "android.permission.MANAGE_USB" ...

**Comment by petefoth** [comment]
Is this still a problem for you with recent builds? If not, I will close the issue (or you can do it yourself)

**Comment by rei-zero246** [comment]
No, I do not have any issues. I have moved to building lineage20.0 since.
