### ISSUE TITLE
wishlist: build ResurrectionRemix with MicroG

### ISSUE THREAD

**Issue by TjrGithub** [lineageos4microg/docker-lineage-cicd#36]
Hi, would it be possible to provide builds of ResurrectionRemix, the same way you do of Lineage? They still support some devices (whyred) that LineageOS dropped.

Edit: ResurrectionRemix devices without Lineage support: 

beckham
deb
enchilada
evert
g3ds
garlic
gsi
helium
hltechn
hltekor
hydrogen
jasmine_sprout
jflte
kenzo
on7xelte
onyx
platina
pme
potter
quark
riva
rolex
rosy
sakura
trlte
tulip
vince
wayne
whyred
Z00L
Z00T
z2_plus
zenfone3
zerofltecan
zerofltexx
zeroltecan

**Comment by corna** [comment]
That is an interesting task, however we are currently "short-staffed". My top priority whish is to offer a set of "unofficial builds", which should cover the devices recently dropped by LineageOS or maintained unofficially. Unfortunately it will take a lot, given my current lack of spare time, I'll keep you updated.

**Comment by spolack** [comment]
> That is an interesting task, however we are currently "short-staffed". My top priority whish is to offer a set of "unofficial builds", which should cover the devices recently dropped by LineageOS or maintained unofficially. Unfortunately it will take a lot, given my current lack of spare time, I'll keep you updated.

That will be covered by #90


Building other Roms than LineageOS wont happen.
