### ISSUE TITLE
Bootloop after updating LineageOS+microG to 20221118 or later

### ISSUE THREAD

**Issue by p2wei** [lineageos4microg/docker-lineage-cicd#360]
As reported in the XDA developers forum (https://forum.xda-developers.com/t/lineageos-for-microg.3700997/post-87754221) and in the Gmscore Issues (microg/GmsCore#1831) updating LineageOS with included microG to a version 20221118 or later (e.g. lineage-19.1-20221118-microG-kirin.zip) causes a boot loop.

This appears to be fixed by lineageos4microg/android_vendor_partner_gms#15

**Comment by eternal-sorrow** [comment]
at least remove the broken updates from the server so that it doesn't affect more people. this won't save my data unfortunately but maybe will help others.

**Comment by ale5000-git** [comment]
They have merged this: https://github.com/lineageos4microg/android_vendor_partner_gms/pull/12
that has the same fix.

**Comment by herrdeh** [comment]
With lineage-18.1-20230102-microG-klte.zip, the device will boot and show the boot animation für several minutes and then reboot to recovery. This does not happen with lineage-18.1-20230227-nightly-klte-signed.zip .

Thank you for you awesome work anyway - shit happens... (-;

**Comment by petefoth** [comment]
When that happens to me on other devices, it can usually be fixed by formatting data partition and reflashing

**Comment by herrdeh** [comment]
@petefoth 
I tried that several times with two microg.lineage-versions, but that did not help.

The change to standard lineageOS did.

**Comment by herrdeh** [comment]
Thank you for this hint. But strange: Why should generic lineageOS do better handling with a possibly corrupt file system on data partition than microg.lineageOS ?

**Comment by vanMacG** [comment]
@herrdeh Have you tried [lineage-18.1-20230221-microG-klte.zip](https://download.lineage.microg.org/klte/lineage-18.1-20230221-microG-klte.zip)? I flashed it sucessfully via updater some days ago on two devices.

**Comment by herrdeh** [comment]
Ah, thank you!

Yes, I tried that one first, and it led to these problems described. But good to know that problems seem not to derive from the update.

Strange. Unusual things are happening with my phone. I'll wait for some daring moment to retry the recent microG version. (-;

**Comment by petefoth** [comment]
Is this still a problem for you with recent builds? If not, I will close the issue (or you can do it yourself)

**Comment by herrdeh** [comment]
Works for me now.

**Comment by petefoth** [comment]
> But seems I cannot close.

OK - I will do it
