### ISSUE TITLE
No updates for many devices on download.lineage.microg.org

### ISSUE THREAD

**Issue by jomo** [lineageos4microg/docker-lineage-cicd#361]
Taking a look at https://download.lineage.microg.org/?sort=time&order=desc, there have been recent builds for devices from a (`akari`) to z (`zippo`). They started appearing between November 16 and November 20, but have since stopped. Many devices are not updated, for example `river`, which has had several lineageos releases since the last lineageos4microg build.

Given the recently discovered lockscreen bypass vulnerability that has been patched in the November 5 security update, it would be great to be able to update these devices.

Were they excluded from the builds on purpose, by accident, or did the builds just fail? Is there any way to help out?

**Comment by daniellandau** [comment]
A reference for "recently discovered lockscreen bypass": https://bugs.xdavidhu.me/google/2022/11/10/accidental-70k-google-pixel-lock-screen-bypass/

I guess the reason for no updates in the past few days is that there's an issue with bootloops on some devices: https://github.com/microg/GmsCore/issues/1831

Anxiously awaiting for an update for my device, but it'll come when it comes.

**Comment by daniellandau** [comment]
Oh and indeed I did test that the lockscreen bypass does work on my up-to-date lineage for microg.

**Comment by jomo** [comment]
Meanwhile, some updates have started appearing from 2022-12-01 to 2022-12-08 (with about one build appearing every two hours: https://download.lineage.microg.org/?sort=time&order=desc)

The last build is currently for `racer`, no new builds have appeared in 4 days and many are still missing.

Can we get some info from maintainers about what the issue is?

**Comment by genofire** [comment]
Fairphone3 either, see #387

**Comment by petefoth** [comment]
> However, there's no new updates zip since april for gauguin

For  number of devices, the May and / or June builds succeeded, but the operation to copy the zips to the download server failed. I have now copied the missing files manually from the build server to the download server for the following devices:
debx gauguin griffin h850 h870 h872 h910 h918 h990 ls997 parker rs988 star2lte starlte us996d us996 us997 vs995

If any other devices are missing zips, please let me know. 

I will close this issue now

**Comment by wi24rd** [comment]
@petefoth Please check gauguin [1]. There's not update again. 
[1] https://download.lineage.microg.org/gauguin/

**Comment by petefoth** [comment]
Gauguin is a 19.1 device. The 19.1 builds for September have not yest started as the 20.0 builds are still ongoing.

In August the 19.1 devices got built before the 20.0 devices, but that was a one-off.
