### ISSUE TITLE
Syncing branch repository fails

### ISSUE THREAD

**Issue by michaelschefczyk** [lineageos4microg/docker-lineage-cicd#363]
Building with the docker image - also with the most recent one updated a few days ago, I am unable to complete syncing the branch repository. Errors are always like (example with jfltexx):

.repo/repo: project not found in manifest.
error: kernel/oneplus/msm8996: Cannot remove project: uncommitted changes are present.

error: Your local changes to the following files would be overwritten by checkout:
	webview.apk
Please commit your changes or stash them before you switch branches.
Aborting

external/chromium-webview/prebuilt/arm/: discarding 1 commits
error: external/chromium-webview/prebuilt/arm/: LineageOS/android_external_chromium-webview_prebuilt_arm checkout c14dd13b992bf4251fe6fb4362f6e46c8d64e72c 
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm
error: Your local changes to the following files would be overwritten by checkout:
	webview.apk
Please commit your changes or stash them before you switch branches.
Aborting

external/chromium-webview/prebuilt/arm64/: discarding 1 commits
error: external/chromium-webview/prebuilt/arm64/: LineageOS/android_external_chromium-webview_prebuilt_arm64 checkout ac62795ad529f4b91e67c56cbdb0a1b7a851e778 
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_arm64
error: Your local changes to the following files would be overwritten by checkout:
	webview.apk
Please commit your changes or stash them before you switch branches.
Aborting

external/chromium-webview/prebuilt/x86/: discarding 1 commits
error: external/chromium-webview/prebuilt/x86/: LineageOS/android_external_chromium-webview_prebuilt_x86 checkout b3d865d141541be00288378b73c857b8ef75d25a 
error: Cannot checkout LineageOS/android_external_chromium-webview_prebuilt_x86

error: Unable to fully sync the tree.
error: Updating local project lists failed.
error: Checking out local projects failed.
Failing repos:
external/chromium-webview/prebuilt/arm
external/chromium-webview/prebuilt/arm64
external/chromium-webview/prebuilt/x86
Try re-running with "-j1 --fail-fast" to exit at the first error.

Is this just my lack of talent or is this maybe connected to the background of missing official builds:

https://github.com/lineageos4microg/docker-lineage-cicd/issues/361

**Comment by bananer** [comment]
You have local changes, I don't know where they came from. If you know what you're doing, you could clean them up by running `git checkout` from the directories it complains about. Alternatively, delete your source directory for a fresh start.

**Comment by michaelschefczyk** [comment]
Thank you very much! I did not understand the cause, but cleaning the source folder did solve the issue.

The background is, that I am the android security and privacy manager of our family. For two older devices which will not go beyond LOS 18.1, I am still building myself in order to include the old stock android e-mail app (more privacy than the Gmail app, I suspect - we use an open source variant of activesync for email, contacts and calendar, so our choice of mail apps is limited). For that I am using this manifest:

<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    
    <project path="packages/apps/Email" name="LineageOS/android_packages_apps_Email" revision="lineage-17.1" />
    <project path="packages/apps/Exchange" name="LineageOS/android_packages_apps_Exchange" revision="lineage-17.1" />
    <project path="packages/apps/UnifiedEmail" name="LineageOS/android_packages_apps_UnifiedEmail" revision="lineage-17.1" />
</manifest>

That, however, did not cause the issue. For the more modern phones, I either (a) use the official LOS MicroG build from download.lineage.microg.org and install the Gmail app (until eventually thunderbird android may be available and may include activesync) or (b) use MicroG included in CalyxOS. As it seems that is impossible to include the old but most privacy friendly stock mail app from LOS 17.1 in LOS 19.1, and as a locked bootloader seems good without full disk encryption, I will probably focus on CalysOS for future hardware.
