### ISSUE TITLE
it looks like SYS_ADMIN is not enough for BUILD_OVERLAY

### ISSUE THREAD

**Issue by 532910** [lineageos4microg/docker-lineage-cicd#365]
```
mount: /srv/tmp/merged: cannot mount overlay read-only.
```

with  `--privileged` it works fine

debian sid docker 20.10.21+dfsg1-1

**Comment by 532910** [comment]
Why was I assigned?

**Comment by petefoth** [comment]
Sorry - meant to add this comment:

Is this still a problem for you with recent builds? If not, I will close the issue (or you can do it yourself)

> Why was I assigned?

So you could let me know whether it is still a problem.

**Comment by petefoth** [comment]
No response. Closing
