### ISSUE TITLE
Builds have stopped on December 8th at /racer

### ISSUE THREAD

**Issue by jw243** [lineageos4microg/docker-lineage-cicd#369]
Hi there,

the last round of updated builds have stopped again on December 8th at /racer.

From December 1st to December 8th new builds have appeared every day in alphabetical order, but since December 8th no new builds were uploaded.

I am desperately waiting for the new build for the z3.

Thanks a lot for your effort!

**Comment by petefoth** [comment]
> I am desperately waiting for the new build for the z3.

June build is available at https://download.lineage.microg.org/z3/. The July build will be along when the current build run finishes - tough running a device that comes at the end of the alphabet :)

You can monitor build progress on the dedicated Matrix channel https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net
