### ISSUE TITLE
Clarify status for Android 7/LineageOS 14.1 devices

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/docker-lineage-cicd#37]
As upstream [has decided to top officially supporting LineageOS 14.1 anymore](https://www.lineageos.org/Changelog-22/#goodbye-lineageos-141) I'd ask what is the status here?

Seems you did some more updates (in March, at least), but currently there are no new builds.

Remember they say:
>  The branches will not be locked, so it’ll still be open for contributions such as security patches, as the 13.0 and 11.0 branches that have been getting security patches backported by the community.

So I guess nothing limits you from just continuing building releases… :thinking: 

Also your website may need some updates regarding this thing.

**Comment by spolack** [comment]
Covered by #90
