### ISSUE TITLE
No new builds for z3 for almost three months

### ISSUE THREAD

**Issue by jw243** [lineageos4microg/docker-lineage-cicd#376]
There haven't been any new builds for z3 (Sony Xperia Z3) for almost 3 months. I really wish this could be solved. Thanks.

**Comment by joshuaBS5** [comment]
Hello, also no new builds for a5y17lte (last build from 1. October 2022), jfltexx (03. October 2022) and YTX703L (16. October 2022). All Lineage 18.1
I think it has to do with #361 
Is there anybody how can give a status about the situation? Thank you.
