### ISSUE TITLE
Can i build LOS16 for I9300

### ISSUE THREAD

**Issue by Huskyhunter** [lineageos4microg/docker-lineage-cicd#38]
Hi Everyone,

I found this build while scrolling through reddit. I have tried to build los16 with offical los build but i cant get my device to be added to lunch,brunch nor breakfast command. So i was thinking would it be easier to build using a docker image since the image comes with everything that required ?. I just need to make few changes to my build 1.Disable the proximity sensor 2.Add device reboot and reboot to recovery toggle 3.Remove any unnecessary features.There already an unofficial build i am planning to use that build`s device tree.[Here](https://forum.xda-developers.com/galaxy-s3/development/rom-lineageos-16-0-t3875899)
Ill be using MicroG too.

**Comment by corna** [comment]
Hi,
I'm sorry, what's the question here?
