### ISSUE TITLE
Fairphone 4 builds?

### ISSUE THREAD

**Issue by phs** [lineageos4microg/docker-lineage-cicd#382]
Hello,

[LOS has supported FP4][0] for some time.  Is a microg build possible for this model?

[0]: https://download.lineageos.org/FP4

**Comment by ArchangeGabriel** [comment]
Yes, but the build failed: https://github.com/lineageos4microg/docker-lineage-cicd/issues/335#issuecomment-1387524389

**Comment by Sam13** [comment]
https://download.lineage.microg.org/FP4/

**Comment by Sam13** [comment]
Did anyone try?
Dirty flash over official LOS installation?
