### ISSUE TITLE
Make build status publicly visible

### ISSUE THREAD

**Issue by bananer** [lineageos4microg/docker-lineage-cicd#383]
> Is there any way to obtain an RSS or Atom feed of build successes and failures, as I'd like to add it to the bot that serves microG's Matrix/IRC chatroom (#microG:matrix.org or #microg on Libera)?

_Originally posted by @LuccoJ in https://github.com/lineageos4microg/docker-lineage-cicd/issues/335#issuecomment-1387689544_

**Comment by bananer** [comment]
@LuccoJ I like your idea. There is no RSS feed or anything alike, it's just a cron job triggering the builds right now. We do have the possibility to run commands before and after a build with info on whether it was successful or not. If your bot provides something like a webhook I could call an URL with curl before/after the build.

**Comment by LuccoJ** [comment]
Thanks. My bot can't give you a webhook because my bot's server isn't accessible from the internet (I'm not good enough at security for that!), but if *you* give me a hook... ;-) Actually, I don't need a hook, if you could just make a plaintext page, with CSV content or really anything that I can parse easily enough, containing a list of builds that succeeded or failed... the bot could use that, I'm sure. Depends on how your web server is set up whether that's easy for you to do, I guess. Could be as simple as a "echo >/var/www/blah.txt kebab failed", probably, and I would just periodically poll for changes.

**Comment by bananer** [comment]
Same problem the other way around - build server is not accessible from the internet. There is a separate web server where the built files are copied to. So slightly more complex to set this up. Has been on my list of things to do for a while...

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Why not have the server post directly to a Matrix chatroom?

`curl 'https://SERVER/_matrix/client/v3/rooms/{roomId}/send/{eventType}/{txnId} -X PUT --data '{"msgtype":"m.text","body":"hello world"}'`

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
See [here](https://matrix.org/docs/api/#put-/_matrix/client/v3/rooms/-roomId-/send/-eventType-/-txnId-)

**Comment by bananer** [comment]
I have no experience with Matrix. Could someone set this up, test it and send the command to me (email in profile)?

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
I sent you a command to your email :)

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Were you able to try it out @bananer ?

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
@LuccoJ the setup is now working, you can now go to `#microg-lineage-os-builds:matrix.domainepublic.net`

So I think this issue can be closed if you document this somewhere @bananer  :)

**Comment by D3SOX** [comment]
Thanks for your efforts. Now I need something that only notifies me when it's about one of my devices and I would prefer if that works via RSS because I don't receive notifications from Element.

**Comment by petefoth** [comment]
> So I think this issue can be closed if you document this somewhere

Documentation will be handled in #454 

> Thanks for your efforts. Now I need something that only notifies me when it's about one of my devices and I would prefer if that works via RSS because I don't receive notifications from Element.

I can see that this would be useful for people who don't have access to Element, but we don't currently have the time or expertise do do anything about it. I've opened new issue #445, in case anyone is able to offer a solution

Closing this issue now
