### ISSUE TITLE
build request for enchilada

### ISSUE THREAD

**Issue by modules** [lineageos4microg/docker-lineage-cicd#384]
The last build for enchilada is from 18.12.2022, is there any chance to get a fresh build?

**Comment by bstnbuck** [comment]
Same for `gauguin`, also last build is from 18.12.2022. Thanks!

**Comment by D3SOX** [comment]
I also want a new build for `kebab` but it seems like noted in https://github.com/lineageos4microg/docker-lineage-cicd/issues/335#issuecomment-1399576758 and as seen on the website
![image](https://user-images.githubusercontent.com/24937357/214051144-f0464661-d978-48ba-a136-c47f81ced2cc.png)
another build round is current running.
So wait and see if it succeeds for your device.

**Comment by bananer** [comment]
`enchilada` and `kebab` should get the first 20.0 build in the next days. Builds for `gaugin` (19.1) were failing, should be fixed by https://github.com/lineageos4microg/android_vendor_partner_gms/pull/19 with the next builds scheduled in the first half of February.

**Comment by modules** [comment]
Just flashed it. Works like charm👍. Thanks a lot.

**Comment by D3SOX** [comment]
Everything looks good on kebab too. Thanks to everybody who was involved in this release :tada:

![Screenshot_20230126-114752_Settings.png](https://user-images.githubusercontent.com/24937357/214821805-9553d6f2-0177-4784-b88c-9c26301604ce.png)

**Comment by bstnbuck** [comment]
@bananer any news for `gauguin`? It seems that the 19.1 cron did not finish and stopped at `d1`.

**Comment by bstnbuck** [comment]
New update is available. Looks good so far.
