### ISSUE TITLE
`lisa` missing

### ISSUE THREAD

**Issue by Iey4iej3** [lineageos4microg/docker-lineage-cicd#385]
`lisa` is officially [supported](https://wiki.lineageos.org/devices/lisa/) by LOS, but missing from LOS4MicroG.

**Comment by Iey4iej3** [comment]
Can I run a local build via docker to test?

**Comment by lp55** [comment]
Any updates on this? The LibreMobileOS ROM (another LineageOS based ROM) already has builds for it. But I would prefer LOS4Microg as I've used it longer and have greater trust in it.

**Comment by FintasticMan** [comment]
It's currently built `d1`, so there are 12 devices to be built before it gets to `lisa`.

**Comment by lp55** [comment]
Thanks for the reply. By the way, is there any public website to follow the build process?

**Comment by FintasticMan** [comment]
If you go to the download page, you can sort by most recently updated, so you can see the devices that were most recently built.

**Comment by bananer** [comment]
Regarding the build status report: https://github.com/lineageos4microg/docker-lineage-cicd/issues/383

**Comment by Iey4iej3** [comment]
> It's currently built `d1`, so there are 12 devices to be built before it gets to `lisa`.

It seems that a new round is triggered, and devices are compiled from zero again.
