### ISSUE TITLE
sha256 for recovery

### ISSUE THREAD

**Issue by Iey4iej3** [lineageos4microg/docker-lineage-cicd#386]
The sha256sum for recovery images is not provided. I hope that this is provided, as for ROM zips.

**Comment by bananer** [comment]
We're not yet generating checksums for the boot/recovery images. Would be a good contribution, if somebody wants to pick it up. See https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L352

**Comment by Iey4iej3** [comment]
Would it work simply by modifying the line https://github.com/lineageos4microg/docker-lineage-cicd/blob/00bf5a0a002ef96a4a120140b727afe5a66563f2/src/build.sh#L360

into

``` bash
cp "$image.img" "$recovery_name" &>> "$DEBUG_LOG"
sha256sum "$recovery_name" > "$ZIP_DIR/$zipsubdir/$recovery_name.sha256sum"
md5sum "$recovery_name" > "$ZIP_DIR/$zipsubdir/$recovery_name.md5sum"
mv "$recovery_name" "$ZIP_DIR/$zipsubdir/$recovery_name" &>> "$DEBUG_LOG"
```

Furthermore, I don't understand why https://github.com/lineageos4microg/docker-lineage-cicd/blob/00bf5a0a002ef96a4a120140b727afe5a66563f2/src/build.sh#L355 is `mv` (with log), while https://github.com/lineageos4microg/docker-lineage-cicd/blob/00bf5a0a002ef96a4a120140b727afe5a66563f2/src/build.sh#L360 is `cp` (**without** log)?

**Comment by bananer** [comment]
I would avoid copying and then moving the file, because `$ZIP_DIR` might be on a different filesystem. Just adding

   sha256sum "$ZIP_DIR/$zipsubdir/$recovery_name" > "$ZIP_DIR/$zipsubdir/$recovery_name.sha256sum"

after the `cp` should be enough already.

The missing log pipe seems like an oversight, feel free to fix that as well!

**Comment by Iey4iej3** [comment]
> sha256sum "$ZIP_DIR/$zipsubdir/$recovery_name" > "$ZIP_DIR/$zipsubdir/$recovery_name.sha256sum"

This will introduce the absolute path in the `.sha256sum` file. I will try to use the last command of [this answer](https://stackoverflow.com/a/786419).

**Comment by bananer** [comment]
I'm trying to avoid subshells, they mess up the error handling. You could just use the original file's path instead: 

    sha256sum "$image.img" > "$ZIP_DIR/$zipsubdir/$recovery_name.sha256sum"

**Comment by Iey4iej3** [comment]
> sha256sum "$image.img" > "$ZIP_DIR/$zipsubdir/$recovery_name.sha256sum"

What we need is the `sha256sum` with path being `$recovery_name`, not `$image.img`. Anyway, I created a pull request https://github.com/lineageos4microg/docker-lineage-cicd/pull/388
