### ISSUE TITLE
microG + CUSTOM_PACKAGES missing after successful build

### ISSUE THREAD

**Issue by fstappert** [lineageos4microg/docker-lineage-cicd#39]
I'm building cm-14.1 for n2awifi and a517lte using the docker command:

```
docker run \
    -e "BRANCH_NAME=cm-14.1" \
    -e "DEVICE_LIST_CM_14_1=n2awifi,a5y17lte" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension" \
    -v "/home/linos/lineage:/srv/src" \
    -v "/home/linos/zips:/srv/zips" \
    -v "/home/linos/logs:/srv/logs" \
    -v "/home/linos/cache:/srv/ccache" \
    -v "/home/linos/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
```

The build completes fine without errors, but the  zip files do not include the CUSTOM_PACKAGES.
I can't see anything suspicious in the logs, see below the one for n2awifi e. g.. (Actually, I don't really know what to look for ;-).)

[lineage-14.1-20190528-UNOFFICIAL-n2awifi.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/3228799/lineage-14.1-20190528-UNOFFICIAL-n2awifi.log)

According to the log file in issue #17, the CUSTOM_PACKAGES should appear somewhere, e. g.

```
[ 42% 21288/49703] target Prebuilt: GsfProxy (/srv/src/CM_14_1/out/target/product/sumire/obj/APPS/GsfProxy_intermediates/package.apk)
[ 42% 21289/49703] Install: /srv/src/CM_14_1/out/target/product/sumire/system/app/GsfProxy/GsfProxy.apk
```
But they're not in my logs.

Furthermore, I have an older, working zip installed on my n2awifi (lineage-14.1-20190414-UNOFFICIAL-n2awifi.zip) which is about 7 MiB bigger than the one built now. Therefore, something's missing definitely.

**Comment by Wieke** [comment]
I was having the same issue when compiling for `gohan`. Turns out I had forgotten to add `custom_packages.xml` to the manifest folder with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="lineageos4microg/android_prebuilts_prebuiltapks" path="prebuilts/prebuiltapks" remote="github" revision="master" />
</manifest>
```

I had missed the instructions to do so when reading the readme. Maybe you did so as well?

**Comment by fstappert** [comment]
Arrgh... Missed that one, too.
Now it works perfectly.
Thanks for the hint!
