### ISSUE TITLE
No builds for vayu (Poco X3 Pro) since december

### ISSUE THREAD

**Issue by danielintempesta** [lineageos4microg/docker-lineage-cicd#393]
Hi. First of all, thank you for your work and effort.

There has been no new builds for Vayu (Poco X3 Pro) since 12/23/2022 (LineageOS 19.1) but it's a supported device: https://github.com/LineageOS/hudson/blob/master/lineage-build-targets

Missed builds: 
lineage-19.1-**20230203**-nightly-vayu-signed.zip
lineage-19.1-**20230127**-nightly-vayu-signed.zip
lineage-19.1-**20230120**-nightly-vayu-signed.zip
lineage-19.1-**20230113**-nightly-vayu-signed.zip

Thanks

**Comment by kstorbakken** [comment]
+1, this is effecting me as well. If I wanted to know what's causing the failures, would the best way to find out be to just trying building the release myself? I tried finding somewhere to check current build status's, but I don't see anything.

**Comment by bstnbuck** [comment]
+1 https://github.com/lineageos4microg/docker-lineage-cicd/issues/384#issuecomment-1418948219
So far there is no build status (afaik). It seems that the 19.1 cron was interrupted and the 20 was started.

**Comment by bstnbuck** [comment]
A new cron for 19.1 has become active a few days ago. `gauguin` has now received an update (installed without problems). This should continue alphabetically.

**Comment by danielintempesta** [comment]
[lineage-19.1-20230213-microG-vayu.zip](https://download.lineage.microg.org/vayu/lineage-19.1-20230213-microG-vayu.zip)

Just flashed it. Thanks!
