### ISSUE TITLE
Recommended way of overriding a part of manifest.xml?

### ISSUE THREAD

**Issue by shaunmulligan** [lineageos4microg/docker-lineage-cicd#394]
I have a fork of https://github.com/LineageOS/android_kernel_google_msm-4.14 which provides additional kernel modules that I need and I was wondering what is the preferred way to override this repo source and point it to my fork when using `docker-lineage-cicd` 

Thanks for the amazing project!

**Comment by shaunmulligan** [comment]
Just to update here. I found that I can add overriding manifests in a folder and mount then to `/srv/local_manifests` using something like `-v "/home/user/manifests:/srv/local_manifests"`. They then appear to be built :D

**Comment by petefoth** [comment]
I'm going to close this issue, as you seem to have solved it yourself :)
