### ISSUE TITLE
Is there a way to just build the kernel or boot.img?

### ISSUE THREAD

**Issue by shaunmulligan** [lineageos4microg/docker-lineage-cicd#395]
What is the recommended way to just build the kernel or boot.img? 

Can I just exec into the container and then `breakfast` for my device within the kernel repo and `make bootimage` or `mka kernel`?

**Comment by shaunmulligan** [comment]
for anyone looking to do this you just need to:
docker exec into the cicd container and run:
```
source build/envsetup.sh
cd /kernel/<path to your kernel>
mka
```

**Comment by bananer** [comment]
Thanks for posting the answer to your question. Maybe someone finds this useful in the future.
