### ISSUE TITLE
Missing latest builds for a5y17lte

### ISSUE THREAD

**Issue by marek22k** [lineageos4microg/docker-lineage-cicd#397]
LineageOS (https://download.lineageos.org/a5y17lte) provides builds from 2023-01-14 and from 2023-02-14, but MicroGs newest version is from 01/01/2023.

**Comment by st3rox** [comment]
Looks like a5y17lte is still on 18.1
18.1 builds have stopped now that 20 builds have started
See https://github.com/lineageos4microg/docker-lineage-cicd/issues/335#issuecomment-1380821815
