### ISSUE TITLE
Add bluejay to build-roster

### ISSUE THREAD

**Issue by Yannik** [lineageos4microg/docker-lineage-cicd#398]
It would be great if bluejay (https://download.lineageos.org/bluejay) could be added to the build-roster. :)

**Comment by DieuDeGlace** [comment]
same with raven and oriole. Not seeing them currently and trying to build lineageos for microg for raven is resulting in EXITED (1)

**Comment by mjenny** [comment]
The issue with raven is that the "TheMuppets" repo doesn't contain the proprietary blobs.

**Comment by DieuDeGlace** [comment]
Truly unfortunate. Been wanting to run with lineageos for microg on my pixel 6 pro

**Comment by DieuDeGlace** [comment]
I wonder if it's relatively easy to add to the muppets repo? Considering it would follow a similar scheme to bramble and others

**Comment by Yannik** [comment]
@bananer I had a look the TheMuppets repo to see if there is a README which explains how to add a new device, but unfortunately, there is none. Could you share what the usual process is for getting a new device added to the microg lineageos builds? Is TheMuppets strictly required?

How comes that lineageos can be built for the aforementioned devices without a corresponding TheMuppets repo? (And why can't microg lineageos use the same method?)

**Comment by endim8** [comment]
+1 for Raven

**Comment by FintasticMan** [comment]
The build roster is just parsed from the LineageOS hudson build-targets whenever a new build round is started. If a device was only recently added, it might take over a month to actually be built, and if the build fails it could take longer.

**Comment by Yannik** [comment]
@FintasticMan 
That makes sense. ([Link for anyone interested](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets))

However, how will this work without a corresponding TheMuppets repo with the required blobs?  
How does lineageos itself do it? Do they have a non-public store of blobs?

**Comment by FintasticMan** [comment]
Officially, they pull it out of the stock firmware every time. But between you and me, they are the ones who maintain TheMuppets' repo, and I don't know why some devices' blobs aren't on there.

**Comment by endim8** [comment]
according to Kermit, some devices aren't on the github because github has a size limit, however GitLab doesnt!:

**Comment by endim8** [comment]
additional devices in the gitlab manifest:
```

  <project name="The-Muppets/proprietary_vendor_firmware" />
  <project name="The-Muppets/proprietary_vendor_google_bluejay" />
  <project name="The-Muppets/proprietary_vendor_google_cheetah" />
  <project name="The-Muppets/proprietary_vendor_google_oriole" />
  <project name="The-Muppets/proprietary_vendor_google_panther" />
  <project name="The-Muppets/proprietary_vendor_google_raven" />
  <project name="The-Muppets/proprietary_vendor_motorola_beckham" />
  <project name="The-Muppets/proprietary_vendor_motorola_berlin" />
  <project name="The-Muppets/proprietary_vendor_motorola_berlna" />
  <project name="The-Muppets/proprietary_vendor_motorola_channel" />
  <project name="The-Muppets/proprietary_vendor_motorola_chef" />
  <project name="The-Muppets/proprietary_vendor_motorola_dubai" />
  <project name="The-Muppets/proprietary_vendor_motorola_evert" />
  <project name="The-Muppets/proprietary_vendor_motorola_exynos9610-common" />
  <project name="The-Muppets/proprietary_vendor_motorola_kane" />
  <project name="The-Muppets/proprietary_vendor_motorola_kiev" />
  <project name="The-Muppets/proprietary_vendor_motorola_lake" />
  <project name="The-Muppets/proprietary_vendor_motorola_nairo" />
  <project name="The-Muppets/proprietary_vendor_motorola_nash" />
  <project name="The-Muppets/proprietary_vendor_motorola_ocean" />
  <project name="The-Muppets/proprietary_vendor_motorola_payton" />
  <project name="The-Muppets/proprietary_vendor_motorola_racer" />
  <project name="The-Muppets/proprietary_vendor_motorola_river" />
  <project name="The-Muppets/proprietary_vendor_motorola_sdm632-common" />
  <project name="The-Muppets/proprietary_vendor_motorola_sdm660-common" />
  <project name="The-Muppets/proprietary_vendor_motorola_sm7250-common" />
  <project name="The-Muppets/proprietary_vendor_motorola_sm7325-common" />
  <project name="The-Muppets/proprietary_vendor_motorola_smith" />
  <project name="The-Muppets/proprietary_vendor_motorola_troika" />
  <project name="The-Muppets/proprietary_vendor_xiaomi" />

```

**Comment by Yannik** [comment]
Thank you @endim8

I think this clears everything up. bluejay actually got built already, and I'm pretty sure the other new lineageos devices will follow suit.
