### ISSUE TITLE
v15.1 builds are unsigned

### ISSUE THREAD

**Issue by iainnicol** [lineageos4microg/docker-lineage-cicd#4]
Thanks for this project, and for upgrading to v15.1.

I am using keytool from OpenJDK 8 to verify the zips. However, both cheeseburger builds for v15.1 are unsigned. The last v14.1 build, in contrast, was correctly signed.

**Comment by corna** [comment]
Thanks for the report, I hadn't noticed it. It seems however that also the official LineageOS ZIPs aren't signed:

```
~/Downloads/temp$ keytool -list -printcert -jarfile lineage-15.1-20180305-nightly-cheeseburger-signed.zip
Not a signed jar file
~/Downloads/temp$ keytool -list -printcert -jarfile lineage-15.1-20180306-microG-cheeseburger.zip
Not a signed jar file
```

They've probably changed the signature scheme, in fact META-INF/ doesn't contain MANIFEST.MF, CERT.SF and CERT.RSA anymore.

I'll have a look.

**Comment by Lanchon** [comment]
android introduced whole-zip-signing a long time ago, which is what recoveries check. "signapk -w" is the canonical implementation i think. jar signing is instead per-file and carried within META-INF/. maybe lineage now only signs whole-zip, which would make sense; the rest is redundant.

note that whole-zip-signing has nothing to do with APK signature scheme v2, which is much newer and not applicable to OTAs.

**Comment by iainnicol** [comment]
Thanks both.

I can't find any standalone verifier for signapk.  The signapk source code refers to the mincrypt verifier.  I think that refers to https://android.googlesource.com/platform/bootable/recovery/+/master/verifier.cpp, which according to the logs previously used mincrypt.

Indeed, TWRP uses verify_file from the above verifier.cpp, if you check the zip signature verification box.  This agrees with what Lanchon was saying about recoveries checking whole-zip-signing.  However, this doesn't help us, even for upgrading an existing system, because the folder /res/keys is empty.

So what should we do?  We could probably cross compile verifier.cpp for the desktop.  I'm not a huge fan of that idea, because any such precompiled verifier program should itself also be signed.  Or we would port verifier.cpp to something transparent and high level like Python.  Thoughts?

**Comment by iainnicol** [comment]
I've written a verifier in Python 3. The good news is the v15 builds are indeed signed with the same key as the v14 builds.

I'll upload the code tonight. My aims is that you would then be able to recommend its use, so that others can verify v15 builds.

**Comment by iainnicol** [comment]
Here it is: https://gitlab.com/iain/otasig

**Comment by rugk** [comment]
Hu, but how inconvenient is it that i still need to download a custom verifier just to verify the LineageOS v15 builds?

LineageOS also [has not modified their instructions for verifying](https://wiki.lineageos.org/verifying-builds.html), so I think this needs to be escalated to upstream.

**Comment by corna** [comment]
@rugk I agree, this is a problem for every LineageOS' user, not just for us, it should be reported and fixed upstream.

**Comment by nExXxuS** [comment]
Not a bug: https://www.reddit.com/r/LineageOS/comments/86uyz8/signature_missing_on_5tdumpling_151_build/

**Comment by jedahan** [comment]
This was annoying to track down. Can we update the install instructions on the website at least?
