### ISSUE TITLE
repo init in build.sh is missing --git-lfs option

### ISSUE THREAD

**Issue by ptensschi** [lineageos4microg/docker-lineage-cicd#402]
Some lineage repos seem to have changed to use git-lfs lately (see e.g. https://github.com/LineageOS/android_external_chromium-webview_prebuilt_arm64), which makes my builds fail.

The lineage build instructions (https://wiki.lineageos.org/devices/heart/build) suggest to use the `--git-lfs` option for `repo init`.

I suggest to adapt `src/build.sh` and add this option.

**Comment by thepartisan** [comment]
adding the option fixed the builds for me.

**Comment by dicer** [comment]
Applying the pull request and cleaning the repo like this, made it work for me as well:
```
rm -rf external/chromium-webview/prebuilt/*
rm -rf .repo/projects/external/chromium-webview/prebuilt/*.git
rm -rf .repo/project-objects/LineageOS/android_external_chromium-webview_prebuilt_*.git
```

**Comment by bananer** [comment]
that seems to explain the failing builds in the current round. thanks!
