### ISSUE TITLE
No network access for prebuilt apps

### ISSUE THREAD

**Issue by kurt-by** [lineageos4microg/docker-lineage-cicd#404]
I upgraded from lineageOS to lineage4microg on a fresh xz2c. The upgrade went smooth by installing the zip from portable SD. No migration zip necessary. Confirming signature mismatch was enough. No wipes.
The new installed apps f-droid and "microG Services Core" had "allow network access" toggled off.

**Comment by Iey4iej3** [comment]
According to the official guide,

> Then, depending on your recovery type, two methods apply:
> 
> - Lineage recovery: Flash the LineageOS for microG ZIP and confirm flash despite signature mismatch.
> - TWRP recovery: Download and flash [the migration ZIP](https://download.lineage.microg.org/extra) and, without rebooting, flash the LineageOS for microG ZIP.

The migration zip is not necessary if you are using the Lineage recovery.

**Comment by kurt-by** [comment]
That piece of guide is by me, i think. I wanted to highlight, there are misding permissions.

**Comment by petefoth** [comment]
@kurt-by  Just to clarify, the problem with network access occurred when you 'dirty flashed' LineageOS for microG over 'normal' lineageOS? I recall similar problems when moving between different ROMs, and I'm not sure that there is an easy fix, other than documenting the fact that after dirty flashing, a user needs to check permissions for the prebuilt apps

**Comment by petefoth** [comment]
> and I'm not sure that there is an easy fix, other than documenting the fact that after dirty flashing, a user needs to check permissions for the prebuilt apps

I have added this documentation change to #454. Are you happy for this issue to be closed now @kurt-by ?

**Comment by petefoth** [comment]
Close when #454 is completed and merged

**Comment by petefoth** [comment]
Fixed in https://github.com/lineageos4microg/docker-lineage-cicd/commit/c251857103c9a8f979bc67bba3fa9f0c3fcf9ae5
