### ISSUE TITLE
lemonadep fails when including microg manifest

### ISSUE THREAD

**Issue by ShadwDrgn** [lineageos4microg/docker-lineage-cicd#408]
After getting my image to succeed with the following command line by emptying all volumes so that i'm building fresh, when I add the microg.xml file from the README.md i now have my builds fail :( Logs attached.
Command:
`docker run --rm --name android -e "BRANCH_NAME=lineage-20.0" -e "DEVICE_LIST=lemonadep" -e "SIGN_BUILDS=true" -e "RELEASE_TYPE=user" -e "WITH_GMS=true" -e "SIGNATURE_SPOOFING=restricted" -e "ZIP_SUBDIR=false" -e "OTA_URL=https://lineage.1ez.us/api" -v "/mnt/ds16_backups/android/lineage:/srv/src" -v "/mnt/ds16_backups/android/keys:/srv/keys" -v "/mnt/ds16_backups/android/zips:/srv/zips" -v "/mnt/ds16_backups/android/logs:/srv/logs" -v "/mnt/ds16_backups/android/ccache:/srv/ccache" -v "/mnt/ds16_backups/android/local_manifests:/srv/local_manifests" lineageos4microg/docker-lineage-cicd`
manifest:
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    <project path="vendor/partner_gms" name="lineageos4microg/android_vendor_partner_gms" remote="github" revision="master" />
</manifest>
```
log:
https://cloud.1ez.us/index.php/s/mQ7x2sJpiPAYaaK

**Comment by petefoth** [comment]
Well the error occurs around line 147282:
```
[ 82% 136404/165311] //packages/apps/Settings:Settings aapt2 link [common]
FAILED: out/soong/.intermediates/packages/apps/Settings/Settings/android_common/aapt2/package-res.apk out/soong/.intermediates/packages/apps/Settings/Settings/android_common/gen/proguard.options out/soong/.intermediates/packages/apps/Settings/Settings/android_common/gen/android/R.srcjar out/soong/.intermediates/packages/apps/Settings/Settings/android_common/R.txt out/soong/.intermediates/packages/apps/Settings/Settings/android_common/extra_packages
rm -rf out/soong/.intermediates/packages/apps/Settings/Settings/android_common/gen/aapt2/R && out/host/linux-x86/bin/aapt2 link -o out/soong/.intermediates/packages/apps/Settings/Settings/android_common/aapt2/package-res.apk --no-static-lib-packages --manifest out/soong/.intermediates/packages/apps/Settings/Settings/android_common/manifest_merger/AndroidManifest.xml  --min-sdk-version 33 --target-sdk-version 33 --version-code 33 --version-name  13 --auto-add-overlay -I out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/package-res.apk -I out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/package-res.apk --product default -c en_US,en_US,af_ZA,am_ET,ar_EG,ar_XB,as_IN,az_AZ,be_BY,bg_BG,bn_BD,bs_BA,ca_ES,cs_CZ,da_DK,de_DE,el_GR,en_AU,en_CA,en_GB,en_IN,en_XA,es_ES,es_US,et_EE,eu_ES,fa_IR,fi_FI,fr_CA,fr_FR,gl_ES,gu_IN,hi_IN,hr_HR,hu_HU,hy_AM,in_ID,is_IS,it_IT,iw_IL,ja_JP,ka_GE,kk_KZ,km_KH,kn_IN,ko_KR,ky_KG,lo_LA,lt_LT,lv_LV,mk_MK,ml_IN,mn_MN,mr_IN,ms_MY,my_MM,nb_NO,ne_NP,nl_NL,or_IN,pa_IN,pl_PL,pt_BR,pt_PT,ro_RO,ru_RU,si_LK,sk_SK,sl_SI,sq_AL,sr_Latn_RS,sr_RS,sv_SE,sw_TZ,ta_IN,te_IN,th_TH,tl_PH,tr_TR,uk_UA,ur_PK,uz_UZ,vi_VN,zh_CN,zh_HK,zh_TW,zu_ZA,ast_ES,gd_GB,cy_GB,en_XC,normal --preferred-density xxxhdpi --java out/soong/.intermediates/packages/apps/Settings/Settings/android_common/gen/aapt2/R --proguard out/soong/.intermediates/packages/apps/Settings/Settings/android_common/gen/proguard.options --output-text-symbols out/soong/.intermediates/packages/apps/Settings/Settings/android_common/R.txt -R @out/soong/.intermediates/packages/apps/Settings/Settings/android_common/aapt2/overlay.list && out/host/linux-x86/bin/soong_zip -write_if_changed -jar -o out/soong/.intermediates/packages/apps/Settings/Settings/android_common/gen/android/R.srcjar -C out/soong/.intermediates/packages/apps/Settings/Settings/android_common/gen/aapt2/R -D out/soong/.intermediates/packages/apps/Settings/Settings/android_common/gen/aapt2/R &&out/host/linux-x86/bin/extract_jar_packages -i out/soong/.intermediates/packages/apps/Settings/Settings/android_common/gen/android/R.srcjar -o out/soong/.intermediates/packages/apps/Settings/Settings/android_common/extra_packages --prefix '--extra-packages '
Segmentation fault (core dumped)
```
I don't think it's anything to do with your extra manifest, which looks fine. Something caused one of the threads in the build process to crash. Did you retry / restart the build? If so, did it fail again in the same place?

I had a similar problem when some builds would crash or be killed  - in  my case due to an 'out-of-memory` error - quite late on in the build process. Restarting the build, by rerunning the same build command, without changing anything else, would usually allow the build to complete

**Comment by ShadwDrgn** [comment]
Thanks again for your help. I normally retry things before submitting tickets, but i'd just had SO MANY failures with this script from my last problem that i'm on edge about it all lately. I had actually rerun the build before submitting the ticket to see if the failure would be the same but it was in fact successful this time. i feel bad for putting a ticket in before the retry finished. will close this. sorry for the ticket "flood" (i've submit two others in the last week)
