### ISSUE TITLE
No download available for supported device 'charlotte'

### ISSUE THREAD

**Issue by cnnrro** [lineageos4microg/docker-lineage-cicd#41]
The FAQ says: "We already build LineageOS for microG for every device supported by LineageOS".

But it seems there is no download available for "[charlotte](https://wiki.lineageos.org/devices/charlotte)."

Is this an oversight, or is there some issue with this build?

If there is an issue, how could I assist?

**Comment by corna** [comment]
See [here](https://forum.xda-developers.com/android/software/lineageos-microg-t3700997/post79759366#post79759366)

**Comment by spolack** [comment]
Build failing at `[ 69% 75103/107952] //device/huawei/kirin970-common/interfaces/fingerprint/2.1:vendor.huawei.hardware.biometrics.fingerprint@2.1_genc++ generate
FAILED: /srv/tmp/merged/out/soong/.intermediates/device/huawei/kirin970-common/interfaces/fingerprint/2.1/vendor.huawei.hardware.biometrics.fingerprint@2.1_genc++/gen/vendor/huawei/hardware/biometrics/fingerprin
t/2.1/ExtBiometricsFingerprintAll.cpp /srv/tmp/merged/out/soong/.intermediates/device/huawei/kirin970-common/interfaces/fingerprint/2.1/vendor.huawei.hardware.biometrics.fingerprint@2.1_genc++/gen/vendor/huawei/
hardware/biometrics/fingerprint/2.1/FidoAuthenticationCallbackAll.cpp 
/srv/tmp/merged/out/soong/host/linux-x86/bin/sbox --sandbox-path /srv/tmp/merged/out/soong/.temp --output-root /srv/tmp/merged/out/soong/.intermediates/device/huawei/kirin970-common/interfaces/fingerprint/2.1/ve
ndor.huawei.hardware.biometrics.fingerprint@2.1_genc++/gen -c '/srv/tmp/merged/out/soong/host/linux-x86/bin/hidl-gen -d __SBOX_DEPFILE__ -o __SBOX_OUT_DIR__ -Lc++-sources -randroid.hardware:hardware/interfaces -
randroid.hidl:system/libhidl/transport -rvendor.huawei.hardware.biometrics:device/huawei/kirin970-common/interfaces vendor.huawei.hardware.biometrics.fingerprint@2.1' --depfile-out /srv/tmp/merged/out/soong/.int
ermediates/device/huawei/kirin970-common/interfaces/fingerprint/2.1/vendor.huawei.hardware.biometrics.fingerprint@2.1_genc++/gen/vendor/huawei/hardware/biometrics/fingerprint/2.1/ExtBiometricsFingerprintAll.cpp.
d __SBOX_OUT_DIR__/vendor/huawei/hardware/biometrics/fingerprint/2.1/ExtBiometricsFingerprintAll.cpp __SBOX_OUT_DIR__/vendor/huawei/hardware/biometrics/fingerprint/2.1/FidoAuthenticationCallbackAll.cpp
ERROR: Could not open package path device/huawei/kirin970-common/interfaces/fingerprint/2.1/ for package vendor.huawei.hardware.biometrics.fingerprint@2.1:
/srv/src/LINEAGE_16_0/device/huawei/kirin970-common/interfaces/fingerprint/2.1/
sbox command (/srv/tmp/merged/out/soong/host/linux-x86/bin/hidl-gen -d /srv/tmp/merged/out/soong/.temp/sbox825524335/vendor/huawei/hardware/biometrics/fingerprint/2.1/ExtBiometricsFingerprintAll.cpp.d -o /srv/tmp/merged/out/soong/.temp/sbox825524335 -Lc++-sources -randroid.hardware:hardware/interfaces -randroid.hidl:system/libhidl/transport -rvendor.huawei.hardware.biometrics:device/huawei/kirin970-common/interfaces vendor.huawei.hardware.biometrics.fingerprint@2.1) failed with err "exit status 1"

`

**Comment by bananer** [comment]
Old device, builds were failing and no help in sight. See https://github.com/lineageos4microg/docker-lineage-cicd/issues/197#issuecomment-918110759 for current state of builds.
