### ISSUE TITLE
some download files disappeared from website

### ISSUE THREAD

**Issue by aiomaster** [lineageos4microg/docker-lineage-cicd#412]
From the website some downloads disappeared in the last few days.
For example:
https://download.lineage.microg.org/guacamole/
and in google cache:
https://webcache.googleusercontent.com/search?q=cache:HDRDXeFL84wJ:https://download.lineage.microg.org/guacamole/&cd=1&ct=clnk

I need one of the disappeared images to fix my phone. What happened?

**Comment by dicer** [comment]
See https://github.com/lineageos4microg/android_vendor_partner_gms/issues/21

**Comment by aiomaster** [comment]
New images are there now and working. Damn, the build process took really long (2h per device).
Thanks for all your work.
