### ISSUE TITLE
Build completely broken for a5y17lte

### ISSUE THREAD

**Issue by sakul987** [lineageos4microg/docker-lineage-cicd#414]
I have tried building for a5y17lte multiple times with different settings but I always get the same result:

I can flash the image (wiped everything before) and when I reboot I see the Lineage animation and then when the initial setup should start, I get a black screen with a status bar that has the time and a battery indicator and shortly after that pop ups keep appearing saying "X keeps stopping" with things like Settings and com.android.phone.

Im am using this docker image (last cloned and tried on 15.04.23) inside a 22.04 ubuntu vm but have also tried different approaches like emulating running the container inside a lxc container. Always the same result.

The settings I use are:
docker run \
   -e "BRANCH_NAME=lineage-18.1" \
   -e "DEVICE_LIST=a5y17lte" \
   -e "SIGN_BUILDS=true" \
   -e "SIGNATURE_SPOOFING=restricted" \
   -e "BUILD_TYPE=user" \
   -e "WITH_GMS=true" \
   -v "/home/usr/lineage:/srv/src" \
   -v "/home/usr/zips:/srv/zips" \
   -v "/home/usr/logs:/srv/logs" \
   -v "/home/usr/cache:/srv/ccache" \
   -v "/home/usr/keys:/srv/keys" \
   -v "/home/usr/manifests:/srv/local_manifests" \
   microg

With the manifest from the readme.

Tried using the Muppets proprietary blobs and extracting them myself from a Lineage build, also the same result.

Using keys I created like this:
openssl genrsa -3 -out temp.pem 2048
openssl req -new -x509 -key temp.pem -out releasekey.x509.pem -days 10000 -subj '...'
openssl pkcs8 -in temp.pem -topk8 -outform DER -out releasekey.pk8 -nocrypt

And then replicated using
for key in platform shared media networkstack sdk_sandbox bluetooth ; do cp releasekey.pk8 "$key".pk8 ; done
and
for key in platform shared media networkstack sdk_sandbox bluetooth ; do cp releasekey.x509.pem "$key".x509.pem ; done

Is this a fault on my side or is building (this device) with this docker container just broken?

**Comment by petefoth** [comment]
A couple of things to check
> I can flash the image (wiped everything before) and when I reboot I see the Lineage animation and then when the initial setup should start, I get a black screen with a status bar that has the time and a battery indicator and shortly after that pop ups keep appearing saying "X keeps stopping" with things like Settings and com.android.phone.

Did you try ***formatting*** data partition, rather than just wiping? Problems like this can often be fixed that way

> Is this a fault on my side or is building (this device) with this docker container just broken?

An official build was made using the latest docker image, and is available for download at https://download.lineage.microg.org/a5y17lte/. Please can you try installing that build (afer formatting data partition), and see if you see the same problem.

If everything works with the new build, then you could try rebuilding yourself.

If the official build does not work, then we may have a bigger problem, but let's wait and see about that :)

**Comment by sakul987** [comment]
Yes, I have formatted the device, wiped all items in twrp except external storage, done this in reverse order etc. 

I havent tried the latest official release, but I dont think I ever had any issues with them, only when building myself
Speaking of twrp, may this be an issue?

**Comment by sakul987** [comment]
Yes I have formatted and wiped every item in twrp, even in reverse order.

I never had any issue with the official builds, only when building myself.

I have until recently only built this on my server inside an lxc / lxd container and whatever was built there was completely broken. A few weeks ago I upgraded my main pc, which now has enough ram to build it as well, and I was able to build it inside a qemu vm. This build seems semi stable, I was able to initialise the OS and install some apps, but after encrypting the disk, it also broke (booting but settings not available, crashing & rebooting after a few seconds).
I have now installed my pc build, encrypted, and then started installing apps and so far it seems to be working.

So I am somewhere close to stable, but only when building from my pc, which is very weird.

I was wondering if my run options could be causing this, for example build_type user for whatever reason. Or twrp, but the official builds work completely fine with it, so shouldnt be.

Only other thing I could think of, why the official builds are working, but only some of mine, are the propietary blobs, but I have no idea why its half working on my pc and not at all on my server when building using the same dockerfile & same blob files.

Are the actually used build options publicly available? I could try to use exactly those, just for one device only

**Comment by petefoth** [comment]
I would recommend that you ask for help in the [XDA forum](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/). There are more people there with the necessary experience and time available to give you nore assistance.

From a quick glance the only things I notice different fro our build commands is you have `-e "BUILD_TYPE=user" `. we don't make `user-builds`, only `user-debug`. No idea why or if that would cause the problems you are seeing

Here is the `docker run` command we use to build (with the `-v entries` stripped out - they are specific to our build server). The first four lines shouldn't be necessary for you
```
docker run \
    --name "lineageos4microg-$(date +%Y%m%d%I%M)" \
    --cap-add=SYS_ADMIN \
    --security-opt apparmor=unconfined \
    --security-opt seccomp=unconfined \
    -e "BRANCH_NAME=$BRANCH" \
    -e "USE_CCACHE=true" \
    -e "CCACHE_SIZE=500G" \
    -e "RELEASE_TYPE=microG" \
    -e "OTA_URL=https://download.lineage.microg.org/api" \
    -e "INCLUDE_PROPRIETARY=true" \
    -e "BUILD_OVERLAY=true" \
    -e "CLEAN_OUTDIR=false" \
    -e "CLEAN_AFTER_BUILD=true" \
    -e "SIGN_BUILDS=true" \
    -e "ZIP_SUBDIR=true" \
    -e "LOGS_SUBDIR=true" \
    -e "LOCAL_MIRROR=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "DELETE_OLD_ZIPS=3" \
    -e "DELETE_OLD_LOGS=3" \
    -e "WITH_GMS=true" \
    -v ....
   -e "DEVICE_LIST=$DEVICES" \
    lineageos4microg/docker-lineage-cicd
```

**Comment by petefoth** [comment]
> An official build was made using the latest docker image, and is available for download at https://download.lineage.microg.org/a5y17lte/. Please can you try installing that build (afer formatting data partition), and see if you see the same problem.

@sakul987 Have you tried installing the official build yet? If so, did it have the same problem, or does the official biuild work?

Thanks
