### ISSUE TITLE
Aurora Services

### ISSUE THREAD

**Issue by PlazmaKG** [lineageos4microg/docker-lineage-cicd#419]
Is there any method to add Aurora Services (Aurora equivalent to F-Droid privileged extension) & Aurora Store to the build? It'd be useful for automatic app updates.

**Comment by petefoth** [comment]
No need to add Aurora Services. If Aurora Store is installed as a system app (i.e. it's included in the ROM) then it can handle automatic installations.

**Comment by sebastianmuell** [comment]
I was able to include Aurora Services as a privileged system app using this Android.mk file and the contents of AuroraServices-v1.1.1-magisk.zip. Unfortunately this solution stopped working for LOS20, i assume because of something related to dexpreopt, but I have not yet looked in detail.

```makefile
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := privapp-permissions-auroraservices.xml
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/permissions
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := AuroraServices
LOCAL_SRC_FILES := AuroraServices_v1.1.1.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_REQUIRED_MODULES := privapp-permissions-auroraservices.xml
include $(BUILD_PREBUILT)
```

**Comment by tomo90** [comment]
> No need to add Aurora Services. If Aurora Store is installed as a system app (i.e. it's included in the ROM) then it can handle automatic installations.

Tried that. Yet no automatic installations on LOS 20.

**Comment by petefoth** [comment]
> Unfortunately this solution stopped working for LOS20, i assume because of something related to dexpreopt, but I have not yet looked in detail.

in Android 13, `dexpreopt` messes with the apk signature. Including something like the following in your makefile should solve the problem:

`LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/$(LOCAL_MODULE).apk`

> Yet no automatic installations on LOS 20.
Depends what you mean by 'automatic installation' . F-Droid and F-droid Privileged Extension to completely automatic installation, downloading and installing in background without any user intervention. The best I could get from Aurora Store / Services was that when you choose 'Updates' followed by 'Update all' in Aurora Store, the installation would happen without any further user input (instead of the app asking 'Do you want to install an update` for each app. Aurora Services used to be necessary for that, but now it's not needed if Aurora Store is installed as a system app.

Have you ever been able to get 'F-Droid style' automatic installation with Aurora Store / Services ? If so I'd love to know how to do it :)

**Comment by dbkblk** [comment]
> Have you ever been able to get 'F-Droid style' automatic installation with Aurora Store / Services ? If so I'd love to know how to do it :)

Well, at first I was expecting this not to work, but after installing Aurora, the first install ask for confirmation, then the updates don't need it. This means a system component is already setup.

**Comment by tomo90** [comment]
> > Unfortunately this solution stopped working for LOS20, i assume because of something related to dexpreopt, but I have not yet looked in detail.
> 
> in Android 13, `dexpreopt` messes with the apk signature. Including something like the following in your makefile should solve the problem:
> 
> `LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/$(LOCAL_MODULE).apk`
> 
> > Yet no automatic installations on LOS 20.
> > Depends what you mean by 'automatic installation' . F-Droid and F-droid Privileged Extension to completely automatic installation, downloading and installing in background without any user intervention. The best I could get from Aurora Store / Services was that when you choose 'Updates' followed by 'Update all' in Aurora Store, the installation would happen without any further user input (instead of the app asking 'Do you want to install an update` for each app. Aurora Services used to be necessary for that, but now it's not needed if Aurora Store is installed as a system app.
> 
> Have you ever been able to get 'F-Droid style' automatic installation with Aurora Store / Services ? If so I'd love to know how to do it :)

Yeah just that F-droid and its extensions have worked beautifully for me so far. I finally took the time to check out the AuroraStore more to make it work as well. And it did. I have to retract my original statement. All I had to do was to push the AuroraStore.apk to /system/priv-app/AuroraStore and create the corresponding configuration file com.aurora.store.xml in /system/etc/permissions. AuroraStore can now install and update apps by itself. All I have to do is tap Install in case of installing a new app or Update / Update all in case of app updates and everything happens automatically without any further intervention or confirmation needed.

No need for AuroraServices anymore!

I am pleasantly surprised 👍

**Comment by TinfoilSubmarine** [comment]
> > > Unfortunately this solution stopped working for LOS20, i assume because of something related to dexpreopt, but I have not yet looked in detail.
> > 
> > 
> > in Android 13, `dexpreopt` messes with the apk signature. Including something like the following in your makefile should solve the problem:
> > `LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/$(LOCAL_MODULE).apk`
> > > Yet no automatic installations on LOS 20.
> > > Depends what you mean by 'automatic installation' . F-Droid and F-droid Privileged Extension to completely automatic installation, downloading and installing in background without any user intervention. The best I could get from Aurora Store / Services was that when you choose 'Updates' followed by 'Update all' in Aurora Store, the installation would happen without any further user input (instead of the app asking 'Do you want to install an update` for each app. Aurora Services used to be necessary for that, but now it's not needed if Aurora Store is installed as a system app.
> > 
> > 
> > Have you ever been able to get 'F-Droid style' automatic installation with Aurora Store / Services ? If so I'd love to know how to do it :)
> 
> Yeah just that F-droid and its Privileged extension have worked beautifully for me so far. I finally took the time to check out the AuroraStore more to make it work as well. And it did. I have to retract my original statement. All I had to do was to push the AuroraStore.apk to /system/priv-app/AuroraStore and create the corresponding configuration file com.aurora.store.xml in /system/etc/permissions. AuroraStore can now install and update apps by itself. All I have to do is tap Install in case of installing a new app or Update / Update all in case of app updates and everything happens automatically without any further intervention or confirmation needed. So you're absolutely right on this.
> 
> No need for AuroraServices anymore!
> 
> I am pleasantly surprised +1

Shouldn't even need to be installed in `/system`. I just install it from F-Droid as a user-installed app and have no issues.

**Comment by tomo90** [comment]
> Shouldn't even need to be installed in `/system`. I just install it from F-Droid as a user-installed app and have no issues.

I doubt this could work, but maybe I'm wrong again. But definitely doesn't work for me on LineageOS 20. When I install the Aurora store as a regular user application and tap on "Install/Update" to install/update some apps, the Android dialog pops up and I have to confirm the installation of each one.

**Comment by TinfoilSubmarine** [comment]
> I doubt this could work, but maybe I'm wrong again. But definitely doesn't work for me on LineageOS 20. When I install the Aurora store as a regular user application and tap on "Install/Update" to install/update some apps, the Android dialog pops up and I have to confirm the installation of each one.

IIRC, it will throw a pop-up the first time you install updates when "switching" to the session installer from e.g. Aurora Services. The next time you receive an update for that app, it should install in the background without user interaction.

**Comment by awfm9** [comment]
> Have you ever been able to get 'F-Droid style' automatic installation with Aurora Store / Services ? If so I'd love to know how to do it :)

It all works great for me. I just install Magisk, and then use the Aurora Services Magisk add-on.

**Comment by petefoth** [comment]
I am going to close this PR, because Android Services does nothing that is not done by Aurora Store when installed - as in los4mg - as a system app (see [this FAQ on the Aurora wiki](https://gitlab.com/AuroraOSS/AuroraStore/-/wikis/Frequently-Asked-Questions#how-does-aurora-store-install-apps)
