### ISSUE TITLE
Problem building 16.0 for sailfish

### ISSUE THREAD

**Issue by scottrix** [lineageos4microg/docker-lineage-cicd#42]
error: frameworks/base/packages/EasterEgg/Android.bp:17:1: module "EasterEgg" variant "android_common": Path is outside directory: /srv/keys

Any ideas ?

docker run \
    -e "BRANCH_NAME=${BRANCH}" \
    -e "DEVICE_LIST=sailfish" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension" \
    -e "WITH_SU=true" \
    -e "BUILD_DELTA=true" \
    -e "DELETE_OLD_ZIPS=5" \
    -e "DELETE_OLD_DELTAS=5" \
    -e "DELETE_OLD_LOGS=5" \
    -e "CLEAN_AFTER_BUILD=false" \
    -e "INCLUDE_PROPRIETARY=false" \
    -v "${PWD}:/srv/src" \
    -v "${PWD}/out/zips:/srv/zips" \
    -v "${PWD}/out/logs:/srv/logs" \
    -v "${PWD}/out/cache:/srv/ccache" \
    -v "${PWD}/out/delta:/srv/delta" \
    -v "${PWD}/out/keys:/srv/keys" \
    -v "${PWD}/local_manifests:/srv/local_manifests" \
     lineageos4microg/docker-lineage-cicd

Thanks.

**Comment by spolack** [comment]
This Device was promoted to LineageOS 17.1 which is now supported. 
This is  related to the master issue #89
