### ISSUE TITLE
Build fails with can't detect android version - lineageos 16.0 for Samsung A5 2016 (a5xelte)

### ISSUE THREAD

**Issue by ashwini215** [lineageos4microg/docker-lineage-cicd#43]
Trying to build lineageos for microg 16.0 for a5xelte.
I am on ubuntu 18.04.2 lts and have previously sucessfully built 15.1 for the same device.

for 16.0, build fails with the error -
Syncing branch repository
sed: can't read build/core/version_defaults.mk: No such file or directory
sed: can't read build/core/version_defaults.mk: No such file or directory
sed: can't read build/core/version_defaults.mk: No such file or directory
>> [Wed Jun 26 10:23:17 UTC 2019] Can't detect the android version

the log shows the following error -
[repo-20190626.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/3329482/repo-20190626.log)

Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

also attaching the local manifest for reference.
Kindly help, guys.
[a5xelte.txt](https://github.com/lineageos4microg/docker-lineage-cicd/files/3329565/a5xelte.txt)

**Comment by Ultracoolguy** [comment]
You aren't the only one with this issue. I'm trying to build LOS 15.1 for marlin(Pixel XL) and the terminal outputs the same thing. 

In both your log and [my log](https://github.com/lineageos4microg/docker-lineage-cicd/files/3339106/repo-20190628.log) it almost at the end it says `error: Exited sync due to fetch errors` . I checked my log more in depth, and I find that in some links `curl` return the error you mentioned(the host key one) followed by a 404, others with just a 404. And yet all of those links work correctly(or atleast, connect to browser).

**Comment by ashwini215** [comment]
Fortunately, I was successful in building LOS 15.1 for Samsung A5 2016. 
For LOS 16.0, my guess is that it repo syncing over ssh (as mentioned in my local manifest), is failing the syncing process. 
Previously for LOS 15.1, I cloned over Https and everything went fine.

**Comment by Ultracoolguy** [comment]
Then I guess that for a workaround I should try manually cloning until then.

**Comment by Ultracoolguy** [comment]
Why did you closed this? It's still a bug from this repo. A workaround isn't a fix.

**Comment by ashwini215** [comment]
thanks. Reopened it. 
Btw, were you able to clone manually ?

**Comment by Ultracoolguy** [comment]
Yeah, and the build came out successfully. It's a problem with this repo.

**Comment by CrimsonFinale** [comment]
> thanks. Reopened it.
> Btw, were you able to clone manually ?

How to clone manually?

**Comment by Yanagibashi004** [comment]
@Ultracoolguy Sorry to necro an old thread but would you be able to elaborate on how you manually cloned it?

**Comment by Ultracoolguy** [comment]
@Yanagibashi004 No problem. I basically just followed the LineageOS guide for my phone, specifically the cloning part(basically install lineageos dependencies, install the repo tool, and do the repo init and repo sync commands) in the directory used by the docker image. After that, I just run the docker image on that directory.

**Comment by spolack** [comment]
Device was promoted to LineageOS 17.1. Please check if the issue still occurs and reopen.
