### ISSUE TITLE
What does bacon mean here?

### ISSUE THREAD

**Issue by hellodword** [lineageos4microg/docker-lineage-cicd#433]
Hi, is `bacon` [a device](https://wiki.lineageos.org/devices/bacon/build)? Or kind of general building option?

https://github.com/lineageos4microg/docker-lineage-cicd/blob/5c35c2e93cad4f5026e81a13f760fb15c854deee/src/build.sh#L343-L346

It works fine with my bullhead, so I'm confused about it.

**Comment by petefoth** [comment]
> Hi, is bacon [a device](https://wiki.lineageos.org/devices/bacon/build)? Or kind of general building option?
`bacon` is essentially  a build target which tells the `mka` tool (an enhanced version of `make`) what you want to build.

See [this page](http://www.trcompu.com/MySmartPhone/AndroidKitchen/Breakfast-Brunch-Lunch.html) for a fuller  explanation of 'breakfast-related' Android vocabulary

**Comment by Komprogue** [comment]
> Hi, is `bacon` [a device](https://wiki.lineageos.org/devices/bacon/build)? Or kind of general building option?
> 
> https://github.com/lineageos4microg/docker-lineage-cicd/blob/5c35c2e93cad4f5026e81a13f760fb15c854deee/src/build.sh#L343-L346
> 
> It works fine with my bullhead, so I'm confused about it.


But bullhead builds were [abandoned](https://github.com/lineageos4microg/lineageos4microg.github.io/issues/101) more than a year ago, unfortunately. Which ones are you using, you own?
