### ISSUE TITLE
Builds for Minimal devices and TV boxes failed

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#436]
Builds failed for the following Android TV box devices: deadpool, wade

All failed with the following error:
```
In file included from vendor/lineage/config/common.mk:227:
^[[1mvendor/lineage/config/partner_gms.mk:9: ^[[31merror: ^[[0m^[[1m vendor/partner_gms-tv/products/gms_minimal.mk does not exist.
```

**Comment by petefoth** [comment]
To build for Android TV boxes, we need another repo which populates the build tree at `vendor/partner_gms-tv`

LOS are successfully building for these devices, but ~~I can't see any sign of a `vendor_partner_gms-v` repo anywhere ,in their repos, TheMuppets vendor repos (on gitlab or github) or anywhere else on gitlab or github~~ of course they don't need one, because they are not building with `WITH_GMS=true`

The only repo I could find that looks like it fits is https://codeberg.org/iNeedADoctor/android_vendor_partner_gms-tv. This repo has files (`mainline_modules.mk`, `gms_gtv.mk`,  `gms_minimal.mk` )  which include only the line
`-include $(LOCAL_PATH)/gms.mk`
and which don't add much beyond what we already have in our `vendor_partner_gms` makefiles.

I can get past the build error by changing the offending instances of `inherit-product` to `inherit-product-if-exists` in vendor/lineage/config/partner_gms.mk`. But
1. No guarantee that the build will work, even if it succeeds and
2. No way of testing the resulting build

**Comment by yetanother-user** [comment]
Have you tried building los for one of the TV boxes yet?

**Comment by petefoth** [comment]
> Have you tried building los for one of the TV boxes yet?

No. LineageOS builds succeed because they build without setting the `WITH_GMS` flag. The LineageOS [`partner-gms.mk`](https://github.com/LineageOS/android_vendor_lineage/blob/lineage-20.0/config/partner_gms.mk) handles this flag, and does 'Special handling for Android TV' (and for Android Automotive devices/builds):
instead of calling makefiles in the `vendor/partner_gms` directory in the build tree (which exists [in our sources](https://github.com/lineageos4microg/android_vendor_partner_gms), it looks instead for a `vendor/partner_gms-tv` directory, which does not exist (yet).

We need to look into how best to handle this and, realistically, that's not going to happen in time for the next build run (which is due to start on Saturday). Until it does, the position is that - sadly - lineages4microg does not yet support Android TV boxes.

**Comment by yetanother-user** [comment]
The repo on codeberg that you linked is mine.

To successfully compile ``wade`` you need to use the ``WITH_GMS=true`` flag otherwise it fails. The problem, if I remember correctly, is that without the flag too much space is reserved for gms and it goes out of space.
If I remember correctly, I read that two users on xda, who compiled los also had the space problem.



> Until it does, the position is that - sadly - lineages4microg does not yet support Android TV boxes.

Wade with los-19.1 with microg works like a charm.
I use it to watch amazon prime video.

**Comment by petefoth** [comment]
> To successfully compile wade you need to use the WITH_GMS=true flag otherwise it fails. 
 
Sorry - it looks like we are talking at cross purposes. When you said

> Have you tried building los for one of the TV boxes yet

I thought you meant 'vanilla' LineageOS, **_without_** microG. That  would mean building **_without_** `WITH_GMS=true`, and we don't do that.

**_This_** project (i.e. lineageos4micro) **_does_** build with `WITH_GMS=true`, and builds for `wade` (and the other TV boxes, `deadpool, wade, m5`) currently fail, because **_with_** `WITH_GMS=true`, file `vendor/lineage/config/partner_gms.mk`  needs a `vendor/partner_gms-tv` repo, and we don't currently have one.

When I said
> the position is that - sadly - lineages4microg does not yet support Android TV boxes.

I meant that **_official_** lineageos4microg  builds of these devices are not supported. For this to change, and for the builds to succeed, we would need to create and populate a `vendor/partner_gms-tv` repo. That's not in the plans at the moment, and I'm not sure the project has the resources to implement and test it. Even if it did, it is not in a position to test the builds, as it does not have access to any Android TV devices for testing. So the project needs to decide if it is going to make the necessary changes to make official builds for Android TV boxes.

**Comment by petefoth** [comment]
Knock-on effect of the `wade` `l-20` build failing is that **all** subsequent builds -  `l-20`, `l-19`, `l-18` - are failing because we are hitting github rate limits - see https://github.com/lineageos4microg/docker-lineage-cicd/issues/438#issuecomment-1630813454

**Comment by petefoth** [comment]
In the July build run, the build for the Banana Pi `m5` device also failed with the same error
```
In file included from vendor/lineage/config/common.mk:227:
vendor/lineage/config/partner_gms.mk:9: error:  vendor/partner_gms-tv/products/gms_minimal.mk does not exist.
```

**Comment by petefoth** [comment]
Unassigning this issue. We won't be working on it until a decision is made about whether we can support these devices

**Comment by JoshTheTofu** [comment]
Hi Pete

I noticed that recently Lineage 21 builds for Wade have been succeeding. Has there been a recent change in Lineage4MicroG that has allowed this to happen? Does it need testing because I will be able to test if you need or is this a case of it successfully builds but still has issues and is not ready to be used at all?

Kind regards

Josh

**Comment by petefoth** [comment]
Hi Josh.

> Has there been a recent change in Lineage4MicroG that has allowed this to happen?

No change in Lineage4MicroG. Whatever change fixed this was made upstream in LineageOS. It's interesting that the device mentioned above (`wade`, `deadpool` & `m5`) have been building OK for a few months now, but there are still three TV devices that do fail (`foster`, `porg`, `sif`). I haven't looked in to whether they are failing for the same reason, but I probably should :)

> Does it need testing because I will be able to test if you need or is this a case of it successfully builds but still has issues and is not ready to be used at all?

You are very welcome to test it, but we - the project - don't do any testing of our builds at all. We are a ***very*** small group of maintainers, all volunteers, and there is no way we could find time to properly test all the builds, even if we had access to the ~250 different devices that we currently build for. So our position on testing- for ***alll*** device is 'If it builds, ship it, and it will ***probably*** work. 

Also, if there are problems with our builds for specific devices, our approach is that the problem is almost certainly an upstream problem, with either LineageOS or microG, and we encourage users to report any problems or issues with the projects directly. If the problem appears to be with LineageOS, we suggest trying to reproduce the issue on an official LineageOS build, to avoid getting the standard rLineageOS esponse of 'That's not an official build so you're on your own'. 

So we would be very interested to hear how it goes running Lineage4MicroG on this device - maybe in[ the XDA Forum thread]((https://forum.xda-developers.com/t/lineageos-for-microg.3700997/) where more users are likely to see it. BUt if there are device-specific issues there's not a lot we will be able to do to fix them.

Good luck!

**Comment by JoshTheTofu** [comment]
Hi Pete

Thank you for your swift and clear response. I will test and post my findings in the XDA forum in due course.

Kind regards

Josh

**Comment by petefoth** [comment]
So, the problem is that, if `PRODUCT_IS_ATV` is set `true`

> The LineageOS [`partner-gms.mk`](https://github.com/LineageOS/android_vendor_lineage/blob/lineage-20.0/config/partner_gms.mk) handles this flag, and does 'Special handling for Android TV' (and for Android Automotive devices/builds):
> instead of calling makefiles in the `vendor/partner_gms` directory in the build tree (which exists [in our sources](https://github.com/lineageos4microg/android_vendor_partner_gms), it looks instead for a `vendor/partner_gms-tv` directory, which does not exist (yet).

Specifically, it looks for makefiles in  `vendor/partner_gms-tv/products`

I wrote above that
> To build for Android TV boxes, we need another repo which populates the build tree at `vendor/partner_gms-tv`

but we don't really need another repo, we can populate `vendor/partner_gms-tv/products` ourselves by copying (or maybe linking) the content of our `vendor/partner_gms/products` .

I will give that a try

**Comment by petefoth** [comment]
OK, there is a new build `lineage-21.0-20241122-microG-wade.zip` available for download at https://download.lineage.microg.org/wade/. It won't show up in the Udater as OTA  updates are broken ATM.

@JoshTheTofu  If you have time, please let me know f the build works for you.

Thanks

**Comment by petefoth** [comment]
@JoshTheTofu  [reported in XDA](https://xdaforums.com/t/lineageos-for-microg.3700997/post-89817916) that the latest issue does fix the problem (at least for Wade)
