### ISSUE TITLE
unable to do dirty install of self compiled, signed build after migrating cert keys

### ISSUE THREAD

**Issue by derMart** [lineageos4microg/docker-lineage-cicd#44]
I am trying to build for Xperiy Z5 Compact, as lineagos guys no longer auto build for this device.
Not sure if this is the right repo to report this bug, since I used the docker image to build the zip I report here.
Used this build command, which succesfully builds the installable zip file:
```
docker run \
    -e "BRANCH_NAME=cm-14.1" \
    -e "DEVICE_LIST=suzuran" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -v "/local/home/lmartin/lineageos/volumes/src:/srv/src" \
    -v "/local/home/lmartin/lineageos/volumes/zips:/srv/zips" \
    -v "/local/home/lmartin/lineageos/volumes/logs:/srv/logs" \
    -v "/local/home/lmartin/lineageos/volumes/cache:/srv/ccache" \
    -v "/local/home/lmartin/lineageos/volumes/keys:/srv/keys" \
    -v "/local/home/lmartin/lineageos/volumes/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
```
On my device is the last official lineageOS for MicroG build for suzuram installed(https://download.lineage.microg.org/suzuran/) (btw. thanks folks that you do NOT delete already available builds for devices no longer maintained, which for whatever unexplainable reason the lineageOS folks do).

Afterwards I successfully followed the migration instructions to upate the official keys to my own created keys (https://wiki.lineageos.org/signing_builds.html). I have done this using the script method. Extracting my own keys in the required format worked as well as updating the packages.xml on the device (at least no error thrown).

Afterwards I wanted to install my build zip without wiping data. Using twrp recovery on the device. I unchecked zip verification checkbox (which failes) but still got this error in twrp:
```
Installing zip file '/external_sd/lineage-14.1-20190715-UNOFFICIAL-suzuran.zip'
Checking for Digest file...
Skipping Digest check: no Digest file found
Target: Sony/suzuran/suzuran:7.1.1/N-MR1-KITAKAMI-170920-0229/1:user/dev-keys
detected filesystem ext4 for /dev/block/bootdevice/by-name/system
Can't install this package on top of incompatible data. Please try another package or run a factory reset
Update process ended with ERROR: 7
Error installing zip file [...]
```
Any help appreciated. Is it maybe possible to get some more meaningful error than "on top of incompatible data" ? Any idea *why* twrp thinks it is incompatible?
I want to avoid wiping data just be able to update the device.

best
Martin

**Comment by spolack** [comment]
Most likely this issue is related to LineageOS / or its documentation.

**Comment by muranava** [comment]
> I am trying to build for Xperiy Z5 Compact, as lineagos guys no longer auto build for this device.
> Not sure if this is the right repo to report this bug, since I used the docker image to build the zip I report here.
> Used this build command, which succesfully builds the installable zip file:
> 
> ```
> docker run \
>     -e "BRANCH_NAME=cm-14.1" \
>     -e "DEVICE_LIST=suzuran" \
>     -e "SIGN_BUILDS=true" \
>     -e "SIGNATURE_SPOOFING=restricted" \
>     -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
>     -v "/local/home/lmartin/lineageos/volumes/src:/srv/src" \
>     -v "/local/home/lmartin/lineageos/volumes/zips:/srv/zips" \
>     -v "/local/home/lmartin/lineageos/volumes/logs:/srv/logs" \
>     -v "/local/home/lmartin/lineageos/volumes/cache:/srv/ccache" \
>     -v "/local/home/lmartin/lineageos/volumes/keys:/srv/keys" \
>     -v "/local/home/lmartin/lineageos/volumes/manifests:/srv/local_manifests" \
>     lineageos4microg/docker-lineage-cicd
> ```
> 
> On my device is the last official lineageOS for MicroG build for suzuram installed(https://download.lineage.microg.org/suzuran/) (btw. thanks folks that you do NOT delete already available builds for devices no longer maintained, which for whatever unexplainable reason the lineageOS folks do).
> 
> Afterwards I successfully followed the migration instructions to upate the official keys to my own created keys (https://wiki.lineageos.org/signing_builds.html). I have done this using the script method. Extracting my own keys in the required format worked as well as updating the packages.xml on the device (at least no error thrown).
> 
> Afterwards I wanted to install my build zip without wiping data. Using twrp recovery on the device. I unchecked zip verification checkbox (which failes) but still got this error in twrp:
> 
> ```
> Installing zip file '/external_sd/lineage-14.1-20190715-UNOFFICIAL-suzuran.zip'
> Checking for Digest file...
> Skipping Digest check: no Digest file found
> Target: Sony/suzuran/suzuran:7.1.1/N-MR1-KITAKAMI-170920-0229/1:user/dev-keys
> detected filesystem ext4 for /dev/block/bootdevice/by-name/system
> Can't install this package on top of incompatible data. Please try another package or run a factory reset
> Update process ended with ERROR: 7
> Error installing zip file [...]
> ```
> 
> Any help appreciated. Is it maybe possible to get some more meaningful error than "on top of incompatible data" ? Any idea _why_ twrp thinks it is incompatible?
> I want to avoid wiping data just be able to update the device.
> 
> best
> Martin

hi i am having similar issue so was wondering if you got a solution?
thx for any info!
