### ISSUE TITLE
missing build for `rhode` 

### ISSUE THREAD

**Issue by radiohertz** [lineageos4microg/docker-lineage-cicd#442]
build for https://wiki.lineageos.org/devices/rhode/ isn't available on [download.lineage.microg.org ](https://download.lineage.microg.org/)

**Comment by petefoth** [comment]
This device was only added to the list of LOS build targets on June 29th
https://github.com/LineageOS/hudson/compare/c0286308e86ea38e1b99f53b41255427b0063dc0...d8f49e45d60d8a7fd109c52970ac883228e95196
so it wasn't in the June build run.

It *should* be in the July build run which is currently in progress, and has currently reached 'instantnoodlep' (builds are made in alphabetical order). So the first build should be there in a few days
