### ISSUE TITLE
Suggestion of better start date for the builds

### ISSUE THREAD

**Issue by kurt-by** [lineageos4microg/docker-lineage-cicd#448]
1st of every month is a bad date for starting lineage4microG builds. Usually security patches are merged in the middle of the month. Can you trigger the build with the change of PLATFORM_SECURITY_PATCH

**Comment by petefoth** [comment]
> 1st of every month is a bad date for starting lineage4microG builds. Usually security patches are merged in the middle of the month.

I'm not convinced that there is any such thing as a ***good*** date. The complete run takes around 16 days to complete (10 days for 20.0 branch, 3 for 19.1 and 3 for 18.1). I quite like that the runs start on the 1st of the month, so we can refer to "the July build run".

> Can you trigger the build with the change of PLATFORM_SECURITY_PATCH

I'm sure it's possible, but I wouldn't want to tie our builds to what may or may not be happening in some external repository.

I don't see any compelling reason to change how we currently do things, but I'm happy to listen if others can put forward such a reason

**Comment by st3rox** [comment]
> > 1st of every month is a bad date for starting lineage4microG builds. Usually security patches are merged in the middle of the month.
> 
> I'm not convinced that there is any such thing as a _**good**_ date. The complete run takes around 16 days to complete (10 days for 20.0 branch, 3 for 19.1 and 3 for 18.1). I quite like that the runs start on the 1st of the month, so we can refer to "the July build run".
> 
> > Can you trigger the build with the change of PLATFORM_SECURITY_PATCH
> 
> I'm sure it's possible, but I wouldn't want to tie our builds to what may or may not be happening in some external repository.
> 
> I don't see any compelling reason to change how we currently do things, but I'm happy to listen if others can put forward such a reason

I agree with keeping 1st of the month start, also since it takes 16 days to build that leaves 14/15 days to fix issues and rerun any failures

**Comment by petefoth** [comment]
Closing for now. Please re-open if new arguments come uo for changing the date

**Comment by ArchangeGabriel** [comment]
Just a note in case it is discussed again in the future: while I would generally agree that building right after the monthly security release bump, unfortunately it has not been consistently early enough in the month to rely on: https://review.lineageos.org/q/subject:security+update

**Comment by petefoth** [comment]
This issue was [raised again in the IodéOS forums](https://community.iode.tech/t/unofficial-builds-for-google-pixel-devices/5233/13)

> Just some thoughts on updates at L4M: As you start the build cycle on the 1st of the month - you will have the security updates from the month before. So if the new updates come out on the 20th. (for a late phone in the build cycle) you will have security updates about 50 days late.
> If you would start the build cycle on, say
> 15th of the month, the LineageOS ASB (security update, see https://archive.ph/divestos.org/pages/patch_history) are usually already merged. So on the 5th of the new month (15 + 20 (days for building) = 35 = 5) the new released update would only be 35 days late - so the security updates would normally come about 15 days earlier.
This suggestion has been made before. For example - see this (closed) issue in one of the L$M project issue trackers:
https://github.com/lineageos4microg/docker-lineage-cicd/issues/448

Earlier comments in this issue still apply, in particular:

> I'm not convinced that there is any such thing as a _**good**_ date. The complete run takes around 16 days to complete (10 days for 20.0 branch, 3 for 19.1 and 3 for 18.1). I quite like that the runs start on the 1st of the month, so we can refer to "the July build run".

and 

> Just a note in case it is discussed again in the future: while I would generally agree that building right after the monthly security release bump, unfortunately it has not been consistently early enough in the month to rely on: https://review.lineageos.org/q/subject:security+update+repo:LineageOS/android

(At the moment, with two build servers, the build run is taking around three weeks rather than 16 days).

My position remains unchanged:

> I don't see any compelling reason to change how we currently do things, but I'm happy to listen if others can put forward such a reason

**Comment by petefoth** [comment]
Another (final?) point: since the restructuring of the build scripts lats September, `repo sync` is now called for each device, so the build will use the most up-to-date source (including the mos recent security patches

**Comment by dktzde** [comment]
@petefoth Thanks for copying my comment.
