### ISSUE TITLE
It is recommended that the LineageOS for microG Bug Reporting community adopt the bug reporting format used by LineageOS issues, as this would make it easier for maintainers and developers to quickly track and subscribe to the Bug list.

### ISSUE THREAD

**Issue by Subtly7360** [lineageos4microg/docker-lineage-cicd#451]
Suggestion: It is recommended that the LineageOS for microG Bug Reporting community adopt the bug reporting format used by LineageOS issues, as this would make it easier for maintainers and developers to quickly track and subscribe to the Bug list.

I suggest that the LineageOS for microG Bug Reporting community could consider adopting the bug reporting model of the LineageOS Bug community, introducing automated robots to review bug reports, which would facilitate maintainers and developers to quickly receive Bug Reports.

**Comment by petefoth** [comment]
Thanks for the suggestion. 

I don't think this project is comparable with LineageOS: they have over 2,500 github repos, and 115 project members[1]. We have 11 repositories, and 5 project members[2], of whom only 2 are currently active in the project.

This project's bug tracking process (people raise GitHub issues, project members deal with them when they have the time) works fine for the project members and - I hope -  for the project users too. We seem to be able to meet our objectives of making and publishing automated builds of lineageos4microg for (most of) the devices officially supported by LineageOS ***without*** the help of automated robots .

Thanks again,

1: Source: https://github.com/LineageOS
2: Source: https://github.com/lineageos4microg
