### ISSUE TITLE
After a fresh installation of the system with LineageOS for microG Rom, upon booting, I can't find any microG gapps components in the system. 

### ISSUE THREAD

**Issue by Subtly7360** [lineageos4microg/docker-lineage-cicd#452]
device lemonade  .

After a fresh installation of LineageOS for microG, the built-in microG GApps are not visible upon system startup.

**Comment by dicer** [comment]
Do you see "MicroG Settings" in the app drawer?

**Comment by Subtly7360** [comment]
> "MicroG Settings"

Can't see "MicroG Settings"

**Comment by dicer** [comment]
Which version did you install? Settings -> About phone -> LineageOS version and Build number

**Comment by Subtly7360** [comment]
> Which version did you install? Settings -> About phone -> LineageOS version and Build number

Android version Android version
13
LineageOS version 
20-20230723-NIGHTLY-lemonade 
Android security update 
July 5,2023
Vendor security patch level 
June 5,2023
Baseband version 
Q_V1_P14
Kernel version
5.4.242-qgki-gafa23b20dc17 #1 Sun Jul 23 06:20:10 UTC 2023 
Build date
Sun Jul 23 04:58:33 UTC 2023 
Build number
lineage_lemonade-userdebug 13 TQ3A.230705.001 f9d6faf0f9

**Comment by Subtly7360** [comment]
> sure you downloaded it from

sure downloaded it from https://download.lineage.microg.org/lemonade/lineage-20.0-20230707-microG-lemonade.zip

**Comment by FintasticMan** [comment]
Well, that's not what the info you sent says. It says you've got [this](https://mirrorbits.lineageos.org/full/lemonade/20230723/lineage-20.0-20230723-nightly-lemonade-signed.zip) installed. Try doing a clean install of lineageos4microg.

**Comment by petefoth** [comment]
> > Which version did you install? Settings -> About phone -> LineageOS version and Build number
> 
> Android version Android version 13 LineageOS version 20-20230723-NIGHTLY-lemonade Android security update July 5,2023 Vendor security patch level June 5,2023 Baseband version Q_V1_P14 Kernel version 5.4.242-qgki-gafa23b20dc17 #1 Sun Jul 23 06:20:10 UTC 2023 Build date Sun Jul 23 04:58:33 UTC 2023 Build number lineage_lemonade-userdebug 13 TQ3A.230705.001 f9d6faf0f9

That's not  lineageos4microg build, it's an official 'plain' LineageOS nightly builg that does not include MicroG.

Closing

**Comment by Subtly7360** [comment]
> Well, that's not what the info you sent says. It says you've got [this](https://mirrorbits.lineageos.org/full/lemonade/20230723/lineage-20.0-20230723-nightly-lemonade-signed.zip) installed. Try doing a clean install of lineageos4microg.

I directly downloaded from https://download.lineage.microg.org/lemonade/lineage-20.0-20230707-microG-lemonade.zip and used this for a clean install. But why can't I see the MicroG Settings after the clean install and system startup?

**Comment by Subtly7360** [comment]
> > > Which version did you install? Settings -> About phone -> LineageOS version and Build number
> > 
> > 
> > Android version Android version 13 LineageOS version 20-20230723-NIGHTLY-lemonade Android security update July 5,2023 Vendor security patch level June 5,2023 Baseband version Q_V1_P14 Kernel version 5.4.242-qgki-gafa23b20dc17 #1 Sun Jul 23 06:20:10 UTC 2023 Build date Sun Jul 23 04:58:33 UTC 2023 Build number lineage_lemonade-userdebug 13 TQ3A.230705.001 f9d6faf0f9
> 
> That's not lineageos4microg build, it's an official 'plain' LineageOS nightly builg that does not include MicroG.
> 
> Closing

I directly downloaded from https://download.lineage.microg.org/lemonade/lineage-20.0-20230707-microG-lemonade.zip and used this for a clean install. But why can't I see the MicroG Settings after the clean install and system startup?
