### ISSUE TITLE
After a clean install of the system with LineageOS for microG Rom, upon booting, I can't find any microG gapps components in the system. 

### ISSUE THREAD

**Issue by Subtly7360** [lineageos4microg/docker-lineage-cicd#453]
I directly downloaded from https://download.lineage.microg.org/lemonade/lineage-20.0-20230707-microG-lemonade.zip and used this for a clean install. But why can't I see the MicroG Settings after the clean install and system startup?

Here are the steps for my clean install：

reset(Erase all data).

device is in fastboot mode.

C:\Users\Qoerak\Downloads\adb>fastboot flash dtbo dtbo.img
Sending 'dtbo' (24576 KB) OKAY [ 0.571s]
Writing 'dtbo' OKAY [ 0.069s]
Finished. Total time: 0.655s

C:\Users\Qoerak\Downloads\adb>fastboot flash vendor_boot vendor_boot.img
Sending 'vendor_boot' (196608 KB) OKAY [ 4.502s]
Writing 'vendor_boot' OKAY [ 0.486s]
Finished. Total time: 5.029s

With the device powered off, hold Volume Up + Volume Down + Power (reboot bootloader).

C:\Users\Qoerak\Downloads\adb>fastboot flash boot boot.img
Sending 'boot_b' (196608 KB) OKAY [ 4.492s]
Writing 'boot_b' OKAY [ 0.424s]
Finished. Total time: 4.982s

Use the menu to navigate to and to select the Recovery option.Factory Reset, then Format data / factory reset,Return to the main menu.

On the device, select “Apply Update”, then “Apply from ADB” to begin sideload.

C:\Users\Qoerak\Downloads\adb>adb sideload lineage-20.0-20230707-microG-lemonade.zip

    daemon not running; starting now at tcp:5037
    daemon started successfully
    Total xfer: 1.00x

Reboot system now

Android version Android version
13
LineageOS version
20-20230723-NIGHTLY-lemonade
Android security update
July 5,2023
Vendor security patch level
June 5,2023
Baseband version
Q_V1_P14
Kernel version
5.4.242-qgki-gafa23b20dc17 
#1 Sun Jul 23 06:20:10 UTC 2023
Build date
Sun Jul 23 04:58:33 UTC 2023
Build number
lineage_lemonade-userdebug 13 TQ3A.230705.001 f9d6faf0f9

**Comment by dicer** [comment]
No need to open new issues. You could have used the old one.

Your process actually looks ok. The phone seems to have an a/b partition scheme, which means you can have 2 systems installed at the same time. The fastboot flash of boot seems to install to boot_b. 

Not sure where the recovery installed the system to. Probably system_a though, as the recovery always installs to the *non-active* partition and then switches the active partition to that new partition on reboot.
You can probably see the active partition scheme displayed in the bootloader btw.

I would first install via recovery, reboot to bootloader from there (which activates the newly installed system/partition scheme) and flash the boot partition. That should install both in the same partition scheme.
If this seems to be too complicated, just do your process twice which should install microg in boot_a *and* boot_b as well as system_a und system_b

Still not really sure why you would end up with plain Lineage though. Did you try to install that before?
Could you also please give us the md5sum of that zip file you are flashing? I think you should be able to use this command on windows:
`certutil -hashfile lineage-20.0-20230707-microG-lemonade.zip MD5`

**Comment by Subtly7360** [comment]
> No need to open new issues. You could have used the old one.
> 
> Your process actually looks ok. The phone seems to have an a/b partition scheme, which means you can have 2 systems installed at the same time. The fastboot flash of boot seems to install to boot_b.
> 
> Not sure where the recovery installed the system to. Probably system_a though, as the recovery always installs to the _non-active_ partition and then switches the active partition to that new partition on reboot. You can probably see the active partition scheme displayed in the bootloader btw.
> 
> I would first install via recovery, reboot to bootloader from there (which activates the newly installed system/partition scheme) and flash the boot partition. That should install both in the same partition scheme. If this seems to be too complicated, just do your process twice which should install microg in boot_a _and_ boot_b as well as system_a und system_b
> 
> Still not really sure why you would end up with plain Lineage though. Did you try to install that before? Could you also please give us the md5sum of that zip file you are flashing? I think you should be able to use this command on windows: `certutil -hashfile lineage-20.0-20230707-microG-lemonade.zip MD5`

Previous issues have been closed and can't be reopened. I also replied to the previous issues, but I thought that closed ones wouldn't receive new replies, so I opened new issues.


I used to use OxygenOS, then I did a fresh install of DivestOS, and then a fresh install of LineageOS. After using it, I found that without flashing Google Apps, many apps and services couldn't be used, and that's when I stumbled upon LineageOS for microG. I then installed LineageOS for microG again using the Clean install (wipe data and installed apps) method.

C:\Users\Qoerak\Downloads\adb>certutil -hashfile lineage-20.0-20230707-microG-lemonade.zip MD5
MD5 hash of lineage-20.0-20230707-microG-lemonade.zip:
2e6a1ec6dbf8b38ea29066ad00bd6493
CertUtil: -hashfile command completed successfully.

**Comment by dicer** [comment]
md5sum matches my fresh download. So that does not seem to be the problem.
Can you please try and flash again with the method I outlines above (first the zip via sideload from recovery, then the boot from fastboot)?

**Comment by Subtly7360** [comment]
> md5sum matches my fresh download. So that does not seem to be the problem. Can you please try and flash again with the method I outlines above (first the zip via sideload from recovery, then the boot from fastboot)?

first the zip via sideload from recovery, then the boot from fastboot.

Microsoft Windows [Version 10.0.19045.3208]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Qoerak\Downloads\adb>adb sideload lineage-20.0-20230707-microG-lemonade.zip
Total xfer: 1.00x


Still not working, still can't see "MicroG Settings" after starting the system

**Comment by Subtly7360** [comment]
> Maybe the flash is failing for some reason? Could you look through the log that is produced by the sideload install? If possible please download the log from the recovery and post it here

how to download the log from the recovery?
how to download recovery logs?

**Comment by dicer** [comment]
Yes, that recovery.log, but it does not show a successful or failed sideload. You need to sideload the image and then (without rebooting!) download the log

**Comment by Subtly7360** [comment]
> Yes, that recovery.log, but it does not show a successful or failed sideload. You need to sideload the image and then (without rebooting!) download the log

The recovery.log has been attached to the above reply , How do I need to resolve this Issues?

**Comment by Subtly7360** [comment]
> Yes, that recovery.log, but it does not show a successful or failed sideload. You need to sideload the image and then (without rebooting!) download the log
[recovery.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/12189205/recovery.log)

**Comment by dicer** [comment]
```
[  192.087946] ERROR:   recovery: failed to verify whole-file signature
[  192.176085] Update package verification took 76.7 s (result 1).
[  192.275145] ERROR:   recovery: Signature verification failed
[  192.374231] ERROR:   recovery: error: 21
[  200.831342] Installing update...
[  200.947105] ERROR:   recovery: Current SPL: 2023-07-05 Target SPL: 2023-06-05 this is considered a downgrade
[  201.062547] ERROR:   recovery: Denying OTA because it's SPL downgrade
.....
[  201.353404] I:/sideload/package.zip
[  201.353406] 0
[  201.353408] time_total: 86
[  201.353410] retry: 0
[  201.353411] error: 21
```
Seems like the zip did not install at all because the SPL version already on the phone is higher than the one that comes with the microg zip.
I unfortunately don't know how to solve this.
Any ideas @petefoth ? Or is this error a known error?

**Comment by petefoth** [comment]
> Could the build upload those extracted files, so people don't have to do it themselves?

What files / images are produced by the build for specific devices is determined by the source files and makefiles which, for us, come from the LineageOS repos. Recent LineageOS builds are now producing these `.img` files. Our latest build does not, presumably because the changes in the LineageOS repos were made ***after*** we synched those repos for the July build run (on 1st July). 

I would guess / hope that our next build run ***will*** pick up those changes and should therefore produce the relevant`.img` files. Let's wait and see. In the mean time, you can try using the LOS provided images.

On a general point, this project is about ***building*** los4microg ROMs for supported devices, and **_making those ROMs available_** for download, and for OTA update over existing ***los4microg*** installations. Issues with and guidance on any other issues are outside our scope and expertise. In particular, we are not in a position to help with
1. Installation instructions for specific devices. In general, that information comes from the Device pages of LOS Wiki. Occasionally - as seems to have happened in this case - our builds seem to have fallen slightly behind the LOS builds and documentation. As mentioned above, we should  catch up eventually
2. Information about, and issues with, installing **_los4microg  ROMs_** over existing **_LOS_** installations. That ***may*** work but is not something over which we have any control, and is a not a use case we are in a position to support. 
3. Information about **_functionality_** of the los4microg ROMs. 
 
Guidance about 2 . and 3.  ***may*** be available on the ['LineageOS for microG' XDA forum thread](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/), from device-specific XDA forum threads, or an various reddit pages / threads / forums / whatever.

Sorry I can't be more helpful, but the process of making and releasing the builds and keeping that process ticking over uses up most of the time project members have available for work on the project.

**Comment by Subtly7360** [comment]
> > Could the build upload those extracted files, so people don't have to do it themselves?
> 
> What files / images are produced by the build for specific devices is determined by the source files and makefiles which, for us, come from the LineageOS repos. Recent LineageOS builds are now producing these `.img` files. Our latest build does not, presumably because the changes in the LineageOS repos were made _**after**_ we synched those repos for the July build run (on 1st July).
> 
> I would guess / hope that our next build run _**will**_ pick up those changes and should therefore produce the relevant`.img` files. Let's wait and see. In the mean time, you can try using the LOS provided images.
> 
> On a general point, this project is about _**building**_ los4microg ROMs for supported devices, and **_making those ROMs available_** for download, and for OTA update over existing _**los4microg**_ installations. Issues with and guidance on any other issues are outside our scope and expertise. In particular, we are not in a position to help with
> 
>     1. Installation instructions for specific devices. In general, that information comes from the Device pages of LOS Wiki. Occasionally - as seems to have happened in this case - our builds seem to have fallen slightly behind the LOS builds and documentation. As mentioned above, we should  catch up eventually
> 
>     2. Information about, and issues with, installing **_los4microg  ROMs_** over existing **_LOS_** installations. That _**may**_ work but is not something over which we have any control, and is a not a use case we are in a position to support.
> 
>     3. Information about **_functionality_** of the los4microg ROMs.
> 
> 
> Guidance about 2 . and 3. _**may**_ be available on the ['LineageOS for microG' XDA forum thread](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/), from device-specific XDA forum threads, or an various reddit pages / threads / forums / whatever.
> 
> Sorry I can't be more helpful, but the process of making and releasing the builds and keeping that process ticking over uses up most of the time project members have available for work on the project.

Please keep LineageOS for microG updated to the latest version of LineageOS in real time.
Please keep LineageOS is latest version .

**Comment by Subtly7360** [comment]
> ```
> [  192.087946] ERROR:   recovery: failed to verify whole-file signature
> [  192.176085] Update package verification took 76.7 s (result 1).
> [  192.275145] ERROR:   recovery: Signature verification failed
> [  192.374231] ERROR:   recovery: error: 21
> [  200.831342] Installing update...
> [  200.947105] ERROR:   recovery: Current SPL: 2023-07-05 Target SPL: 2023-06-05 this is considered a downgrade
> [  201.062547] ERROR:   recovery: Denying OTA because it's SPL downgrade
> .....
> [  201.353404] I:/sideload/package.zip
> [  201.353406] 0
> [  201.353408] time_total: 86
> [  201.353410] retry: 0
> [  201.353411] error: 21
> ```
> 
> Seems like the zip did not install at all because the SPL version already on the phone is higher than the one that comes with the microg zip (probably because of the prior ROMs you installed).
> 
> Seems someone else had the same problem with the same phone and solved it: https://forum.xda-developers.com/t/denying-ota-because-it-is-a-spl-downgrade.4463975/ Also see: https://www.reddit.com/r/MicroG/comments/vxkblq/getting_the_error_message_denying_ota_because_its/
> 
> You need to get the proper files from the zip and flash them first. I used this repo before to do that (python3 extract_android_ota_payload.py lineage-20.0-20230707-microG-lemonade.zip): https://github.com/cyxx/extract_android_ota_payload/ Or this one seems to work as well: https://github.com/vm03/payload_dumper Then follow the steps in the reddit comment.
> 
> @petefoth Could the build upload those extracted files, so people don't have to do it themselves?

thanks you.

**Comment by petefoth** [comment]
> Please keep LineageOS for microG updated to the latest version of LineageOS in real time.

That is not possible for us. We build monthly. The build run for all devices takes 16 days. We have neityer the time nor the resources to make builds more often than that, even if we wanted to

**Comment by Subtly7360** [comment]
> That is not possible for us. We build monthly. The build run for all devices takes 16 days. We have neityer the time nor the resources to make builds more often than that, even if we wanted to

Can't it be automated?

**Comment by petefoth** [comment]
It **_is_** automated - it runs once a month, automatically, but problems occur and have to be cleared up. And we are not going to run cpu-intensive jobs on our server non-stop. 

I'm going to stop responding to this issue now as there is no more to be said :)

**Comment by Subtly7360** [comment]
> It **_is_** automated - it runs once a month, automatically, but problems occur and have to be cleared up. And we are not going to run cpu-intensive jobs on our server non-stop.
> 
> I'm going to stop responding to this issue now as there is no more to be said :)

So why does LineageOS have frequent updates? LineageOS is updated at least twice within a month
