### ISSUE TITLE
RSS feed showing build status

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#455]
_Originally posted by @D3SOX in https://github.com/lineageos4microg/docker-lineage-cicd/issues/383#issuecomment-1450092098_

Thanks for your efforts. Now I need something that only notifies me when it's about one of my devices and I would prefer if that works via RSS because I don't receive notifications from Element.

**Comment by petefoth** [comment]
This is a 'nice to have' feature, bit it's not essential, especially now we report build status on the Matrix channel. I'm going to leave it open, with the label 'Fix sometime': if anyone knows how to do this easily, we would be happy to try and put it in place

**Comment by LuccoJ** [comment]
It's no RSS, but for the record, I took advantage of the bridge mess between Matrix and Libera to set up a private bridge for that room to Libera, so now you can also follow builds on #microg-builds on Libera.chat.

If it's easier for anyone to set up an RSS feed based on the IRC channel than the Matrix room, go right ahead.

**Comment by petefoth** [comment]
> Now I need something that only notifies me when it's about one of my devices and I would prefer if that works via RSS because I don't receive notifications from Element.

You can configure Element to notify when messages are posted containing a keyword. I use the word 'failed' so I get a notification if any builds fail. If you use your device name as a keyword, you will be notified when your device is built (or if the build fails)

Closing this issue because I won't be adding an RSS feed
