### ISSUE TITLE
Low disk space on download server

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#457]
Many of the problems with the July build run (see #438 ) were caused because of low disk space on the download server, which meant that builds for some devices were successful, but were not uploaded.

**Comment by petefoth** [comment]
The problem has now been resolved, and 50GB of free disk space is now available. 
```
Filesystem      Size  Used Avail Use% Mounted on
...
/dev/vdb1       590G  540G   21G  97% /mnt/archive
```

**Comment by petefoth** [comment]
Some more information on the cause and on the fix.

The cause:
- Although we try to keep only the three most recent builds (on both the build & download servers), by setting `-e "DELETE_OLD_ZIPS=3" \` in the build command, for some devices, there were more than three, in some cases significantly more. At somewhere between 500 & 800GB per excess build, they were gobbling up a lot of disk space on both servers. When I looked at the download server on Saturday 29th July, there was only 67**MB** free disk space on `mnt/archive`
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.9G     0  7.9G   0% /dev
tmpfs           1.6G  588K  1.6G   1% /run
/dev/vda1        50G  9.2G   38G  20% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/vdb1       590G  560G   67M 100% /mnt/archive
tmpfs           1.6G     0  1.6G   0% /run/user/1337
```
The fix:
- for each directory with more than three builds present on the build server
  - start a docker session with write access to persistent storage
  - delete the excess builds
  - `rsync` the `zips/<device-name>` directory to the download server

The result:
- there is now more than 50GB free disk space on the download server
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.9G     0  7.9G   0% /dev
tmpfs           1.6G  588K  1.6G   1% /run
/dev/vda1        50G  9.3G   38G  20% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/vdb1       590G  508G   52G  91% /mnt/archive
tmpfs           1.6G     0  1.6G   0% /run/user/1337
```

**Comment by Skirmisher** [comment]
Just wanted to say cheers for the informative status updates, they're much appreciated :)
