### ISSUE TITLE
 Suggestion: continue to provide new builds for discontinued devices when a new version of microG comes out.

### ISSUE THREAD

**Issue by tuxayo** [lineageos4microg/docker-lineage-cicd#46]
Hi,

To avoid having an old version during months before noticing it and having to search how to upgrade. Related: microg/android_packages_apps_GmsCore#904

**Comment by tuxayo** [comment]
I fear that a large number of LineageOS for microG 14.1 installations don't have an up to date microG

**Comment by corna** [comment]
As already explained in microg/android_packages_apps_GmsCore#904, we bundle the official GmsCore signed with the official keys, so you can update GmsCore directly from FDroid, even if we don't build for your device anymore.
