### ISSUE TITLE
Oneplus 8T (kebab) wasn't built

### ISSUE THREAD

**Issue by LuccoJ** [lineageos4microg/docker-lineage-cicd#463]
According to the build logs provided at [#microg-lineage-os-builds:matrix.domainepublic.net](https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net),

```
Completed build for h990
Starting build for kirin
Completed build for kirin
Starting build for liber
```

So far, they have been invariably built in alphabetical order (except 19.1 and 18.1 devices which are built later, but this is a 20 device), so even though this is pretty recent, I feel reasonably confident to point out it was skipped. As to why, I have no idea: it's definitely still a supported device [by official LOS](https://download.lineageos.org/devices/kebab/builds).

**Comment by petefoth** [comment]
For a number of reasons this month's build run is making the builds in the following order
- 19.1 devices
- 18.1 devices
- 20.0 devices

The devices you list are all 19.1 devices that have built successfully. As yours is a 20.0 device the build should be availbe later in the month.


The list of build target devices, showing which branch they belong to is [here](https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets)
I'll close this issue. Feel free to reopen, or to raise another if no build for your device is available once the full build run is completed - probably around 16th or 17th August

**Comment by henrypp** [comment]
@petefoth hi, whats going on? 21 builds for 8, 8 pro, 8t and 9 etc are not available, u changed build date for this devices or what?

**Comment by petefoth** [comment]
> @petefoth hi, whats going on? 21 builds for 8, 8 pro, 8t and 9 etc are not available, u changed build date for this devices or what?

See https://github.com/lineageos4microg/docker-lineage-cicd/issues/578#issuecomment-1988259359

**Comment by henrypp** [comment]
@petefoth thx

**Comment by henrypp** [comment]
@petefoth anyway, on native LOS already have [signature spoofing (for MicroG)](https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/383573), just install microg services and thats ALL, so...

**Comment by LuccoJ** [comment]
@henrypp okay, so what's your point? Go install that, if you can't wait for the limited resources of this project. This is a closed issue about something unrelated to the current situation; do you really have to point out that after years of scorning microG, now LineageOS doesn't anymore, here on the place where people have been working hard for years to *make* LineageOS work with microG?!

**Comment by petefoth** [comment]
> @petefoth anyway, on native LOS 14 already have [signature spoofing (for MicroG)](https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/383573), just [install microg services](https://microg.org/download.html), configure it in self-check and thats ALL, so...

See [this post in our XDA Forms thread](https://xdaforums.com/t/lineageos-for-microg.3700997/post-89373840)
