### ISSUE TITLE
August build seemingly stopped

### ISSUE THREAD

**Issue by svalo** [lineageos4microg/docker-lineage-cicd#464]
[It seems that august builds stopped](https://download.lineage.microg.org/?sort=time&order=desc) at `natrium`, `parker` started but never finished according to the build notification channel. These are still build for LineageOS 19.1, builds for LineageOS 20.0 never started.

Is there an issue with the build server?

**Comment by svalo** [comment]
@petefoth (and @bananer ) I have experience with docker and was self-building lineage4microg, if it can be useful I'm available to help understand issues with build system during a shared screen call

**Comment by petefoth** [comment]
> @petefoth (and @bananer ) I have experience with docker and was self-building lineage4microg, if it can be useful I'm available to help understand issues with build system during a shared screen call

Thanks @svalo 
Sorry, I've only just spotted this post. I was able to complete the build run with not problems. No idea what caused the the docker image to die, but I'll write it off as 'just one of those things` unless it happens again :)
