### ISSUE TITLE
openjdk-7-jdk has no installation candidate

### ISSUE THREAD

**Issue by mdhooge** [lineageos4microg/docker-lineage-cicd#47]
Hello,
I tried to build the docker image and it couldn't find the openjdk-7-jdk package. It is indeed not available after Jessie, according to https://packages.debian.org/.

Note : it was introduced by 324a10e762accd8a7b0af8cf69404d41c41bc089.

I'm trying to build without it…
M.

**Comment by fgerling** [comment]
Did you manage to build successfully?

Removing `openjdk-7-jdk` worked for me:
```
BRANCH_NAME=lineage-16.0
DEVICE_LIST=enchilada
```

**Comment by corna** [comment]
Yes, it was available in the `experimental` repo but it has been removed.
openjdk-7 was needed for LineageOS/Cyanogenmod 11.0-13.0, I think it is time to drop support for them.

**Comment by mdhooge** [comment]
Sorry, vacation time...

So, `repo` finished to download everything only yesterday -- this is so huge! :astonished:

And then it failed to build for my bullhead nexus. I quickly looked into the logs but found nothing. I'll dig deeper ASAP.

M.

**Comment by mdhooge** [comment]
The `build.sh` script has the following code:

```
    if [ "$android_version_major" -ge "7" ]; then
      jdk_version=8
    elif [ "$android_version_major" -ge "5" ]; then
      jdk_version=7
    else
      echo ">> [$(date)] ERROR: $branch requires a JDK version too old (< 7); aborting"
      exit 1
    fi
```

So, yes, maybe, this could be dropped.

**Comment by fgerling** [comment]
I can't find any build with a version less than `14.1` (android 7 Nougat) on [download.lineageos.org](https://download.lineageos.org). So dropping jdk_7 should be okay.
Is there any ressources about what android versions lineage os is supporting?

**Comment by corna** [comment]
IIRC LineageOS currently supports (officially at least) 15.1 and 16.0.
I tried to keep support for old versions because people may use this project to build old or unsupported versions of LineageOS, but LineageOS/Cyanogenmod <= 13.0 is becoming really ancient now (and OpenJDK 7 is near EOL anyways).
Try with [this](https://cloud.docker.com/repository/docker/corna/docker-lineage-cicd) image and let me know if it works.

**Comment by fgerling** [comment]
The failed build from @mdhooge could be anything. If he kept the build logs, we could look into it. I suspect that it is not related to jdk_7. 

I have a `docker-compose.yml` that was building `docker-lineage-cicd` and then lineage os.
I'm starting a run with `corna/docker-lineage-cicd` to see if I get similar (successful) results.

**Comment by mdhooge** [comment]
Yes, not related at all: I just keep running out of disk space!

(in the first place, I wanted to test/address that bug: https://www.reddit.com/r/LineageOS/comments/a7gtck/privacy_guard/ :sob: — I need to find an additional disk :pensive:)

**Comment by fgerling** [comment]
@corna My enchilada (oneplus 6) build successfully with [orna/docker-lineage-cicd](https://cloud.docker.com/repository/docker/corna/docker-lineage-cicd) :)
```
Package Complete: /srv/src/LINEAGE_16_0/out/target/product/enchilada/lineage-16.0-20190821-aeglos-enchilada.zip

#### build completed successfully (01:41:56 (hh:mm:ss)) ####
```

**Comment by fgerling** [comment]
> Yes, not related at all: I just keep running out of disk space!

Have you dissable `ccache`? That may help.

**Comment by corna** [comment]
Pushed to lineageos4microg/docker-lineage-cicd, thanks for the feedback.

@mdhooge 
> Yes, not related at all: I just keep running out of disk space!

I let you imagine the amount of space we need to build for every LineageOS-supported device ;)
