### ISSUE TITLE
oriole 20230812 build installation always aborts

### ISSUE THREAD

**Issue by watchingvideos845** [lineageos4microg/docker-lineage-cicd#470]
Did these steps when installing.

```
1. fastboot flash boot boot.img
2. fastboot flash dtbo dtbo.img
3. fastboot flash vendor_boot vendor_boot.img
4. adb sideload lineage-20.0-20230812-microG-oriole.zip
```

But received this error.

```
Error applying update: 7 (ErrorCode::kInstallDeviceOpenError)
ERROR: recovery: Error in /sideload/package.zip (status 1)
Installation aborted with status 1
Installation aborted
```

Is the build broken? 
Or did I make a mistake somewhere?

**Comment by dicer** [comment]
Could you please get the log from the recovery itself? I'm assuming the 
error is from your machine right?

And where did you get the .img files from? Try extracting them from the 
zip if you didn't do that already.

**Comment by watchingvideos845** [comment]
While the status said the installation aborted, it actually installs successfully so not sure what's wrong.
