### ISSUE TITLE
The Future of F-Droid Privileged Extensions

### ISSUE THREAD

**Issue by kwsuperman** [lineageos4microg/docker-lineage-cicd#472]
Based on changelog F-Droid client (1.17.0)

* _Unattended upgrades without privileged extensions (F-Droid Basic only for now)._

Does that mean F-Droid Privileged Extensions are unnecessary and won't be included in future builds?

**Comment by TheLastProject** [comment]
Hi, F-Droid contributor here (not LineageOS 4 microG) contributor:

> Does that mean F-Droid Privileged Extensions are unnecessary

No, not yet. As stated, it is currently only available in F-Droid **basic**, not regular F-Droid.

Also, Google adds many additional restrictions (apps need to have a certain targetSdk, F-Droid can only silently update after having installed the app with confirmation once, if another app updates the app, F-Droid needs permission again), so the experience may always stay less nice than the Privileged Extension experience is.

What the LineageOS 4 microG team will do with this info, I don't know :)

**Comment by petefoth** [comment]
> Based on changelog F-Droid client (1.17.0)
> 
>     * _Unattended upgrades without privileged extensions (F-Droid Basic only for now)._
> 
> 
> Does that mean F-Droid Privileged Extensions are unnecessary and won't be included in future builds?

@kwsuperman thanks for spotting this and raising the issue

> No, not yet. As stated, it is currently only available in F-Droid **basic**, not regular F-Droid.

@TheLastProject thanks for the response

> What the LineageOS 4 microG team will do with this info, I don't know :)

I think we'll close this issue. There's nothing we need to do for now and we will continue to include the Privileged Extension in our ROM to allow for unattended upgrades. If things change in the future, we will deal with it then.

Thanks again
