### ISSUE TITLE
August builds are heavily outdated?

### ISSUE THREAD

**Issue by xs1vr** [lineageos4microg/docker-lineage-cicd#473]
My first time installing los4microg so sorry in advance but: I installed August 14th build on my device (surya) and apparently the LOS source is older than the previous 2 or 3 versions (nigthlies*) of the source (noticed immediately by verifying notification and ringtone are still together and security patch is still July even though builts happened hours after August sp merge)

**Comment by st3rox** [comment]
The builds are bases on what the lineageos code was at end of month, since the build cycle starts the first of the month
So yes surya will build with 2 week+ old code

**Comment by petefoth** [comment]
This project only has the resources run builds monthly. Are builds will therefore ***always*** be up to a month behind that latest LOS nightly build. This isn't going to change :)

Closing this issue

**Comment by xs1vr** [comment]
> The builds are based on what the lineageos code was at end of month, since the build cycle starts the first of the month So yes surya will build with 2 week+ old code

So, that's 2 week+ old kernel too or just the source? @st3rox sry idk if you receive notifications without the tag

**Comment by st3rox** [comment]
> 
> So, that's 2 week+ old kernel too or just the source? @st3rox sry idk if you receive notifications without the tag

Yes that includes the kernel

**Comment by LuccoJ** [comment]
What's the point of building the LOS 20 builds around the middle of the month if they're built with source from the start of the mouth? I thought I'd understood (admittedly from rumors and places I don't remember) that it was meant to make it more likely to catch the month's security updates.

**Comment by st3rox** [comment]
> What's the point of building the LOS 20 builds around the middle of the month if they're built with source from the start of the mouth? I thought I'd understood (admittedly from rumors and places I don't remember) that it was meant to make it more likely to catch the month's security updates.

AFAIK LOS 20 builds right away on the first
My phone (enchilada) builds around the 4th typically
My testing phone (shamu, 18.1) builds around the 19th
I'm trying to learn more about the build process so I can contribute in the future so I've started building 18.1 for shamu
Maybe you should give it a shot ;)

**Comment by petefoth** [comment]
> What's the point of building the LOS 20 builds around the middle of the month if they're built with source from the start of the mouth?

The builds ***start*** on the first of the month. We build for all the devices listed [here](https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets) - something over 200 devices - usually in the order listed. At roughly 2hrs per build, the complete build run usually take until roughly the middle of the month.

**Comment by LuccoJ** [comment]
Uh, last time this just wasn't the case, and 19.1 builds happened before 20 builds.

**Comment by petefoth** [comment]
> Uh, last time this just wasn't the case, and 19.1 builds happened before 20 builds.

That's why I said "***usually*** in the order listed" :)
