### ISSUE TITLE
My installation is broken

### ISSUE THREAD

**Issue by D3SOX** [lineageos4microg/docker-lineage-cicd#475]
**Device Info**

model: kebab
currently installed version: 20-20230606-microG-kebab

---

My installation is somewhat broken, and I don't know what I did wrong or how to fix it. The first thing I noticed is that strings are completely switched up (see screenshot 1) and everything that has to do with the setting app is cursed.
The popups overlap like on screenshot 2
It crashes the settings app when normally the adb confirmation popup would come up so I can't use ADB from the booted system right now. Wireless ADB settings page instantly crashes.

And I tried to fix it, but didn't succeed. I'm still stuck on the same buggy version.

I first tried it like every time with the updater where it always worked in the past.
But now I think the updater app is incompatible or something like that.
Because when I try to update the install fails. Can I provide some logs here?
I read something here on GitHub if I remember correctly. Can I just install the new Updater and update then?

Another thing I tried is
1. installing latest vendor files
2. installing latest lineageformicrog recovery and dtbo
3. Sideloading latest zip

But I still ended up on the old version which seems very weird to me.

<details><summary>Screenshot 1</summary>
<p>

![Screenshot_20230822-185316_Select log buffers to store persistently on device](https://github.com/lineageos4microg/docker-lineage-cicd/assets/24937357/62ecf407-4ad7-4c29-a630-a11feb583e4f)

</p>
</details> 

<details><summary>Screenshot 2</summary>
<p>

![Screenshot_20230822-151119_Select log buffers to store persistently on device](https://github.com/lineageos4microg/docker-lineage-cicd/assets/24937357/821b1d20-b5a2-44ed-8fe2-41355e10e2e7)

</p>
</details> 

<details><summary>Screenshot 3</summary>
<p>

![Screenshot_20230822-185345_Select log buffers to store persistently on device](https://github.com/lineageos4microg/docker-lineage-cicd/assets/24937357/faf51226-eb8c-4c1a-9a2b-c4ada96ffd81)

</p>
</details> 

Thanks for any help!
If you need any more information, please contact me.

**Comment by D3SOX** [comment]
Yeah that what I've guessed that I need to do a full reinstall

**Comment by petefoth** [comment]
Before you do, it might be worth trying a backup using  [Android Backup and Restore Tools project](https://forum.xda-developers.com/t/tools-zips-scripts-android-backup-and-restore-tools-multiple-devices-platforms.4016617/). See [this post](https://community.e.foundation/t/how-to-do-a-nandroid-backup-without-twrp/47519/8) for guidance on how to use the tool

**Comment by D3SOX** [comment]
@petefoth Do you know if the `backup_apps.sh` also backups apps permissions and other data like Swift Backup does?
![image](https://github.com/lineageos4microg/docker-lineage-cicd/assets/24937357/6b36b3d8-6022-4ea1-bd84-82931b2d7f48)

**Comment by petefoth** [comment]
Sorry I don't know. I use it when migrating between devices and / or different ROMs or ROM versions. Most apps work fine after restore, but some need permission changes,and a few need all data cleared. But it's the best solution I've come across for non-rooted phones (though you need to enable rooted debugging in Developer options)

**Comment by D3SOX** [comment]
Ok I'm doing my old trusted routine for Android backups which consists of
- Use Swift Backup to backup everything it can do
- Save important internal storage folders (`Documents`, `Download`, `Pictures`, `DCIM`, `Music`, `Snapchat`, `Telegram`, `Aegis`, ...)
- Signal backup (because it doesn't work with any other backup method I think)
- Lawnchair homescreen backup

**Comment by D3SOX** [comment]
Successfully reinstalled!
