### ISSUE TITLE
Safetynet-fix integration

### ISSUE THREAD

**Issue by Iey4iej3** [lineageos4microg/docker-lineage-cicd#476]
It is suggested in https://github.com/Displax/safetynet-fix#rom-integration to have a ROM integration for Safetynet-fix. It might be an idea to integrate it into LineageOS for MicroG.

**Comment by D3SOX** [comment]
I currently don't get SafetyNet on my OnePlus 8T with LOS4Microg. I used to pass the test, but someday it changed.
I'm using the Magisk module from Displax + the old MagiskHideProps set to the fingerprint of my device. This used to work for me


<details><summary> but now my result looks like this</summary>
<p>

![Screenshot_20230827-200533_Simple Play Integrity Checker](https://github.com/lineageos4microg/docker-lineage-cicd/assets/24937357/31e3ecfa-5e78-44f7-b81b-4bdd584c3c7d)


</p>
</details> 



But I think nowadays, apps tend to use the Play Integrity API anyways, and I don't think there's a way to pass that without Play Services.

**Comment by Iey4iej3** [comment]
Not sure whether https://github.com/Displax/safetynet-fix/issues/28 is related. It works on my Xiaomi 11 Lite 5G NE (lisa), with [safetynet-fix-v2.4.0-MOD_1.3-microG.zip](https://github.com/Displax/safetynet-fix/releases/download/v2.4.0-MOD_1.3/safetynet-fix-v2.4.0-MOD_1.3-microG.zip).

**Comment by D3SOX** [comment]
Thank you! Using 1.3-microG version fixed it for me!

**Comment by petefoth** [comment]
I don't see any good arguments for trying to do this, or any suggestion as to ***how*** we might integrate this.

I'll leave the issue open for now i case anyone has anything further to add.

**Comment by petefoth** [comment]
Closing
