### ISSUE TITLE
Missing davinci build

### ISSUE THREAD

**Issue by In-line** [lineageos4microg/docker-lineage-cicd#477]
Hi, Lineage OS officially supports davinci. Can you please add it to build bot?

Blank page: https://download.lineage.microg.org/davinci/
Not blank page: https://download.lineageos.org/devices/davinci/builds

**Comment by FintasticMan** [comment]
L4M automatically uses the build targets from LOS, so once the next build round starts it will be included.

**Comment by petefoth** [comment]
> Where we can see the schedule for build round?

See this cmmment
https://github.com/lineageos4microg/docker-lineage-cicd/issues/473#issuecomment-1694346129
