### ISSUE TITLE
MicroG version outdated

### ISSUE THREAD

**Issue by jeroen7s** [lineageos4microg/docker-lineage-cicd#48]
Seems like MicroG version isn't updated on my phone
Using Oneplus3T with the latest L4M
v0.2.8.17785 was released about a month ago, however after 4 weeks of updates it's still on v0.2.8.17455 on LineageOS4MicroG

**Comment by fgerling** [comment]
I think this issue is related to this one: https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/issues/18

Close as duplicate?

**Comment by jeroen7s** [comment]
Yeah seems like it
Not sure which repository is relevant to fix it tho. But since most conversations is in the other ticket I will close it for now
