### ISSUE TITLE
oneplus/instantnoodlep builds don't seem to feature all the correct additional partitions

### ISSUE THREAD

**Issue by RainShinotsu** [lineageos4microg/docker-lineage-cicd#480]
Accoring to the [LineageOS install instructions for instantnoodlep](https://wiki.lineageos.org/devices/instantnoodlep/install), before flashing recovery, the user needs to [flash `dtbo.img` and `vbmeta.img`](https://wiki.lineageos.org/devices/instantnoodlep/install#flashing-additional-partitions). However, the [LineageOS for microG builds](https://download.lineage.microg.org/instantnoodlep/) as of 2023-09-08 (last build 2023-08-04/2023-08-09) include `dtbo.img` and `boot.img`, meaning `vbmeta` is missing. Is that intentional?

At first glance, it seems like LOS4mG installs just fine even skipping `vbmeta`, but I'm concerned that something might indeed be wrong, and I just haven't encountered it yet. I think it'd be good to build the correct additional partitions when the next build wave happens, or at least explain why flash `dtbo` and `boot` instead of `dtbo` and `vbmeta`.

**Comment by st3rox** [comment]
This is likely to be addressed as #474 progresses

**Comment by petefoth** [comment]
All of the partitions ***are*** present in the full ROM `.zip` file.

The September builds are (should be) also delivering the needed `.img` files separately.

Once this issue is fixed / implemented, then the `.img` files will be included in - and can be extracted from - the `img.zip` file that will be created and published

**Comment by petefoth** [comment]
After this month's build, the required images are present in https://download.lineage.microg.org/instantnoodlep/
