### ISSUE TITLE
Latest OnePlus 6 build round shows 28 MB image download

### ISSUE THREAD

**Issue by Forage** [lineageos4microg/docker-lineage-cicd#488]
There's a wrong image that snuck in apparently:

![Screenshot_20231005-142223_Updater](https://github.com/lineageos4microg/docker-lineage-cicd/assets/550915/94413093-69e6-4b1e-89e5-2d6db83b6cac)

It has a link to the 28 MB at: https://download.lineage.microg.org/builds/full/enchilada/lineage-20.0-20231001-microG-enchilada-images.zip

**Comment by st3rox** [comment]
That is the flashable images zip created in #483 
I hope the name will change to differentiate it next build round

**Comment by petefoth** [comment]
> That is the flashable images zip created in #483 I hope the name will change to differentiate it next build round

No, that zip file is ***not*** flashable. The solution described in #483 will not be implemented as the flashable zips take up to Mich space..

The images.zip file is the implementation of #483, and it should not be appearing in the updater app

**Comment by petefoth** [comment]
Easiest way to fix this is to revert the changes made to fix #483

**Comment by IGNNE** [comment]
I assume that fixes it for the future, but right now, the 28 MB zip file is still showing up. Is it possible that you delete it manually to avoid some confusion?

**Comment by petefoth** [comment]
> Is it possible that you delete it manually to avoid some confusion?

It is possible, but I'm not going to: new users will need to use the `img` files in the `images-zip` file.

**Comment by petefoth** [comment]
Closing - no more to be done with this
