### ISSUE TITLE
Build Server Problems - October 2023

### ISSUE THREAD

**Issue by mddvul22** [lineageos4microg/docker-lineage-cicd#489]
Looks like we have build server problems again. The last successful build was for enchilada on 10/04/2023 at 05:01:28 PM.  There are no builds after that one.

**Comment by petefoth** [comment]
Thanks. I'm going to roll out a fix for #488, then I'll start a build of the remaining devices

**Comment by petefoth** [comment]
It looks like docker just died, then can't be restarted: this from the log. It happens :(
```
>> [Wed Oct  4 22:02:54 UTC 2023] Starting build for equuleus, lineage-20.0 branch
Building branch lineage-19.1
Building devices blueline,bonito,crosshatch,discovery,gauguin,gemini,kirin,liber,mermaid,monet,natrium,parker,pioneer,sargo,tissot,vayu,voyager
docker: error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create?name=lineageos4microg-202310041029: read unix @->/var/run/docker.sock: read: connection reset by peer.
See 'docker run --help'.
Building branch lineage-18.1
Building devices a5y17lte,a7y17lte,addison,ahannah,albus,bacon,castor,castor_windy,cedric,debx,ether,flox,foster,foster_tab,FP2,ginkgo,griffin,hannah,hlte,hltechn,hltekor,hltetmo,jactivelte,jflteatt,jfltespr,jfltevzw,jfltexx,jfvelte,klte,klteactivexx,klteaio,kltechn,kltechnduo,klteduos,kltedv,kltekdi,kltekor,montana,oneplus3,porg,porg_tab,rhannah,s3ve3gds,s3ve3gjv,s3ve3gxx,shamu,sirius,victara,x2,z3,z3c,zl1
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

**Comment by mddvul22** [comment]
> It looks like docker just died, then can't be restarted: this from the log. It happens :(

> So it looks like the root cause is a comms bug - probably transient - causing calls to githup to fail.This too happens. It would be nice to know why the comms failure kills docker, but I don't have the time.

Thanks for looking into this.  Can you please clarify, does this mean that the remaining builds won't be finished this month?

**Comment by petefoth** [comment]
> Can you please clarify, does this mean that the remaining builds won't be finished this month?

No it doesn't mean that. The builds have restarted - firstly for `equuleus`, which was the first build to fail. Once I have checked that build has succeeded and published the correct files on the download server, I will start the building of all the remaining devices. They **_should_** all be done by just after the normal date

**Comment by mddvul22** [comment]
Great, thank you!

**Comment by petefoth** [comment]
I'll close this when the whole build run has completed

**Comment by mddvul22** [comment]
Thanks for assisting with this!

**Comment by akumar-xyz** [comment]
Is this why we have not had new builds for `sweet` since `2023-09-06` as well?

**Comment by petefoth** [comment]
> Is this why we have not had new builds for `sweet` since `2023-09-06` as well?

No - that is normal. we run builds once a month, in the order llsted in the [LOS Build Target list](https://raw.githubusercontent.com/LineageOS/hudson/master/lineage-build-targets) `sweet` is near the end of the 20.0 devices, and this month's build run is currently up to `renoir`

Lats month's build for `sweet` arrived several days early, because problems connecting to github caused builds for 30 or so devices before yours in the list to fail quickly. (They were built successfully after the normal build run has completed)

Please remember that we offer **no guarantees** of when - or if :)  - builds will be made and/or delivered.

**Comment by mddvul22** [comment]
Thank you!
