### ISSUE TITLE
repo error: Unable to fully sync the tree

### ISSUE THREAD

**Issue by konradmoesch** [lineageos4microg/docker-lineage-cicd#494]
I get multiple errors when trying to run the docker container. I tried to delete the src and mirror folders and tried again, but still get errors:
```
repo command failed due to the following `SyncError` errors:
GitCommandError: git command failure
    Project: LineageOS/android_kernel_xiaomi_gauguin
    Args: fetch --quiet --update-head-ok github --force --prune --recurse-submodules=no --tags +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
    Stdout:
fatal: unable to access 'https://github.com/LineageOS/android_kernel_xiaomi_gauguin/': Could not resolve host: github.com
    Stderr:
None
[...]
```
The affected repos differ from run to run; how to fix this? Is there a way to increase e.g. retry count?

**Comment by petefoth** [comment]
> fatal: unable to access 'https://github.com/LineageOS/android_kernel_xiaomi_gauguin/': Could not resolve host: github.com

That looks to me like you have lost network connection during the sync. Not something we could easily fix in the docker image.

I would suggest trying `repo sync` outside of the docker container, until you can get it to complete, then do the the `docker run ...`

**Comment by konradmoesch** [comment]
Thanks, running `repo sync` manually works.
Is there a way to set `--retry-fetches` inside the docker container, e.g. by setting a env var?

**Comment by petefoth** [comment]
is `--retry-fetches` andan argument to `repo sync`? If so it may be possible to add it, but it would take time and resources which we don't really have.

If someone were to submit a Pull Request, with tested modifications, then merging it wouldn't take a lot of effort ;)

As a fix to your immediate problem though, now you've managed a full manual sync, the sync inside docker might have a much better chance of succeeding

**Comment by konradmoesch** [comment]
Yes, it is an argument for `repo sync`
Is there an option to manually edit the build.sh script adding the argument (just for me when I use the docker container)?

**Comment by konradmoesch** [comment]
I still get (a lot)  of the `unable to access...` errors when running the container

**Comment by petefoth** [comment]
> Is there an option to manually edit the build.sh script adding the argument (just for me when I use the docker container)?

I think it's relatively easy to do, maybe by creating a new docker image based on ours, with just the change `build.sh` script added.But I'm not an expert, and I don't have time to chase it up, but an internet search should help. Maybe start wik looking at closed issues here

**Comment by konradmoesch** [comment]
Thanks for your help, I did exactly that and it works fine :)
Will provide a PR with my change later

**Comment by petefoth** [comment]
> Thanks for your help, I did exactly that and it works fine :)

Asa matter of interest, what value did you use for `--retry-fetches` to get round your sync errors?
