### ISSUE TITLE
arm64 macbook m1 not build?

### ISSUE THREAD

**Issue by xucongyong** [lineageos4microg/docker-lineage-cicd#496]
❯ docker run \
    -e "BRANCH_NAME=lineage-20.0" \
    -e "DEVICE_LIST=oriole" \
    -v "/Users/xucongyong/android/lineage/LINEAGE_20_0:/srv/src" \
    -v "/Users/xucongyong/android/zips:/srv/zips" \
    -v "/Users/xucongyong/android/logs:/srv/logs" \
    -v "/Users/xucongyong/android/cache:/srv/ccache" \
    lineageos4microg/docker-lineage-cicd
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Set cache size limit to 50.0 GB

... A new version of repo (2.37) is available.
... You should upgrade soon:
    cp /srv/src/.repo/repo/repo /usr/local/bin/repo

**Comment by petefoth** [comment]
Building LineageOS on Apple Silicon is not supported. 

From [the LineageOS build instructions for `oriole`](https://wiki.lineageos.org/devices/oriole/build)
> What you’ll need
>
> *    A Google Pixel 6.
> *    A relatively recent x86_64 computer:
> *        Linux, macOS, or Windows - these instructions are only tested using Ubuntu 20.04 LTS, so we recommend going with that.
> * ...

Those pages could be changed to make it clearer that  building on Macs with M1 chips, is not yet possible, but those pages are owned by LineageOS not by us.

You could ask in the LineageOS reddit, A quick search shows 2 old threads [here](https://tinyurl.com/y53chn8u) and [here](https://tinyurl.com/2p876rnx), bith of which state it is not possible.

Closing this issue
