### ISSUE TITLE
Specify the changes made between this fork and LineageOS

### ISSUE THREAD

**Issue by Lionirdeadman** [lineageos4microg/docker-lineage-cicd#5]
These changes should be documented and put either in a wiki entry or in the readme.

Right now it seems only the signature spoofing is documented. Please correct me if I'm wrong.

**Comment by rugk** [comment]
Is not the explanation on https://lineage.microg.org/ enouzgh?

**Comment by Lionirdeadman** [comment]
I thought more changes were made. Maybe I was wrong. If so, I'll close this issue.

**Comment by corna** [comment]
The only changes are:
 * "restricted" signature spoofing
 * embedded apps (four microG's components, two location providers, FDroid and its Privileged Extension)

Plus some obvious change:
 * different signing keys
 * different OTA server

Everything else is the identical

**Comment by Lionirdeadman** [comment]
Alright then. Thanks :)

**Comment by corna** [comment]
No problem :)
