### ISSUE TITLE
LOS+microG v20.0 for kirin

### ISSUE THREAD

**Issue by p2wei** [lineageos4microg/docker-lineage-cicd#504]
I'm not sure if this is an issue that I need to file a ticket for, but I've just noticed that LineageOS v20.0 is now available for kirin as well, https://download.lineageos.org/devices/kirin/builds lists builds for 20231103 and 20231110 at the moment.
Please consider changing the microG build from v19.1 to v20.0 as well, the currently listed last build is v19.1 from 20231007 (on https://download.lineage.microg.org/kirin/).

Please let me know if I should post this request somewhere else.

**Comment by petefoth** [comment]
kirin  was [moved from the LOS19.1  build targets to the 20.0 list](https://github.com/LineageOS/hudson/commit/bd473973b8d37829807381d1db934e32a44fab11) shortly after we started the November build run (49 minutes after to be precise) so this month's build will be 19.1. The December build run should make the 20.0 version for kirin (and for liber, parket, vayu and gauguin, and all the other 19.1 devices which have now moved to 20.0

So no need to do anything except be patient :)

I'll leave this issue open until the December build run is completed

**Comment by p2wei** [comment]
lineage-20.0-20231208-microG-kirin.zip appeared at https://download.lineage.microg.org/kirin/ and was detected by the internal updater. The update (with adb sideload as documented on the LineageOS wiki) worked for me and everything seems to run nicely.
So I guess this can be closed.
