### ISSUE TITLE
[QUESTION] Would options to download and build only the kernel be possible?

### ISSUE THREAD

**Issue by FridgeRacer** [lineageos4microg/docker-lineage-cicd#514]
Plain and simple in the title, I would like to only download the kernel sources, make my changes to it, and build boot.img, but I'm really scratching my head as to how to go about that..

I managed to do it through a lot of trial and error with the regular LineageOS kernel for my beryllium device, and succeeded by running make bootimg after adding what I wanted (KernelSU); but that kernel doesn't work with LineageOS for MicroG, so here we are!

(Really really painfully new and having a hard time figuring out building Android things from source, BOY is it heavy. I build software from source very often on my Linux machine, but this is a whole other ball game. I hope you don't mind this "issue")

**Comment by petefoth** [comment]
I'm sorry but what you are asking is well outside the scope of this project, and well outside my own expertise and experience. I'll leave this issue open for a while in case anyone else can give you advice, but there's nothing in this project that will be changing.

**Comment by petefoth** [comment]
Closing
