### ISSUE TITLE
January 24 build run status

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#515]
Full run
- started: 
  - [x] 20.0 branch
    - started: [Mon Jan  1 00:00:31 UTC 2024]
    - expected failures: m5, deadpool, odroidc4, pstar, radxa0, wade
    - unexpected failures: none
    - completed [Wed Jan 17 09:51:24 UTC 2024]
  - [x]  no 19.1 branch devices
  - [x] 18.1 branch
     - started: [Wed Jan 17 09:51:56 UTC 2024]
     - expected failures: none
     - unexpected failures: none
     - completed:  [Fri Jan 19 23:15:06 UTC 2024]
- completed:  [Fri Jan 19 23:15:06 UTC 2024]
----------------------------
Build targets:
- 20.0 (183): a52q a52sxq a72q a73xq akari akatsuki alioth apollon aura aurora avicii axolotl barbet bardock bardockpro beckham berlin berlna beryllium beyond0lte beyond1lte beyond2lte beyondx bluejay blueline bonito bramble channel cheeseburger cheetah cheryl chiron coral crosshatch crownlte d1 d2s d2x davinci deadpool devon dipper discovery dre DRG dubai dumpling enchilada equuleus evert f62 fajita flame FP3 FP4 G gauguin gemini grus gta4l gta4lwifi gta4xl gta4xlwifi gtowifi gts4lv gts4lvwifi guacamole guacamoleb h830 h850 h870 h872 h910 h918 h932 h990 hawao haydn heart hotdog hotdogb instantnoodle instantnoodlep joan kane kebab kiev kirin lake lancelot lemonade lemonadep lemonades liber lisa lmi ls997 lynx m5 m5_tab m52xq marlin mars martini mata merlinx mermaid messi Mi439 Mi8917 Mi8937 miatoll nairo nash natrium nio nx563j nx606j nx609j nx611j nx619j nx651j nx659j ocean odroidc4 odroidc4_tab onclite oriole panther parker payton pdx214 pdx215 perseus pioneer PL2 polaris pro1 pro1x pstar pyxis racer radxa0 radxa0_tab raven redfin renoir rhode river rosemary rs988 sagit sailfish sake sargo starlte star2lte sunfish surya sweet taimen tangorpro tissot TP1803 troika ursa us996 us996d us997 vayu vela violet voyager vs995 wade walleye X00TD xmsirius xpeng xz2c Z01R z2_plus zippo
- 19.1 (0)
- 18.1 (52): a5y17lte a7y17lte addison ahannah albus bacon castor castor_windy cedric debx ether flox foster foster_tab FP2 ginkgo griffin hannah hlte hltechn hltekor hltetmo jactivelte jflteatt jfltespr jfltevzw jfltexx jfvelte klte klteactivexx klteaio kltechn kltechnduo klteduos kltedv kltekdi kltekor montana oneplus3 porg porg_tab rhannah s3ve3gds s3ve3gjv s3ve3gxx shamu sirius victara x2 z3 z3c zl1

**Comment by rozhuk-im** [comment]
Are this build from fresh LineageOS?
https://github.com/lineageos4microg/lineageos4microg.github.io/issues/128 not fixed, but should.

**Comment by petefoth** [comment]
> Are this build from fresh LineageOS?

This build started on 01/01/2024 at 00:01. It will use whatever code was in the upstream LineageOS repos at that time. It looks like your defect was fixed upstream in December, so the fix ***should*** be in our latest build at https://download.lineage.microg.org/sweet/

**Comment by rozhuk-im** [comment]
But it is not here.

**Comment by petefoth** [comment]
> But it is not here.
https://download.lineage.microg.org/sweet/lineage-20.0-20240115-microG-sweet.zip

**Comment by petefoth** [comment]
Build completed last night
