### ISSUE TITLE
LineageOS 21.0 is coming

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#516]
See https://www.lineageoslog.com/21.0

I know we will need the following:
- [x] changes to `src/build.sh` 
- [x] a new signature spoofing patch
- [ ] Keep the most recent 20.0 build for promoted device, until we are sure the 21.0 build is stable. See [this comment thread](https://github.com/lineageos4microg/docker-lineage-cicd/issues/506#issuecomment-1845758738) for more info: we may have some debugging / code inspection to do :) )

Anything else?

Any ideas about ***when*** LOS might release 21.0 - it would be good to be ready when they do :) ( have taken a quick look round their github repos, reddit, blog and wiki pages but no joy. Is there anywhere else to look?

Any contributions, patches, thoughts, assistance welcome. I don't really have the experience or expertise to be confident of handling this correctly myself, and I would rather we didn't have a gap in our monthly builds :)

Thanks

**Comment by petefoth** [comment]
From @kurtn on XDA Forums 
> We should see first 21.0 devices here: probably weeks before official announcement
> https://github.com/LineageOS/hudson/commits/master/lineage-experimental-targets

**Comment by ArchangeGabriel** [comment]
You can watch https://review.lineageos.org/q/project:LineageOS%252Fhudson also because any change to hudson would happen there.

**Comment by petefoth** [comment]
Thanks. I've subscribed for notifications there

**Comment by petefoth** [comment]
> From @kurtn on XDA Forums
> 
> > We should see first 21.0 devices here: probably weeks before official announcement
> > https://github.com/LineageOS/hudson/commits/master/lineage-experimental-targets

Actually the link is https://github.com/LineageOS/hudson/commits/main/lineage-experimental-targets - `master` branch still exists, but is not the default. 

There is now  a [`lineage-21.0`branch of the LOS Android repo](https://github.com/LineageOS/android/tree/lineage-21.0)

We can use this to start making our changes.

[`cheetah` is the experimental 21.0 target](https://github.com/LineageOS/hudson/commit/96e8e1754b8c991f58817591cb9699f3cf212e75)

**Comment by kurt-by** [comment]
> From @kurtn on XDA Forums
> 
> > We should see first 21.0 devices here: probably weeks before official announcement
> > https://github.com/LineageOS/hudson/commits/master/lineage-experimental-targets

not kurtn i'm kurt-by

**Comment by petefoth** [comment]
> not kurtn i'm kurt-by

Apologies!

**Comment by bene64** [comment]
The LOS 21.0 build roster was added a few hours ago: https://github.com/LineageOS/hudson/commit/d83774ae4bd85250b5fd6e3f742e40931780f32e, so their 21.0 builds should start appearing in the next few days.

**Comment by petefoth** [comment]
Thanks. That's great timing: I've just finished implementing the 21.0 changes (see #566), and I should have time to test them before the March build run

**Comment by petefoth** [comment]
Testing the changes needed to the docker engine for building `lineage-21` See #566
 If I build with `-e "SIGN_BUILDS=true"`, I see the following error:
```
ERROR: /srv/src/LINEAGE_21_0/out/bazel/output/external/soong_injection/product_config_platforms/products/lineage_sunfish-userdebug/BUILD:9:16: no such package 'user-keys': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.

 - /srv/src/LINEAGE_21_0/out/soong/workspace/user-keys and referenced by '@soong_injection//product_config_platforms/products/lineage_sunfish-userdebug:lineage_sunfish-userdebug_product_vars'
```
(More context at https://pastebin.com/nK4iM0sK)

If I build with `-e "SIGN_BUILDS=false"`, everything seems fine.

Any ideas how to fix?

**Comment by chirayudesai** [comment]
Just a heads up / letting you know: https://review.lineageos.org/q/I8fc82ed266a2cc59636b662c7ea7e29c94f509b5

**Comment by petefoth** [comment]
> Just a heads up / letting you know: https://review.lineageos.org/q/I8fc82ed266a2cc59636b662c7ea7e29c94f509b5

Thanks. See my post in the XDA Forum thread

https://xdaforums.com/t/lineageos-for-microg.3700997/post-89356095

**Comment by petefoth** [comment]
I think this can be closed. We can now build 21.0, using the LOS signature spoofing changes instead of our patches. We'll keep our patches, for the sake of backwards compatibility, and in case LOS change their minds about the acceptability of signature spoofing :)
