### ISSUE TITLE
Include Aurora Store as a system app?

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#517]
For my personal, unofficial builds, I include Aurora Store as a system app. The benefit is that updates for apps installed by Aurora can be installed without having to confirm the update for each app. I do that by pointing my local manifest to [my own fork of the `android_vendor_partner_gms` repo](https://github.com/petefoth/android_vendor_partner_gms) instead of [the los4microg 'official' repo](android_vendor_partner_gms). I know other contributors do something similar in their builds.

I am wondering whether we should include Aurora Store in our officail monthly builds (by adding it to our `android_vendor_partner_gms`).

Any thoughts?

**Comment by FintasticMan** [comment]
Aurora store should be able to do unattended upgrades without being installed as a system app on modern versions of android. This is because it can use the session installer when the app was last installed/updated by Aurora. You still need to confirm the initial installation or updates if the app was installed from another source.

**Comment by petefoth** [comment]
OK. I thought that 

> Aurora store should be able to do unattended upgrades without being installed as a system app on modern versions of android.

I thought that only worked on rooted devices. Seems I was wrong. Is that documented anywhere?

**Comment by FintasticMan** [comment]
I can't find documentation for that easily unfortunately, but you can try it yourself to check that it works. Just make sure to select session installer when configuring Aurora. It should be the one selected by default.

**Comment by petefoth** [comment]
My reading of https://aurora-oss.vercel.app/faq/#how-does-aurora-store-install-apps, and of the Installer page in the app is that unattended upgrades are only possible 
- using the Root installer (which requires a rooted phone) OR
- using Aurora Service (which I believe is deprecated) OR
- Having Aurora Store  installed as a system app
> If you have Aurora Store ***installed as a system application***, this will have the same effect as if you were to install Aurora Services as a system application

The reason I changed my personal unofficial builds is that, with Aurora Store installed from F-Droid and the session installer chosen at startup, I had to confirm the installation of every update. I don't see anything [in the change logs](https://gitlab.com/AuroraOSS/AuroraStore/-/releases) that indicates that has changed recently..

I ***will*** run a check, but I'm fairly sure we do need to have it as a system app to get unattended upgraded

**Comment by Findus23** [comment]
I also can't find any information on how it works, but can confirm that since a while ago having "Session installer" selected as the installation method, Aurora works without any prompts for me on lineageos4microg.

**Comment by petefoth** [comment]
OK. I just need to find an app or two on Aurora that get very regular updates, do I can test

**Comment by FintasticMan** [comment]
you could also use the version code option in aurora to install an older version so you can test immediately.

**Comment by petefoth** [comment]
To do that I need to find a valid code and I didn't manage that (yet)

There's no rush in any case :)

**Comment by FintasticMan** [comment]
A valid version code is `1541152192` for youtube.

**Comment by petefoth** [comment]
> A valid version code is 1541152192 for youtube.

Thanks. Installed that version on a non-rooted device running 18.1, with Aurora Store v4.3.5 installed from F-Droid. Opened it to check it works.

Installation method in Aurora Store is set to Session installer:
![Screenshot_20240102-054552_Aurora_Store_044757](https://github.com/lineageos4microg/docker-lineage-cicd/assets/795668/021127ce-9c03-4d50-ac20-bd260d97eee6)

Restarted the phone. Went into Aurora Store | Updates and an update to the latest version was offered :)

I clicked 'Update' and the 'Do you want to install an update...' dialog is displayed
![Screenshot_20240102-060003_Package_installer_050023](https://github.com/lineageos4microg/docker-lineage-cicd/assets/795668/0534f8f7-a3f0-4cae-8bad-b8fc30618ba4)
 I have to click 'Install' to install the update.

When I do the same on an non-rooted 20.0 device, with Aurora Store v4.3.5 built-in to the ROM as a system app, then when i select 'Update' I see the app icon being filled as it is downloaded, then ***with no further input from me*** the app is installed and I see the `Successfully installed` notification

![Screenshot_20240102-170751_Aurora Store](https://github.com/lineageos4microg/docker-lineage-cicd/assets/795668/11e0a51e-9a92-4e0d-9c7f-70abc72b7508)

This isn't to do with the Android / LOS version: I encountered the same behaviour on the 20.0 device before I started building Aurora Store into my unofficial builds.

**Comment by petefoth** [comment]
> Anyway I don’t think we should make it a system app, the less system apps the best. ;)
 Noted! (Though I disagree: one of the main reasons I moved my daily driver device to IodéOS- which includes Aurora Store as a system app - instead of los4microg was that I did not have to keep clicking on  'Do you want to install an update...' dialogs foor all my installed apps)

Anyway, the score is 1:1 now :)

**Comment by FintasticMan** [comment]
I think the issue with the 18.1 device not updating without user input is that it's not a recent enough version of android. IIRC the feature of unattended upgrades was added in A12. If you have a device running A12, A13 or A14, it should work without root or being installed as a system app.

**Comment by petefoth** [comment]
> If you have a device running A12, A13 or A14, it should work without root or being installed as a system app.

Interesting - I'll try to find an unofficial A13 without Aurora Store as a system app, and see what happens with that. 

This project still supports more than 50 devices which run A11, so they would benefit

**Comment by st3rox** [comment]
I vote to include it as a system app
I have 2 rooted devices running lineageos4microg, enchilada (20.0) and shamu (18.1)
Both have root installer selected and require only tapping update all to install all updates
To test I selected session installer in aurora settings and rebooted, then tapped install all in Aurora
![I got a prompt to install](https://github.com/lineageos4microg/docker-lineage-cicd/assets/7464097/187ffd11-c4c7-4a63-b756-fc7dccdc5135)
BTW @petefoth brave nightly updates almost every day, perfect for this kind of test :)

**Comment by st3rox** [comment]
> > If you have a device running A12, A13 or A14, it should work without root or being installed as a system app.
> 
> Interesting - I'll try to find an unofficial A13 without Aurora Store as a system app, and see what happens with that.
> 
Non-rooted bramble running lineageos4microg (20.0) just tested, installs all updates without additional prompt

**Comment by petefoth** [comment]
A key point made in [the XDA Forum thread](https://xdaforums.com/t/lineageos-for-microg.3700997/post-89253749)

>The main goal is to have a pure LOS with just the signature spoofing patch in it and microG on top (to avoid any 'google connection' or interface to google :) , as stated in the OT: ... 'Our ROM is a fork of LineageOS with just the necessary changes to have microG built-in ..'
>
> All the other apps (even app-stores) can be installed by the users easily if really needed ... so I would want to keep the system as lean as possible .. ;)

I think that clinches the argument in favour of ***not*** adding Aurora Store to the ROM as a system app. Unless there are any compelling new arguments the other way...

**Comment by vanMacG** [comment]
I support the quote from XDA. Please don't include it.
Also the "problem" is only on 18.1 devices, which aren't so many any more...

**Comment by petefoth** [comment]
> Please do not.
> 
> Since Android 12, Google has added automatic app updates to the package installer. https://developer.android.com/about/versions/12/features#automatic-app-updates
> 
> [h](https://developer.android.com/reference/android/content/pm/PackageInstaller.SessionParams#setRequireUserAction(int))

Thanks. This has been noted before, as has the fact that it does not apply for for lineage-18.1 devices, which ***would*** benefit from the proposed change.

But not need to worry, this proposal _**will not**_ be implemented, as the majority view (of those who have expressed an opinon) is that it should not be included as a system app
