### ISSUE TITLE
Build error: Failed to create directory /srv/ccache/tmp: Permission denied

### ISSUE THREAD

**Issue by gund** [lineageos4microg/docker-lineage-cicd#518]
Tried to build using:
```
docker run \
    -e "BRANCH_NAME=lineage-20.0" \
    -e "DEVICE_LIST=taimen" \
    -v "/home/dev/lineageos/lineageos-src:/srv/src" \
    -v "/home/dev/lineageos/zips:/srv/zips" \
    -v "/home/dev/lineageos/logs:/srv/logs" \
    -v "/home/dev/lineageos/cache:/srv/ccache" \
    lineageos4microg/docker-lineage-cicd
```
Building in WSL2 Docker on Windows 11 everything is updated to latest.

And the build phase fails almost immediately with repeated:
```
ccache: error: Failed to create directory /srv/ccache/tmp: Permission denied
```

Also noticed a few other build failure messages like:
```
FAILED: out/target/product/taimen/obj/EXECUTABLES/folio_daemon_intermediates/main.o
FAILED: out/target/product/taimen/obj/STATIC_LIBRARIES/libglob_intermediates/glob.o
FAILED: out/target/product/taimen/obj/STATIC_LIBRARIES/libglob_intermediates/xmbsrtowcs.o
FAILED: out/target/product/taimen/obj/STATIC_LIBRARIES/libglob_intermediates/strmatch.o
FAILED: out/target/product/taimen/obj/STATIC_LIBRARIES/libglob_intermediates/gmisc.o
FAILED: out/target/product/taimen/obj/EXECUTABLES/bash_intermediates/array.o
FAILED: out/target/product/taimen/obj/EXECUTABLES/bash_intermediates/alias.o
FAILED: out/target/product/taimen/obj/STATIC_LIBRARIES/libglob_intermediates/smatch.o
```
Which I assume failed because of the ccache permission error above?

And a small note - I'm launching docker build from a user without sudo permissions in case this is relevant.

Anyway would be great to get some advise.
Thanks!

**Comment by petefoth** [comment]
> And the build phase fails almost immediately with repeated:
> 
> ```
> ccache: error: Failed to create directory /srv/ccache/tmp: Permission denied
> ...
> ```

> And a small note - I'm launching docker build from a user without sudo permissions in case this is relevant.

That's almost certainly the cause of your problem: you won't have permission to create a directory in `/`
You could try adding the following to your build command
`-v "/home/dev/lineageos/ccache:/srv/ccache" \`

I don't know whether that is the cause of the other build errors, but it's worth a try.

I run without `sudo` on my Linux machine by running in 'Rootless mode' see https://docs.docker.com/engine/security/rootless . I have no idea whether that will work in Windows / WSL as I don't own any Windows machines. If no-one else replies here, you could try asking in the [XDA Forum Thread](https://xdaforums.com/t/lineageos-for-microg.3700997/)

Good luck.

**Comment by gund** [comment]
I tried to execute docker build from a root user and got exactly the same issue so I guess it's not the root cause.

Also what is curious is that the build actually managed to create a file under `/srv/ccache` called `ccache.conf` which has `root` user permissions so technically the build can write to that directory but for some reason not everything...

It seems really odd and I think it might actually be cause of the WSL/Windows combo.
I will try to spin up another WSL with Ubuntu but install native docker (without a windows bridge) and see if it has a different result.

If you have any other ideas feel free to post them here too!

**Comment by petefoth** [comment]
> UPDATE2: I've hit OOM issue at 92% and the build process got killed so I had to set memory limit to 15gb (despite having 23gb allocated for WSL) and threads limit to 8 (out of 32 available) for java as suggested in [this issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/429#issuecomment-1616816335) and then the build completed!

I used to get that regularly on my build machine (running Linux Mint 20) with 16GB of memory. I got round it by configuring 28GB of swap. The swap usage regularly gets up to > 50% during the latter stages of the build.

Can this issue be closed now?

**Comment by petefoth** [comment]
Thanks
