### ISSUE TITLE
Image lineage-16.0-20190827-microG-FP2.zip seems corrupted

### ISSUE THREAD

**Issue by florentls** [lineageos4microg/docker-lineage-cicd#52]
I have a Fairphone FP2.

I was using lineage-16.0-20190819-microG-FP2.zip properly on my device.
Then today I got update image from OTA=> lineage-16.0-20190827-microG-FP2.zip
But then my phone tried to boot and end's up in TWRP.

Then I tried to manually install the same image from website and push it to TWRP via ADB sideload. The same happened. 

My phoen was unusable.

Then I installed again via ADB sidelaod  lineage-16.0-20190819-microG-FP2.zip and my phone is back as normal.

**Comment by florentls** [comment]
Sorry if it's not the correct place to talk about that, but I did not find other place. Please redirect to proper place if needed.

**Comment by corna** [comment]
Weird, I've done a diff between the two images and they almost have the same set of files.
For now I'm removing the problematic build, I will manually build another zip this weekend

**Comment by florentls** [comment]
Yes very weird.
I know someone having a FP2 with Lineage OS (no microg) and he has the same issue on the same period.
So it look like something coming from Lineage OS itself. I do not know if you can inform them on that too ?

**Comment by corna** [comment]
Sometimes it might happen that the upstream source is broken, let's just wait for the next build to see if they have already fixed the issue.

**Comment by Korsola** [comment]
@corna 
Same issue on tissot

https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/issues/19

**Comment by corna** [comment]
[Upstream issue](https://github.com/LineageOS/hudson/commit/940cce835009ec610c9783ffcdee90f4d4a5bbac), we just have to wait.
