### ISSUE TITLE
[REJECTED] Allow ROM to pass Safety Net

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#523]
Do-able with a patch to `android_system_core` - see this commit from ProtonAOSP 
https://github.com/ProtonAOSP/android_system_core/commit/3102e9e8c

Worth the overhead of maintaining and applying this patch if it allows us to pass SafetyNet

**Comment by dicer** [comment]
Sounds great, but I wonder if there is a reason why Lineage does not do 
this?

**Comment by petefoth** [comment]
> I wonder if there is a reason why Lineage does not do this?

Same reason as they won't allow signature spoofing (and why this project exists): because they think it is naughty :) From the [LOS Wiki FAQs](https://wiki.lineageos.org/faq#my-device-doesnt-pass-safetynet)
> Some devices pass their bootloader unlock status and verity status to android’s kernel during boot. We don’t purposefully remove those flags, as it isn’t our place to lie about security features. There’s also a [blog post](https://www.lineageos.org/Safetynet/) about this topic, which explains our reasons further.

And from the [linked blog post](url)
> Our official stance is that we will not intentionally circumvent an integrity check that Google has put in place for app developers. Any action taken to bypass SafetyNet risks a backlash against all custom OSes, and could cause Google to block them entirely from the Play Store.

and
> For apps that are no longer visible in the Play Store, you can pursue alternative methods of app installation. For apps that inhibit functionality, you can always install your device’s stock software and relock your bootloader.

**Comment by petefoth** [comment]
I'll also check out how IodéOS go about passing SafetyNet

**Comment by yetanother-user** [comment]
They do this unofficially (property editing): [ih8sn](https://github.com/luk1337/ih8sn)

**Comment by petefoth** [comment]
> > Sounds great, but I wonder if there is a reason why Lineage does not do this?
> 
> They do this unofficially (properties editing): [ih8sn](https://github.com/luk1337/ih8sn)

That's the method IodéOS used for a while, but it's never - as far as I know - been part of the LineageOS project.

From what I know, and certainly in IodéOS, `ih68sn` requires ***device-specific*** changes. With ~230 devices ti build for, device-specific changes are out of the question for us.
