### ISSUE TITLE
Tidy up old 17.1, 18.1 & 19.1 builds on both servers 

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#525]
To Do
-
- [x] Check status after January build run completes - see table below
- for devices which currently have at least one 20.0 build 
    - [x] Remove 17.1, 18.1, 19.1 zips from both build & download  servers
    - [x] Tidy up old 20.0 `.ing` files for [G](https://download.lineage.microg.org/G/)
    - [ ] Test run for a couple of devices with only a single 20.0 build, check that we keep **_two_** builds
    - [ ] Check after February build run that we have ***two*** 20.0 builds for these devces
- [ ] Put in place a process for handling 'promoted' devices

Checked
-
`ls -t */line*.zip`
`find . -name *.zip`

Current state| Devices| Action
|:---:|:---:|:---:|
last 2 20.0 zips, .img files goin back to march 23| G | Removed old .img files
1x19.1 1x20.0, should be two 20.0 | gemini FP3 flame fajita evert equuleus enchilada dumpling dubai DRG dre dipper d2x d2s d1 crosshatch cheryl cheeseburger channel bramble bonito blueline beyondx beyond2lte beyond1lte beyond0lte beryllium berlna berlin beckham apollon 
1x18.1 1x19.1 1x20.0, should be two 20.0 | gauguin 
**1x18.1** 1x20.0, should be two 20.0 | chiron crownlte coral bardockpro 
**1x17.1** 1x20.0, should be two 20.0 | davinci crownlte coral 
1x18.,1 1x19.1,1x20.0, should be two 20.0| discovery 
1x19.1, 2x20.0 | alioth akari 
2x20.0 | avicii aurora aura akatsuki a72q a52sxq a52q | No action required
1 x 20.0 build | zippo z2_plus Z01R xz2c xpeng xmsirius X00TD walleye vs995 voyager violet vela vayu us997 us996d us996 ursa troika TP1803 tissot tangorpro taimen sweet surya sunfish star2lte starlte sargo sake sailfish sagit rs988 rosemary river rhode renoir redfin raven radxa0_tab racer pyxis pstar pro1x pro1 polaris PL2 pioneer perseus pdx215 pdx214 payton parker panther oriole onclite odroidc4_tab ocean nx659j nx651j nx619j nx611j nx609j nx606j nx563j nio natrium nash nairo miatoll Mi8937 Mi8917 Mi439 messi mermaid merlinx mata martini mars marlin m52xq m5_tab lynx ls997 lmi lisa liber lemonades lemonadep lemonade lancelot lake kirin kiev kebab kane joan instantnoodlep instantnoodle hotdogb hotdog heart haydn hawao h990 h932 h918 h910 h872 h870 h850 h830 guacamoleb guacamole gts4lvwifi gts4lv gtowifi gta4xlwifi gta4xl gta4lwifi gta4l grus gemini gauguin FP4 f62 devon cheetah bluejay bardock barbet axolotl  a73xq

**Comment by petefoth** [comment]
*Sat 06 Jan 24* 
- checked  `a52q` -> `gauguin`
- continue from `gingko`

**Comment by petefoth** [comment]
*Sat 20 Jan 24*
- Remove 17.1, 18.1, 19.1 zips from both build & download servers
     - Done, but removed latest `griffin`, `s3ve3gjv` & `jfltexx` 18.1 builds: rebuilding them

**Comment by petefoth** [comment]
*Sun 21 Jan 24*
- remove ***empty*** directories
```
# 45 on download server
find . -type d -empty | wc -l
45
find . -type d -empty -exec rmdir {} \;
# leaves 237 directories with 266 builds, disk space 
df -h
Filesystem      Size  Used Avail Use% Mounted on
...
/dev/vdb1       590G  251G  309G  45% /mnt/archive

# 68 on build server
find . -type d -empty | wc -l
68
find . -type d -empty -exec rmdir {} \;
# leaves 268 directories with 334 builds
```
We have 'extra' builds on the build server, which are old 18.1 builds for devices which are no longer supported / on the LOS build target list

**Comment by petefoth** [comment]
After the February build run, we should have two builds of all current build targets, 18.1 & 20.0, except for devices which built for the first time this month (radxa0, odroidc4, m5)

So we can safely delete ***all*** files matching pattern `lineage*2023*` in the `zips` directory tree (25 complete builds(
`find . -name lineage*2023*.zip -delete`
Then we can remove any empty directories, because if there are no 2024 builds, the device is no longer in the current build target list.

**Comment by ArchangeGabriel** [comment]
Your missing the fact that some devices did not have builds in January, e.g. pdx203 and pdx206. So you would only keep one file.

Also I don’t agree with removing device that are not built anymore: people should be able to access the last existing build.

**Comment by ArchangeGabriel** [comment]
(For instance in the case of my pdx203, I would have been quite unhappy if the July build was removed while no newer one was published)

**Comment by petefoth** [comment]
> Also I don’t agree with removing device that are not built anymore: people should be able to access the last existing build.

So how far back do we go? By that logic we would have a lot of 15.1, 16.1 and 17.1 builds hanging around.



> For instance in the case of my pdx203, I would have been quite unhappy if the July build was removed while no newer one was published

Why? So long as you pick up the OTA update then you don't need that build again. Our aim is to 

> deliver regular builds of the project for all the phones and tablets currently supported officially by LOS

LIneageOS don't keep builds around fro long once they are removed from the build target list

**Comment by ArchangeGabriel** [comment]
> > Also I don’t agree with removing device that are not built anymore: people should be able to access the last existing build.
> 
> So how far back do we go? By that logic we would have a lot of 15.1, 16.1 and 17.1 builds hanging around.

I’ve edited my post to say not forever, I don’t know what LineageOS policy is, but something similar I guess?

> > For instance in the case of my pdx203, I would have been quite unhappy if the July build was removed while no newer one was published
> 
> Why? So long as you pick up the OTA update then you don't need that build again.

When I got the device (late 2023), the July build was the only one available. If you had removed it because the device was not build anymore, there would have been none.

> Our aim is to
> 
> > deliver regular builds of the project for all the phones and tablets currently supported officially by LOS
> 
> LIneageOS don't keep builds around fro long once they are removed from the build target list

OK, then I would say remove them once LineageOS did so. FTR, pdx203 and 206 were not removed from their download while it wasn’t build, likely because it was meant to be temporary (they were waiting for a modem crash issue to be fixed). However I can see that e.g. https://download.lineage.microg.org/Spacewar/ is already removed.

**Comment by petefoth** [comment]
See new issue ` Build retention strategy` #573 for a more flexible approach to this issue

Closing this issue now - I won't 'tidy' any more builds until we can agree on, and implement that startegy

**Comment by petefoth** [comment]
Re-opening, the 18.1 devices that have been built this month seem to have **_three_** builds - because I did a second build run on Jan 20 - and they are not getting deleted. I'll clean up the earlier January builds
