### ISSUE TITLE
50-lineage.sh broken after OTA due to LOS have low inodes

### ISSUE THREAD

**Issue by rozhuk-im** [lineageos4microg/docker-lineage-cicd#527]
I report to LOS about low free space and low inodes: https://gitlab.com/LineageOS/issues/android/-/issues/6496 and https://gitlab.com/LineageOS/issues/android/-/issues/6495
in https://gitlab.com/LineageOS/issues/android/-/issues/6495 ```50-lineage.sh``` is zero sized. It happen after OTA update.
On new installation file is ok.

**Comment by petefoth** [comment]
> Upstream is ok, but microg build is not.

Which microG build - are you using the latest build from today?

We use the same code as upstream, we add our built-in apps and microG. What space is left is what there is

EDIT: Looked at the code changes they made; they have made changes which only apply if the `WITH_GMS` environment variable ***is not*** set. IN our build that variable ***is*** set (becasue that's how we know we are building "forMicroG"), so their changes won't be applied.

I'm not sure what it is you are trying to do, or why you are creating files in "`/system`, `/product` and other", but the amount of space is controlled by the upstream code, npt by us so there is nothing we can do. If you a  microG build with different space reserved in `BoardConfigCommon.mk`, then you will have to make your own build, and experimant with changes.

This seems very similar to #358 which was closed as 'Not a bug' and 'Won't fix'
