### ISSUE TITLE
Google Pixel 2 (walleye) buggy monthly update process (?)

### ISSUE THREAD

**Issue by Komprogue** [lineageos4microg/docker-lineage-cicd#528]
The freshly installed system getting glitchy and unresponsible (sometimes with a bunch of crashes/freezes of some random apps running in the background) during installation of every monthly update.
And more over, it takes **EXTREMELY** long time (~1-1,5 hour) to complete update, but after all it's working fine, though something definitely is wrong.

**Comment by petefoth** [comment]
There is a new `axolotl` build available [here](https://download.lineage.microg.org/axolotl/)

Please check whether this fixes your problem and report back. If it does fix it, then please feel free to close the issue.

Thanks

**Comment by petefoth** [comment]
@Komprogue  Sorry - I responded in the wrong issue.

**Comment by petefoth** [comment]
> The freshly installed system getting glitchy and unresponsible (sometimes with a bunch of crashes/freezes of some random apps running in the background) during installation of every monthly update.

Not sure there is much we can do about this. The update process will be using resources in a way which makes other apps less performant. If it's only a transient problem (i.e. only ***during*** the update process) and goes away when the device is rebooted afterthe update, then I guess we can live with the problem.

> And more over, it takes **EXTREMELY** long time (~1-1,5 hour) to complete update, but after all it's working fine, though something definitely is wrong.

Have you tried keeping the device awake and stopping the screen from timing out during the update? (Settings | Display | Screen timeout - set display to 30 minutes)

**Comment by Komprogue** [comment]
> Have you tried keeping the device awake and stopping the screen from timing out during the update? (Settings | Display | Screen timeout - set display to 30 minutes)

Yes, cos it's only possible way to achieve the most fastest update.
