### ISSUE TITLE
no fingerprint in last axolotl-build (SHIFT 6mq)

### ISSUE THREAD

**Issue by Roiperceval** [lineageos4microg/docker-lineage-cicd#529]
After the last update the fingerprint-sensor is no longer working. Apparently it works in the last Lineage "vanilla" build, so could you build it from that again?

**Comment by petefoth** [comment]
There is a new `axolotl` build available [here](https://download.lineage.microg.org/axolotl/)

Please check whether this fixes your problem and report back. If it does fix it, then please feel free to close the issue.

Thanks

**Comment by petefoth** [comment]
@Roiperceval Is fingerprint sensor working for you in the latest 21.0 build [lineage-21.0-20240302-microG-axolotl.zip](https://download.lineage.microg.org/axolotl/lineage-21.0-20240302-microG-axolotl.zip)?

If so, please will you close this issue

**Comment by Roiperceval** [comment]
Thanks, yes it works now. I am new here, so I didn't know I had to close the issue...
