### ISSUE TITLE
[Device] berkeley missing from build

### ISSUE THREAD

**Issue by naxs6** [lineageos4microg/docker-lineage-cicd#53]
Hi,

I noticed berkeley is missing from https://download.lineage.microg.org/ despite LineageOS downloadable at https://download.lineageos.org/berkeley.

By the way, is there a list for all devices built by LineageOS for microG? The homepage says all LineageOS devices are supported.

**Comment by corna** [comment]
The list is [here](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets).

Unfortunately it is one of the few unlucky devices which fails to build, I haven't found the cause yet.

**Comment by spolack** [comment]
This Device was promoted to LineageOS 17.1 which is now supported. 
This is  related to the master issue #89
