### ISSUE TITLE
The latest builds for beryllium do not boot

### ISSUE THREAD

**Issue by Sci3ntia** [lineageos4microg/docker-lineage-cicd#54]
The only available builds for beryllium do not boot on the official lineageOS microG repo, even on clean flash

**Comment by Korsola** [comment]
Same issue on tissot

https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/issues/19

**Comment by anonimou0** [comment]
I'm running the build 20190708. I was going to upgrade to 20190729 when I saw your comment.

@corna , this hasn't been built since then. Is there any problem? How can I help?

**Comment by joelselvaraj** [comment]
I guess its due to the vendor files in https://github.com/TheMuppets/proprietary_vendor_xiaomi being removed due to DMCA violations.

**Comment by morten-b** [comment]
LineageOS still provides new builds: https://download.lineageos.org/beryllium

**Comment by corna** [comment]
(Almost) duplicate of lineageos4microg/android_prebuilts_prebuiltapks#19
