### ISSUE TITLE
Can't update with OTA (or manual) since the 14th May.

### ISSUE THREAD

**Issue by Booteille** [lineageos4microg/docker-lineage-cicd#55]
I tried to update my OnePlus 3T since the 21th May but once the phone restarts I just get the TWRP homepage and nothing else.
When I try to build it manually using `adb sideload`, I get an error telling me the build is not compatible.

What should I do to update my phone?

**Comment by corna** [comment]
Can you try with the official LineageOS build and check if it boots?

**Comment by Booteille** [comment]
I tried too. And it didn't boot neither.

**Comment by SuperITMan** [comment]
Hey @Booteille,

I already had this issue with my OnePlus 5 and my OnePlus 3.
This is unfortunately a firmware issue. You have to upgrade the firmware of your OP3 before you can upgrade to the new version of LineageOS.

For the OnePlus 5, there is a project which allows to upgrade **only** the firmware easily. See: https://sourceforge.net/projects/cheeseburgerdumplings/ 

On the OnePlus 3, I never saw any project like this. Last time I wanted to upgrade it, I formatted the phone, installed the latest version of OxygenOS then reinstalled LineageOS (with backup done thanks to "[Titanium Backup](https://www.titaniumtrack.com/titanium-backup.html)").

If you find any project that gives only the firmware for the OP3, please share it :blush: 

Good luck for your phone.

**Comment by Booteille** [comment]
Hi.  @SuperITMan. If I don't find the firmware only, should I just erase all data and reinstall the last version of LineageOS? Will it fix the issue?

**Comment by SuperITMan** [comment]
@Booteille 
I don't know if the firmware available on xda-developers is good (I guess yes because the thread is there for a long time now). If it is, you can simply install the firmware through TWRP.
This should not erase your data neither your config.
Then you should be able to update LineageOS again :blush:

Of course, doing a backup is always a good idea before doing this kind of manipulations :blush:

**Comment by Booteille** [comment]
Yeah. I read a bit different threads and I think I'll try it. But I'll wait for LineageOS 17 to be released before trying anything (I still made a backup, just in case). Then, if I break everything, I can just do a clean install with LineageOS 17.

**Comment by spolack** [comment]
Doesnt seem to be related to specifically lineageos for microg.
