### ISSUE TITLE
[Tissot/Xiaomi Mi A1] The latest LineageOS for microG gives bootloop

### ISSUE THREAD

**Issue by Korsola** [lineageos4microg/docker-lineage-cicd#56]
When trying to install LineageOS for microg, it gives a bootloop. This doesn't happen on LineageOS.

Reference:
https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/issues/19

**Comment by joelselvaraj** [comment]
I guess its due to the vendor files in https://github.com/TheMuppets/proprietary_vendor_xiaomi being removed due to DMCA violations.

**Comment by Korsola** [comment]
@joelselvaraj 
Any idea when the repo is coming back? I just gor Xiaomi Mi A1 and now I can't even use LineageOS for microG on it :disappointed:

**Comment by Korsola** [comment]
@joelselvaraj 
Do you have any idea when the repo will come back? I just got my Xiaomi Mi A1 and now I can't even use LineageOS for microG :disappointed:

**Comment by Korsola** [comment]
Maybe we should move this discussion to here
https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/issues/19

I will close this issue.
