### ISSUE TITLE
Latest build for nio is broken

### ISSUE THREAD

**Issue by JuniorJPDJ** [lineageos4microg/docker-lineage-cicd#561]
After update phone started randomly freezing on the lockscreen making itself unusable. I waited for new build but it seems like none is scheduled for a few weeks now. I'm on lineage-20.0-20240111-microG-nio.zip.
Previous build worked great (I don't remember the date) and switching slot back ends with the bootloop.

**Comment by petefoth** [comment]
Sounds like a hardware problem. 

Does the same issue occur with the plain LineageOS ROM? https://wiki.lineageos.org/devices/nio/

**Comment by petefoth** [comment]
OK the new build is available, and I have removed the old/broken build from the download server

@JuniorJPDJ Please let us know whether the new build fixes the problem.

Thanks

**Comment by JuniorJPDJ** [comment]
Thank you very much, I'll let you know

**Comment by JuniorJPDJ** [comment]
Latest build doesnt fix the issue - it's a bit better but it still happens. Tried clearing cache now.

**Comment by JuniorJPDJ** [comment]
Can I ask you to please provide a new build? Bug has probably been fixed as stated on XDA thread.

**Comment by petefoth** [comment]
The February build run is currently in progress and is up to `Mi8917`. `nio` is 6 places further down [the list](https://raw.githubusercontent.com/LineageOS/hudson/main/lineage-build-targets) so the build should be done in 12-15 hours time. The`repo sybc` for this build was done at `[Thu Feb  8 14:40:09 UTC 2024]`. According the the XDA thread, dated Feb 26 at 17:45, the code should have been in the next nightly build. If that did happen, then the fix _**should**_ also be in our build for `nio` happening later today.

Please will you test today's build when it arrives, and report back here whether or not the bug is fixed for you? If it is not, I can try another bulld when the full build run completes, which should be around Feb 20th or 21st

**Comment by JuniorJPDJ** [comment]
https://review.lineageos.org/c/LineageOS/android_kernel_motorola_sm8250/+/381654

The supposed fix was merged 2024.02.06

I'll try the build and report back, thank you very much!

**Comment by JuniorJPDJ** [comment]
I got freeze on a lockscreen, can we test more r

**Comment by petefoth** [comment]
> I got freeze on a lockscreen again, can we test more recent sync to be sure?

I will try another build for nio when the February build run completes. Will be around 20th Feb

**Comment by petefoth** [comment]
> I will try another build for nio when the February build run completes. Will be around 20th Feb

There's a new build available https://download.lineage.microg.org/nio/lineage-20.0-20240220-microG-nio.zip

The `repo sync` was done at  09:06:08 UTC today, so it's got the latest LOS code

@JuniorJPDJ  Please let me know how this goes

**Comment by JuniorJPDJ** [comment]
Sure, thanks

**Comment by Machion** [comment]
I just wanted to say, that I also had kernel panics/random reboots with the last couple of builds (I reported in the lineage issue tracker too). 
And I still have it with the last lineage20 build. It seems, the fix was merged into the first lineage21 build, so I hope there will be a microg version soon.

**Comment by petefoth** [comment]
> It seems, the fix was merged into the first lineage21 build, so I hope there will be a microg version soon.

It's your lucky day, There is a 21.0 build available for download at https://download.lineage.microg.org/nio/. It should show up in your 20.0 Updater app, but it won't install from there. You will have to install the upgrade manually as described at https://wiki.lineageos.org/devices/nio/upgrade/variant1/

Please note, this build is not tested at all - take care :)

Please let me know if this fixes your problem

**Comment by Machion** [comment]
Great thanks! 
I will test it asap. 
I know, I already did version upgrades in the past.

**Comment by Machion** [comment]
So I upgraded in the morning and after this day I can say its not better, maybe even worse 😂 😩 
I will try to make a new ticket at lineage.

**Comment by petefoth** [comment]
> So I upgraded in the morning and after this day I can say its not better, maybe even worse 😂 😩
Oh dear!

> I will try to make a new ticket at lineage.

 Is this change in response to your ticket?
https://review.lineageos.org/c/LineageOS/lineage_wiki/+/384193

> devices: Temorarily unship moto 8250
> * BSOD issues for some users after modem crashes.

You asked
> Btw since around the last 2 versions there is no console-ramoops file any more. Is this specific to the microg builds?

I have only a very hazy idea about what a `console-ramoops file` is. I don't believe there have been any changes in our code or tools that might affect this, so I would be surprised if it is specific to our builds

**Comment by Machion** [comment]
> Is this change in response to your ticket?
> https://review.lineageos.org/c/LineageOS/lineage_wiki/+/384193

I don't think so. At least I didn't had any BSODs yet and no new ticket.

> I have only a very hazy idea about what a `console-ramoops file` is. I don't believe there have been any changes in our code or tools that might affect this, so I would be surprised if it is specific to our builds

I just asked to be shure. 
Console-ramoops is a log, when the kernel panics and should be at /sys/fs/pstore/. Infos says kernel must be build with pstore support. Infos are [here](https://android.stackexchange.com/questions/213336/how-can-i-enable-last-kmsg)

**Comment by petefoth** [comment]
This issue is 'On Hold' until we can clarify whether it is a problem with upstream plain LOS, or whether it's specific to our build

**Comment by JuniorJPDJ** [comment]
It is problem with upstream

**Comment by Machion** [comment]
> It is problem with upstream

I would agree and I think because it can't get worse, at least want to benefit from ongoing fixes in LOS releases

**Comment by red-black-bonsai** [comment]
[Sounds like the upstream issue might be fixed](https://xdaforums.com/t/rom-official-lineageos-21-for-edge-s-moto-g100.4650662/page-9#post-89409714) but unfortunately nio didn't build in the latest run.
Is there a chance to get a nio build sooner than in 2 weeks? The the last build available for download is really unstable, crashing all the time :(

**Comment by petefoth** [comment]
> Is there a chance to get a nio build sooner than in 2 weeks?

Sorry - no. At the moment it is not possible to make more 21.0 builds for any devices. See this post in XDA forums for details:
https://xdaforums.com/t/lineageos-for-microg.3700997/post-89412440

**Comment by JuniorJPDJ** [comment]
We have a build now. Let's see if problem is fixed

**Comment by Machion** [comment]
I updated to build 20240330 on saturday and had no crashes since then. Seems pretty stable.

**Comment by JuniorJPDJ** [comment]
Same! Let's close it!
