### ISSUE TITLE
Implement changes needed for `lineage-21.0`

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#566]
See `LineageOS 21.0 is coming` #516 

Tasks
- [x] Create [a new branch `lineage-21`](https://github.com/lineageos4microg/docker-lineage-cicd/tree/lineage-21)
- [x] Make new Signature Spoofing patch
- Code changes (if any)
    - [x] ~~`Dockerfile`?~~ None needed
    - [x] ~~`init.sh`?~~ None needed
    - [x] `build.sh`?
    - [ ] `README.md`?
- [ ] Make a test build for cheetah using `docker pull lineageos4microg/docker-lineage-cicd:lineage-21`
- [ ] Cloud test build for `sunfish`, so I can test the sig spoofing
- [ ] Merge changes to `main` branch

**Comment by petefoth** [comment]
### Signature spoofing patches
For Android 13 / 20.0 change the following:
- repo: https://github.com/LineageOS/android_frameworks_base
files:
    - 'core/api/current.txt b/core/api/current.txt`
    - `core/res/res/values/strings.xml`
    - `services/core/java/com/android/server/pm/ComputerEngine.java`
- repo: https://github.com/LineageOS/android_packages_modules_Permission
    - file:`PermissionController/src/com/android/permissioncontroller/permission/utils/Utils.java`

**Comment by petefoth** [comment]
*Wed 14 Feb 24*
- Make new Signature Spoofing patch
  - use experimental target `cheetah`
  - work in ~/srv/l21/src/LINEAGE_21_0
  - need a manifest for blobs
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="TheMuppets/proprietary_vendor_google_cheetah" path="vendor/google/cheetah" revision="lineage-21" />
</manifest>
```
  - start by building unmodified `PermissionController` normal LOS for cheetah - see https://wiki.lineageos.org/devices/cheetah/build/
- Modify the files
  - repo: https://github.com/LineageOS/android_frameworks_base
  files:
    - `core/api/current.txt b/core/api/current.txt
    - `core/res/AndroidManifest.xml`
    - `core/res/res/values/strings.xml`
    - `services/core/java/com/android/server/pm/ComputerEngine.java`
  - repo: https://github.com/LineageOS/android_packages_modules_Permission
  file:
    - `PermissionController/src/com/android/permissioncontroller/permission/utils/Utils.java`
- build `mka PermissionController`
- Create patches
```
cd frameworks/base
git diff > /home/pete/l4m-docker/src/signature_spoofing_patches/android_frameworks_base-Android14.patch
cd ../../
cd packages/modules/PermissionController
git diff > /home/pete/l4m-docker/src/signature_spoofing_patches/packages_modules_Permission-Android14.patch
```
- commit and push to `lineage-21` branch
```
git add src/signature_spoofing_patches/android_frameworks_base-Android14.patch
git add src/signature_spoofing_patches/packages_modules_Permission-Android14.patch
git commit -m "Sig spoofing patches for Android 14 / LOS 21"
```
- changes to `build.sh`
- commit and push to `lineage-21` branch
- build the patched code `mka bacon | tee -a build_cheetah-21.0-$(date '+%Y%m%d').log`

**Comment by dicer** [comment]
I'm also trying a build of this. I noticed two things in your latest commits:

Wrong muppets branch in build.sh:
```
       lineage-21.0*)
-        themuppets_branch="lineage-20.0"
+        themuppets_branch="lineage-21.0"
```

Syntax error in init.sh:
```
-  cat > $"KEYS_DIR"/BUILD << _EOB
+  cat > "$KEYS_DIR"/BUILD << _EOB
```

**Comment by petefoth** [comment]
Thanks for that. Fixes implemented and pushed to `lineage-21` and `experimental` branches.

**Comment by petefoth** [comment]
OK. I think I've managed to push all the `lineage-21` changes to ***all*** of the branches: `master`, `lineage-21`, & `experimental`

Please let me know if you hit any problems with any of them. Let's hope the changes to `master` don't screw up the current build run.

@dicer  Thanks again for your help & comments

**Comment by dicer** [comment]
Will let you know tomorrow. Still syncing the repo...
I had to start the container 2 or 3 times though to get it working. It just stopped for a couple of times after `(Re)initializing branch repository` and after `Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'`. There was no logs of what went wrong and when I tried to debug it just went past those and started to sync...
So no idea what happened, but lets see if the build works ok

**Comment by TinfoilSubmarine** [comment]
I'm running into this issue:
```
...
[ 98% 407/415] converting Android.bp files to BUILD files at out/soong/bp2build
[ 98% 408/415] Creating Bazel symlink forest
[ 98% 409/415] test android/soong/cc
[ 98% 410/415] test android/soong/rust
[ 99% 411/415] test android/soong/aidl
[ 99% 412/415] test android/soong/java
[ 99% 413/415] test android/soong/sdk
[ 99% 414/415] test android/soong/apex
[100% 415/415] analyzing Android.bp files and generating ninja file at out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     -o out/soong/build.ninja --bazel-mode --globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.build Android.bp
Killed
ninja: build stopped: subcommand failed.
19:03:51 soong bootstrap failed with: exit status 1

#### failed to build some targets (03:19 (mm:ss)) ####

>> [Thu Feb 15 19:03:51 UTC 2024] Failed build for redfin
>> [Thu Feb 15 19:03:51 UTC 2024] Finishing build for redfin
>> [Thu Feb 15 19:03:51 UTC 2024] Cleaning source dir for device redfin
19:04:10 Entire build directory removed.

#### build completed successfully (19 seconds) ####
```
Full log: [lineage-21.0-20240215-UNOFFICIAL-redfin.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/14301666/lineage-21.0-20240215-UNOFFICIAL-redfin.log)

I've tried building for redfin, oriole, and cheetah so far with the same result.

**Comment by petefoth** [comment]
I used to get that 'killed:' error when I ran out of memory. Increasing swap fixed it gir me

**Comment by TinfoilSubmarine** [comment]
Yep, you are correct. That's unfortunate though-- LineageOS <= 20 was able to build with 32GB of RAM. Now it appears to need at least 40GB, maybe more like 48GB if you don't completely dedicate the machine to building.

**Comment by petefoth** [comment]
> Now it appears to need at least 40GB, maybe more like 48GB if you don't completely dedicate the machine to building.

I build on a machine with 16GB of physical memory, and 30GB of swap. Pretty straightforward to set up on my machine running Linux Mint

**Comment by TinfoilSubmarine** [comment]
> > Now it appears to need at least 40GB, maybe more like 48GB if you don't completely dedicate the machine to building.
> 
> I build on a machine with 16GB of physical memory, and 30GB of swap. Pretty straightforward to set up on my machine running Linux Mint

Yep, it was easy enough to set up. I just had never needed swap before so it was a bit of an alien experience.

**Comment by petefoth** [comment]
SO, I think everything is ready to go

I will run a test build for a couple of devices when the February build run completes

**Comment by dicer** [comment]
Build works for me as well! No problems encountered, but had no time to 
actually test it yet.

**Comment by flukeeey** [comment]
Build ran fine and I have been testing 21 on my lemonadep device for a few days now. Everything appears to be working great!

Thank you for the excellent project. :heart:

**Comment by petefoth** [comment]
> Build ran fine and I have been testing 21 on my lemonadep device for a few days now. Everything appears to be working great!
> 
> Thank you for the excellent project. ❤️

Thank you for the test 😄

**Comment by petefoth** [comment]
Closing this issue. We can make 21.0 builds
