### ISSUE TITLE
What are the next steps regarding f-droid client and f-froid privileged extension?

### ISSUE THREAD

**Issue by ghost** [lineageos4microg/docker-lineage-cicd#568]
[Unattended updates for everyone, 1.19 is here](https://f-droid.org/en/2024/02/01/twif.html)
[One new, one broken, one beta, more updates](https://f-droid.org/en/2024/02/08/twif.html)
[CalyxOS & F-Droid](https://calyxos.org/news/2023/09/04/f-droid/)

I know this has been mentioned #472

**Comment by FintasticMan** [comment]
I propose removing the privileged extension for LOS 19, 20 and up. As we established in #517, we should be making the minimum number of changes to LOS for microG to work.

**Comment by petefoth** [comment]
Thanks for raising this.

Looking at https://f-droid.org/en/packages/org.fdroid.fdroid/, the latest available version of the F-Droid client is 
> Version 1.19.0 (1019050) - Added on 2024-01-30 

The 'Unattended updates' functionality is new in v1.19, so I definitely don't think we should remove the privileged extension just yet :)

The privileged extension is still needed to provide the 'unattended updates' functionalityin builds in los versions up to and including 18.1, and it looks like it always will be. Removing it would mean that the 'unattended updates' functionality - provided by the privileged extension - would no longer be available for these builds.

A complication is that there is only a single branch in the `android_vendor_partner_gms ` repo, so to remove it only for certain versions, we would need to create and maintain another branch there, change our manifests and document the changes users would need to make to their manifests.

Looking at https://f-droid.org/en/packages/org.fdroid.fdroid.privileged/, the extension `.apk` is only 44 KiB, so it's not taking up very much space.

So my thinking is that we won't make any changes in our repos. The only benefit of changing is to reduce the size of our v19.1 + builds by a relatively tiny amount. The downside is the potential for breaking earlier builds (if we get the changes wrong), and creating additional complications in maintaining our repos, our manifests, and our documentation. To me, the cost/benefit analysis falls clearly on the side of 'don't change'.

I will listen to other opinions, and I'm happy to consider PRs which remove the extension for 19.1 builds onwards, but leave it in place for 18.1 and earlier builds, but I won't necessarily accept them.

**Comment by petefoth** [comment]
> which do you prefer, standard or basic f-droid client?
> installed by default as a system app or as a user app?

I know your question wasn't directed at me, but we currently use the standard client, installed as a system app. Is there any reason we should change that?

**Comment by ArchangeGabriel** [comment]
Yes, same as for dropping the privileged extension: security. The basic F-Droid client as user app should be enough for most people. Everything that has unneeded rights adds attack surface.

That being said, I understand the needs about handling the different versions in the building tools and that not being something you want to consider..

**Comment by FintasticMan** [comment]
The basic app has also had unattended upgrade functionality for a lot longer. I'll have a look into changing build.sh to use a different branch of the manifest depending on LOS version.

**Comment by petefoth** [comment]
> I'll have a look into changing build.sh to use a different branch of the manifest depending on LOS version.

It's not that simple:
1. at the moment is possible to build ***without*** a manifest pulling in the  `android_vendor_partner_gms` repo;
2. if there is a manifest, we don't know its name;
3. It is possible to build with `WITH_GMS=false` in which case  the  `android_vendor_partner_gms` components are not pulled in, even if the repo is mentioned in a manifest.

The more I think about this, the more I am inclined ***not*** to make any changes.We can continue to ship the normal client, and the privileged extension. The only downside is the 44 KiB of space the extension takes up. From the [Project Status section of `README.md`](https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/README.md#project-status)
> The project is therefore - in the opinion of the currently active maintainers - essentially 'feature complete' and in 'maintenance' mode. The only change that we believe might significantly improve the project is to support other classes of Android devices,

In my view making changes to either stop shipping the privileged extension for some builds, and/or to use the basic F-Droid client rather than the normal client, does not significantly improve the project.

**Comment by FintasticMan** [comment]
I would add an environment variable that lets you choose whether it should do it and which manifest to modify, of course. I would say that this is not adding features, it is simply updating the project to keep up with the changing ecosystem. Seeing as the main F-Droid app has unattended upgrades, there is no need to switch to the basic one.

**Comment by petefoth** [comment]
> I would say that this is not adding features, it is simply updating the project to keep up with the changing ecosystem.
The added feature is 'including different components from `android_vendor_partner_gms` dependendent on the version being built.' As previously mentioned, I don't see enough benefit from that feature to make the change worthwhile. Clearly you have a different opinion. As also stated earlier, I will look at any PRs that are submitted to implement the change, but I don't guarantee that I will accept them.

> Seeing as the main F-Droid app has unattended upgrades, there is no need to switch to the basic one.

For the sake of clarity, the unattended update functionality in both basic & traditional clients is available _**only in Android 12 / LOS 19.1 and later builds**_. Privileged extension remains the only solution for unattended updates in earlier versions

**Comment by petefoth** [comment]
Closing this issue: we will continue to ship F-Droid client app and Provileged Extension
