### ISSUE TITLE
Test signature spoofing

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#576]
Now that LOS have added support for signature spoofing, we need to decide whether we can stop applying our signature spoofing patches in our monthly builds. See #575 and, in particular, [this post](https://github.com/lineageos4microg/docker-lineage-cicd/issues/575#issuecomment-1962979072)

To do this we need, to make some test builds with the patches ***not*** applied (i.e. build with `SIGNATURE_SPOOFING=no` - the default). We need to check that signature spoofing works as expected, for the components which, in our builds do spoof the signature of another component: specifically
- GmsCore
- FakeStore

For each device build we should log 
- whether or not everything works with no problems
- what problems if any were encountered

**Comment by flukeeey** [comment]
I would like to test this for my next build run for lemonadep (OnePlus 9 Pro), but just to clarify:

1. All I need to change from my previous docker command is to set `SIGNATURE_SPOOFING=no`, previously 'restricted'
2. I still need to include `android_vendor_partner_gms` as a manifest and set `WITH_GMS=true` - FYI, I also update microG to v0.3 after flashing via F-Droid, so maybe I don't even need to include the manifest? microG should run fine as a user app?
3. If the above 2 points are true, do I even need to use this project and maybe I can go vanilla LOS? :thinking: 

@tduboys Can I ask, what's the benefit of including Aurora as a system app? I'm using it as a user app and it seems to work fine?

Thanks!

**Comment by petefoth** [comment]
> 1. All I need to change from my previous docker command is to set `SIGNATURE_SPOOFING=no`, previously 'restricted'

Correct

> I still need to include android_vendor_partner_gms as a manifest and set WITH_GMS=true
Correct

> FYI, I also update microG to v0.3 after flashing via F-Droid, 
I do that too. v3.0 is looking quite good. We'll add it to the `android_vendor_partner_gms` repo when upstream mark it as stable

> maybe I don't even need to include the manifest? microG should run fine as a user app?

It should run OK. But you won't be getting F-Droid built-in, or the other stuff from the `android_vendor_partner_gms` repo

> do I even need to use this project and maybe I can go vanilla LOS?

If you're happy to manually install the other stuff we ship in the project, then you could do that. Particularly since you're using F-Droid basic :)

**Comment by petefoth** [comment]
> Today I installed the latest LineageOS 21 for my Pixel 7 (Panther). I installed all three microG components and it works well. No problems so far with installing third party apps.

Thanks for taking the time to do that

> 1. As some have reported on an XDA Forum, (sorry don't remember where), the pull down Quick Settings are in dark mode no matter if dark mode is on or not. The notifications below are in light mode though. I remember someone saying that this is by design for some reason on LOS 21. Is it possible that someone can change that for LOS for microG project? Maybe even allow some transparency to it?

Sorry, but I'm afraid that is not going to happen: our scope is just to build a ROM that includes LineageOS with functioning microG and F-Droid built-in. We are not in the business of making changes to parts of LineageOS functionality that users don't happen to like 😄  If you don't like something that has been implemented by LineageOS, then you need to persuade LineageOS to change it, not us. Good luck with that!

> 2. I previously had /e/ OS T 1.20 (Android 13) and wanted to go back to Lineage OS for microG because location services was always incorrect by as much as 100 miles, except in Magic Earth which was precisely correct. But all weather apps detected my location in the same spot 100 miles away. It still happens with LOS 21. Is it a microG Mozilla issue?

When you say `It still happens with LOS 21.` you're not still talking about /e/OS are you? When you installed LOS 21 and microG, did you format data? Your problem sounds like there is something from /e/OS's broken 'Advance Privacy` still hanging around and stopping your location from being detected correctly. Whatever, if it is a a problem with microG, then the best place to ask about it is in one of the microG projects issue trackers in the repos at https://github.com/microg. I don;' really know very much about microG - I only know how to build ROMs that include it :)

One thing that occurs to me is that you said
> I installed all three microG components 

But when I look at https://microg.org/, I see ***four*** components: GmsCore, GsfProxy, UnifiedNlp, and mapsv1. Did you maybe miss one of these? 

But I would be very surprised if it is a general problem with microG and LOS 21. I hope you can get it sorted.

As we don't have any functioning  21.0 los4microG builds yet, I'm afraid we can't do any testing. And I'm afraid that `panther` is a long way down the list of targets for this month's build run, so it will be a while (~10 days or so?) before we have a build that you can test.

Thanks again for helping test the signature spoofing stuff.

**Comment by petefoth** [comment]
> Today I installed the latest LineageOS 21 for my Pixel 7 (Panther). I installed all three microG components and it works well. No problems so far with installing third party apps.

Thanks for taking the time to do that

> 1. As some have reported on an XDA Forum, (sorry don't remember where), the pull down Quick Settings are in dark mode no matter if dark mode is on or not. The notifications below are in light mode though. I remember someone saying that this is by design for some reason on LOS 21. Is it possible that someone can change that for LOS for microG project? Maybe even allow some transparency to it?

Sorry, but I'm afraid that is not going to happen: our scope is just to build a ROM that includes LineageOS with functioning microG and F-Droid built-in. We are not in the business of making changes to parts of LineageOS functionality that users don't happen to like 😄  If you don't like something that has been implemented by LineageOS, then you need to persuade LineageOS to change it, not us. Good luck with that!

> 2. I previously had /e/ OS T 1.20 (Android 13) and wanted to go back to Lineage OS for microG because location services was always incorrect by as much as 100 miles, except in Magic Earth which was precisely correct. But all weather apps detected my location in the same spot 100 miles away. It still happens with LOS 21. Is it a microG Mozilla issue?

When you say `It still happens with LOS 21.` you're not still talking about /e/OS are you? When you installed LOS 21 and microG, did you format data? Your problem sounds like there is something from /e/OS's broken 'Advance Privacy` still hanging around and stopping your location from being detected correctly. Whatever, if it is a a problem with microG, then the best place to ask about it is in one of the microG projects issue trackers in the repos at https://github.com/microg. I don;' really know very much about microG - I only know how to build ROMs that include it :)

One thing that occurs to me is that you said
> I installed all three microG components 

But when I look at https://microg.org/, I see ***four*** components: GmsCore, GsfProxy, UnifiedNlp, and mapsv1. Did you maybe miss one of these? 

But I would be very surprised if it is a general problem with microG and LOS 21. I hope you can get it sorted.

As we don't have any functioning  21.0 los4microG builds yet, I'm afraid we can't do any testing. And I'm afraid that `panther` is a long way down [the list of targets for this month's build run](https://raw.githubusercontent.com/LineageOS/hudson/main/lineage-build-targets), so it will be a while (~10 days or so?) before we have a build that you can test.

Thanks again for helping test the signature spoofing stuff.

**Comment by ToughDBlue** [comment]
> Sorry, but I'm afraid that is not going to happen: our scope is just to build a ROM that includes LineageOS with functioning microG and F-Droid built-in. We are not in the business of making changes to parts of LineageOS functionality that users don't happen to like 😄 If you don't like something that has been implemented by LineageOS, then you need to persuade LineageOS to change it, not us. Good luck with that!

No problem. I totally understand. Thank you for clarification. I'll try and send them a request. 😁


> When you say `It still happens with LOS 21.` you're not still talking about /e/OS are you?

No. I did a complete wipe and reinstall of the Pixel 7 stock ROM and then installed LOS 21. Thank you for the link to the microg Github. I'll ask there and hopefully figure out what's going on. It happens on my wife's OnePlus 7T as well.


> But when I look at https://microg.org/, I see _**four**_ components: GmsCore, GsfProxy, UnifiedNlp, and mapsv1. Did you maybe miss one of these?

I went to https://microg.org/download.html and downloaded the three apks they have listed there: microg services, microg companion, and Services framework policy. UnifiedNlp and Maps API are no longer being developed.



> As we don't have any functioning 21.0 los4microG builds yet, I'm afraid we can't do any testing. And I'm afraid that `panther` is a long way down [the list of targets for this month's build run](https://raw.githubusercontent.com/LineageOS/hudson/main/lineage-build-targets), so it will be a while (~10 days or so?) before we have a build that you can test.

Yes it is way down there. My wife's phone is a OnePlus 7T (hotdogb) so maybe that will be available in a couple days??



> Thanks again for helping test the signature spoofing stuff.

You're welcome! Thank you again for the time to work on this project. Greatly appreciated as it's much easier to install a ROM that has microG already setup and ready to go.

**Comment by petefoth** [comment]
Signature spoofing using the upstream LOS changes seems to be working fine. Closing
