### ISSUE TITLE
March 24 build run status

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#578]
Headline
-
**Update 21/03/2024**

20.0 builds and final 18.1 builds are complete

Builds of remaining 21.0 devices started failing - last successful build was `lynx` at 20/03/2024, 20:02:35. see #592 for details

I don't know what has caused the build failure and I have no idea how to fix it. We are running out of time in March, so unless a fix appears in the next day or so, the March build run is finished. Sorry!

The list of devices which ***have not*** built this month is:
`kane kebab kirin lake lemonade lemonadep lemonades ls997 lynx m5_tab m52xq marlin martini mata mermaid messi Mi439 Mi8917 Mi8937 nash natrium nio nx563j nx606j nx609j nx611j nx619j nx651j ocean odroidc4_tab oriole panther payton pdx203 pdx206 pdx214 pdx215 perseus pioneer PL2 polaris pro1 pro1x pstar pyxis radxa0_tab raven redfin rhode river rosemary rs988 sagit sailfish salami sargo shiba sunfish taimen tangorpro TP1803 troika ursa us996 us996d us997 vela voyager vs995 walleye xpeng Z01R`

The list of 21.0 devices which ***have***  built this month is:

`a52q a52sxq a72q a73xq aura avicii axolotl barbet beckham berlin berlna beryllium bluejay blueline bonito bramble caprip channel cheeseburger cheetah cheryl chiron coral crosshatch devon dipper discovery DRG dubai dumpling enchilada equuleus evert fajita felix flame FP4 gemini grus gta4l gta4lwifi gts4lv gts4lvwifi guacamole guacamoleb h830 h850 h870 h872 h910 h918 h990 hawao hotdog hotdogb husky instantnoodle instantnoodlep joan kane kebab kirin lake lemonade lemonadep lemonades ls997 lynx`

Root cause of the 21.0 build failures seems to be [this commi](https://github.com/LineageOS/android/commit/be7f0beae92f366520fd2d85323d69a04195ddd8) in LineageOS/android repo, commited Mar 11 2024 12:25pm

----
- All builds after the first failed due to #582
- When trying to fix that, I accidentally delete files in `userscripts` . I could recreate all of them from github, ***except*** for the key file used to `rsync` the builds with the download server - see #580
- I then restarted the remaining 21.0 builds ***without*** syncing, (using `build-list.sh`) allowing build run to continue while I tried to solve the `rsync` problem
- the `rsync` problem is now fixed, but the builds need to be synched manually, using `retry-rsync.sh`. The first batch,up to and including `discovery` synced OK. I will do this once or twice a day until all the 21.0 builds are done & synced
- 20.0 and unofficial builds can be started using `build-branch.sh` ***with*** `rsync`
- 18.1 builds will need to be started using `build-list.sh`  ***with*** `rsync`, because all 18.1 builds have been reomved from the LOS build target list - see #581

_________________

- started: [Fri Mar  1 00:01:39 UTC 2024]
- killed due to errors
- restarted [Fri Mar  1 08:02:39 UTC 2024] 
  - [ ] 21.0 branch
    - started:
    - expected failures: none
    - unexpected failures: 
    - completed:
  - [x] 20.0 branch
    - started:
    - expected failures: 
        - `dopinder` - Google TV Box, so no `vendor/partner_gms-tv/products/gms_minimal.mk` file
    - unexpected failures: 
        - `lmi` - errors building kernel
    - completed: [Sat Mar  16 07:02:39 UTC 2024] 
  - [x] no 19.1 branch devices
  - [x] 18.1 branch
     - started: [Sat Mar  16 07:32:39 UTC 2024] 
     - expected failures: none
     - unexpected failures: none
     - completed: [Tue Mar 19 13:28:51 UTC 2024]
  - [ ] retry failed 21.0 builds
      - started: [Tue Mar 19 16:09:04 UTC 2024]
     - expected failures: none
     - unexpected failures:
     - completed:
  - [ ] 18.1 unofficial devices: (z3tc,z3tcw)
    - started:
    - expected failures: none
    - unexpected failures: 
    - completed:
  - [ ] 21.0 unofficial devices: (lilac,poplar,poplar_dsds,maple,maple_dsds)
    - started:
    - expected failures: none
    - unexpected failures: 
    - completed:
- completed:

**Comment by petefoth** [comment]
*Sat 09 Mar 24*
- 21.0 builds OK up to `joan`
- `kane` failed with error
```
FAILED: out/target/product/kane/obj/ETC/build-manifest_intermediates/build-manifest.xml
/bin/bash -c "(mkdir -p out/target/product/kane/obj/ETC/build-manifest_intermediates/ ) && (python3 .repo/repo/repo manifest -o - -r | grep -Ev \"proprietary_\" > out/target/product/kane/obj/ETC/build-manifest_intermediates/build-manifest.xml )"
Traceback (most recent call last):
  File "/srv/src/LINEAGE_21_0/.repo/repo/git_command.py", line 460, in _RunCommand
    p = subprocess.Popen(
  File "internal/stdlib/subprocess.py", line 966, in __init__
  File "internal/stdlib/subprocess.py", line 1842, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/srv/src/LINEAGE_21_0/packages/apps/SimpleSettingsConfig'
```
- so did all following builds
- possibly [this commit](https://github.com/LineageOS/android_packages_apps_SimpleSettingsConfig/commit/6d87e7a264bce0b0f7fc01538aa09e545858c4e0). Need to repo sync.  and start the builds again  for kane-Z01R (these builds should all sync)
- 21.0 builds synched for `

**Comment by petefoth** [comment]
kane build dies again
```
[ 97% 166953/171660] //frameworks/base/services/core:services.core.unboosted javac29 [common]
posix_spawn: Argument list too long
20:22:04 ninja failed with: exit status 1

#### failed to build some targets (02:32:59 (hh:mm:ss)) ####
>> [Sat Mar  9 20:22:04 UTC 2024] Failed build for kane
```
- I remember seeing this a long time ago - can;t remember how I got round it, have to go digging
- see what happens with subsequent builds

**Comment by petefoth** [comment]
*Sun 10 Mar 24*
- all 21.0 build failing with same error - give upfor now. Maybe make 20.0 uilds when the other branches are done
- try building the remaining branches

**Comment by ToughDBlue** [comment]
Installed 21.0 build for my wife's OnePlus 7T (hotdogb). Works great!! In fact, I believe I figured out the location services issue where it was off by at least 100 miles on every app but maps app.  She had /e/ OS before and I currently have upstream LOS 21 on my Pixel 7 (Panther), both of which had microG 0.3.0.233515. LOS for microG uses the current stable version of microG (0.2.27.223616) and Locations Services are correct in all apps! hurray! PLEASE don't put the latest version of microG in LOS for microG!! :)

**Comment by ToughDBlue** [comment]
@glemco Doesn't matter where I go it's off by a good 50-100 miles. I'm in the US and even visited a major city and it was off by 50 miles. No problems with 0.2.7. According to the microG website 0.2.7 is the official stable version. I did report this on the microG Github a few days ago. No replies yet. Is there no way to change the NLP back ends in version 0.3.0?

**Comment by glemco** [comment]
@ToughDBlue I don't think so but you can enable some kind of caching (I guess something like what the Dejavu backend was doing, you can try that but it'll work only in places where you've been before), but let's not spam this issue since your topic is unrelated. MicroG's folks would for sure know how to support you better

**Comment by petefoth** [comment]
Here is the current status of the March build run
1. 21.0 builds started to fail after successfully building devices up to `joan`. This is caused by upstream changes which have 'broken' our build engine for 21.0 builds. I have some ideas how to fix this, but they will need time to test
2. 20.0 builds are in progress, and seem to be going OK
3. 18.1 builds will be started when the 20.0 builds complete, followed by unofficial 18.1 builds (for `z3tc` and `z3tcw`)
4. After that, if I have a working for for 1, then i will make the unofficial 21.0 builds (`lilac, poplar, poplar_dsds, maple, maple_dsds`)
5. I ***may*** then retry the 21,0 builds for the devices that failed in 1, or I may leave it until April's build run. That will depend on how long the previous steps take

**Comment by petefoth** [comment]
- 20.0 build of `lmi` failed with kernel build errors
- [LOS `/android_kernel_xiaomi_sm8250` repo](https://github.com/LineageOS/android_kernel_xiaomi_sm8250) was [updated 3 days ago](https://github.com/LineageOS/?q=sm8250&type=all&language=&sort=)
```
../../../../../../kernel/xiaomi/sm8250/drivers/scsi/ufs/ufshcd.c:8510:18: error: unused variable 'lun' [-Werror,-Wunused-variable]
../../../../../../kernel/xiaomi/sm8250/drivers/scsi/ufs/ufshcd.c:8581:1: error: unused label 'skip_unit_desc' [-Werror,-Wunused-label]
../../../../../../kernel/xiaomi/sm8250/drivers/scsi/ufs/ufshcd.c:8512:6: error: unused variable 'd_lu_wb_buf_alloc' [-Werror,-Wunused-variable]
3 errors generated.
make[4]: *** [/srv/src/LINEAGE_20_0/kernel/xiaomi/sm8250/scripts/Makefile.build:338: drivers/scsi/ufs/ufshcd.o] Error 1
make[3]: *** [/srv/src/LINEAGE_20_0/kernel/xiaomi/sm8250/scripts/Makefile.build:642: drivers/scsi/ufs] Error 2
make[2]: *** [/srv/src/LINEAGE_20_0/kernel/xiaomi/sm8250/scripts/Makefile.build:642: drivers/scsi] Error 2
make[1]: *** [/srv/src/LINEAGE_20_0/kernel/xiaomi/sm8250/Makefile:1216: drivers] Error 2
make: *** [Makefile:153: sub-make] Error 2
```

**Comment by petefoth** [comment]
*Thu 14 Mar 24*
 - 20.0 build of `miatoll` failed 
 -  kernel repo`android_device_xiaomi_sm6150-common ` updated 2 days ago - retry later
```
[  1% 1912/153211] target Generated: audio_kernel_headers_32 <= kernel/motorola/sm6150/techpack/audio/4.0/include/uapi/linux/avtimer.h
FAILED: out/target/product/miatoll/obj/vendor/qcom/opensource/audio-kernel/include/linux/avtimer.h
/bin/bash -c "\$(cd out/target/product/miatoll/obj/KERNEL_OBJ; ../../../../../../../kernel/msm-4.14/scripts/headers_install.sh ../../../../../../../out/target/product/miatoll/obj/vendor/qcom/opensource/audio-kernel/include/linux/ ../../../../../../../kernel/motorola/sm6150/techpack/audio/4.0/include/uapi/linux/ avtimer.h)"
/bin/bash: line 1: ../../../../../../../kernel/msm-4.14/scripts/headers_install.sh: No such file or directory
[  1% 1913/153211] target Generated: audio_kernel_headers_32 <= kernel/motorola/sm6150/techpack/audio/4.0/include/uapi/linux/avtimer.h
FAILED: out/target/product/miatoll/obj/vendor/qcom/opensource/audio-kernel/include/linux/mfd/wcd9xxx/wcd9320_registers.h
/bin/bash -c "\$(cd out/target/product/miatoll/obj/KERNEL_OBJ; ../../../../../../../kernel/msm-4.14/scripts/headers_install.sh ../../../../../../../out/target/product/miatoll/obj/vendor/qcom/opensource/audio-kernel/include/linux/mfd/wcd9xxx/ ../../../../../../../kernel/motorola/sm6150/techpack/audio/4.0/include/uapi/linux/mfd/wcd9xxx/ wcd9320_registers.h)"
/bin/bash: line 1: ../../../../../../../kernel/msm-4.14/scripts/headers_install.sh: No such file or directory

```

**Comment by petefoth** [comment]
- 20.0 build of `vayu` failed
```
[  1% 1953/154776] target Generated: audio_kernel_headers_32 <= kernel/motorola/sm6150/techpack/audio/include/uapi/linux/avtimer.h
FAILED: out/target/product/vayu/obj/vendor/qcom/opensource/audio-kernel/include/linux/avtimer.h
/bin/bash -c "\$(cd out/target/product/vayu/obj/KERNEL_OBJ; ../../../../../../../kernel/msm-4.14/scripts/headers_install.sh ../../../../../../../out/target/product/vayu/obj/vendor/qcom/opensource/audio-kernel/include/linux/ ../../../../../../../kernel/motorola/sm6150/techpack/audio/include/uapi/linux/ avtimer.h)"
/bin/bash: line 1: cd: out/target/product/vayu/obj/KERNEL_OBJ: No such file or directory
/bin/bash: line 1: ../../../../../../../kernel/msm-4.14/scripts/headers_install.sh: No such file or directory
```
- 'wade' failure expected - it's a tv device

**Comment by petefoth** [comment]
*Sat 16 Mar 24*
- 20.0 builds completed Mar 16, 2024, 07:02:16
- 18.1 builds started, Mar 16, 2024, 07:33:36:33

**Comment by ivangal2** [comment]
> 20.0 builds completed Mar 16, 2024, 07:02:16

Hi @petefoth , dozens of 20.0 builds haven't completed, e.g. lemonade (and builds alphabetically around). Is there a plan to run them eventually? Thanks.

**Comment by petefoth** [comment]
lemonade has been 'promoted" to 21, and was one if the casualties of the 21 build failures reported above.
As mentioned above
> I may then retry the 21,0 builds for the devices that failed in 1, or I may leave it until April's build run. That will depend on how long the previous steps take

**Comment by ivangal2** [comment]
Thanks for the info. Is there a list of 20 vs 21 devices?

**Comment by petefoth** [comment]
https://github.com/LineageOS/hudson/blob/main/lineage-build-targets

**Comment by petefoth** [comment]
*Tue 19 Mar 24*
- Final 18.1 builds complete
- Retrying missed 21.0 devices

**Comment by petefoth** [comment]
*Wed 20 Mar 24*
- Failed build ` m5_tab`and all subsequent devices
- m5_tab error
```
19:08:09 Build sandboxing disabled due to nsjail error.
build/make/core/config.mk:842: error: When PRODUCT_SHIPPING_API_LEVEL >= 28, TARGET_USES_64_BIT_BINDER must be true.
19:08:12 dumpvars failed with: exit status 1
19:08:13 Build sandboxing disabled due to nsjail error.
build/make/core/config.mk:842: error: When PRODUCT_SHIPPING_API_LEVEL >= 28, TARGET_USES_64_BIT_BINDER must be true.
19:08:13 dumpvars failed with: exit status 1
```
- subsequent builds fail with different errors: blow everything away and start again from `marlin` (go back to `m5_tab,m52xq`)

**Comment by petefoth** [comment]
*Thu 21 Mar 24*
- Clean builds failing with this build error during `soong bootstrap`
```
[ 96% 137/142] compile out/host/linux-x86/bin/go/soong-api/pkg/android/soong/api.a
FAILED: out/host/linux-x86/bin/go/soong-api/pkg/android/soong/api.a
....
frameworks/base/api/api.go:64:10: undefined: android.BazelModuleBase
frameworks/base/api/api.go:357:10: undefined: android.InitBazelModule
frameworks/base/api/api.go:384:25: undefined: android.BazelLabelForModuleDepSingle
frameworks/base/api/api.go:391:47: undefined: android.BazelLabelForModuleDeps
frameworks/base/api/api.go:402:7: ctx.CreateBazelTargetModule undefined (type android.TopDownMutatorContext has no field or method CreateBazelTargetModule)
frameworks/base/api/api.go:402:46: undefined: android.CommonAttributes
```
- try just one build `marlin` so I can check `out/` directory after failed build

**Comment by petefoth** [comment]
I need to make a test build, to test [merge of `experimental` branch to `master`](https://github.com/lineageos4microg/docker-lineage-cicd/pull/579/). I'll build `lmi` as that failed in the earlier run

**Comment by petefoth** [comment]
Closing: the March build run is done, and April is here 😄 see #596
