### ISSUE TITLE
Android 11 / LineageOS 18.1 EOL

### ISSUE THREAD

**Issue by ghost** [lineageos4microg/docker-lineage-cicd#581]
https://review.lineageos.org/q/topic:%22RIPLegacy%22

**Comment by petefoth** [comment]
> https://review.lineageos.org/q/topic:%22RIPLegacy%22

Thanks. So, depending on how quickly that change gets approved upstream, the upcoming 18.1 build may be the last one. This will affect the following devices:
`a5y17lte,a7y17lte,addison,ahannah,albus,bacon,castor,castor_windy,cedric,debx,ether,flox,foster,foster_tab,FP2,ginkgo,griffin,hannah,hlte,hltechn,hltekor,hltetmo,jactivelte,jflteatt,jfltespr,jfltevzw,jfltexx,jfvelte,klte,klteactivexx,klteaio,kltechn,kltechnduo,klteduos,kltedv,kltekdi,kltekor,montana,oneplus3,porg,porg_tab,rhannah,s3ve3gds,s3ve3gjv,s3ve3gxx,shamu,sirius,victara,x2,z3,z3c,zl1`

In my latest thinking on #557, what should happen after the final build is:
- the  final ***two*** builds will be available in the usual download directory, for at least one month. This give time for current users to update OTA to the final build,, and for anyt problems with the final build to be noticed;
- after that time, the final build will be moved to [the `archive` directory on the download server](https://download.lineage.microg.org/archive/), for 'new' users to find and use.
- the final build will be available in the `archive` directory for as long as there is sufficient storage space available on the download server.

**Comment by petefoth** [comment]
> has been merged.

So this month's builds ***will*** be the final 18.1 builds

**Comment by petefoth** [comment]
I'll close this when the 18.1 builds have been moved to https://download.lineage.microg.org/archive/

**Comment by petefoth** [comment]
All 18.1 builds have now been moved to https://download.lineage.microg.org/archive/
