### ISSUE TITLE
[Tissot/Xiaomi Mi A1] The OTA Update provides a "LineageOS 16.0 20190724" build that is already installed

### ISSUE THREAD

**Issue by ghost** [lineageos4microg/docker-lineage-cicd#59]
![OTA Update](https://user-images.githubusercontent.com/54710734/65071042-77382200-d996-11e9-833f-c2fbc8cd2998.png)

The OTA Update provides a `lineage-16.0-20190724-microG-tissot.zip` build from `https://download.lineage.microg.org/ota/full/tissot/lineage-16.0-20190724-microG-tissot.zip` URL. The build is already installed because it is the latest build.

**Comment by ghormoon** [comment]
I've also just tried to install it, the website says there are OTA updates every week, but the dowlnoads page gives out only this 2 months old build, the OTA updates the same ... is it that the builds run only for some devices and not for all anymore?

**Comment by Korsola** [comment]
> but the dowlnoads page gives out only this 2 months old build

That is a different "issue". There weren't any LineageOS (for microG) builds for a while because TheMuppets repo went down. It is now fixed on LineageOS side, now just @corna needs to build/fix it up on LineageOS for microG side. Follow this issue:
https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/issues/19

**Comment by corna** [comment]
Duplicate, closed

**Comment by ghormoon** [comment]
i've tried updating to current build, the build itself installs fine, but this issue as described originally also persists. it shows the button to  install it again, if i delete it, it shows button to download it again

**Comment by Oooppeli** [comment]
@corna 

This issue should probably be reopened.
