### ISSUE TITLE
21.0 builds failing - upstream issue with LineageOS

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#592]
The build run for remaining 21.0 devices failed while building `m5_tab`,  and all subsequent builds failed with a different error (see https://github.com/lineageos4microg/docker-lineage-cicd/issues/578#issuecomment-2010654772).

<details><summary>`m5_tab` error</summary>
```
19:08:09 Build sandboxing disabled due to nsjail error.
build/make/core/config.mk:842: error: When PRODUCT_SHIPPING_API_LEVEL >= 28, TARGET_USES_64_BIT_BINDER must be true.
19:08:12 dumpvars failed with: exit status 1
19:08:13 Build sandboxing disabled due to nsjail error.
build/make/core/config.mk:842: error: When PRODUCT_SHIPPING_API_LEVEL >= 28, TARGET_USES_64_BIT_BINDER must be true.
19:08:13 dumpvars failed with: exit status 1
```

</details>

Starting from a clean `srv/src/` all builds fail with the following error during `soong bootstrap`
```
[ 96% 137/142] compile out/host/linux-x86/bin/go/soong-api/pkg/android/soong/api.a
FAILED: out/host/linux-x86/bin/go/soong-api/pkg/android/soong/api.a
....
frameworks/base/api/api.go:64:10: undefined: android.BazelModuleBase
frameworks/base/api/api.go:357:10: undefined: android.InitBazelModule
frameworks/base/api/api.go:384:25: undefined: android.BazelLabelForModuleDepSingle
frameworks/base/api/api.go:391:47: undefined: android.BazelLabelForModuleDeps
frameworks/base/api/api.go:402:7: ctx.CreateBazelTargetModule undefined (type android.TopDownMutatorContext has no field or method CreateBazelTargetModule)
frameworks/base/api/api.go:402:46: undefined: android.CommonAttributes
```
- Internet search doesn't give any clues :(

**Comment by petefoth** [comment]
- try just one build `marlin` so I can check `out/` directory after failed build

**Comment by SANYIQIN** [comment]
Check LineageOS Gerrit, they seems didnt push fixes yet

**Comment by petefoth** [comment]
Thanks. I don't really know my way around gerrit: can you point me at a specific change so that I can track it?

**Comment by SANYIQIN** [comment]
> Thanks. I don't really know my way around gerrit: can you point me at a specific change so that I can track it?

https://review.lineageos.org & I dont actully know which patches is needed LOL

**Comment by SANYIQIN** [comment]
> Thanks. I don't really know my way around gerrit: can you point me at a specific change so that I can track it?

https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/385560 take this may fix

**Comment by notstarboard** [comment]
> Thanks. I don't really know my way around gerrit: can you point me at a specific change so that I can track it?

I don't either, but [this](https://review.lineageos.org/c/LineageOS/android_vendor_lineage/+/383589) looks promising. They're modifying a make file with "soong" in the name and the description specifically references marlin. It's hard to be sure though since I can't see any linked bug report.

**Comment by petefoth** [comment]
This is part of a wider problem: building LOS 21.0 is currently completely broken, due to the March 2024 Quarterly Platform Release and Security update from Android. See this XDA forum post for more details

https://xdaforums.com/t/lineageos-for-microg.3700997/post-89416684

**Comment by steffenWi** [comment]
There is a build for the nio device from the 18th of March 2024 that fixes a big issue that has plagued the nio since the start of the year. Would it be possible to trigger a build for this? See https://xdaforums.com/t/rom-official-lineageos-21-for-edge-s-moto-g100.4650662/page-9#post-89424951 and https://gitlab.com/LineageOS/issues/android/-/issues/6675#note_1819116916 not sure why the nio build went through when others seem to be failing though?

**Comment by petefoth** [comment]
> Would it be possible to trigger a build for this?

Done. It should show up in the matrix room once the repo sync has finished

> not sure why the nio build went through when others seem to be failing though?

I guess because the device maintainer has made the necessary changes to allow the build to complete. No idea what thos changes are though :)

**Comment by petefoth** [comment]
> Would it be possible to trigger a build for this?

OK the build is done (after a couple of false starts)

Please let us know of this fixes #561

**Comment by steffenWi** [comment]
Yes, I saw that, that's what the heart emoji was for. Didn't want to pollute the comment history. On a sidenote: I don't understand where exactly one should report issues with a particular image. We have 3 bug reports for one bug.

1. [this one on gitlab I linked before.](https://gitlab.com/LineageOS/issues/android/-/issues/6675)
2. [this thread on XDA forums that got replies from the maintainer of the nio image](https://xdaforums.com/t/rom-official-lineageos-21-for-edge-s-moto-g100.4650662/)
3. https://github.com/lineageos4microg/docker-lineage-cicd/issues/561 this one I was completely unaware of until just now.

**Comment by petefoth** [comment]
> On a sidenote: I don't understand where exactly one should report issues with a particular image. We have 3 bug reports for one bug.
> 
>  1. [this one on gitlab I linked before.](https://gitlab.com/LineageOS/issues/android/-/issues/6675)
>  2. [this thread on XDA forums that got replies from the maintainer of the nio image](https://xdaforums.com/t/rom-official-lineageos-21-for-edge-s-moto-g100.4650662/)
>  3. https://github.com/lineageos4microg/docker-lineage-cicd/issues/561 this one I was completely unaware of until just now.

In general, bugs with a specific device like the problem with `nio` are likely to be an issue with the upstream LineageOS (and will need to be fixed there) as this project doesn't own or maintain any device-specific code. So the bug needs to be raised upstream in either 1. or 2.
- If the device is officially supported by LOS, then I would start with 1 (gitlab), because all device maintainers should be monitoring that issue tracker. If there is an XDA forum thread for the official LOS build for the device, then I would mention it there too, for the benefit of other users of the LOS build.
- If it's an unofficial build, then raise it wherever the build maintainer hangs out

This issue tracker is really for problems specific to LineageOS for microG builds [1] It is unlikely - though not impossible - that device-specific issues will be specific to these builds, so here is probably not the correct place to raise them. If such a bug does get raised here, I will usually suggest that it is raised in either 1 or 2 as well / instead, though I probably won;t close it until the upstream fix is in place, and has been picked up in our latest build run.

[1] Actually it's only really for ***the docker image used to make the builds***, but it's one of only two public issue trackers we have [2]
[2] The [other is for the `android_vendor_partner_gms` components](https://github.com/lineageos4microg/android_vendor_partner_gms/issues) [3]
[3] But if the problem is specific to one of the microG compnents, eg. `GmsCore` - rather than how we have integrated it in our builds - the it should be raised in the relevant `microg` issue tracker e.g. https://github.com/microg/GmsCore/issues

I'm surprised that you didn't understand all that 😉

**Comment by petefoth** [comment]
21.0 builds (both for upstream LOS, and for our los4microg builds) are working now.

We will make new builds in the May build run for all the 20.0 and 21.0 devices in the [LOS build target list](https://github.com/LineageOS/hudson/blob/main/lineage-build-targets)

I'll close this issue now
