### ISSUE TITLE
Try 21.0 builds for 'Hello again, QPR2' devices

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#609]
Stopping the builds, closing the issue and removing the new builds: they may not have been tested upstream - see https://old.reddit.com/r/LineageOS/comments/1bp83tb/is_there_a_new_build_schedule/kyt9tns/

------------
[This gerrit change](https://review.lineageos.org/c/LineageOS/hudson/+/386717) (not yet approved or merged) re-enables a number of 21.0 devices in `lineage-build-targets` (see also [this commit](https://github.com/LineageOS/hudson/commit/0e3388aca39213220fadf53d8f27f28607443a89)). The devices are:
`avicii,axolotl,barbet,berlin,berlna,beryllium,bluejay,bramble,caprip,channel,cheeseburger,cheetah,coral,devon,dipper,discovery,DRG,dubai,dumpling,enchilada,equuleus,fajita,felix,flame,FP4,gta4l,gta4lwifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,hawao,hotdog,hotdogb,husky,instantnoodle,instantnoodlep,kebab,kirin,lemonade,lemonadep,lemonades,lynx,m5_tab,martini,mermaid,nio,ocean,odroidc4_tab,oriole,panther,pdx203,pdx206,pdx214,pdx215,perseus,pioneer,PL2,polaris,pro1,pro1x,pstar,radxa0_tab,raven,redfin,rhode,river,rosemary,salami,shiba,sunfish,tangorpro,TP1803,ursa,voyager,xpeng,Z01R,`

According to [this comment](https://github.com/lineageos4microg/docker-lineage-cicd/pull/608#issuecomment-2045252040) it's possible that builds for these devices may work, so worth trying.

**Comment by petefoth** [comment]
- start with`m5_tab`. It's the first device in the list that didn't get built when 21.0 builds started failing in March

**Comment by petefoth** [comment]
- succeeded: lemonadep,nio,ocean
    - failed:m5_tab,martini,mermaid
    - remove the new builds: they may not have been tested upstream - see https://old.reddit.com/r/LineageOS/comments/1bp83tb/is_there_a_new_build_schedule/kyt9tns/

**Comment by ArchangeGabriel** [comment]
@petefoth I think you got that wrong: any device added back is one that has been checked to be properly working. Those that are not re-enabled are either not tested or tested non-working/building.
