### ISSUE TITLE
Restart 21.0 builds

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#610]
Upstream builds of lineage-21.0 branch have started and:~90  21.0 devices have been re-enabled in the [build target list](https://github.com/LineageOS/hudson/blob/main/lineage-build-targets), so we'll try building them

<details><summary>Current 21.0 targets</summary>

a52q,a52sxq,a72q,a73xq,avicii,axolotl,barbet,berlin,berlna,beryllium,bluejay,bramble,caprip,channel,cheeseburger,cheetah,coral,devon,dipper,discovery,DRG,dubai,dumpling,enchilada,equuleus,fajita,felix,flame,FP4,grus,gta4l,gta4lwifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,guamp,hawao,heart,hotdog,hotdogb,husky,instantnoodle,instantnoodlep,joan,kebab,kirin,lemonade,lemonadep,lemonades,lynx,m5_tab,m52xq,martini,mermaid,Mi439,Mi8917,Mi8937,nio,ocean,odroidc4_tab,oriole,panther,pdx203,pdx206,pdx214,pdx215,perseus,pioneer,PL2,polaris,pro1,pro1x,pstar,pyxis,radxa0_tab,raven,redfin,rhode,river,rosemary,salami,shiba,sunfish,surya,tangorpro,TP1803,ursa,vela,voyager,xpeng,Z01R,zippo,

<details>

**Comment by petefoth** [comment]
**Sat 13 Apr 24**
-  as of Sat 13 Apr 24 11:38BST, the folowing devices have upstream 21.0 builds, so we'll start by building those: (`alioth` has also been built, but it's not yet in the target list so leave it for now)
bramble,pro1,dipper,mermaid,berlin,devon,rhode,dipper,bluejay,river,pdx206,gts4lvwifi,

**Comment by petefoth** [comment]
> not trying to be impatient or anything, but can you shed a bit of light on whats the issue with devices like `sargo` and similar ones which have received their last update in mid-february on v20?

The list of devices to be built - by upstream LineageOS and by this project - is maintained in [this build target list](https://github.com/LineageOS/hudson/blob/main/lineage-build-targets).

Google Pixel 3a sargo was 'promoted' to 21.0 in time for it to be included in the March build run. The builds are done alphabetically, and the last 21.0 device that was successfully built by **_this project_** before the builds started failing was
`lynx`. So every device from `m5_tab` onwards - including `sargo`- did not get a build in March. 

When the builds started failing, LineageOS disabled builds for **_all_** 21.0 devices (in [this commit](https://github.com/LineageOS/hudson/commit/f4adb0c30793cba4118a020c161bd435b4551669)) until any necessary code changes were made in the generic LineageOS and device-specific code source code.

The 21.0 builds were re-enabled ***for some devices*** - not including `sargo` - (in [this commit](https://github.com/LineageOS/hudson/commit/6eb62bd63d80a725ca859db3226ccfd91e0157a5) and [subsequent commits](https://github.com/LineageOS/hudson/commits/main/lineage-build-targets)). At that point `sargo' was not in the build target list **_for any branch_**, and that is still the case: that is why the [LOS Devices Wiki](https://wiki.lineageos.org/devices/sargo/) says
> The Google Pixel 3a is no longer maintained

even though there are 21.0 builds of LineageOS (from before the changes which broke the 21.0 builds) [available for download](https://download.lineageos.org/devices/sargo/builds)

I believe that LOS plan to 'restore' to the list of **_20.0_** targets all the devices - including `sargo` - which were on the 21.0 list but which are not currently buildable for 21.0. Some [changes have been proposed](https://review.lineageos.org/q/topic:%22return-to-20%22) for this, but they have not yet been approved or implemented, and there is no guarantee that they ever will be. That decision is up to the LOS maintainers.

_**If**_ the affected devices - including `sargo` get added back to the build target list, then they will be included in our builds in our next build run that starts after the changes have been merged to the build target list. When (and if) that happens is outside the control of this project.

> couldn't really get a good idea on what exactly it is that has to be fixed for the mentioned devices to get the v21 build

I don't know what exactly these changes were: they will probably have involved different changes for different devices, and will have been made in different places  in the [LOS project's ~2,700 git repositories](https://github.com/orgs/LineageOS/repositories).

I'm sorry that the process has been confusing, and I hope that it will get resolved in a timely manner. And I hope this post has clarified things a bit.

**Comment by tsterbak** [comment]
I just installed the new version on pyxis and as far as I can tell it works perfectly! Awesome work!

**Comment by petefoth** [comment]
> I believe that LOS plan to 'restore' to the list of **_20.0_** targets all the devices - including `sargo` - which were on the 21.0 list but which are not currently buildable for 21.0.

@kaduvert FYI the change to restore `sargo` (and other pixel 3 devices) to the 21.0 target list looks like it is nearly ready to be merged into the `main` branch - https://review.lineageos.org/c/LineageOS/hudson/+/389764 So there's a good chance it will be done before the May build run

**Comment by andsmir** [comment]
Upstream finished building gts4lv. Could you be so kind to re-enable build?

**Comment by petefoth** [comment]
`gts4lv` got a 21.0 build in the March build run. It will get another in the May build run

**Comment by andsmir** [comment]
Okay, got it. March build was a little bit buggy, there was some problems with vp9 hardware acceleration in some apps and with custom keyboards. It's not urgent, anyway.

**Comment by petefoth** [comment]
> _**If**_ the affected devices - including `sargo` get added back to the build target list, then they will be included in our builds in our next build run that starts after the changes have been merged to the build target list. When (and if) that happens is outside the control of this project.

The Pixel 3 devices got restored to the 21.0 build target list in [this commit](https://github.com/LineageOS/hudson/commit/8d12267ae572e62dfbf61a90d4ad41186ea6b50d), so they should get 21.0 los4microG builds in the May build run

**Comment by Komprogue** [comment]
> Google Pixel 3a sargo was 'promoted' to 21.0 in time for it to be included in the March build run. The builds are done alphabetically, and the last 21.0 device that was successfully built by **_this project_** before the builds started failing was
> `lynx`. So every device from `m5_tab` onwards - including `sargo`- did not get a build in March.



> The 21.0 builds were re-enabled _**for some devices**_ - not including `sargo` - (in [this commit](https://github.com/LineageOS/hudson/commit/6eb62bd63d80a725ca859db3226ccfd91e0157a5) and [subsequent commits](https://github.com/LineageOS/hudson/commits/main/lineage-build-targets)). At that point `sargo' was not in the build target list **_for any branch_**, and that is still the case: that is why the [LOS Devices Wiki](https://wiki.lineageos.org/devices/sargo/) says
> 
> > The Google Pixel 3a is no longer maintained
> 
> even though there are 21.0 builds of LineageOS (from before the changes which broke the 21.0 builds) [available for download](https://download.lineageos.org/devices/sargo/builds)

I suppose it's the same story with [Pixel 2](https://wiki.lineageos.org/devices/walleye/). 21th build had been sucessfully made by an official LOS in the [end of February](https://download.lineageos.org/devices/walleye/builds) (and now it's marked as "unsupported" anymore, but ROM images are still downloadable), though 21th build of **LOS4mG** was failed and device now stuck based on last 20th build from February.

**Comment by petefoth** [comment]
> suppose it's the same story with [Pixel 2](https://wiki.lineageos.org/devices/walleye/). 21th build had been sucessfully made by an official LOS in the [end of February](https://download.lineageos.org/devices/walleye/builds) (and now it's marked as "unsupported" anymore, but ROM images are still downloadable), though 21th build of **LOS4mG** was failed and device now stuck based on last 20th build from February.

It looks as though the plan is for LOS to revert to 20.0 devices for `walleye` and other devices which do not yet support 21.0 after the QPRS changes: see [this change](https://review.lineageos.org/c/LineageOS/hudson/+/389423) (which has not yet been implemented or approved upstream). 

If / when the change is implemented, the affected devices will be included in our builds in our next build run that starts after the changes have been merged to the build target list.

**Comment by petefoth** [comment]
All our planned 21.0 builds for this month have succeeded, and al devices which support 21.0 should now have a buuld available, either from this month, or the pre-QPRS March build run.

Updates will appear in our next scheduled build run in May 

Closing this issue

**Comment by Komprogue** [comment]
> > suppose it's the same story with [Pixel 2](https://wiki.lineageos.org/devices/walleye/). 21th build had been sucessfully made by an official LOS in the [end of February](https://download.lineageos.org/devices/walleye/builds) (and now it's marked as "unsupported" anymore, but ROM images are still downloadable), though 21th build of **LOS4mG** was failed and device now stuck based on last 20th build from February.
> 
> It looks as though the plan is for LOS to revert to 20.0 devices for `walleye` and other devices which do not yet support 21.0 after the QPRS changes: see [this change](https://review.lineageos.org/c/LineageOS/hudson/+/389423) (which has not yet been implemented or approved upstream).
> 
> If / when the change is implemented, the affected devices will be included in our builds in our next build run that starts after the changes have been merged to the build target list.

By the way, found this explanation from developer or the [official LOS ROM](https://xdaforums.com/t/official-lineageos-21-for-the-google-pixel-2.4649873/):

![LOS](https://github.com/lineageos4microg/docker-lineage-cicd/assets/84424346/1c53d7e8-a630-4273-a27b-c9d25a917f3e)
