### ISSUE TITLE
Fajita build and download

### ISSUE THREAD

**Issue by Alixerid** [lineageos4microg/docker-lineage-cicd#62]
This device is in the list of [build targets](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets) but not available as download.

On the [XDA thread](https://forum.xda-developers.com/android/software/lineageos-microg-t3700997) it was mentioned that there were "build errors" for this device. That's why I tried to build it myself using these parameters:
```
docker run \
    -e "BRANCH_NAME=lineage-16.0" \
    -e "DEVICE_LIST=fajita" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -v "/media/LOS4mg/src:/srv/src" \
    -v "/media/LOS4mg/zips:/srv/zips" \
    -v "/media/LOS4mg/logs:/srv/logs" \
    -v "/media/LOS4mg/cache:/srv/ccache" \
    -v "/media/LOS4mg/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
```
That was successful. I did not find errors in the logs. I flashed the zip and everything including microG and unifiedNLP is working. (As far as I understand, the parameters are close to standard for Lineage for microG.) 
 
Could someone let me know what the errors are? Also, is there some place to find the build logs?

**Comment by tobiasKaminsky** [comment]
Same for me.
It works fine here.

@corna (as I saw that you are quite active here).
Can you give us an hint whom we can "bug"/ping that fajita become an official microg build? :heart:

**Comment by corna** [comment]
I'm that person ;)
I will have a look, as soon as I have some spare time

**Comment by tobiasKaminsky** [comment]
@corna thanks for your reply.
If you need any help, please do not hesitate to ping me, maybe I can help you / test something.

**Comment by tobiasKaminsky** [comment]
@corna I do not want to hurry you, but do you have an ETA for checking?
If this is too long/uncertain, I will migrate LineageOS to my private build and do manual updates from time to time.
But then I have to switch to the official ones, which is additional work, which I do like to skip.

**Comment by corna** [comment]
I don't have an ETA unfortunately.
The error we have is:

```
ERROR: Could not open package path device/oneplus/common/interfaces/fingerprint/extension/1.0/ for package vendor.oneplus.fingerprint.extension@1.0:
/srv/src/LINEAGE_16_0/device/oneplus/common/interfaces/fingerprint/extension/1.0/
sbox command (/srv/tmp/merged/out/soong/host/linux-x86/bin/hidl-gen -d /srv/tmp/merged/out/soong/.temp/sbox093901857/vendor/oneplus/fingerprint/extension/1.0/IVendorFingerprintExtensions.h.d -o /srv/tmp/merged/out/soong/.temp/sbox093901857 -Lc++-headers -randroid.hidl:system/libhidl/transport -rvendor.oneplus:device/oneplus/common/interfaces vendor.oneplus.fingerprint.extension@1.0) failed with err "exit status 1"
```

As soon as the build server is not busy (this weekend probably) I'll try to clean all the mirror sources and caches and see it the problem persists.

**Comment by winst0nsmith** [comment]
i appreciate the work of all the developers and volunteers involved in the lineageos for microg project. thank you very much!

any movement on this build? if some users are able to build their own images, i suppose i could do the same, but having never built a custom rom the learning curve might be too steep for me. i'd rather have an official build.

**Comment by tobiasKaminsky** [comment]
@winst0nsmith it is not that hard, it is mainly running docker:
```
docker run \
    -e "BRANCH_NAME=lineage-16.0" \
    -e "CLEAN_AFTER_BUILD=false" \
    -e "DEVICE_LIST=fajita" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -v "/mnt/mount/fajita/src:/srv/src" \
    -v "/mnt/mount/fajita/zips:/srv/zips" \
    -v "/mnt/mount/fajita/logs:/srv/logs" \
    -v "/mnt/mount/fajita/keys:/srv/keys" \
    -v "/mnt/mount/fajita/cache:/srv/ccache" \
    -v "/mnt/mount/fajita/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
``` 

Please adjust the "mnt/mount" path

@corna I run this every week and update my device, so far no problems.

**Comment by Yanagibashi004** [comment]
@tobiasKaminsky is there a guide somewhere on how to run docker in windows? I have no idea what I'm doing and just popping that into powershell after installing docker didn't do the trick.

**Comment by tobiasKaminsky** [comment]
No idea, sorry, as I only use Linux.

**Comment by Yanagibashi004** [comment]
@tobiasKaminsky got any guides for linux? ill just use virtualbox.

**Comment by tobiasKaminsky** [comment]
Best practice is to search in wiki on your desired distribution, e.g. https://wiki.archlinux.org/index.php/Docker (as I am using Arch btw)

Then you can do a small test and after that fire up https://github.com/lineageos4microg/docker-lineage-cicd/issues/62#issuecomment-558012222

**Comment by edern-appere** [comment]
I just got a fajita device and wanted to install the magical Lineage+MicroG built but it is not available in the repository :-( I was waiting for it since tuesday, I hopefully found this thread.

I'm really  not a developper so trying to figure out how docker works and then how to make a built by myself is totaly out of my reach. 

Is there any way I can install the classic LineageOs and then install MicroG on top of it ? 
or maybe someone that successfully made a built can share it so I can install it on my device ?
Thanks a lot for your help !

**Comment by tobiasKaminsky** [comment]
I can share mine later today, but of course without any support / guarantee.
However it works very well for me.

**Comment by edern-appere** [comment]
Thansk @tobiasKaminsky for your proposal.

Since I wrote my message I realized that if I install your build, there won't be any updates since Fajita does not work on MicroG repo, so I guess it's safer to stick with standard LineageOs until @corna works out the issue on the server ?

If I replace standard LineageOs with your built, I guess it will wipe all my data ?

**Comment by tobiasKaminsky** [comment]
There is a key migration script available, so you can switch between every version (with caution).

https://wiki.lineageos.org/signing_builds.html#using-a-script

**Comment by tobiasKaminsky** [comment]
https://nextcloud.kaminsky.me/s/6nNYAdjKbkHxYs4

md5sum: c3a99530d93519b3ad0385d0cf3d5e84  lineage-16.0-20191209-UNOFFICIAL-fajita.zip

Usual disclaimer: do it on your own risk, I am not responsible for any damages to your phone, cat, etc ;-)

**Comment by edern-appere** [comment]
Hi Tobias,

Thanks a lot for your built !!
I installed it on top of my previous LineageOS and it works like a charm. I only have a problem with one specific app but I think it must be on my side.

**Comment by edern-appere** [comment]
Well, after a couple hours of usage it turns out I was overly optimistic : neither the Wifi nor the Fingerprint reader works :-(
I'm considering switching back to standard LineageOs built (which had both wifi+FP reader working) but don't know if it's possible, considering the migration keys I had to install :-/

**Comment by tobiasKaminsky** [comment]
Hm. For me both is working quite fine, since ~6 weeks.

**Comment by edern-appere** [comment]
Just to clarify : you did a clean install of a Lineage+MicroG built or a migration from a standard LineageOs built ? And have you installed lineage's addonsu ?
I installed addonsu yesterday and went into recovery bootloop but I repaired it thanks to the twrp fonction "Repair recovery bootloop". That might have caused the wifi to stop working. 
I guess the very best way to go is to wipe everything and make a clean fresh install...

**Comment by Alixerid** [comment]
Wifi and fingerprint sensor stopped working for me as soon as I installed SU addon or TWRP. So I am still without these 2.

**Comment by tobiasKaminsky** [comment]
I upgraded from LineageOS to my microG version.
I do not have su addon.

**Comment by edern-appere** [comment]
Thanks @Alixerid for the tip. I will try removing su addon and figure out if it brings back the WiFi and fingerprint reader. It will be quicker than having to make a fresh install.

I think it can be useful if I report this bug upstream to the lineageos team. 

I installed su add-on in order to use oandbackup app which is really nice to backup and restore apps. I guess I will have to find another solution then. I heard that it is possible to make backups using adb. Less convenient but if it does the job...

**Comment by spinningD20** [comment]
Hey @edern-appere , I'll be setting up docker and getting that going, but I am curious if you tracked down the cause of the wifi, etc no longer working with su or twrp?  Figured I would ask before I install it on the device :)

**Comment by edern-appere** [comment]
Hi @spinningD20 ,
I'm not an android developper (only LineageOs user) so I cannot track why wifi and fingerprint reader did not work with addonsu, sorry. I wiped everything and installed standard LineageOs with addonsu and everything works out of the box. So, no microg for me...
I think it might be valuable to try with other means of getting su on the lineage+microg built like installing Magisk instead of addonsu. I heard on XDA that Lineage team might drop support for addonsu...
Good luck !

**Comment by edern-appere** [comment]
Also, because of christmas holidays I don't have time right now to post a bug report for the addonsu bug with wifi and fingerprint reader. Contrary to what I posted earlier this month, I don't think this issue has to do with LineageOS upstream but with the Lineage+microg built. So this should be reported here instead of upstream.

**Comment by nworb-cire** [comment]
Hi, I am unsure if this is related to the original build error that this thread is originally about. I can successfully create and run my own build, but the extra packages don't seem to come pre-installed. I have tested another build I found on XDA and they work fine on it. I am using a command almost identical to the one @tobiasKaminsky shared above:
```
docker run -d \
    -e "BRANCH_NAME=lineage-16.0" \
    -e "CLEAN_AFTER_BUILD=false" \
    -e "DEVICE_LIST=fajita" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -e "OTA_URL=http://mywebsite/" \
    -v "/home/me/fajita/src:/srv/src" \
    -v "/home/me/fajita/zips:/srv/zips" \
    -v "/home/me/fajita/logs:/srv/logs" \
    -v "/home/me/fajita/keys:/srv/keys" \
    -v "/home/me/fajita/cache:/srv/ccache" \
    -v "/home/me/fajita/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
```
There's nothing noteworthy in the docker log; it even says it is building the image with them. Does anyone have any idea why none of the custom packages would be working?

**Comment by Alixerid** [comment]
@nworb-cire, if you want to include custom packages in the build you also need to add a `manifest.xml` file, see [this example in the readme](https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/README.md#build-for-angler-lineage-151-officially-supported-custom-keys-restricted-signature-spoofing-with-integrated-microg-and-fdroid). I missed that first, too.

For anyone who needs SU, you can include it in the build via the switch `-e "WITH_SU=true"` and wifi, fingerprint etc will work.

**Comment by mihaisumedre** [comment]
@corna Hi Nicholas. Any chance for the fajita build soon? It seems that this would make a lot of people happy... :p Thanks!

**Comment by tobiasKaminsky** [comment]
I built a new version: https://nextcloud.kaminsky.me/s/zmpjYC3TCdSYZXi

**Comment by Lemm99** [comment]
> I built a new version: https://nextcloud.kaminsky.me/s/zmpjYC3TCdSYZXi

is there any possible way you can provide a step by step of how to build it? the reason i ask is for a few reasons. 1) i don't know how to build it. 2) lineage4microg obviously isn't going to fix the build issues, we've been waiting forever. 3) i don't want to bother you every week for a build. 4) lineage regular + nanodroid sig patcher doesn't work.

thank you so much

**Comment by tobiasKaminsky** [comment]
https://github.com/lineageos4microg/docker-lineage-cicd/issues/62#issuecomment-558012222

This is what I am doing.
As I do not need root/other specific, it is a very simple build command.

**Comment by tobiasKaminsky** [comment]
In https://nextcloud.kaminsky.me/s/zmpjYC3TCdSYZXi you can find now a 17.1 build.
Caution: A direct upgrade did NOT worked for me! I had to do a factory reset.
Additionally I used a twrp version for Android 10 (Q), which is also available in the above link.

**Comment by mihaisumedre** [comment]
@tobiasKaminsky Thank you, Tobias! I guess this is an unofficial build of Lineage (not taliking about microg), as it has not appeared on their site, right? How is it running so far?

**Comment by tobiasKaminsky** [comment]
Yes, totally unofficial and no responsibility for anything ;-)
I am running it since two days and it is very stable.

**Comment by mihaisumedre** [comment]
Hi @tobiasKaminsky. Hope you are alright and can still supply us with image updates! ;) Any chance for an update to L17? I'm also uncomfortable to always ask you for updates, have seen the posted docker build command but, as I have never done this, am not sure where to start and what's needed to place all puzzle pieces together. Maybe, if time permits you could write a short bullet list with the process, so that I, and others, could do it ourselves.
Thanks again for your contribution, Tobias! Regards, Mihai.

**Comment by tobiasKaminsky** [comment]
@mihaisumedre no problem for pinging me :-)
I created a fresh new build

**Comment by github-n00b** [comment]
@tobiasKaminsky do you use this command for your 17.1 builds?
```
docker run \
    -e "BRANCH_NAME=lineage-17.1" \
    -e "CLEAN_AFTER_BUILD=false" \
    -e "DEVICE_LIST=fajita" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -v "/mnt/mount/fajita/src:/srv/src" \
    -v "/mnt/mount/fajita/zips:/srv/zips" \
    -v "/mnt/mount/fajita/logs:/srv/logs" \
    -v "/mnt/mount/fajita/keys:/srv/keys" \
    -v "/mnt/mount/fajita/cache:/srv/ccache" \
    -v "/mnt/mount/fajita/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
```
I'm trying to run it on Windows but run into a 403 error like this #74 . Unfortunately I'm not nearly experienced enough doing any of this stuff, to fix that error as described in that issue. Did you run into this?

Here's the full docker log:
```
Set cache size limit to 50.0 GB
>> [Mon Apr  6 12:23:06 UTC 2020] Branch:  lineage-17.1
>> [Mon Apr  6 12:23:06 UTC 2020] Devices: fajita,
>> [Mon Apr  6 12:23:06 UTC 2020] (Re)initializing branch repository
>> [Mon Apr  6 12:23:11 UTC 2020] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Mon Apr  6 12:23:11 UTC 2020] Can't find a matching branch on github.com/TheMuppets, using lineage-15.1
Traceback (most recent call last):
  File "/root/build_manifest.py", line 36, in <module>
    source_manifest = urlopen(args.url).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
>> [Mon Apr  6 12:23:12 UTC 2020] Syncing branch repository
/root/build.sh: line 145: [: $(PLATFORM_VERSION.$(TARGET_PLATFORM_VERSION)): binary operator expected
/root/build.sh: line 153: [: $(PLATFORM_VERSION
$(TARGET_PLATFORM_VERSION): integer expression expected
/root/build.sh: line 158: [: $(PLATFORM_VERSION
>> [Mon Apr  6 12:55:13 UTC 2020] Missing "vendor/cm", aborting
```

**Comment by mddvul22** [comment]
Can @corna please provide an update on this issue?

**Comment by tobiasKaminsky** [comment]
Do you use this one? https://github.com/lineageos4microg/docker-lineage-cicd/pull/70

**Comment by tobiasKaminsky** [comment]
Not as far as I know… :/

**Comment by subpop** [comment]
I built my own ROM using this docker image and installed it onto my device. Wifi worked until I sideloaded MinMicroG. I didn't test fingerprint reader. I'm building a new image with WITH_SU=false to see if that makes a difference.

**Comment by subpop** [comment]
FWIW, fajita is listed in the lineage-17.1 build targets, but not the lineage-16.0. It looks like it was dropped during the promotion of 17.1 (It existed as a nightly build in lineage-16.0, but no longer exists as a weekly build).

**Comment by subpop** [comment]
So I found that https://review.lineageos.org/c/LineageOS/hudson/+/271386 removed fajita from the lineage-16 list. I can't see a clear reason why in the changeset anywhere.

**Comment by mddvul22** [comment]
@subpop I'm not following what you are getting at, here.  The link you've provided is for lineage, not lineage for microg.  Still, fajita is clearly being built for lineage, every night.  See https://download.lineageos.org/fajita
Sorry, if I'm misunderstanding the point you are trying to make.

**Comment by subpop** [comment]
It's built for Lineage, yes, but only for 17.1 (I just asked in #lineage on IRC; they only support building for one platform at a time). So until this docker image can build 17.1, we won't likely see fajita images for lineageos4microg any time soon. Unless lineageos4microg supports its own list of build targets apart from hudson?

**Comment by Lemm99** [comment]
What is the new command to build 17.1? I get the same exact error as https://github.com/lineageos4microg/docker-lineage-cicd/issues/62#issuecomment-609790776

**Comment by github-n00b** [comment]
> What is the new command to build 17.1? I get the same exact error as [#62 (comment)](https://github.com/lineageos4microg/docker-lineage-cicd/issues/62#issuecomment-609790776)

If you're on Windows like I was, I suggest you try running it on a Linux system. Trying to get it to work on Windows is a waste of time. 99% of my problems dissapeared when I ran the docker on a Linux VM. Steps I took:

- Set up a Ubuntu VM with VMware
- Give it lots of diskspace, especially if you leave CCACHE enabled. I went with 500GB.
- Give it lots of RAM, 16GB at the minimum. All errors I ran into when building on the Linux VM were RAM related.
- Make a swap file for Ubuntu in case it runs out of RAM
- Clone this forked repo to your VM drive: https://github.com/SolidHal/docker-lineage-cicd
- Add the fix as described here #75 
- Build the docker image using `docker build -t docker-lineage-cicd [path of dockerfile]`
- Run the command (adjust options as needed):
```
docker run \
    -e "BRANCH_NAME=lineage-17.1" \
    -e "DEVICE_LIST=fajita" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -v "/mnt/mount/fajita/src:/srv/src" \
    -v "/mnt/mount/fajita/zips:/srv/zips" \
    -v "/mnt/mount/fajita/logs:/srv/logs" \
    -v "/mnt/mount/fajita/keys:/srv/keys" \
    -v "/mnt/mount/fajita/cache:/srv/ccache" \
    -v "/mnt/mount/fajita/manifests:/srv/local_manifests" \
    docker-lineage-cicd
```

**Comment by subpop** [comment]
I'm not able to build lineage-17.1 with this image. It fails with an error message:

```
error: hardware/google/pixel/pixelstats/Android.bp:39:1: "libpixelstats" depends on undefined module "chre_api"
error: hardware/google/pixel/pixelstats/Android.bp:39:1: "libpixelstats" depends on undefined module "chre_client"
```

**Comment by spolack** [comment]
This Device was promoted to LineageOS 17.1 which is now supported. 
This is  related to the master issue #89

**Comment by tobiasKaminsky** [comment]
Fajita did not received any update since end of January: 
https://download.lineage.microg.org/fajita/

Also the latest change seems to be on 05.02 on zl1.

Does anyone knows what happened?
