### ISSUE TITLE
2024-05-02 build used testkeys

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [lineageos4microg/docker-lineage-cicd#622]
Is that intentional? Of course signature verification is failing on the phone.

tested with beryllium

**Comment by petefoth** [comment]
Thanks, and well spotted. I introduced an error in the main build script an error in the build scripts so builds made on 1st and 2nd May were not properly signed. The affected builds have been removed from the download server and will be rebuilt.

The restarted build status run be followed in #623

**Comment by petefoth** [comment]
The new build for `beryllium` (`lineage-21.0-20240303`) is available [here](https://download.lineage.microg.org/beryllium/) and should be signed properly.
Please can you check, and close this issue if it is OK?

Thanks

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Installed it to my phone, build information shows dev keys and there was no signature warning. Seems good!
