### ISSUE TITLE
May 24 build run status

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#623]
(Note: an error in the build scripts meant that the first builds made on 1st and 2nd May were not properly signed. The affected builds have been removed from the download server and will be rebuilt

- started: 
  - [x] 21.0 branch
    - started: [Wed May  1 00:00:30 UTC 2024]
    - stopped: [Thu May  2 16:23:32 UTC 2024] - builds were unsigned
    - re-started: >> [Thu May  2 17:10:37 UTC 2024]
    - expected failures: m5, deadpool, odroidc4, pstar, radxa0, wade
    - unexpected failures: blueline, bonito, crosshatch (all Pixel 3 family)
    - `kane' build removed from download server because of [this bug](https://gitlab.com/LineageOS/issues/android/-/issues/7112)
- [x] 20.0 branch
     - started:
     - **unexpected** failures: none
     - expected failures: dopinder, foster, porg, sif (TV box)es
     - completed:
- [x] 21.0 builds 
    - for devices that got promoted after 21.0 build started but before 20.0: `akari,akatsuki,alioth,aurora,chiron,sagit,FP3,xz2c`
        - failures: `alioth lmi`
    -  for failed 21.0 builds`crosshatch bonito blueline pdx203 pdx206 pdx214 pdx215 sargo` - all OK
- [x] 20.0 builds for `alioth & lmi`. These are 21.0 in the target list but our 21.0 builds are failing, so make a new 20.0 build and try 21.0 again next month
- completed: >> [Fri May 24 12:04:27 UTC 2024]

FInal note: free space on the download server is now `/dev/vdb1 590G  518G   43G  93%`

**Comment by petefoth** [comment]
21.0 devices:
`a52q,a52sxq,a72q,a73xq,avicii,axolotl,barbet,berlin,berlna,beryllium,bluejay,blueline,bonito,bramble,caprip,channel,cheeseburger,cheetah,coral,crosshatch,devon,dipper,discovery,DRG,dubai,dumpling,enchilada,equuleus,fajita,felix,flame,FP4,gemini,grus,gta4l,gta4lwifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,guamp,hawao,heart,hotdog,hotdogb,husky,instantnoodle,instantnoodlep,joan,kane,kebab,kirin,lemonade,lemonadep,lemonades,lynx,m5_tab,m52xq,martini,mermaid,Mi439,Mi8917,Mi8937,natrium,nio,ocean,odroidc4_tab,oriole,panther,pdx203,pdx206,pdx214,pdx215,perseus,pioneer,PL2,polaris,pro1,pro1x,pstar,pyxis,radxa0_tab,raven,redfin,rhode,river,rosemary,rtwo,salami,sargo,shiba,sunfish,surya,tangorpro,TP1803,troika,ursa,vela,voyager,xpeng,Z01R,zippo,`

**Comment by petefoth** [comment]
`blueline` (Pixel 3) failed 

```
[ 99% 179736/179738] Package OTA (retrofit dynamic partitions): out/target/product/blueline/lineage_blueline-ota-retrofit.zip (priority: 2)
FAILED: out/target/product/blueline/lineage_blueline-ota-retrofit.zip
/bin/bash -c "PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:out/host/linux-x86/bin/:\$PATH out/host/linux-x86/bin/ota_from_target_files --verbose --path out/host/linux-x86 --backup=  -k user-keys/releasekey --retrofit_dynamic_partitions out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files out/target/product/blueline/lineage_blueline-ota-retrofit.zip"
...
2024-05-04 03:44:38 - ota_from_target_files.py - INFO    : VABC XOR Not supported, disabling
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/srv/tmp/merged/out/host/linux-x86/bin/ota_from_target_files/__main__.py", line 12, in <module>
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "ota_from_target_files.py", line 1517, in <module>
  File "ota_from_target_files.py", line 1488, in main
  File "ota_from_target_files.py", line 1017, in GenerateAbOtaPackage
  File "ota_from_target_files.py", line 753, in GetTargetFilesZipForRetrofitDynamicPartitions
AssertionError: Missing OTA/super_system.img in /srv/tmp/merged/out/soong/.temp/target_files5w29fnw2; IMAGES/system.img cannot be written
[ 99% 179737/179738] Package OTA: out/target/product/blueline/lineage_blueline-ota.zip (priority: 2)
```

**Comment by petefoth** [comment]
*Thu 09 May 24*
- removed latest `kane` build because of [this bug](https://gitlab.com/LineageOS/issues/android/-/issues/7112)

**Comment by PixsaOJ** [comment]
Surya is not booting, I don't think new builds were uploaded?

**Comment by mddvul22** [comment]
> Surya was not booting, I don't think new builds were uploaded?

Builds are not finished yet.

**Comment by petefoth** [comment]
*Sat 11 May 24*
- Builds failed: Xperia 1 II `pdx203`, Xperia 1 III `pdx206`,  Xperia 5 III `pdx214`, Xperia 5 III `pdx215`. All withe the same error
```
FAILED: out/target/product/pdx206/obj/SHARED_LIBRARIES/audio_amplifier.kona_intermediates/audio_amplifier.o
FAILED: out/target/product/pdx206/obj_arm/SHARED_LIBRARIES/audio_amplifier.kona_intermediates/audio_amplifier.o
```

**Comment by petefoth** [comment]
- sargo build failed
```
[ 99% 179831/179833] Package OTA (retrofit dynamic partitions): out/target/product/sargo/lineage_sargo-ota-retrofit.zip (priority: 2)
FAILED: out/target/product/sargo/lineage_sargo-ota-retrofit.zip
/bin/bash -c "PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:out/host/linux-x86/bin/:\$PATH out/host/linux-x86/bin/ota_from_target_files --verbose --path out/host/linux-x86 --backup=  -k user-keys/releasekey --retrofit_dynamic_partitions out/target/product/sargo/obj/PACKAGING/target_files_intermediates/lineage_sargo-target_files out/target/product/sargo/lineage_sargo-ota-retrofit.zip"
2024-05-13 06:32:13 - common.py - WARNING : Failed to read SYSTEM/etc/build.prop
2024-05-13 06:32:13 - common.py - WARNING : Failed to read VENDOR/etc/build.prop
...
2024-05-13 06:32:14 - common.py - INFO    :   Running: "/srv/tmp/merged/out/host/linux-x86/bin/simg2img out/target/product/sargo/obj/PACKAGING/target_files_intermediates/lineage_sargo-target_files/RADIO/persist.img /srv/tmp/merged/out/soong/.temp/target_fileshekmoh8q/RADIO/persist.img"
2024-05-13 06:32:14 - common.py - INFO    :
2024-05-13 06:32:14 - ota_from_target_files.py - INFO    : VABC XOR Not supported, disabling
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/srv/tmp/merged/out/host/linux-x86/bin/ota_from_target_files/__main__.py", line 12, in <module>
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "ota_from_target_files.py", line 1517, in <module>
  File "ota_from_target_files.py", line 1488, in main
  File "ota_from_target_files.py", line 1017, in GenerateAbOtaPackage
  File "ota_from_target_files.py", line 753, in GetTargetFilesZipForRetrofitDynamicPartitions
AssertionError: Missing OTA/super_system.img in /srv/tmp/merged/out/soong/.temp/target_fileshekmoh8q; IMAGES/system.img cannot be written
[ 99% 179832/179833] Package OTA: out/target/product/sargo/lineage_sargo-ota.zip (priority: 2)
```

**Comment by PixsaOJ** [comment]
Installed `surya` successfully

**Comment by petefoth** [comment]
20.0 devices:
`alphaplus,apollon,bardock,bardockpro,betalm,beyond0lte,beyond1lte,beyond2lte,beyondx,crownlte,d1,d2s,d2x,davinci,deadpool,dopinder,dre,f62,foster,foster_tab,G,gauguin,gta4xl,gta4xlwifi,gtowifi,haydn,kiev,lancelot,liber,lisa,lmi,m5,mars,merlinx,mh2lm,miatoll,nairo,nx659j,odroidc4,onclite,parker,porg,porg_tab,quill,quill_tab,racer,radxa0,renoir,sake,sif,star2lte,starlte,sweet,tissot,vayu,violet,wade,X00TD,xmsirius,z2_plus,zangya,zangyapro,`

**Comment by petefoth** [comment]
> `blueline` (Pixel 3) failed
> 
> ```
> [ 99% 179736/179738] Package OTA (retrofit dynamic partitions): out/target/product/blueline/lineage_blueline-ota-retrofit.zip (priority: 2)
> FAILED: out/target/product/blueline/lineage_blueline-ota-retrofit.zip
> /bin/bash -c "PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:out/host/linux-x86/bin/:\$PATH out/host/linux-x86/bin/ota_from_target_files --verbose --path out/host/linux-x86 --backup=  -k user-keys/releasekey --retrofit_dynamic_partitions out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files out/target/product/blueline/lineage_blueline-ota-retrofit.zip"
> ...
> 2024-05-04 03:44:38 - ota_from_target_files.py - INFO    : VABC XOR Not supported, disabling
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/srv/tmp/merged/out/host/linux-x86/bin/ota_from_target_files/__main__.py", line 12, in <module>
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "ota_from_target_files.py", line 1517, in <module>
>   File "ota_from_target_files.py", line 1488, in main
>   File "ota_from_target_files.py", line 1017, in GenerateAbOtaPackage
>   File "ota_from_target_files.py", line 753, in GetTargetFilesZipForRetrofitDynamicPartitions
> AssertionError: Missing OTA/super_system.img in /srv/tmp/merged/out/soong/.temp/target_files5w29fnw2; IMAGES/system.img cannot be written
> [ 99% 179737/179738] Package OTA: out/target/product/blueline/lineage_blueline-ota.zip (priority: 2)
> ```
> 
>     * `bonito` (Google Pixel 3a XL) failed with the same error
> 
>     * `crosshatch` (Google Pixel 3 XL)-  failed with the same error

This may be related to this change topic upstream: https://review.lineageos.org/q/topic:%2214-embed-super_empty_img%22

**Comment by mddvul22** [comment]
> This may be related to this change topic upstream: https://review.lineageos.org/q/topic:%2214-embed-super_empty_img%22

I assume this means that blueline will have to wait until next month?

**Comment by petefoth** [comment]
> I assume this means that blueline will have to wait until next month?

Depends whether or not a fix has been applied upstream. I've kicked of 21 builds for devices that  got promoted after 21.0 build started but before 20.0 builds started ( `akari,akatsuki,alioth,aurora,chiron,sagit,FP3,xz2c`), followed by devices where the 21.0 build failed (`crosshatch bonito blueline pdx203 pdx206 pdx214 pdx215`). So you may get lucky :)

**Comment by notstarboard** [comment]
> followed by devices where the 21.0 build failed (`crosshatch bonito blueline pdx203 pdx206 pdx214 pdx215`)

Don't forget `sargo` :)

**Comment by petefoth** [comment]
> Don't forget `sargo` :)

Good spot. I'll do that when the others have finished

**Comment by petefoth** [comment]
- 21.0 build for`alioth` failed
```
[ 99% 520/521] finishing legacy Make module parsing ...
FAILED:
build/make/core/main.mk:1376: warning:  device/xiaomi/alioth/lineage_alioth.mk includes non-existent modules in PRODUCT_PACKAGES
Offending entries:
android.hardware.power-service.xiaomi-libperfmgr
build/make/core/main.mk:1376: error: Build failed.
12:59:01 ckati failed with: exit status 1
```

**Comment by petefoth** [comment]
- Retrying  failed 21.0 builds: Pixel 3 devices are still failing. Created #627 to track & fix this

**Comment by petefoth** [comment]
> Retrying  failed 21.0 builds: Pixel 3 devices are still failing. 

these devices all now have 21.0 builds
