### ISSUE TITLE
can't download super_empty.img (Mi8937, Mi8917,  Mi439)

### ISSUE THREAD

**Issue by tomo90** [lineageos4microg/docker-lineage-cicd#624]
download attempt ends with 403
happens for all 21 builds

e.g.
Mi8937
https://download.lineage.microg.org/Mi8937/lineage-21.0-20240510-microG-Mi8937-super_empty.img
https://download.lineage.microg.org/Mi8937/lineage-21.0-20240416-microG-Mi8937-super_empty.img

Mi8917
https://download.lineage.microg.org/Mi8917/lineage-21.0-20240509-microG-Mi8917-super_empty.img
https://download.lineage.microg.org/Mi8917/lineage-21.0-20240415-microG-Mi8917-super_empty.img

Mi439
https://download.lineage.microg.org/Mi439/lineage-21.0-20240509-microG-Mi439-super_empty.img
https://download.lineage.microg.org/Mi439/lineage-21.0-20240415-microG-Mi439-super_empty.img

**Comment by petefoth** [comment]
These are Xiami devices: Redmi 3S, 3A, 7A

If you need `super_empty.img` for these devices, should be safe to use the latest LOS version from .e.g https://download.lineageos.org/devices/Mi439/builds

There seem to be problems with these files - see this post in LOS DIscord / irc: https://discord.com/channels/628008280605589549/653821647102672926/1238493951112122499

**Comment by petefoth** [comment]
Looks like a file permissions issue 
```
$ ls -l Mi*/*.img
-rw-r--r-- 1 rsync rsync 21190656 Apr 16 04:12 Mi8937/lineage-21.0-20240416-microG-Mi8937-boot.img
-rw-r--r-- 1 rsync rsync 31307776 Apr 16 04:12 Mi8937/lineage-21.0-20240416-microG-Mi8937-recovery.img
-rw------- 1 rsync rsync     4708 Apr 16 04:12 Mi8937/lineage-21.0-20240416-microG-Mi8937-super_empty.img
-rw-r--r-- 1 rsync rsync 21192704 May 10 03:02 Mi8937/lineage-21.0-20240510-microG-Mi8937-boot.img
-rw-r--r-- 1 rsync rsync 31309824 May 10 03:02 Mi8937/lineage-21.0-20240510-microG-Mi8937-recovery.img
-rw------- 1 rsync rsync     4708 May 10 03:02 Mi8937/lineage-21.0-20240510-microG-Mi8937-super_empty.img
```
- add `r` permission
`for device in  Mi439 Mi8917 Mi8937 ; do chmod a+r $device/*super_empty.img; done`
- done
```
$ ls -l Mi*/*super_empty.img
-rw-r--r-- 1 rsync rsync 4772 Apr 15 22:34 Mi439/lineage-21.0-20240415-microG-Mi439-super_empty.img
-rw-r--r-- 1 rsync rsync 4772 May  9 21:25 Mi439/lineage-21.0-20240509-microG-Mi439-super_empty.img
-rw-r--r-- 1 rsync rsync 4708 Apr 16 01:23 Mi8917/lineage-21.0-20240415-microG-Mi8917-super_empty.img
-rw-r--r-- 1 rsync rsync 4708 May 10 00:13 Mi8917/lineage-21.0-20240509-microG-Mi8917-super_empty.img
-rw-r--r-- 1 rsync rsync 4708 Apr 16 04:12 Mi8937/lineage-21.0-20240416-microG-Mi8937-super_empty.img
-rw-r--r-- 1 rsync rsync 4708 May 10 03:02 Mi8937/lineage-21.0-20240510-microG-Mi8937-super_empty.img
```

@tomo90 Pleas e check that the downlod now works for you, and close the issue if it does. Thanks

**Comment by tomo90** [comment]
All good now. Thank you!
