### ISSUE TITLE
Pixel 3 family devices are not building

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#627]
Builds are failing for the following Pixel 3 family devices: `blueline, bonito, crosshatch, sargo`

We have not managed to build successfully for these devices since March. In the time there have been two major changes:
1. The QPRS changes which broke upstream builds
2. We implemented the fix for #588 in this commit [Use `mka otaimage bacon`: see if we hit the posix spawn error ](https://github.com/lineageos4microg/docker-lineage-cicd/commit/13e9fa8f252c327ca729b90e4112b470dab9637b) and PR #601 

Upstream are building successfully for these devices, so it's not 1. Upstream build using `brunch` rather than `mka ...` - maybe we need to do that

**Comment by petefoth** [comment]
Possible fix: change the command in [this line in src/build.sh](https://github.com/lineageos4microg/docker-lineage-cicd/blob/ae2a4cdc8383153498f93eec41d9d64a63d051aa/src/build.sh#L484) from
`mka "${jobs_arg[@]}" otapackage bacon`
to 
`brunch "${jobs_arg[@]}" $codename`

**Comment by petefoth** [comment]
Try using the `pf-use-target-files-package` branch
```
screen -S l4mDockerBuild

docker run \
  -v "/srv/src:/srv/src" \
  -v "/srv/zips:/srv/zips" \
  -v "/srv/logs:/srv/logs" \
  -v "/srv/cache:/srv/ccache" \
  -v "/srv/keys:/srv/keys" \
  -v "/srv/tmp:/srv/tmp" \
  -v "/srv/local_manifests:/srv/local_manifests" \
  -v "/srv/userscripts:/srv/userscripts" \
  -e "BRANCH_NAME=lineage-21.0" \
  -e "WITH_GMS=true" \
  -e "RELEASE_TYPE=4microg-UNOFFICIAL" \
  -e "SIGN_BUILDS=true" \
  -e "SIGNATURE_SPOOFING=no" \
  -e "INCLUDE_PROPRIETARY=false" \
  -e "DEVICE_LIST=bonito" \
  lineageos4microg/docker-lineage-cicd:pf-use-target-files-package
```

**Comment by petefoth** [comment]
All these devices now have 21.0 builds. I'll close the defect when the working branch (`pf-use-target-files-package` ) is megred to `master` (after a bit more testing 😄 )

**Comment by mddvul22** [comment]
Thank you!
