### ISSUE TITLE
Bump latest OnePlus 7 Pro (guacamole) Build 

### ISSUE THREAD

**Issue by MicahBird** [lineageos4microg/docker-lineage-cicd#631]
Greetings! I'm not sure if this is the right place to request this, but there was a breaking Bluetooth regression made in LineageOS 21 that prevents a swath of watches from being able to pair, [which has since been fixed!](https://review.lineageos.org/c/LineageOS/android_packages_modules_Bluetooth/+/391977) However, the latest build for guacamole only dates back to May 7th, which is the day before this was fixed... 

Would it be possible to request that guacamole gets bumped to be up to date? I'd be more than happy to donate any compute and/or storage to the cause!

**Comment by petefoth** [comment]
New build available at https://download.lineage.microg.org/guacamole/

**Comment by MicahBird** [comment]
**_HOLY COW!_** You have made my week and then some my good sir! Thank you so much for the unbelievably fast turnaround!

**Comment by MicahBird** [comment]
Quick PSA to anyone else, DO NOT FLASH AND/OR UPDATE TO THIS VERSION (lineage-21.0-20240524-microG-guacamole). I did a both clean and dirty flash and it has broke everything, every app reports "<App> keeps stopping" and cellular doesn't function :/

A clean flash is even worse because the setup app never loads, it perpetually stays on a black screen. Regardless, thank you for your time and assistance @petefoth!

**Comment by ristein** [comment]
I just OTA-updated and it's all broken:
 - sim not detected
 - no wifi connection
 - settings crashing, not being opened
 - phone and message storage crashing
 - status bar has different battery icon
 - logcat showing this five times a millisecond:

> 05-25 10:10:50.781     0     0 W init    : DM_DEV_STATUS failed for system: No such device or address
> 05-25 10:10:50.781     0     0 W init    : DM_DEV_STATUS failed for vroot: No such device or address
