### ISSUE TITLE
June 24 build run status

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#636]
Full run
- started: 
- [x] 21.0 branch 
    - started: >> [Sat Jun  1 00:10:10 UTC 2024]
    - expected failures: m5, ~deadpool~, odroidc4, ~pstar~, radxa0, ~wade~
        - deadpool, pstar, wade succeeded :)
    - unexpected failures: `alioth,m5,m5_tab,martini,odroidc4_tab,radxa0_tab`
- [x] 20.0 branch
     - started:
     - expected failures: foster, porg, sif (TV Boxes)
     - unexpected failures:
     - completed:
- [x] Unofficial 21.0 builds for `lilac,poplar,poplar_dsds,maple,maple_dsds`
- [x] Retry failed 21.0 builds for `alioth,m5,m5_tab,martini,odroidc4,odroidc4_tab,radxa0,radxa0_tab`
- [ ] Build newly added 21.0 devices `abrina,dre,earth,pdx234,nx,nx_tab`
    - `nx_tab` failed. Retrying - that worked. All  done 😄 
- completed:

21.0 devices: 
`a52q,a52sxq,a72q,a73xq,akari,akatsuki,alioth,aura,aurora,avicii,axolotl,barbet,berlin,berlna,beryllium,bluejay,blueline,bonito,bramble,caprip,channel,cheeseburger,cheetah,cheryl,chiron,coral,crosshatch,davinci,deadpool,devon,dipper,discovery,dopinder,DRG,dubai,dumpling,enchilada,equuleus,fajita,felix,flame,FP3,FP4,FP5,gemini,grus,gta4l,gta4lwifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,guamp,hawao,haydn,heart,hotdog,hotdogb,husky,ingot,instantnoodle,instantnoodlep,joan,kane,kebab,kirin,lemonade,lemonadep,lemonades,lisa,lmi,lynx,m5,m5_tab,m52xq,mars,martini,mata,mermaid,Mi439,Mi8917,Mi8937,miatoll,natrium,nio,ocean,odroidc4,odroidc4_tab,oriole,panther,pdx203,pdx206,pdx214,pdx215,perseus,pioneer,PL2,polaris,pro1,pro1x,pstar,pyxis,r8q,radxa0,radxa0_tab,raven,redfin,renoir,rhode,river,rosemary,rtwo,sagit,salami,sargo,shiba,sunfish,surya,sweet,tangorpro,TP1803,troika,umi,ursa,vela,voyager,wade,xpeng,xz2c,Z01R,zippo`

20.0 devices:
`alphaplus,apollon,bardock,bardockpro,betalm,beyond0lte,beyond1lte,beyond2lte,beyondx,crownlte,d1,d2s,d2x,f62,foster,foster_tab,G,gauguin,gta4xl,gta4xlwifi,gtowifi,kiev,lancelot,liber,merlinx,mh2lm,nairo,nx659j,onclite,parker,porg,porg_tab,quill,quill_tab,racer,sake,sif,star2lte,starlte,tissot,vayu,violet,X00TD,xmsirius,z2_plus,zangya,zangyapro`

**Comment by petefoth** [comment]
- `a52q` build not synched: 
  - need to swap out the `post-build.sh` used for test builds for the production version
  - manually sync the `a52q` build
  - [ ] check the `a52sxq` syncs automatically

**Comment by petefoth** [comment]
- alioth build failed. It's an upstream problem: last two official LOS build (22/5 & 29/5) failed too.

**Comment by petefoth** [comment]
*Thu 06 Jun 24*
- Builds died during build of FP3.  Restart from there

**Comment by BurhanBudak** [comment]
Latest hotdogb works flawlessly and installed smootly. But I wonder what version of lineage build it uses? Is it the older May 5 version? Because LOS released a build yesterday thr 7th.

**Comment by petefoth** [comment]
> Latest hotdogb works flawlessly and installed smootly. But I wonder what version of lineage build it uses? Is it the older May 5 version? Because LOS released a build yesterday the 7th.

It uses whatever code was in the LineageOS repos when the build started. LOS don't tag there code for releases, so we build using the latest

**Comment by petefoth** [comment]
*Mon 10 Jun 24*
- `m5` & `m5_tab` builds failed with the error below.  Official LOS builds have succeeded, so retry at the end of the build run
<details><summary>`m5_tab` build error</summary>

```
[ 82% 111585/134670] //system/sepolicy/contexts:vendor_property_contexts checking namespace of vendor_property_contexts (priority: 18)
FAILED: out/soong/.intermediates/system/sepolicy/contexts/vendor_property_contexts/android_common/m5_tab/vendor_property_contexts_namespace_checked
out/host/linux-x86/bin/check_prop_prefix --property-contexts out/soong/.intermediates/system/sepolicy/contexts/vendor_property_contexts/android_common/m5_tab/vendor_property_contexts --allowed-property-prefix ctl.odm. --allowed-property-prefix ctl.vendor. --allowed-property-prefix 'ctl.start$odm.' --allowed-property-prefix 'ctl.start$vendor.' --allowed-property-prefix 'ctl.stop$odm.' --allowed-property-prefix 'ctl.stop$vendor.' --allowed-property-prefix init.svc.odm. --allowed-property-prefix init.svc.vendor. --allowed-property-prefix ro.boot. --allowed-property-prefix ro.hardware. --allowed-property-prefix ro.odm. --allowed-property-prefix ro.vendor. --allowed-property-prefix odm. --allowed-property-prefix persist.odm. --allowed-property-prefix persist.vendor. --allowed-property-prefix vendor. --allowed-property-prefix persist.camera. --strict && cp -f out/soong/.intermediates/system/sepolicy/contexts/vendor_property_contexts/android_common/m5_tab/vendor_property_contexts out/soong/.intermediates/system/sepolicy/contexts/vendor_property_contexts/android_common/m5_tab/vendor_property_contexts_namespace_checked # hash of input list: b62fce6fb5bf5669a4737b7f2f0cd2b3b9e5ea72cbd7d4ef80ce418eb9fd7607
******************************
1 violations found:
ro.media.maxmem                     u:object_r:media_prop:s0
******************************
vendor's and odm's property_contexts MUST use ONLY vendor-prefixed properties.
This is enforced by VTS, so please fix such offending properties.
Allowed property prefixes for out/soong/.intermediates/system/sepolicy/contexts/vendor_property_contexts/android_common/m5_tab/vendor_property_contexts: ['ctl.odm.', 'ctl.vendor.', 'ctl.start$odm.', 'ctl.start$vendor.', 'ctl.stop$odm.', 'ctl.stop$vendor.', 'init.svc.odm.', 'init.svc.vendor.', 'ro.boot.', 'ro.hardware.', 'ro.odm.', 'ro.vendor.', 'odm.', 'persist.odm.', 'persist.vendor.', 'vendor.', 'persist.camera.']
You can temporarily disable this check with setting BUILD_BROKEN_VENDOR_PROPERTY_NAMESPACE := true in BoardConfig.mk.
But property namespace is enforced by VTS, and you will need to fix such violations to pass VTS.
```

</details>

- latest LOS 21.0 `alioth` build succeeded https://buildkite.com/lineageos/android/builds/66755. so retry at the end of the build run

**Comment by petefoth** [comment]
*Tue 11 Jun 24*
- `odroidc4_tab` failed - same error as expected `odroidc4` failure
```
>> [Tue Jun 11 13:33:13 UTC 2024] breakfast failed for odroidc4_tab, lineage-21.0 branch
```

**Comment by Machion** [comment]
Installation error for `nio`: 
I could download the new june build, but when I tap on install it immediately says "installation error". 
Already downloaded 2 times just to be shure.

**Comment by petefoth** [comment]
> Installation error for `nio`: I could download the new june build, but when I tap on install it immediately says "installation error". Already downloaded 2 times just to be shure.

Is this via the Updater app? Try installing using recovery & adb sidelooad
- Download zip file [lineage-21.0-20240611-microG-nio.zip](https://download.lineage.microg.org/nio/lineage-21.0-20240611-microG-nio.zip)
- Ensure that the SHA Sim matches with the contents of [lineage-21.0-20240611-microG-nio.zip.sha256sum](https://download.lineage.microg.org/nio/lineage-21.0-20240611-microG-nio.zip.sha256sum). The correct value is `4136ef4a510e55bad9a38299c57adbfb498b1038fde366d9934af6c3c7b9c97b`
- Install via `adb sideload` as described [here](https://wiki.lineageos.org/devices/nio/install/variant1/#installing-lineageos-from-recovery) or [here](https://wiki.lineageos.org/devices/nio/install/variant1/#installing-lineageos-from-recovery) depending on which variant of `nio` you have

**Comment by Machion** [comment]
Ok finally got time to test it. 
Yes Updater app failed, sideload was successful. Strange. I hope it was a single case

**Comment by RoiArthurB** [comment]
> -`alioth` failed. latest LOS 21.0 `alioth` build succeeded https://buildkite.com/lineageos/android/builds/66755. so retry at the end of the build run

This issue has been fixed on the last nightly released ([link](https://buildkite.com/lineageos/android-nightly/builds/1731)), and waiting for the new nightly to see if new issue ([link nightly](https://buildkite.com/lineageos/android-nightly/builds/1738#01902dcc-b1bc-4004-8412-abe97eae5023) - [waiting for `alioth`](https://buildkite.com/lineageos/android/builds/67216))

**Comment by stefan-niedermann** [comment]
Feedback: Just received an update notification for `alioth` 2024-06-29 build being available. I installed it via the updater app and everything seems to work fine :) Thank you.

**Comment by petefoth** [comment]
> Feedback: Just received an update notification for `alioth` 2024-06-29 build being available. I installed it via the updater app and everything seems to work fine :) Thank you.

That'll be 2024-06-**20** - we're not using a time machine (yet 😄 ).

Great it's working!

**Comment by petefoth** [comment]
*Sat 22 Jun 24*
- 21.0 build for `nx_tab` failed:
```
[ 99% 171701/171716] build out/target/product/nx_tab/obj/PACKAGING/check_vintf_all_intermediates/check_vintf_compatible.log (priority: 4)
FAILED: out/target/product/nx_tab/obj/PACKAGING/check_vintf_all_intermediates/check_vintf_compatible.log
...
List 'out/target/product/nx_tab/product/etc/vintf/': NAME_NOT_FOUND
The following HALs in device manifest are not declared in FCM <= level 5:
  android.hardware.bluetooth.audio.IBluetoothAudioProviderFactory/default (@3)
  android.hardware.cas.IMediaCasService/default (@1)
  android.hardware.drm.IDrmFactory/clearkey (@1)
  android.hardware.health.IHealth/default (@2)
  android.hardware.light.ILights/default (@2)
  android.hardware.usb@1.3::IUsb/default
  android.hardware.wifi.IWifi/default (@1)
  android.hardware.wifi.hostapd.IHostapd/default (@1)
  android.hardware.wifi.supplicant.ISupplicant/default (@2)
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No kernel entry found for kernel version 4.9 at kernel FCM version 5. The following kernel requirements are checked:
...
```
- retry in case it's something transient

**Comment by petefoth** [comment]
All done!
