### ISSUE TITLE
Explore possibility of passing SafetyNet

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#638]
- /e/OS do it
- IodéOS do it
- FlameFire's Unofficial LOS ROM for lilac does it

Can we use one of those approaches with our builds so that they pass SafetyNet?

**Comment by petefoth** [comment]
- Flamefire's approach: this patch: https://github.com/Flamefire/android_device_sony_lilac/blob/lineage-20/patches/make-snet-pass.patch, based on 
    - https://protonaosp.org/developers/details/safetynet 
> Squash of:
>     "Spoof build fingerprint for Google Play Services" https://github.com/ProtonAOSP/android_frameworks_base/commit/14cadef1690f
>     "keystore: Block key attestation for SafetyNet" https://github.com/ProtonAOSP/android_frameworks_base/commit/13dc7d28c12d
> Combined with code from:
>     https://github.com/chiteroman/PlayIntegrityFix
>     https://github.com/osm0sis/PlayIntegrityFork

**Comment by Forage** [comment]
For what it's worth, the chiteroman PlayIntegrityFix Magisk module works like a charm on my OnePlus 6 (enchilada) with your LOS21 builds. 
I realise the Magisk route is not what you're after, build I figured I'd mention it for reference.

**Comment by videoman614** [comment]
Sadly [PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix) no longer works for me, was looking at [TrickyStore](https://github.com/chiteroman/TrickyStore) but not sure if it works with MicroG but from the readme, this might be something to look in to.

> If you are using a custom ROM and it passes Play Integrity (BASIC & DEVICE) by default, there is a good chance that this module won't work for you as your ROM is probably blocking Key Attestation. To see if your ROM is compatible, look in the android_frameworks_base repo of your ROM and search for PixelPropsUtils or setProps.
> 
> To fix this issue, search for engineGetCertificateChain in that repo and see if there's some block of code that throws an exception if some condition that checks if it's related to key attestation (e.g. PixelPropsUtils.getIsKeyAttest() or isCallerSafetyNet()) is filled. You can delete this block of code and build your ROM yourself, or submit a commit to the maintainer of your ROM to add, for example, a system property to enable/disable this blocking. See [this commit](https://github.com/PixelBuildsROM/android_frameworks_base/commit/378ae3b7034d441fd0455639dc1a4b29b2876798) for reference.

**Comment by BurhanBudak** [comment]
> Sadly [PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix) no longer works for me, was looking at [TrickyStore](https://github.com/chiteroman/TrickyStore) but not sure if it works with MicroG but from the readme, this might be something to look in to.
> 
> > If you are using a custom ROM and it passes Play Integrity (BASIC & DEVICE) by default, there is a good chance that this module won't work for you as your ROM is probably blocking Key Attestation. To see if your ROM is compatible, look in the android_frameworks_base repo of your ROM and search for PixelPropsUtils or setProps.
> > 
> > To fix this issue, search for engineGetCertificateChain in that repo and see if there's some block of code that throws an exception if some condition that checks if it's related to key attestation (e.g. PixelPropsUtils.getIsKeyAttest() or isCallerSafetyNet()) is filled. You can delete this block of code and build your ROM yourself, or submit a commit to the maintainer of your ROM to add, for example, a system property to enable/disable this blocking. See [this commit](https://github.com/PixelBuildsROM/android_frameworks_base/commit/378ae3b7034d441fd0455639dc1a4b29b2876798) for reference.
> 
> This looks promising, hopefully for us with MicroG passing this asinine system might be finally possible ~~until google breaks it again~~ [Spoof locked bootloader on local hardware attestations
> ](https://github.com/chiteroman/android_system_security/commit/680c8de5b26c944f14d72fe24c043ecf8d45b895)

Isnt the issue with MicroG phones(not Sandboxed GMS like in GOS) don't or can't install a gapps package that handles the Play Integrity API. If I'm right, we only need a Google Play Store that is good enough for modded users.

**Comment by petefoth** [comment]
All of the reading I've done on this up to now suggest that
1. It probably wont work
2. If it does work it could stop working at any time if Google change things
3. Latest Play Integrity checks are even harder to fool than Safety Net

For those reasons, and because this is pretty clearly out of scope for this project (see [here](https://github.com/lineageos4microg/docker-lineage-cicd?tab=readme-ov-file#project-scope), I'm going to close this issue: nice idea, but it's not going to happen :(
