### ISSUE TITLE
Impossible to install Magisk on latest miatoll build

### ISSUE THREAD

**Issue by mike855** [lineageos4microg/docker-lineage-cicd#642]
Hello,

I'm trying to install Magisk on latest miatoll build, but it seems there is a problem with Magisk and some custom rom.
I do not understand all the issue, but it is know on Magick side and they says it is related to the custom rom.

Here is my issue on Magisk github : [](https://github.com/topjohnwu/Magisk/issues/8145)

And the related issue, with explanations on the problem : [](https://github.com/topjohnwu/Magisk/issues/6914)

Have a nice day :)

**Comment by petefoth** [comment]
Sorry but we are not in a position to provide support for Magisk. If there is a known fix we could make which would solve the issue for Msgisk , we are happy to receive PRs but it's not something we can work on or investigate

**Comment by mike855** [comment]
Magisk team do not want to work on that issue, rejecting fault to custom roms and kernel. So as I know, nobody fixed the issue yet without flashing another kernel

**Comment by FintasticMan** [comment]
You didn't link the issues correctly, so I'm not able to check what needs to happen. Could you see if you can post the links? Thanks

**Comment by mike855** [comment]
Ho yeah indeed.

My issue : https://github.com/topjohnwu/Magisk/issues/8145

Duplicates with : https://github.com/topjohnwu/Magisk/issues/6914

**Comment by petefoth** [comment]
Closing. If this is still an issue, it's almost certainly not our issue :)
