### ISSUE TITLE
21.0 lemonadep failures.

### ISSUE THREAD

**Issue by ShadwDrgn** [lineageos4microg/docker-lineage-cicd#645]
[lineage-21.0-20240623-user-lemonadep.log](https://github.com/user-attachments/files/15945578/lineage-21.0-20240623-user-lemonadep.log)
I've tried compiling for lemonadep a few times in the last week and have gotten the same error every time i think. not sure what's going on. tried deleting ccache and linage dirs so it repo syncs from scratch. no such luck:
command to build:
```
docker run --rm --name android -e "BRANCH_NAME=lineage-21.0" -e "DEVICE_LIST=lemonadep" -e "SIGN_BUILDS=true" -e "RELEASE_TYPE=user" -e "WITH_GMS=true" -e "ZIP_SUBDIR=false" -e "OTA_URL=https://lineage.1ez.us/api" -v "/mnt/ds16_backups/android/lineage:/srv/src" -v "/mnt/ds16_backups/android/keys:/srv/keys" -v "/mnt/ds16_backups/android/zips:/srv/zips" -v "/mnt/ds16_backups/android/logs:/srv/logs" -v "/mnt/ds16_backups/android/ccache:/srv/ccache" -v "/mnt/ds16_backups/android/local_manifests:/srv/local_manifests" lineageos4microg/docker-lineage-cicd | tee /home/user/android_`date +'%Y%m%d'`.log`
```

local manifests folder only contains one file with this:
```[root@archlinux android]# cat local_manifests/microg.xml 
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    <project path="vendor/partner_gms" name="lineageos4microg/android_vendor_partner_gms" remote="github" revision="master" />
</manifest>
```
This is the first time i've tried a build in some time, and I've never tried 21.0 before this. I don't know if this is something i'm doing wrong or if the aosp repos are just busted for this hardware right now or what.

Any assistance would be greatly appreciated.

**Comment by petefoth** [comment]
A couple of things
1. We make `userdebug` builds not `user`. Try changing the `-e "RELEASE_TYPE=user"` to `-e "RELEASE_TYPE=userdebug"`
2. The error messages in the log indicate a problem building the `tv` HAL from `https://github.com/LineageOS/android_hardware_interfaces/tree/lineage-21.0/tv`. It's possible this is caused by having a 'dirty` source tree. Worth trying a `rm -rf *` in `/mnt/ds16_backups/android/lineage:/srv/src`.
```
ERROR: hardware/interfaces/tv/tuner/aidl/aidl_api/android.hardware.tv.tuner/current/android/hardware/tv/tuner/RecordSettings.aidl:41.52-99: Bad internal state: !resolved_: Should be resolved first: android.hardware.tv.tuner.DataFormat.UNDEFINED
Aborted (core dumped)
###############################################################################
# ERROR: AIDL API change detected on frozen interface                         #
###############################################################################
Above AIDL file(s) has changed. The AIDL API is marked `frozen: true` so it
cannot be modified. Change this to `frozen: false`, then run `m android.hardware.tv.tuner-update-api`
to reflect the changes to the current version so that it is reviewed by
android-aidl-api-council@google.com.
And then you need to change dependency on android.hardware.tv.tuner-V(n)-* to android.hardware.tv.tuner-V(n+1)-* to use
new APIs.

```

**Comment by petefoth** [comment]
FWIW, there were no problems at all making the latest 21.0 build for this device

**Comment by ShadwDrgn** [comment]
I will try userdebug, but i have already tried to delete all of lineage/* and ccache/* multiple times and still get this error.
Will reply here with results of userdebug and will close the issue if it succeeds. Thx.

**Comment by ShadwDrgn** [comment]
[repo-20240623.log](https://github.com/user-attachments/files/15945696/repo-20240623.log)
this is the repo sync log in case that somehow helps determine the issue.

**Comment by petefoth** [comment]
Another thought: have you done a `docker pull lineageos4microg/docker-lineage-cicd` recently? Problem could be caused by having an out-of-date docker image on your build machine.

**Comment by ShadwDrgn** [comment]
I have not, though i recently did a docker system prune -a  It's possible the container was somehow running when i did it though. I will pull again if this build fails.

**Comment by ShadwDrgn** [comment]
This failed again after pulling latest, rm -rf lineage/* ccache/* and setting to "userdebug". Is it possible for this to somehow be due to the keys/ folder being populated from lineage 20 builds? At this point i've freed up 450G on my primary nvme so i can rule out the nfs share being janky somehow, but i don't know what to do anymore.  It would feel awful to know my entire extremely expensive NAS is just broken or something, but we'll see i suppose. if this fails now (i've even deleted the keys/* files in case somehow old 20.* keys are breaking something.

If this doesn't work i'm giving up, so i guess i'll close this in defeat. :~( Thanks for trying to help. Thx for providing all of this and the support to the community. Thanks to you I can at least just go get your builds since i'm somehow incapable of building it anymore.

**Comment by petefoth** [comment]
> This failed again after pulling latest, rm -rf lineage/* ccache/* and setting to "userdebug". Is it possible for this to somehow be due to the keys/ folder being populated from lineage 20 builds?

Sorry it's still not working. Please will you post the log from the most recent failure, and I'll have another look when I get some time?
