### ISSUE TITLE
July 2024 build run status

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#648]
Full run
- started: [Mon Jul  1 00:00:27 UTC 2024]
- [x] 21.0 branch
    - started: [Mon Jul  1 00:00:27 UTC 2024]
    - expected failures: ~~`m5`, `odroidc4`,`radxa0`,`odroidc4` builds all worked 😄~~ none 
    - unexpected failures: `cheetah,nio,pdx234`
- [x] 20.0 branch
     - started:
     - expected failures: `foster, porg, sif `(TV Boxes)
     - unexpected failures: ``
     - completed:
 - [x] unofficial 21.0 builds: lilac,poplar,poplar_dsds,maple,maple_dsds: Faileed. Will fail continue to fail unless / until QPR3 work is done in yoshin0-common repo
 - [x] More 21.0 builds
     - [x] Retry  failed 21.0 devices: `cheetah,nio,pdx234`
     - [x] 21.0 builds for devices added or promoted since 1 July: `grus,pyxis,vela,FP3,heart,zippo,Z01R,gta4l,gta4lwifi,oscar,judyln,judypn,judyp,gtowifi` 
     - [x] Retry  `broken` builds: `enchilada,fajita`
- completed:  [Wed Jul 24 17:48:22 UTC 2024]

Note we are now down to 14GB free space on the download server `/dev/vdb1       590G  546G   14G  98% /mnt/archive`

------
21.0 devices (145): `a52q,a52sxq,a72q,a73xq,akari,akatsuki,akita,alioth,aura,aurora,axolotl,barbet,beckham,berlin,berlna,beryllium,bluejay,blueline,bonito,bramble,beyond0lte,beyond1lte,beyond2lte,beyondx,caprip,channel,cheeseburger,cheetah,cheryl,chiron,coral,crosshatch,d1,d2s,d2x,davinci,deadpool,devon,dipper,discovery,dopinder,dre,DRG,dubai,dumpling,earth,enchilada,equuleus,evert,f62,fajita,felix,flame,FP4,FP5,gemini,gta4xl,gta4xlwifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,guamp,hawao,haydn,hotdog,hotdogb,husky,ingot,instantnoodle,instantnoodlep,kane,kebab,kirin,lake,lemonade,lemonadep,lemonades,lisa,lmi,lynx,m5,m5_tab,m52xq,marlin,mars,martini,mata,mermaid,messi,Mi439,Mi8917,Mi8937,miatoll,nash,natrium,nio,nx,nx_tab,ocean,odroidc4,odroidc4_tab,oriole,panther,payton,pdx203,pdx206,pdx214,pdx215,pdx234,perseus,pioneer,PL2,polaris,pro1,pro1x,pstar,r8q,radxa0,radxa0_tab,raven,redfin,renoir,rhode,river,rtwo,sabrina,sagit,sailfish,sargo,shiba,sunfish,surya,sweet,taimen,tangorpro,TP1803,troika,umi,ursa,voyager,wade,walleye,xpeng,xz2c`

20.0 devices:  (37-ish) `alphaplus,apollon,bardock,bardockpro,betalm,crownlte,foster,foster_tab,G,gauguin,kiev,lancelot,liber,merlinx,mh2lm,nairo,nx659j,onclite,parker,porg,porg_tab,quill,quill_tab,racer,sake,sif,star2lte,starlte,tissot,vayu,violet,X00TD,xmsirius,z2_plus,zangya,zangyapro`

**Comment by petefoth** [comment]
- cheetah failed. With luck it's transient. Retry

<details><summary> Error log </summary>

```
[ 99% 195067/195376] Extracting apexes... (priority: 5)
FAILED: out/target/product/cheetah/obj/PACKAGING/check_vintf_all_intermediates/apex/apex-info-list.xml
/bin/bash -c "(echo out/target/product/cheetah/vendor/apex/com.android.hardware.cas.apex out/target/product/cheetah/vendor/apex/com.google.android.hardware.biometrics.face.pixel22.apex out/target/product/cheetah/vendor/apex/com.google.android.widevine-wv_341113000.apex out/target/product/cheetah/vendor/apex/com.google.pixel.camera.hal.apex out/target/product/cheetah/vendor/apex/com.google.pixel.euicc.update.apex out/target/product/cheetah/vendor/apex/com.google.pixel.wifi.ext.apex > /dev/null ) && (rm -rf out/target/product/cheetah/obj/PACKAGING/check_vintf_all_intermediates/apex ) && (mkdir -p out/target/product/cheetah/obj/PACKAGING/check_vintf_all_intermediates/apex ) && (out/host/linux-x86/bin/apexd_host --vendor_path out/target/product/cheetah/vendor 	   --apex_path out/target/product/cheetah/obj/PACKAGING/check_vintf_all_intermediates/apex )"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/srv/tmp/merged/out/host/linux-x86/bin/apexd_host/__main__.py", line 12, in <module>
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "apexd_host.py", line 204, in <module>
  File "apexd_host.py", line 200, in main
  File "apexd_host.py", line 162, in ActivateApexes
  File "apexd_host.py", line 149, in ScanApexes
  File "apexd_host.py", line 86, in __init__
  File "apex_manifest.py", line 51, in fromApex
  File "internal/python3.11/zipfile.py", line 1302, in __init__
  File "internal/python3.11/zipfile.py", line 1369, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
```

</details>

**Comment by petefoth** [comment]
- `enchilada` build: mobile data and wifi not working - see #651: working on upstream LOS. Build removed to `not_working` directory. Maybe retry when build run is finished

**Comment by olokelo** [comment]
Oneplus 7T (hotdogb) works flawlessly with the new update. Thankfully I haven't noticed any problems with WiFi or broadband like in Oneplus 6 (enchilada).

Thanks for maintaining the project.
By the way, how can I donate financially? Link on your site redirects to microg's liberapay (which I already donated to).

**Comment by petefoth** [comment]
> By the way, how can I donate financially?

Thanks for the thought, but I do this for fun, in my spare time when I’m not playing golf. I don’t want or need payment :slight_smile:
If you really want to express your appreciation with money, then please donate something to a charity local to you

**Comment by petefoth** [comment]
`nio` failed. . With luck it's transient. Retry

```
[100% 1565/1565] writing legacy Make module rules ...
FAILED:
build/make/core/Makefile:161: error: overriding commands for target `out/target/product/nio/vendor/lib/libqti-perfd-client.so', previously defined at out/soong/installs-lineage_nio.mk:372369
01:33:56 ckati failed with: exit status 1
```

**Comment by Komprogue** [comment]
> Full run
> 
>     * started: [Mon Jul  1 00:00:27 UTC 2024]
> 
>     * [ ]  21.0 branch
>       
>       * started: [Mon Jul  1 00:00:27 UTC 2024]
>       * expected failures: ~`m5`, `odroidc4`,`radxa0`,`odroidc4` builds all worked 😄~ none
>       * unexpected failures: `cheetah,nio,pdx234`
> 
>     * [ ]  20.0 branch
>       
>       * started:
>       * expected failures: `foster, porg, sif `(TV Boxes)
>       * unexpected failures: ``
>       * completed:
> 
>     * [ ]  unofficial 21.0 builds: lilac,poplar,poplar_dsds,maple,maple_dsds  (will fail unless QPR3 work has been done in yoshin0-common repo)
> 
>     * [ ]  More 21.0 builds
>       
>       * [ ]  Retry  failed 21.0 devices: `cheetah,nio,pdx234`
>       * [ ]  21.0 builds for devices added or promoted since 1 July: `grus,pyxis,vela,FP3,heart,zippo,Z01R,gta4l,gta4lwifi,oscar,judyln,judypn,judyp,gtowifi`
>       * [ ]  Retry  `broken` builds: `enchilada,fajita`
> 
>     * completed:
> 
> 
> 21.0 devices (145): `a52q,a52sxq,a72q,a73xq,akari,akatsuki,akita,alioth,aura,aurora,axolotl,barbet,beckham,berlin,berlna,beryllium,bluejay,blueline,bonito,bramble,beyond0lte,beyond1lte,beyond2lte,beyondx,caprip,channel,cheeseburger,cheetah,cheryl,chiron,coral,crosshatch,d1,d2s,d2x,davinci,deadpool,devon,dipper,discovery,dopinder,dre,DRG,dubai,dumpling,earth,enchilada,equuleus,evert,f62,fajita,felix,flame,FP4,FP5,gemini,gta4xl,gta4xlwifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,guamp,hawao,haydn,hotdog,hotdogb,husky,ingot,instantnoodle,instantnoodlep,kane,kebab,kirin,lake,lemonade,lemonadep,lemonades,lisa,lmi,lynx,m5,m5_tab,m52xq,marlin,mars,martini,mata,mermaid,messi,Mi439,Mi8917,Mi8937,miatoll,nash,natrium,nio,nx,nx_tab,ocean,odroidc4,odroidc4_tab,oriole,panther,payton,pdx203,pdx206,pdx214,pdx215,pdx234,perseus,pioneer,PL2,polaris,pro1,pro1x,pstar,r8q,radxa0,radxa0_tab,raven,redfin,renoir,rhode,river,rtwo,sabrina,sagit,sailfish,sargo,shiba,sunfish,surya,sweet,taimen,tangorpro,TP1803,troika,umi,ursa,voyager,wade,walleye,xpeng,xz2c`
> 
> 20.0 devices: (37-ish) `alphaplus,apollon,bardock,bardockpro,betalm,crownlte,foster,foster_tab,G,gauguin,kiev,lancelot,liber,merlinx,mh2lm,nairo,nx659j,onclite,parker,porg,porg_tab,quill,quill_tab,racer,sake,sif,star2lte,starlte,tissot,vayu,violet,X00TD,xmsirius,z2_plus,zangya,zangyapro`

[walleye ](https://download.lineage.microg.org/walleye/)build folder has only the old one from February, is it failed?

**Comment by petefoth** [comment]
> [walleye ](https://download.lineage.microg.org/walleye/)build folder has only the old one from February, is it failed or what is wrong with it?

Good spot - thanks!

`walleye` was not in the target list for April, May, or June and the March build failed because of the QPR2 changes.
The July build was made OK, but was not copied over to the upload server. I don't know why, but I have copied the files across manually.

I'll try to remember to check on this in the August build run, but I may forget, so please feel free to remnd me or let me know if the problem recurs

**Comment by petefoth** [comment]
> The July build was made OK, but was not copied over to the upload server. I don't know why,

it's an `rsync` error - maybe caused bi disk space, may be by transient comms error - broken pipe
```
```
rsync: [receiver] write failed on "/mnt/archive/zips/walleye/lineage-21.0-20240718-microG-walleye-boot.img": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(380) [receiver=3.2.7]
rsync: [sender] write error: Broken pipe (32)
```

**Comment by petefoth** [comment]
*Mon 22 Jul 24*
- Kill off the failing yoshino builds
- 21.0 builds for promoted devices and failed builds: `grus,pyxis,vela,FP3,heart,zippo,Z01R,gta4l,gta4lwifi,oscar,judyln,judypn,judyp,gtowifi,enchilada,fajita,cheetah,nio`

**Comment by petefoth** [comment]
> I can't come up with a better/more fair way of ordering the build priority, but just want to say, that it is a little frustrating, when waiting for a new, maybe urgent build.

Try looking at it this way: 
- there are no guarantees that ***any*** build will happen: you are not paying for any level of service, the project is run by volunteers, and it relies on resources that may become unavailable at any time, with notwarning;
- the builds will be available if and when they are made;
- whether or not a build arrives, you ***already*** have a phone running software that is significantly more up-to-date than the manufacturers stock ROM;
- the idea of an 'urgent' build for a free mobile phone operating system is a nonsense;
- there are many things in life that are worth getting frustrated about: LineageOS for microG is not one of them :)

**Comment by Machion** [comment]
Yes of course 😄 👍 
When the `nio` build had the problem of random reboots (it was a LOS problem), that was urgent 😮‍💨 but you tried to make in-between builds as I remember correctly 👍 
Unfortunatelly with `nio` since the beginning I had more problems, then I ever had with my former MotoX4/payton. Otherwise it's a good phone.

**Comment by petefoth** [comment]
@Machion Your nio build should be available now :)

**Comment by petefoth** [comment]
> * `enchilada` build: mobile data and wifi not working - see [Oneplus 6 latest build broken #651](https://github.com/lineageos4microg/docker-lineage-cicd/issues/651): working on upstream LOS. Build removed to `not_working` directory. Maybe retry when build run is finished

New builds for `fajita` and `enchilada` are now available: see https://github.com/lineageos4microg/docker-lineage-cicd/issues/651#issuecomment-2248623774

**Comment by petefoth** [comment]
I failed to note the 21.0 build for pdx234 failed also, so I didn't retry: I'll do that now

**Comment by petefoth** [comment]
The retried `pdx234` build succeeded, and is now available at https://download.lineage.microg.org/pdx234/

I'll close this issue again :)
