### ISSUE TITLE
August 2024 build run status

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#658]
***ABANDONED THIS BUILD RUN***  >> [Fri Aug 30 18:52:12 UTC 2024]
There is an upstream problem see https://buildkite.com/lineageos/android/builds?branch=lineage-21.0&page=1&state=failed

Let's see what happens when September's builds start on Sunday

--------------------

Full run
- started: >> [Thu Aug  1 00:00:22 UTC 2024]
- [x] 21.0 branch
    - started: >> [Thu Aug  1 00:00:22 UTC 2024]
    - stopped: >> [Sun Aug  4 05:11:51 AM UTC] due to Battery meter bug - see below. Will redo when 20.0 builds are complete
    - expected failures: none
    - unexpected failures: 
- [x] 20.0 branch
     - started: >> [Sun Aug  4 05:08:23 UTC 2024]
     - expected failures: `foster, porg, sif `(TV Boxes)
     - unexpected failures: none
     - completed:
 - [x] unofficial 21.0 builds: ~lilac,poplar,poplar_dsds,maple,maple_dsds~ still failing
 - [x] Re-do  stopped 21.0 devices Completed >> [Fri Aug 30 04:54:12 UTC 2024]
     - unexpected failures: `munch,quill,quill_tab,rtwo`
 - [ ] Retry 21.0 builds - all failing. There is an upstream problem see https://buildkite.com/lineageos/android/builds?branch=lineage-21.0&page=1&state=failed
     - [ ] broken builds `rtwo,hotdogb,hotdog,kebab,instantnoodle,instantnoodlep,lemonade,lemonadep,lemonades,lmi` (use `pf-add-boot_init-image` branch/tag to check #661 is fixed 
         - started >> [Fri Aug 30 05:23:18 UTC 2024]

No time to do any of the following before next build run:
 - [ ] failed builds 21.0 builds: `munch,quill,quill_tab` 
 - [ ] devices added or promoted to 21.0 since 4th August: `a71,socrates,luigi,billie,salami,cebu` 
 - [ ] Retry  failed 20.0 devices: `alphaplus` 

------
21.0 devices: `Building devices a52q,a52sxq,a72q,a73xq,akari,akatsuki,akita,alioth,aura,aurora,axolotl,barbet,beckham,berlin,berlna,beryllium,bluejay,blueline,bonito,borneo,bramble,beyond0lte,beyond1lte,beyond2lte,beyondx,caprip,channel,cheeseburger,cheetah,cheryl,chiron,coral,crosshatch,d1,d1x,d2s,d2x,davinci,deadpool,devon,dipper,discovery,dopinder,dre,DRG,dubai,dumpling,earth,enchilada,equuleus,evert,f62,fajita,felix,flame,foster,foster_tab,FP3,FP4,FP5,g710n,g710ulm,gemini,grus,gta4l,gta4lwifi,gta4xl,gta4xlwifi,gtowifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,guam,guamp,hawao,haydn,heart,hotdog,hotdogb,husky,ingot,instantnoodle,instantnoodlep,joan,judyln,judyp,judypn,kane,kebab,kiev,kirin,lake,lemonade,lemonadep,lemonades,lisa,lmi,lynx,m5,m5_tab,m52xq,marlin,mars,martini,mata,mermaid,messi,Mi439,Mi8917,Mi8937,miatoll,munch,nairo,nash,natrium,nio,nx,nx_tab,ocean,odroidc4,odroidc4_tab,oriole,oscar,panther,payton,pdx203,pdx206,pdx214,pdx215,pdx234,perseus,pioneer,PL2,polaris,porg,porg_tab,pro1,pro1x,pstar,pyxis,quill,quill_tab,r8q,racer,radxa0,radxa0_tab,raven,redfin,renoir,rhode,river,rtwo,sabrina,sagit,sailfish,sargo,shark,shiba,sif,sunfish,surya,sweet,taimen,tangorpro,TP1803,troika,umi,ursa,vela,voyager,wade,walleye,xpeng,xz2c,Z01R,zippo`

20.0 devices: `alphaplus,apollon,bardock,bardockpro,betalm,crownlte,foster,foster_tab,G,gauguin,lancelot,liber,merlinx,mh2lm,nx659j,onclite,porg,porg_tab,quill,quill_tab,sake,sif,star2lte,starlte,tissot,vayu,violet,X00TD,xmsirius,z2_plus,zangya,zangyapro`

**Comment by macearl** [comment]
As it's not really a problem with the microg part/the patches but somewhat related to the builds/the used upstream commits I'll think a comment here suffices and will probably be found the easiest by anyone else noticing this:

At least the beryllium / Poco phone F1 build does not show a battery icon on the latest build. Depending on when upstream was pulled for a specific build I suspect a lot of other devices could be affected as well. If so and seeing as the builds are still running for the "b" devices maybe the run should be stopped and restarted with the newer upstream commits? This could prevent some unnecessary/broken builds. If this is not possible ignore this as I'm completely oblivious to the actual build mechanism which is used here :) 

It seems this was fixed upstream shortly after the builds started? 
Reddit thread i found first: https://www.reddit.com/r/LineageOS/comments/1eht9av/lineageos_21_android_14_30th_july_ota_update/ )

And the patches I found afterwards and which fixed it? (I'm not at all familiar with the code and haven't looked deeper into it, at a first glance they look "correct") :
LOS21: https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/398844
LOS20: https://review.lineageos.org/c/LineageOS/android_packages_apps_LineageParts/+/398842

**Comment by petefoth** [comment]
Thanks for pointing this out. I've stopped the 21.0 builds. The 20.0 builds should pick up the new fix, and I will restart to 21.0 builds when the 20.0 builds are complete

**Comment by petefoth** [comment]
- [Sun Aug  4 06:04:12 UTC 2024] Failed build for alphaplus
<details><summary>Error message</summary>
`FAILED: out/soong/build.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     -o out/soong/build.ninja --globListDir build --globFile out/soong/globs-build.ninja -t -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.build Android.bp
error: hardware/samsung/aidl/camera/device/Android.bp:7:1: "camera.device-impl.samsung" depends on undefined module "android.hardware.graphics.common-ndk_shared"``
```
<details>


```

**Comment by petefoth** [comment]
*Thu 08 Aug 24*
- Builds stopped during `akari` - not clear why.
`>> [Wed Aug  7 19:17:16 UTC 2024] Starting build for akari, lineage-21.0 branch`
- restart from `akari`

**Comment by BurhanBudak** [comment]
I would like to inform you that I get bootloops after doing the OTA for hotdogb.

**Comment by petefoth** [comment]
> I would like to inform you that I get bootloops after doing the OTA for hotdogb.

:( 

You could try manual re-install of previous version [lineage-21.0-20240709-microG-hotdogb.zip](https://download.lineage.microg.org/hotdogb/lineage-21.0-20240709-microG-hotdogb.zip)

**Comment by BurhanBudak** [comment]
> > I would like to inform you that I get bootloops after doing the OTA for hotdogb.
> 
> :(
> 
> You could try manual re-install of previous version [lineage-21.0-20240709-microG-hotdogb.zip](https://download.lineage.microg.org/hotdogb/lineage-21.0-20240709-microG-hotdogb.zip)

Thanks for the support, but should I disable all other mods like magisk before updating?

**Comment by petefoth** [comment]
Sorry - I don't know anything about magisk or other mods. It is quite possible those mods may be causing the bootloop.

I would try removing the mods (and applying them again - if you must - after the update)

**Comment by BurhanBudak** [comment]
> Sorry - I don't know anything about magisk or other mods. It is quite possible those mods may be causing the bootloop.
> 
> I would try removing the mods (and applying them again - if you must - after the update)

In the LOS recovery it says 20240818 is installed. But would a dirty downgrade wipe all my data?

**Comment by tablet0ps** [comment]
> I would like to inform you that I get bootloops after doing the OTA for hotdogb.

I'm facing the same issue on hotdogb and I haven't installed magisk or any other mods. I have important data on my phone that I don't want to wipe. @BurhanBudak If you have successfully downgraded the version, can you please tell how did you do it without losing data?

**Comment by petefoth** [comment]
Thanks for the second report. I've removed the offending build from the download server.

I don't think dirty flashing an older build will work: you will probably need to factory reset . It may be too late this time around, but checkout the solutions in [this wiki post](https://github.com/lineageos4microg/docker-lineage-cicd/wiki/Backup-Migrate-Downgrade). They won't backup EVERYTHING', but they are the best I've found.

**Comment by BurhanBudak** [comment]
> Thanks for the second report. I've removed the offending build from the download server.
> 
> I don't think dirty flashing an older build will work: you will probably need to factory reset . It may be too late this time around, but checkout the solutions in [this wiki post](https://github.com/lineageos4microg/docker-lineage-cicd/wiki/Backup-Migrate-Downgrade). They won't backup EVERYTHING', but they are the best I've found.
> 
> I will kick off a new build when the normal build run is complete

Thx again, but I cant downgrade at all because of SPD, the recovery is to new for older ROMS. 

recovery.img boot.img dtbo.img super_empty.img vbmeta.img from the previous version is needed.

But I think the issue is also these files from the current update, FYI, your update came after official LOS august security update nightly.

**Comment by petefoth** [comment]
> the recovery is to new for older ROMS.

Try flashing the older recovery

**Comment by tablet0ps** [comment]
> I don't think dirty flashing an older build will work: you will probably need to factory reset . It may be too late this time around, but checkout the solutions in [this wiki post](https://github.com/lineageos4microg/docker-lineage-cicd/wiki/Backup-Migrate-Downgrade). They won't backup EVERYTHING', but they are the best I've found.

All of these solutions require booting into android, so they are not an option. Will flashing the older recovery, then flashing the previous ROM work?

**Comment by BurhanBudak** [comment]
> > the recovery is to new for older ROMS.
> 
> Try flashing the older recovery

Yeap, bad update. data corrupt, downgrading flashboot files did nothing. Also we dont know why the August update failed. I have been very clean with the OTA updates and installing Magisk on the other slot for months. Normally Magisk disables itself if it notices safemode. But I did notices before that magisk gets uninstalled by itself randomly even when there is no OTA.

**Comment by petefoth** [comment]
> All of these solutions require booting into android, so they are not an option

As I said, too late this time around, but worth doing in future.

> but I could install older ROMS like 20240709

Good - at least you've got a working phone.



> Also we dont know why the August update failed

True. And there's no way I can investigate. All I can  do is make another build

**Comment by BurhanBudak** [comment]
> Good - at least you've got a working phone.

Nope, it still says I need to factory reset because of corruption. Sure but I really want to backup pictures and videos. Signal is FUBAR so I didnt do any updates for a long time. even if Im on 20240709 and I still need to YOLO reset the phone, should I still try to install the bad 20240818 as Im already on a bad spot?

**Comment by BurhanBudak** [comment]
> All of these solutions require booting into android, so they are not an option. Will flashing the older recovery, then flashing the previous ROM work?

Kind off but data is still corrupt for me, Im forced to do a factory reset. If it comes to this, I might as well go to main LOS and install microg with magisk as bundling up LOS and microG isnt necessary now that spoofing is enabled by default.

But off topic, did you by any chance install Android Auto for MicroG? I had it but removed it because of risk.

**Comment by petefoth** [comment]
> Sure but I really want to backup pictures and videos.

Maybe try installing the latest LOS nightly build from https://download.lineageos.org/devices/hotdogb/builds  and see if that will boot



> did you by any chance install Android Auto for MicroG?

I donl' know anything about Android Auto for MicroG

**Comment by BurhanBudak** [comment]
> Maybe try installing the latest LOS nightly build from https://download.lineageos.org/devices/hotdogb/builds and see if that will boot

To late, already wiped data, ask the other user if he had better luck.

> I donl' know anything about Android Auto for MicroG
I asked @tablet0ps

**Comment by tablet0ps** [comment]
> But off topic, did you by any chance install Android Auto for MicroG? I had it but removed it because of risk.

No, I didn't know it existed.

> Maybe try installing the latest LOS nightly build from https://download.lineageos.org/devices/hotdogb/builds and see if that will boot

I should try this. Till now I was using TWRP to try to recover my data partition but it is not able to mount it for some reason

**Comment by metent** [comment]
This worked! Thanks, @petefoth

**Comment by tablet0ps** [comment]
Able to boot with the nightly `lineage-21.0-20240816-nightly-hotdogb-signed.zip`. Thanks @petefoth for the suggestion

**Comment by BurhanBudak** [comment]
@petefoth, does this bugg happen often? Has it happened before? If yes, then the fix should be on the official troubleshooter. Is it not recommended to dirty flash the orignal code ontop of the MicroG build?

**Comment by petefoth** [comment]
> does this bugg happen often? Has it happened before?

Not that I know of. There was a ***different*** issue with last month's builds for `enchilada` and `fajita` (about broken WiFi and mobile data - see #651 ) which was fixed by making a new build. I have no idea what caused that issue either, but it is what prompted me to write the ['Backup Migrate Downgrade' wiki page](https://github.com/lineageos4microg/docker-lineage-cicd/wiki/Backup-Migrate-Downgrade) and to [add some words about backup to `README.md` ](https://github.com/lineageos4microg/docker-lineage-cicd/commit/faf4c902f0a7c296f3dfdf7d025e71688e29fe3e). I will also add some words there about trying the latest LineageOS build in case an update fails.

>  Is it not recommended to dirty flash the orignal code ontop of the MicroG build?

Sorry - I'm not sure what you mean. By  'the orignal code' do you mean the official LIneageOS build? Flashing that over a failed OTA update has not been recommended before, because this is the first time (that I am aware of) that an OTA update caused a device to boot loop.

**Comment by petefoth** [comment]
I have [added some words to `README.md` ](https://github.com/lineageos4microg/docker-lineage-cicd/commit/dd018f817b79fc9abd9d5d3a38a402c62d7434ce)about failed updates and 'boot loops'

**Comment by schrieveslaach** [comment]
> Able to boot with the nightly `lineage-21.0-20240816-nightly-hotdogb-signed.zip`. Thanks @petefoth for the suggestion

Having the same issue but this suggestion worked for me as well. Thanks @petefoth.

**Comment by petefoth** [comment]
@schrieveslaach Just to confirm, the issue is with `hotdogb`, not some other device?

**Comment by petefoth** [comment]
This post in the LOS Discord ***may*** be of interest:

https://discord.com/channels/628008280605589549/653821647102672926/1274809331623399607

>  I thought I soft bricked the phone with the update as the three circling loading bubbles were there so long that the system rebooted and the bubbles came again and again...
> After an hour of troubleshooting the phones just started normally

**Comment by fixxi** [comment]
I just updated my Oneplus 8 Pro (instantnoodlep) and it also got stuck in boot.

**Comment by petefoth** [comment]
> I just updated my Oneplus 8 Pro (instantnoodlep) and it also got stuck in boot.

Did you see the previous post? The discord user had this problem which went away after an hour or so

**Comment by fixxi** [comment]
> > I just updated my Oneplus 8 Pro (instantnoodlep) and it also got stuck in boot.
> 
> Did you see the previous post? The discord user had this problem which went away after an hour or so

That's weird!
After I read your reply, once again tried to boot my phone and et voilá it started properly.

Is there an explanation for this mysterious behavior?

**Comment by petefoth** [comment]
> Is there an explanation for this mysterious behavior?

Not that I know of. Maybe I should add some words in the README, like "If your device fails to boot after an update, go and do something else for an hour then try again." 😄

**Comment by schrieveslaach** [comment]
> @schrieveslaach Just to confirm, the issue is with `hotdogb`, not some other device?

yes, hotdogb.

**Comment by EnnoxHD** [comment]
Just a note that the boot problem also occurred with `kebab`!

**Comment by Coder-DG** [comment]
> Just a note that the boot problem also occurred with `kebab`!

Same for me, but like that other user after an hour the boot loop stopped and it's back to normal

**Comment by fixxi** [comment]
I believe I figured it out. It seems that my phone reverted back the previous version after X failed attempts.

**Comment by Coder-DG** [comment]
I checked and it indeed got reverted back on my end as well

-------- Original Message --------

**Comment by petefoth** [comment]
> I believe I figured it out. It seems that my phone reverted back to the previous version after X failed attempts.

That makes sense - thanks. In that case there is clearly a problem with the latest builds for all of these devices. I will remove them and try making new builds when the current build run is complete. 

The devices reported up to now are `hotdogb`, `kebab`, `instantnoodlep'. Please let us know if it occurs with any other devices

**Comment by petefoth** [comment]
> Edit: A little faster answer would have saved me.

This project is maintained by a very small group of volunteers, all working for free in their spare time. The fact that you got an answer at all on a Saturday, means that someone is giving up their free time to help you. Maybe consider whether the level of service you get is worth the money you paid for it ;)

If the level of service you require is not available here, then there are other custom ROMs available. Some of them may even have have paid developers available to give you the instant answer you require - good luck!

**Comment by petefoth** [comment]
I've created a new issue to track the bootloop issue - please make any further comments there.

#668

**Comment by petefoth** [comment]
Failed build for `munch`: error building kernel image

Retry

**Comment by videoman614** [comment]
Some good news, possibly unrelated.

[OnePlus 11 (salami)](https://wiki.lineageos.org/devices/salami/) was discontinued for a short period due to A14 QPR3 breaking the camera but [it's back again](https://download.lineageos.org/devices/salami/builds), was told new builds would [resume either this Friday or next Friday](https://xdaforums.com/t/rom-official-lineageos-21-weeklies-for-oneplus-11.4640224/page-17#post-89671767)

**Comment by petefoth** [comment]
> but [it's back again](https://download.lineageos.org/devices/salami/builds),

Thanks.  See the edited section 'devices added or promoted since 4th August` in the first post. I subscribe to changes in https://github.com/LineageOS/hudson/ so I can see when devices are added to or removed from the build target list. So `salami` should get a build here soon (though no guarantees the build will succeed)

**Comment by petefoth** [comment]
Removed broken `lmi` build

**Comment by petefoth** [comment]
*Tue 27 Aug 24*
- failed builds for `quill quill_tab rtwo`
    -  `quill quill_tab` `error: out/target/product/quill/vendor.img+out/target/product/quill/recovery.img too large (602931200 > 536870912)` 
    -  `rwto` killed while building kernel

**Comment by petefoth** [comment]
*Fri 30 Aug 24*
- Build run completed at 04:54:12 UTC today. This gives us less than 42 hours for new builds before the next build run starts.  
  - 16 builds at just over 3 hours per build doesn't work. 
  - forgetting failed builds (munch quill quill_tab) leaves 13 ~42 hours. Too close
  - forgetting about promoted devices (a71 socrates luigi billie salami cebu) eaves 10 which should work, leaving time for merging  `:pf-add-boot_init-image` branch (and maybe a server reboot)
  - so we'll try new builds for just the 'broken' builds:  `rtwo,hotdogb,hotdog,kebab,instantnoodle,instantnoodlep,lemonade,lemonadep,lemonades,lmi`
