### ISSUE TITLE
Builds bootlooping for `hotdogb`, `kebab` & `instantnoodlep`

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#668]
The new builds for these devices are failing to boot. After an hour or so of attempting to boot the broken build, the devices revert to the previous working build

Devices affected:
- OnePlus 7T `hotdogb`
- OnePlus 8T `kebab`
- OnePlus 8 `instantnoodle` (see  https://xdaforums.com/t/lineageos-for-microg.3700997/post-89669749)
- OnePlus 8T Pro `instantnoodlep`

_Originally posted by @BurhanBudak in https://github.com/lineageos4microg/docker-lineage-cicd/issues/658#issuecomment-2295141166_

**Comment by petefoth** [comment]
Similar problems reported in LOS reddit for
- [Poco 3 NFC `surya](https://old.reddit.com/r/LineageOS/comments/1ew8kxa/warning_lineage21020240819nightlysuryasignedzip/)
- [Moto Edge S / Moto G100 `nio`](https://www.reddit.com/r/LineageOS/comments/1ew8rdj/aug_19th_update_doesnt_boot_lineageos_21_nio/)

**Comment by olokelo** [comment]
I'm so grateful to the community for reporting issues with Hotdogb so fast. Had I upgraded earlier and my personal phone would have been borked.

**Comment by Corbachini33** [comment]
Add *lemonade* to the list of devices having bootloops after the new update.

**Comment by aidanchappuis** [comment]
Experiencing this with lemonadep as well.

**Comment by fixxi** [comment]
> The new builds for these devices are failing to boot. After an hour or so of attempting to boot the broken build, the devices revert to the previous working build
> 
> Devices affected:
> 
>     * OnePlus 7T `hotdogb`
> 
>     * OnePlus 8T `kebab`
> 
>     * OnePlus 8T Pro `instantnoodlep`
> 
>     * OnePlus 8T `instantnoodlep`(see  https://xdaforums.com/t/lineageos-for-microg.3700997/post-89669749)
> 
> 
> _Originally posted by @BurhanBudak in [#658 (comment)](https://github.com/lineageos4microg/docker-lineage-cicd/issues/658#issuecomment-2295141166)_

just a little correction, the last two lines should read:
    * OnePlus 8 Pro `instantnoodlep`
    * OnePlus 8 'instantnoodle'

**Comment by petefoth** [comment]
> Just a little correction, the last two lines should read:
> ...

Thanks - corrected.

Just a thought, I wonder whether any of the failing devices had Magisk (or another add-on) installed. Please add your answers below

Devicee|Magisk installed|
|:---:|:---:|
OnePlus 7T `hotdogb` | Yes/No
OnePlus 8T `kebab`|   Yes/No
OnePlus 8T Pro `instantnoodlep` | Yes/No
OnePlus 8T `instantnoodlep` | Yes/No
OnePlus 9`lemonade` | Yes/No
OnePlus 9 Pro`lemonadep` | Yes/No

**Comment by petefoth** [comment]
Another post in LOS Reddit about OnePlus 8t 'bricked' with a fresh install of the latest official LOS build https://old.reddit.com/r/LineageOS/comments/1ex2qzi/oneplus_8t_bricked/

**Comment by fixxi** [comment]
OnePlus 8 Pro `instantnoodlep`
no add-ons
reverted back to previous build 21-20240709-microG-instantnoodlep

**Comment by Corbachini33** [comment]
Oneplus 9 lemonade, no magisk

**Comment by n-hawi** [comment]
Oneplus 8T `kebab`
no magisk

**Comment by petefoth** [comment]
OK - magisk isn't the problem :(

**Comment by Corbachini33** [comment]
Another one that might have the same issue, base lineage os and posted Aug 02. 

https://xdaforums.com/t/lineage-os-update-issue.4684473/

**Comment by aidanchappuis** [comment]
Might be a little late, but if it helps, my lemonadep had magisk.

**Comment by samsapti** [comment]
OnePlus 8T (`kebab`) here. No add-ons.

So, I didn't know it would rollback by itself, so I ended up wiping and reinstalling everything. Both OTA and clean install had the bootloop issue.
I actually tried to switch slot (a/b) via `fastboot` before wiping to hopefully be able to boot back into the old version, but it didn't work.

At least I can confirm that SeedVault works :D

**Comment by petefoth** [comment]
A user in the XDA Forum thread appears to have found a solution: 

https://xdaforums.com/t/lineageos-for-microg.3700997/post-89671565

My interpretation of that post s the the key step was the 'Flashing additional partitions' step, beforeflashing recovery. 

If you need more information about this, I suggest asking by responding to that post in XDA

**Comment by cstuht** [comment]
[](url)Hi, didn't know it would rollback itself either.

Tried solution from user in XDA Forum without success:

	adb sideload lineage-21.0-20240820-microG-lemonadep.zip
	
failed with the following error:

```
Supported API: 3
Finding update package...
Verifying update package...
Update verification took 75.1 s (result 0).
Installing update...
Step 1/2
Error applying update: 7 (ErrorCode: kInstallDeviceOpenError)
ERROR:	recovery: Error in /sideload/package.zip (status 1)

Install completed with status 1.
Installation aborted.
```

Errors from _/tmp/recovery.log_:

```
[  114.996999] 05-27 02:19:41.693   805   805 E libprocessgroup: [ERROR:task_profiles.cpp(814)] Failed to read task profiles from /etc/task_profiles.json
[  114.997023] 05-27 02:19:41.693   805   805 E libprocessgroup: [ERROR:task_profiles.cpp(787)] Loading /etc/task_profiles.json for [805] failed
[  114.997056] 05-27 02:19:41.693   805   805 W libprocessgroup: [WARN:task_profiles.cpp(1059)] Failed to find OtaProfiles task profile
[  114.997253] 05-27 02:19:41.693   805   805 E update_engine_sideload: [ERROR:update_attempter_android.cc(1073)] prefs_->GetInt64(kPrefsPreviousSlot, &previous_slot) failed.
[  114.997543] 05-27 02:19:41.694   805   805 E update_engine_sideload: [ERROR:snapshot.cpp(2807)] Open failed: /metadata/ota: No such file or directory
[  115.373387] 05-27 02:19:42.070   805   805 E update_engine_sideload: [ERROR:fstab.cpp(704)] [libfstab] ReadFstabFromFileCommon(): failed to read file: '/system/etc/fstab.postinstall': No such file or directory
[  115.379187] 05-27 02:19:42.075   805   805 E update_engine_sideload: [ERROR:snapshot.cpp(212)] An update is already in progress, cannot begin a new update
[  115.379212] 05-27 02:19:42.075   805   805 E update_engine_sideload: [ERROR:dynamic_partition_control_android.cc(977)] Cannot begin new update.
[  115.379272] 05-27 02:19:42.076   805   805 E update_engine_sideload: [ERROR:snapshot.cpp(224)] Cannot cancel update after it has completed or started merging
[  115.379288] 05-27 02:19:42.076   805   805 E update_engine_sideload: [ERROR:dynamic_partition_control_android.cc(548)] snapshot_->CancelUpdate() failed.
[  115.379315] 05-27 02:19:42.076   805   805 E update_engine_sideload: [ERROR:delta_performer.cc(919)] Unable to initialize partition metadata for slot A ErrorCode::kSuccess
[  115.379337] 05-27 02:19:42.076   805   805 E update_engine_sideload: [ERROR:delta_performer.cc(459)] Failed to parse manifest
[  115.379355] 05-27 02:19:42.076   805   805 E update_engine_sideload: [ERROR:download_action.cc(227)] Error ErrorCode::kInstallDeviceOpenError (7) in DeltaPerformer's Write method when processing the received payload -- Terminating processing
[  115.379402] 05-27 02:19:42.076   805   805 E update_engine_sideload: [ERROR:delta_performer.cc(1552)] Failed to submit transaction in checkpointing
[  115.383917] 05-27 02:19:42.080   805   805 E update_engine_sideload: [ERROR:snapshot.cpp(2807)] Open failed: /metadata/ota: No such file or directory
[  115.486303] ERROR:   recovery: Error in /sideload/package.zip (status 1)
```

Desperately waiting for the next release which I hope to be able to sideload as OTA update.

**Comment by petefoth** [comment]
Added `hotdog` to the list of devices to be rebuilt

**Comment by petefoth** [comment]
Also reported in `lmi`.

**Comment by tsterbak** [comment]
My Xiaomi 9 Lite (`pyxis`) also bootloops after OTA update.

**Comment by petefoth** [comment]
Ran out of time to get new builds working before September build run starts:  builds were failing upstream too until very recently.
Let's see what happens with the September build run

**Comment by cstuht** [comment]
I ended up doing a factory reset.
As [LineageOS has enabled internal microg support ](https://www.reddit.com/r/LineageOS/comments/1b11zex/los_has_added_internal_microg_support/) for me there is no to need to use lineageos4microg any more.
Installed [vanilla lineage-21.0-20240819](https://download.lineageos.org/devices/lemonadep/builds), then [microg](https://www.reddit.com/r/LineageOS/comments/1bkhmwb/how_to_install_microg/?rdt=55882) and upgraded to lineage-21.0-20240826-nightly without any issues.

**Comment by ivangal2** [comment]
oneplus 9 - lemonade, no magisk, bootlooped for an hour, reverted luckily automatically to July build (i believe it tried the new version in one slot, after x unsuccessful tries it reverted to the former slot). God bless the A/B partitions. :pray:

**Comment by ivangal2** [comment]
Is here someone brave to test the September build whether the bootloop issue still persists?

**Comment by cashflys** [comment]
Installed the OTA for September (not the August rebuild) on hotdogb without any notable issues.  My daily driver is not rooted, exposed, or magisk'd so it was a "stock" install upgrade from the July LOS w/MicroG.  So far it is working as expected no bootloops.  - Cheers

**Comment by olokelo** [comment]
Can confirm, hotdogb with no root works fine after September 17th update.

**Comment by petefoth** [comment]
`instantnoodle` reported as working [in XDA forums](https://xdaforums.com/t/lineageos-for-microg.3700997/post-89735452)

I'll close this if / when we get one more of the remaining affected devices (`instantnoodlep, lemonade, lemonadep`) reported as working OK

**Comment by petefoth** [comment]
`lemonade` [reported as working in XDA forum](https://xdaforums.com/t/lineageos-for-microg.3700997/post-89736217)

Closing this issue

**Comment by ivangal2** [comment]
confirming fajita and lemonade working perfectly with the September build, thank you!

**Comment by AliceOrBob** [comment]
instantnoodlep is working with the September build.

**Comment by ZJaume** [comment]
kebab also working

**Comment by Corbachini33** [comment]
Lemonade upgraded correctly

**Comment by BurhanBudak** [comment]
As the first to report this issue, after I backed up Signal and Seedvault to a Sanddisk USB stick, I installed and didn't get a  bootloop. But now a good backup schedule is need as there is a 1% risk. 

But I forgot to do the inactive slot Magisk step so yeah.
