### ISSUE TITLE
Replace some default settings to weaken our dependency on Google even more

### ISSUE THREAD

**Issue by livingsilver94** [lineageos4microg/docker-lineage-cicd#67]
Hi,
on [r/lineageos](https://www.reddit.com/r/LineageOS) I just found [this post](https://www.reddit.com/r/degoogle/comments/cldohl/how_to_degoogle_lineageos_in_2019). It's a guide to replace some network service endpoints that Android uses by default (DNS and A-GPS, to name a few) from Google to other providers. What would you think to change some of these settings for this fork?

Here's a little list of what we can patch:

- Change the captivity portal. I don't have time to dig to find where we should patch Android P and Q for it, but for R [it's a lot simpler](https://android.googlesource.com/platform/packages/modules/CaptivePortalLogin/+/710e8e27ebcbc739a8fef60bef75f9fe072d07da). Maybe this commit will be backported to Android Q.
- DNS-over-TSL. In Android P it's supported and simple to change via GUI, maybe it's just a matter of changing a config file somewhere.
- A-GPS. We should patch `/system/etc/gps.conf` .

**Comment by petefoth** [comment]
I don't think we are going to do anything with . Unless you have strong objections, I'll close this issue in the next week or so

**Comment by petefoth** [comment]
Closing
