### ISSUE TITLE
Nondescript breakfast failed error when trying to build

### ISSUE THREAD

**Issue by K4sum1** [lineageos4microg/docker-lineage-cicd#670]
Trying to build LineageOS 15.1 for lilac using custom sources.
Here's what I have in ~/manifests/lilac.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    <project name="Eclipse-Community/android_kernel_sony_msm8998_oreo" path="kernel/sony/msm8998" remote="github" revision="lineage-15.1" />
    <project name="Eclipse-Community/android_device_sony_common-treble_oreo" path="device/sony/common-treble" remote="github" revision="lineage-15.1" />
    <project name="Eclipse-Community/android_device_sony_yoshino_oreo" path="device/sony/yoshino" remote="github" revision="lineage-15.1" />
    <project name="Eclipse-Community/android_device_sony_lilac_oreo" path="device/sony/lilac" remote="github" revision="lineage-15.1" />
    <project name="Eclipse-Community/android_vendor_sony_lilac_oreo_full" path="vendor/sony/lilac" remote="github" revision="lineage-15.1" />
</manifest>
```
Here's the command line output:
```
$ sudo docker run \
    -e "BRANCH_NAME=lineage-15.1" \
    -e "DEVICE_LIST=lilac" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "WITH_GMS=true" \
    -e "INCLUDE_PROPRIETARY=false" \
    -v "/home/user/lineage:/srv/src" \
    -v "/home/user/zips:/srv/zips" \
    -v "/home/user/logs:/srv/logs" \
    -v "/home/user/cache:/srv/ccache" \
    -v "/home/user/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd
Unable to find image 'lineageos4microg/docker-lineage-cicd:latest' locally
latest: Pulling from lineageos4microg/docker-lineage-cicd
3c645031de29: Pull complete 
15d6f1255cee: Pull complete 
5f6ce342a41b: Pull complete 
ff004e7f3bd5: Pull complete 
52efe58150b3: Pull complete 
dba5fdb068cc: Pull complete 
4f4fb700ef54: Pull complete 
441868447003: Pull complete 
Digest: sha256:785f3c4caf71d499761ae814a4e9ab4f86b10b040edcae7b00fea59d98a5e656
Status: Downloaded newer image for lineageos4microg/docker-lineage-cicd:latest
Set cache size limit to 50.0 GB
>> [Tue Aug 20 11:48:36 UTC 2024] Branch:  lineage-15.1
>> [Tue Aug 20 11:48:36 UTC 2024] Devices: lilac,
>> [Tue Aug 20 11:48:36 UTC 2024] (Re)initializing branch repository
>> [Tue Aug 20 11:48:40 UTC 2024] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Tue Aug 20 11:48:40 UTC 2024] Syncing branch repository
>> [Tue Aug 20 13:35:42 UTC 2024] Calling git lfs pull disabled
>> [Tue Aug 20 13:35:43 UTC 2024] Applying the restricted signature spoofing patch (based on android_frameworks_base-O.patch) to frameworks/base
>> [Tue Aug 20 13:35:43 UTC 2024] Setting "UNOFFICIAL" as release type
>> [Tue Aug 20 13:35:43 UTC 2024] Adding OTA URL overlay (for custom URL )
>> [Tue Aug 20 13:35:43 UTC 2024] Preparing build environment
>> [Tue Aug 20 13:35:44 UTC 2024] breakfast failed for lilac, lineage-15.1 branch
>> [Tue Aug 20 13:35:44 UTC 2024] Cleaning up
>> [Tue Aug 20 13:35:44 UTC 2024] Cleaning source dir for device lilac
```

**Comment by K4sum1** [comment]
Ok, so I didn't expect /home/**user**/ to be the actual path. I expected user would just be the current user. Anyways I moved the manifests (the above lilac one and the MicroG one) to /home/user/manifests, and tried again. Now it just stops after Preparing build environment without any error.

(This was before your comment)

I renamed the logs folder and ran the command again twice to get fresh logs, and this is what I have. (both old logs before I got manifests, and after)
[logs.zip](https://github.com/user-attachments/files/16677387/logs.zip)

**Comment by petefoth** [comment]
The key line is 
> `build/core/product_config.mk:238: *** Can not locate config makefile for product "lineage_lilac".  Stop.`

Building LOS expects to see a file called `lineage_lilac.mk` in `device/sony/lilac`. That file does not exist in the` Eclipse-Community/android_device_sony_lilac_oreo` repo so the build fails.

PS some text about sharing log files from a very useful telegram channel called @sfx_android
> when sharing logs or longer texts it is recommended a so-called "paste service". This is useful to keep a forum / chat readable for everyone and it dramatically helps a developer to read the log without saving tons of log files on their phones/PC's.
> 
> Here are some examples (use your fav search engine to find more):
> 
> ● https://hastebin.com
> ● https://controlc.com
> ● https://justpaste.me
> ● https://privatebin.net
> ● https://pastebin.com
> ● https://gist.github.com (no size limit!)
> ● https://gitlab.com/dashboard/snippets (no size limit!)
> There you will always have an option how long you want to store that paste:
> 
> Please ensure you choose at least several months (better 1 year) because developers have a real life, too and so its uncertain when they might find time to look into it.
> 
> Once you pasted your text in there you will get an paste URL which you then can simply share without spamming a group/forum.

**Comment by K4sum1** [comment]
So I found this commit from upstream that added lineage_lilac.mk and cherry picked it over.
https://github.com/Eclipse-Community/android_device_sony_lilac_oreo/commit/881a7d3c477041652333004b233e137f09e03c17

I now get this

```
>> [Tue Aug 20 20:10:12 UTC 2024] Preparing build environment
>> [Tue Aug 20 20:10:12 UTC 2024] breakfast failed for lilac, lineage-15.1 branch
>> [Tue Aug 20 20:10:12 UTC 2024] Cleaning up
>> [Tue Aug 20 20:10:12 UTC 2024] Cleaning source dir for device lilac
```
and this in the log
```
including vendor/lineage/vendorsetup.sh
build/core/product_config.mk:238: *** Can not locate config makefile for product "lineage_lilac".  Stop.
Device lilac not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Repository for lilac not found in the LineageOS Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
build/core/product_config.mk:238: *** Can not locate config makefile for product "lineage_lilac".  Stop.
build/core/product_config.mk:238: *** Can not locate config makefile for product "lineage_lilac".  Stop.

** Don't have a product spec for: 'lineage_lilac'
** Do you have the right repo manifest?

>> [Tue Aug 20 20:10:12 UTC 2024] breakfast failed for lilac, lineage-15.1 branch
>> [Tue Aug 20 20:10:12 UTC 2024] Cleaning up
>> [Tue Aug 20 20:10:12 UTC 2024] Cleaning source dir for device lilac
20:10:13 Entire build directory removed.

#### build completed successfully (1 seconds) ####
```

**Comment by petefoth** [comment]
Well it's still looking for a product spec, and not finding it. Do the following lines appear in the `device/sony/lilac/lineage_lilac.mk` that is in your source tree?

If they do, then I am right out of ideas. Good luck

**Comment by K4sum1** [comment]
> I'm going to close this issue, because I'm pretty sure your problems are not caused by an issue with out docker image (which is the purpose of this issue tracker)

I can get it to at least build outside of Docker on Ubuntu. I'm pretty sure that means it is the Docker image and not the sources.

> Do the following lines appear in the device/sony/lilac/lineage_lilac.mk that is in your source tree?

What following lines?

**Comment by petefoth** [comment]
> What following lines?

Sorry - forgot to add them

```
## Device identifier. This must come after all inclusions
PRODUCT_NAME := lineage_lilac
PRODUCT_DEVICE := lilac
```

**Comment by petefoth** [comment]
> I can get it to at least build outside of Docker on Ubuntu. I'm pretty sure that means it is the Docker image and not the sources.

When you build without using Docker. what is the output from the `breakfast` command?

**Comment by K4sum1** [comment]
It has those lines. I don't have a build VM that I can use just yet though. I didn't have the space, but I'll get one set up now.

**Comment by K4sum1** [comment]
> When you build without using Docker. what is the output from the `breakfast` command?

With that commit applied (lineage.mk -> lineage_lilac.mk) I get
```
$ lunch lineage_lilac-userdebug
build/core/product_config.mk:238: *** Can not locate config makefile for product "lineage_lilac".  Stop.
Device lilac not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Repository for lilac not found in the LineageOS Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
build/core/product_config.mk:238: *** Can not locate config makefile for product "lineage_lilac".  Stop.
build/core/product_config.mk:238: *** Can not locate config makefile for product "lineage_lilac".  Stop.

** Don't have a product spec for: 'lineage_lilac'
** Do you have the right repo manifest?
```

If I undo that commit, I get 
```
$ lunch lineage_lilac-userdebug
Trying dependencies-only mode on a non-existing device tree?

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=8.1.0
LINEAGE_VERSION=15.1-20240820-UNOFFICIAL-lilac
TARGET_PRODUCT=lineage_lilac
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_PLATFORM_VERSION=OPM1
TARGET_BUILD_APPS=
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a73
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a73
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.15.0-118-generic-x86_64-with-glibc2.29
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=OPM7.181205.001
OUT_DIR=/home/administrator/android/lineage/out
AUX_OS_VARIANT_LIST=
============================================
```

How do I make the docker script work with a lineage.mk file?

**Comment by petefoth** [comment]
> How do I make the docker script work with a lineage.mk file?

Sorry - I have no idea.

And I'm afraid I don't have any more time to spend on this particularly as
1. You can already build outside of Docker 
2. This for an build that is **_five_** Android versions and _**seven**_ years out-of-date: functioning builds for this device are available:
    1. lIneage-17.1, & 19.1, with & without microG available from [Flamefire in XDA](https://xdaforums.com/t/rom-lineageos-17-18-19-unofficial-update-2024-08-09.4308295/unread) 
    2. [20.0 ](https://xdaforums.com/t/rom-final-lineageos-20-0-unofficial-1-2-2023-12-28.4500913/)and [21.0 ](https://xdaforums.com/t/rom-lineageos-21-0-unofficial-1-1-2024-06-16.4658694/) builds without microG from derf elot /  No1Alien
    3.  'Semi-officiai' 20.0 & 21.0 builds from [los4microG ](https://download.lineage.microg.org/lilac/)
    4. Several other ROMs based on earlier Android versions in [XDA](https://xdaforums.com/f/sony-xperia-xz1-compact-roms-kernels-recoveries.6930/)

As a final contribution, when I get some time, I will try a 15.1  build for a Sony device that was officially supported by LineageOS at version 15.1. If that works, then the problem here is with your sources and / or manifests. If it does not, then there may be a problem with our Docker image, and I will raise an issue about that. (That issue would be fixed by adding a statement to the documentations saying that we no longer support building versions 15.1 and earlier)

**Comment by petefoth** [comment]
> As a final contribution, when I get some time, I will try a 15.1 build for a Sony device that was officially supported by LineageOS at version 15.1.

I started a 15.1 build for Sony Xperia XA2 `pioneer`. The `repo sync` and `breakfast` stages completed fine. The build did not complete, due to an error probably caused by differences in Pythein version
<details><summary>Error details</summary>

```
[  0% 267/111612] build /srv/src/LINEAGE_15_1/out/target/common/obj/all-event-log-tags.txt
FAILED: /srv/src/LINEAGE_15_1/out/target/common/obj/all-event-log-tags.txt
/bin/bash -c "build/tools/merge-event-log-tags.py -o /srv/src/LINEAGE_15_1/out/target/common/obj/all-event-log-tags.txt frameworks/base/core/java/android/app/admin/SecurityLogTags.logtags frameworks/base/core/java/android/content/EventLogTags.logtags frameworks/base/core/java/android/net/EventLogTags.logtags frameworks/base/core/java/android/speech/tts/EventLogTags.logtags frameworks/base/core/java/android/webkit/EventLogTags.logtags frameworks/base/core/java/com/android/internal/logging/EventLogTags.logtags frameworks/base/packages/SettingsProvider/src/com/android/providers/settings/EventLogTags.logtags frameworks/base/packages/SystemUI/src/com/android/systemui/EventLogTags.logtags frameworks/base/services/core/java/com/android/server/EventLogTags.logtags frameworks/base/services/core/java/com/android/server/am/EventLogTags.logtags frameworks/ex/common/java/com/android/common/GoogleLogTags.logtags frameworks/native/services/surfaceflinger/EventLog/EventLogTags.logtags frameworks/opt/telephony/src/java/com/android/internal/telephony/EventLogTags.logtags packages/apps/Settings/src/com/android/settings/EventLogTags.logtags packages/providers/CalendarProvider/src/com/android/providers/calendar/EventLogTags.logtags packages/providers/ContactsProvider/src/com/android/providers/contacts/EventLogTags.logtags packages/services/Telephony/src/com/android/phone/EventLogTags.logtags system/bt/main/../EventLogTags.logtags system/core/liblog/event.logtags system/core/libsysutils/EventLogTags.logtags system/core/logcat/event.logtags system/core/logd/event.logtags system/core/storaged/EventLogTags.logtags"
  File "/srv/src/LINEAGE_15_1/build/tools/merge-event-log-tags.py", line 51
    except getopt.GetoptError, err:
           ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

```
</details>

So it looks like the Docker image will not currently make 15.1  builds, and I will raise an issue to cover that. 

But that does not explain your build errors, which ***are*** caused by errors in either
- your sources OR
- your manifest OR
- the state of your source tree

... and not caused by the Docker image
