### ISSUE TITLE
Missing FP5 namespace for Pixel 6a?

### ISSUE THREAD

**Issue by 0bscur3** [lineageos4microg/docker-lineage-cicd#674]
Hi,

when I am trying to build for Pixel 6a (bluejay) with the following settings it fails due to some missing namespace for the Fairphone 5? Looks like something is synchronising the wrong vendor code?

```
sudo docker run \
    -e "BRANCH_NAME=lineage-21.0" \
    -e "DEVICE_LIST=bluejay" \
    -e "WITH_GMS=true" \
    -e "SIGN_BUILDS=true" \
    -v "/mnt/cache/appdata/lineageos/src:/srv/src" \
    -v "/mnt/cache/appdata/lineageos/zips:/srv/zips" \
    -v "/mnt/cache/appdata/lineageos/logs:/srv/logs" \
    -v "/mnt/cache/appdata/lineageos/ccache:/srv/ccache" \
    -v "/mnt/cache/appdata/lineageos/manifests:/srv/local_manifests" \
    -v "/mnt/cache/appdata/lineageos/keys:/srv/keys" \
    lineageos4microg/docker-lineage-cicd \
```

Error:

> FAILED: out/soong/build.lineage_bluejay.ninja
> cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.lineage_bluejay.variables -o out/soong/build.lineage_bluejay.ninja --globListDir lineage_bluejay --globFile out/soong/globs-lineage_bluejay.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.lineage_bluejay.build Android.bp
> error: vendor/fairphone/FP5/Android.bp:5:1: module "soong_namespace": namespace device/fairphone/FP5 does not exist; Some necessary modules may have been skipped by Soong. Check if PRODUCT_SOURCE_ROOT_DIRS is pruning necessary Android.bp files.
> fatal errors encountered

**Comment by petefoth** [comment]
I am seeing that error too, whatever device I try and build for. I have no idea what is causing it.

So I checked out the LineageOS builds, and they seem to be having the same problem: latest build for `walleye` is also failing with that error: see https://buildkite.com/lineageos/android/builds/69531#0191a3b5-8683-4671-ae45-ab517f87cb4b

Sp this is an upstream problem, not a problem with our docker image.  And it's only taken me about 36 hours to figure out 😄 

Thanks for your report, which is what kicked me into having a closer look at the official LOS builds

**Comment by petefoth** [comment]
This is the same problem as in #677 

More information about a fix / workaround in [this comment](https://github.com/lineageos4microg/docker-lineage-cicd/issues/677#issuecomment-2323343561)

I am currently testing out a fix , which I will share once it's tested OK

**Comment by 0bscur3** [comment]
Thanks for the update. I am already following the issue.
