### ISSUE TITLE
September build run status

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#683]
A bit later than usual ...
  Full run
- started:
  - [x] 21.0 branch
    - All builds failed, due to a breaking change upstream: see #677
  - [x] 20.0 branch
    - started: Sun Sep 1 2024 04:15
    - expected failures: none
    - unexpected failures:
    - completed: Tue Sep 3 2024 14:30
  - [ ] Re-run 21.0 builds (using [`pf-restructure-build` branch](https://github.com/lineageos4microg/docker-lineage-cicd/tree/pf-restructure-build))
    - started: Thu Sep  5 17:42:54 UTC 2024
    - expected failures: none
    - unexpected failures: `billie,haydn,pioneer,voyager,xz2c,polaris,porg,porg_tab,pro1,pro1x,pstar,pyxis,quill,quill_tab,racer,radxa0,radxa0_tab,raven,redfin,renoir,rhode,river,rtwo,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif`
    - completed:
    - [ ] Re-run 21.0 builds: there probably won't be time for this
        - failed builds `billie,haydn,pioneer,voyager,polaris,porg,porg_tab,pro1,pro1x,pstar,pyxis,quill,quill_tab,racer,radxa0,radxa0_tab,raven,redfin,renoir,rhode,river,rtwo,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif` 
        - promoted devices: `cmi`
- completed:

------------------------
Devices:
- 21.0: `a52q,a52sxq,a71,a72q,a73xq,akari,akatsuki,akita,alioth,aura,aurora,axolotl,barbet,beckham,berlin,berlna,beryllium,billie,bluejay,blueline,bonito,borneo,bramble,beyond0lte,beyond1lte,beyond2lte,beyondx,caprip,cebu,channel,cheeseburger,cheetah,cheryl,chiron,coral,crosshatch,d1,d1x,d2s,d2x,davinci,deadpool,devon,dipper,discovery,dopinder,dre,DRG,dubai,dumpling,earth,enchilada,equuleus,evert,f62,fajita,felix,flame,foster,foster_tab,FP3,FP4,FP5,g710n,g710ulm,gemini,grus,gta4l,gta4lwifi,gta4xl,gta4xlwifi,gtowifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,guam,guamp,hawao,haydn,heart,hotdog,hotdogb,husky,ingot,instantnoodle,instantnoodlep,joan,judyln,judyp,judypn,kane,kebab,kiev,kirin,lake,lemonade,lemonadep,lemonades,lisa,lmi,luigi,lynx,m5,m5_tab,m52xq,marlin,mars,martini,mata,mermaid,messi,Mi439,Mi8917,Mi8937,miatoll,munch,nairo,nash,natrium,nio,nx,nx_tab,ocean,odroidc4,odroidc4_tab,oriole,oscar,panther,payton,pdx203,pdx206,pdx214,pdx215,pdx234,perseus,pioneer,PL2,polaris,porg,porg_tab,pro1,pro1x,pstar,pyxis,quill,quill_tab,racer,radxa0,radxa0_tab,raven,redfin,renoir,rhode,river,rtwo,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif,socrates,sunfish,surya,sweet,taimen,tangorpro,TP1803,troika,umi,ursa,vela,voyager,wade,walleye,xpeng,xz2c,Z01R,zippo`
- 20.0: `alphaplus,apollon,bardock,bardockpro,betalm,crownlte,G,gauguin,lancelot,liber,merlinx,mh2lm,nx659j,onclite,sake,star2lte,starlte,tissot,vayu,violet,X00TD,xmsirius,z2_plus,zangya,zangyapro`

**Comment by petefoth** [comment]
- `billie` failed: not picking up the vendor files from TheMuppets
`In file included from build/make/target/product/telephony_vendor.mk:21:
device/oneplus/billie/device.mk:30: error:  vendor/oneplus/billie/billie-vendor.mk does not exist..
06:31:33 dumpvars failed with: exit status 1`

**Comment by petefoth** [comment]
- failed `haydn`
```
FAILED:
build/make/core/Makefile:161: error: overriding commands for target `out/target/product/haydn/vendor/lib64/libnotifyaudiohal.so', previously defined at out/soong/installs-lineage_haydn.mk:220943
```

**Comment by videoman614** [comment]
Did something break?
Builds seem to have stopped at ```lake```

**Comment by petefoth** [comment]
Well spottted - thanks.

- Builds died due to uncommitted changes in `vendor/xiaomi/earth`- tidied up  & restarted builds for remaining devices
- Created #685 to handle this failure better

**Comment by ivangal2** [comment]
@petefoth , if I understand it correctly, all the new builds do not incorporate the signature spoofing, right?

**Comment by petefoth** [comment]
They don't include ***our*** signature spoofing patches: none of our builds have included those patches for a few months now, since upstream LOS implemented code that allows restricted signature spoofing. All our recent builds, including the latest, support restricted signature spoofing (i.e. only what is needed for MicroG to work) using the upstream changes.

**Comment by petefoth** [comment]
*Thu 26 Sep 24*
- `pioneer` failed - retry
```
[ 99% 1599/1600] finishing legacy Make module parsing ...
FAILED:
build/make/core/main.mk:1377: warning:  device/sony/pioneer/lineage_pioneer.mk includes non-existent modules in PRODUCT_PACKAGES
Offending entries:
SimDetect
```

**Comment by petefoth** [comment]
*Sat 28 Sep 24*
- `voyager`failed: same error as `pioneer`
```
[ 99% 1674/1675] finishing legacy Make module parsing ...
FAILED:
build/make/core/main.mk:1377: warning:  device/sony/voyager/lineage_voyager.mk includes non-existent modules in PRODUCT_PACKAGES
Offending entries:
SimDetect
```

**Comment by videoman614** [comment]
```zippo``` seemed to have built correctly, will there be enough time to rerun the failed 21 builds?
Wasn't enough time for ```salami``` and it missed a build in August and ```cmi``` started getting official builds this month.

**Comment by petefoth** [comment]
As of a few hours agoI reckoned ther was time left to make another 11 builds before the next buil run was due to start. So I initiated a build of the following devices which didn't get built this month: `polaris,porg,porg_tab,pro1,pro1x,pstar,pyxis,quill,quill_tab,racer,radxa0`

That leaves the following
1. Didn't get built in time this month`radxa0_tab,raven,redfin,renoir,rhode,river,rtwo,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif`
2. New device: `cmi`
3. Failed builds this month: `billie,haydn,pioneer,voyager,xz2c`

The first two will be first in line in the October build run. 3 will  be done first in the list of remaining 21.0 builds. So the full target list for October will be
- Missed & failed21.0 builds: `radxa0_tab,raven,redfin,renoir,rhode,river,rtwo,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif`
- 20.0 builds: for all 2.0 devices that are in the build target list at 202410-00:01
- Remaining 21.0 builds: `cmi,billie,haydn,pioneer,voyager,xz2c,a52q,a52sxq,a71,a72q,a73xq,akari,akatsuki,akita,alioth,aura,aurora,axolotl,barbet,beckham,berlin,berlna,beryllium,bluejay,blueline,bonito,borneo,bramble,beyond0lte,beyond1lte,beyond2lte,beyondx,caprip,cebu,channel,cheeseburger,cheetah,cheryl,chiron,coral,crosshatch,d1,d1x,d2s,d2x,davinci,deadpool,devon,dipper,discovery,dopinder,dre,dubai,dumpling,earth,enchilada,equuleus,evert,f62,fajita,felix,flame,foster,foster_tab,FP3,FP4,FP5,g710n,g710ulm,gemini,grus,gta4l,gta4lwifi,gta4xl,gta4xlwifi,gtowifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,guam,guamp,hawao,heart,hotdog,hotdogb,husky,ingot,instantnoodle,instantnoodlep,joan,judyln,judyp,judypn,kane,kebab,kiev,kirin,lake,lemonade,lemonadep,lemonades,lisa,lmi,luigi,lynx,m5,m5_tab,m52xq,marlin,mars,martini,mata,mermaid,messi,Mi439,Mi8917,Mi8937,miatoll,munch,nairo,nash,natrium,nio,nx,nx_tab,ocean,odroidc4,odroidc4_tab,oriole,oscar,panther,payton,pdx203,pdx206,pdx214,pdx215,pdx234,perseus,PL2,socrates,sunfish,surya,sweet,taimen,tangorpro,TP1803,troika,umi,ursa,vela,wade,walleye,xpeng,Z01R,zippo`

We will need to keep an eye on how long a 'full' build run for 208 devices takes, and maybe move to e.g. a 40-day build cycle rather then the current monthly cycle: we need some 'down time' for .e.g implementing & testing  changes to the CI/CD tools

-

**Comment by videoman614** [comment]
> maybe move to e.g. a 40-day build cycle rather then the current monthly cycle

I was going to suggest a longer build cycle after observing these past few months, even without 18 and 19 builds, if one device build fails or because of upstream bugs, within the monthly build window there is no time to rebuild for that device.

**Comment by petefoth** [comment]
- failed `pro1` and all subsequent devices: missing namespace bug- 
     - Clearout `vendor/* `and retry for `pro1,pro1x,pstar,pyxis,quill,quill_tab,racer` (which is all we'll have time for)
     - ad `radxa0` to the top of the list of devices for 21.0 builds in October

**Comment by petefoth** [comment]
*Mon 30 Sep 24*
- `quill` and `quill_pad` builds failed - add to main 21.0 list for October build
```
[ 99% 170953/171772] Target vendor fs image: out/target/product/quill/vendor.img (priority: 7)
FAILED: out/target/product/quill/vendor.img
/bin/bash -c "(mkdir -p out/target/product/quill/vendor ) && (mkdir -p out/target/product/quill/obj/PACKAGING/
<snip>
\"error: \$printname too large (\$total > \$maxsize)\"; false; elif [ \"\$total\" -gt \$((maxsize - 32768)) ]; then echo \"WARNING: \$printname approaching size limit (\$total now; limit \$maxsize)\"; fi )"
error: out/target/product/quill/vendor.img+out/target/product/quill/recovery.img too large (602931200 > 536870912)
```

**Comment by petefoth** [comment]
Closing - September was a long time ago 😄
