### ISSUE TITLE
Wrong OTA URL pattern?

### ISSUE THREAD

**Issue by 7FM** [lineageos4microg/docker-lineage-cicd#69]
I am not sure if the OTA URL pattern is intended to be that way:
https://github.com/lineageos4microg/docker-lineage-cicd/blob/e724032a86cfd469b97c82027a7617a83149f05e/src/build.sh#L223
At least it does not work out of the box with the advertised [OTA REST Server]( https://github.com/julianxhokaxhiu/LineageOTA)
The reason is that the server expects a URL pattern like this:
`$OTA_URL/api/v1/{device}/{type}/{incr}`
(See: [README](https://github.com/julianxhokaxhiu/LineageOTA#buildprop))

But because I am fairly new to lineage things it could be that this URL pattern might be intended?
If so I would be glad for a additional hint in the README that '/api' needs to be appended to OTA_URL when using [above server solution]( https://github.com/julianxhokaxhiu/LineageOTA).
I am sure I won't be the only one having struggles because of that.

**Comment by 7FM** [comment]
Well looks like I did not noticed this [section](https://github.com/julianxhokaxhiu/LineageOTA#how-to-integrate-within-your-rom). But still an example containing the /api suffix would have been useful because on the current examples it looks like it just works without.

**Comment by angarod** [comment]
Up this issue since I cannot build a ROM with a custom OTA server.
Not clear if device, type and incr have to be replaced in the build script. If it has to, how to buld multiple devices with the same OTA_URL variable ?

**Comment by diresi** [comment]
I agree that this is a bit strange. Both on https://github.com/julianxhokaxhiu/LineageOTA#how-to-integrate-within-your-rom and here.

Why not automatically add the `/api/` component as well? It appears to me that everything before `/api/` is custom, but starting with it is fixed/predefined, isn't it?

I can imagine that you'd add a quick sanity check with curl to see whether the final URL makes sense.

**Comment by bananer** [comment]
Merged some documentation changes regarding OTA in #153 

Feel free to create a PR or new issue if you have any more suggestions.
