### ISSUE TITLE
Builds failing for `renoir,rhode,river,rtwo,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif`

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#693]
> `renoir,rhode,river,rtwo,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif` builds fine for official, why is it failing for lineageos for microg?

> Probably [the same reason as the September 21.0 builds failed](https://github.com/lineageos4microg/docker-lineage-cicd/issues/683#issue-2512223024).I fixed that problem for most devices, but it seems the fix didn;t work for these devices. I will look into it further when I get some free time

The root cause of all these problems, is that we are not cleaning up properly after each device build. If we are not using `BUILD_OVERLAY` (which we're not because it doesn't work ATM) we are only calling `mka clean`. We are not getting rid f the source directories created and synced during the call to `breakfast`. To do the job properly we should remove the device-specific  code in`device`, `kernel` and `vendor`. Easiest way to do it is to completely remove the content of those three directories: the 'common' stuff will get repopulated  when `repo sync is called at the start of the next device build. THis change is handled in two issues: #688 &  #696

_Originally posted by @videoman614 in https://github.com/lineageos4microg/docker-lineage-cicd/issues/689#issuecomment-2387163578_

**Comment by petefoth** [comment]
Affected devices:
renoir Xiaomi Mi 11 Lite 5G
rhode Motorola moto g52
river Motorola moto g7
rtwo Motorola edge 40 pro, moto X40, edge+ (2023)
sabrina Google Chromecast with Google TV (4K)
sagit Xiaomi Mi 6
sailfish Google Pixel
salami OnePlus 11 5G
sargo Google Pixel 3a
shark Xiaomi Black Shark
shiba Google Pixel 8
sif NVIDIA Shield TV (2019) [Android TV]

**Comment by subiol** [comment]
My device is affected by this issue and the last updated build from more than two months ago has a bug that removes some functionality from the phone. Newer builds of LineageOS have fixed the bug. Until this is fixed it makes no sense to use LineageOS for microG. Any idea when this will be fixed?

**Comment by petefoth** [comment]
> My device is affected by this issue and the last updated build from more than two months ago has a bug that removes some functionality from the phone.

Which device?

Which branch, 20.0 or 21.0?

What functionality is removed?

> Any idea when this will be fixed?

When a new build for the device succeeds, If you tell me the device, I can tell you roughly when that may happen. If you tell me quickly, before I restart the builds, then I can bump it to the head of the queue

**Comment by subiol** [comment]
> Which device?

Rtwo

> Which branch, 20.0 or 21.0?

21.0

> What functionality is removed?

It only detects one sim card slot on the Moto X40. I have tested the current build of LineageOS and detects both without an issue.

> When a new build for the device succeeds, If you tell me the device, I can tell you roughly when that may happen. If you tell me quickly, before I restart the builds, then I can bump it to the head of the queue

I'd appreciate.

**Comment by petefoth** [comment]
> My device is affected by this issue and the last updated build from more than two months ago has a bug that removes some functionality from the phone.

Has today's build for `rtwo` solved this issue for you?

**Comment by videoman614** [comment]
```rtwo``` actually successfully builds!
Hopefully this means ```renoir,rhode,river,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif``` builds stop failing.

**Comment by petefoth** [comment]
I have made builds for `salami` & `renoir` on a rented cloud virtual server, as 
1. we are running out of time for this build run
2. I need to test out the possibility of using a rented cloud virtual server as extra / backup resource for regular build runs

These builds 
- are signed with the same keys as builds on the normal build server
- should appear as OTA updates

Feedback is very welcome, in particular
1. do they appear in updater app
2. can the update be installed successfully.

**Comment by deckultra734** [comment]
>     2. can the update be installed successfully.

I normally install by flashing through fastboot and ADB and salami installs without issue.

**Comment by petefoth** [comment]
Builds for all these devices are now available. I'll close the issue in a few days, unless anyone reports any problems
