### ISSUE TITLE
Pixel 8a - Problems with build-in (bottom) microphone

### ISSUE THREAD

**Issue by famfop** [lineageos4microg/docker-lineage-cicd#697]
Hi, I am not sure if this is actually an issue with lineage + microg (or just plain lineage) but I hope I am at the right location here.

I have installed lineage+microg, i.e. the akita build for my Pixel 8a, and am experiencing issues with my bottom microphone (i.e. very strong noise when on telephone or recorder apps but also in third-party apps like whatsapp or signal.

The funny thing is that the day of the install the telephone did work but starting from the following day it started having this strong noise that makes it almost impossible to hear my voice when talking.

Unfortunately, I was not able to open the diagnosis tool typing `*#*#7287#*#*` so I am unaware of how to debug it. Any help is appreciated. Note: I just installed the latest october update but the problem still persists.

**Comment by petefoth** [comment]
It is very unlikely that this is an issue with LineageOS for microG. It seems to e more like a hardware problem, or a problem with LineageOS. Have you checked in the LineageOS support channels (irc/discord, Reddit) to see if other usrs of your dvice have a problem?

**Comment by famfop** [comment]
Ok, I will try to reset the phone to the original android and check whether the problem persists. Actually, I was hoping this was not the case but I could not find any threads or anything about this issue on lineage on the pixel 8a. If the problem does persist on the Google Android I will close this issue (and else come back here)

**Comment by petefoth** [comment]
@famfop Any progress on this. Can I close this issue now?

**Comment by famfop** [comment]
Hi, sorry I will close it. It turned out to be a hardware issue indeed and also happened with google's factory image.
