### ISSUE TITLE
P4 [Flame] Auto-Fill SMS not working with some apps [LOS 21-microG-flame]

### ISSUE THREAD

**Issue by sibhjas048** [lineageos4microg/docker-lineage-cicd#698]
banking apps unable to read and auto-fill sms/otp from notifications. allowed permissions for SMS, Phone and Notification. banking apps do not allow manually entering sms, it has to read and auto-fill to continue to login

**Comment by petefoth** [comment]
Please be more specific.  
1. Which banking app(s)? I have some apps which I'm pretty sure ***do*** autofill
2. Which app is your default SMS messaging app?
3. Have you tried using a different SMS messaging app?
4. Does the problem also occur using official LineageOS?

The problem is (in my opinion) very unlikely to be with microG, or with LineageOS, or with LIneageOS for microG. Much more likely to be a problem with a specific messaging app.

PS Apologies for the delay in responding - my email provider was offline for several days so I was not seeing notifications for new issues

Please can you provide logs
5. Can you provide logs

**Comment by sibhjas048** [comment]
Thanks for reply, no apologies necessary. 
1. App name : BHIM (https://play.google.com/store/apps/details?id=in.org.npci.upiapp) 
2. Initially, I used LOS messaging app as default, I also tried QKSMS, QUIK, Fossify SMS apps. 
3. Yes, I tried using different SMS messaging apps.
4. I tried installing official LOS, but was unable to successfully boot with error: No valid operating system could be found. The device will not boot. 

After posting this issue last week, I found out that it was happening with all apps. Also, I was having problem with Rapido app (play.google.com/store/apps/details?id=com.rapido.passenger), which was not displaying maps. So, I flashed another ROM. 
Sorry can't provide logs currently, but I am planning to flash LOS-microg or LOS-official build again very soon.
When I install any ROM, I keep getting error : wipe userdata complete, unable to format.

**Comment by qokrb2t** [comment]
To add, rapido shows map for me. That's when searching for ride. Didn't  book or take a ride to check during commute.

Version 0.3.3.240913
com.google.android.gms

Online location service selected was position

**Comment by sibhjas048** [comment]
> Please be more specific.
> 
>     1. Which banking app(s)? I have some apps which I'm pretty sure _**do**_ autofill
> 
>     2. Which app is your default SMS messaging app?
> 
>     3. Have you tried using a different SMS messaging app?
> 
>     4. Does the problem also occur using official LineageOS
> 
> 
> The problem is (in my opinion) very unlikely to be with microG, or with LineageOS, or with LIneageOS for microG. Much more likely to be a problem with a specific messaging app.
> 
> Please can you provide logs? (See https://xdaforums.com/t/guide-providing-a-good-logcat.3814517/#post-77033951/ for how to provide logs)
> 
> PS Apologies for the delay in responding - my email provider was offline for several days so I was not seeing notifications for new issues

Apologies for the delay in replying, I had to reinstall LOS-official build and LOS-microG to test things again.
Please find attached the logcat file
[logcat.txt](https://github.com/user-attachments/files/17529631/logcat.txt) 
Also, I have following observations:
1. No problem with LOS-official builds.
2. After reading qokrb2t 's comment, I updated MicroG, btw f-droid does not suggest the latest. I had to manually select versions.
3. The pre-installed microG that comes with ROM is not up to date and most of the problems are solved after updating microG, but Auto-Fill SMS not working problem still persists.
4. Blank map issue with com.rapido.passenger is solved, but blank map issue with com.rapido.rider still persists. 

Thanks petefoth and qokrb2t for assisting

**Comment by qokrb2t** [comment]
I think this is an issue (autoread otp) of greater and interesting complexity but not sure if it will be entertained here as it looks primarily as something related to microg & they have unfortunately turned off the option of faster interactions

A google search on bhim's inability to autoread otp throws a wide range of suggested solutions with changed goal posts. From turning on mobile data on the sim to be verified (hinting at the ability of the h/w to manage standby or two active sims, to changing default messaging app, default keyboard, make the sim to be verified installed in the physical slot-1, to probable issue with autofill service used. So many points of failures including the app's implementation of autoreading.

From your log, it looks like the selinux logs attempts of reads from something that originated from bhim & reports the attempts were denied. If these were the autoread requests, then they were clearly denied by selinux. But. What makes it interesting is that it probably was allowed on los (i assume you had gapps) where the selinux must be set  enforcing as well. In that case there is microg that's doing something different. I assume their next release is on 13th nov cause of an issue with the last one

**Comment by petefoth** [comment]
> 2\. After reading qokrb2t 's comment, I updated MicroG, btw f-droid does not suggest the latest. I had to manually select versions.

If you enable 'Allow beta updates', you should be offered the latest `0.3.3` build

> 3\. The pre-installed microG that comes with ROM is not up to date and most of the problems are solved after updating microG, but Auto-Fill SMS not working problem still persists.

We currently ship the latest ***stable*** release of of microG services which, according to [the microG website](https://microg.org/download.html)  is `0.2.27`: releases after that are all classified as 'preview' releases. I don't really want to start shipping 'beta' or 'preview' releases. It's easy enough to get the latest `0.3.3` version, by enabling 'Allow beta updates'. I will contact the microG project to see if and when they plan to designate the 0.3 branch as 'stable'.

I'm afraid I don't have time to start debugging or decoding your logcat output, but if you or @qokrb2t can find something that need changing in this project, I will try to help with getting that done. ***However***,  I think the problem is much more likely to be with microG than with this project. 

If the problem ***is*** with microG, then the fix will probably have to come from them. Have you raised either of these two issues (autofill SMS and maps) with them? If not I suggest you do raise it. 

Worth looking in the following places t see if these issues have been raised, fixed or worked-around there.
- microG reddit https://www.reddit.com/r/MicroG/ - someone has [raised it already](https://www.reddit.com/r/MicroG/comments/1g1w9c4/microglos_21_flame_autofill_issue/) - is that you
- gmsCore issue tracker https://github.com/microg/GmsCore/issues - nothing about SMS -auto-fill there yet. I suggest raising an issue there and attaching your logcat.txt. If you want to raise the maps issue, I suggest raising it ***in a separate issue*** as it's clearly a different problem.
Good luck!

**Comment by sibhjas048** [comment]
> I think this is an issue (autoread otp) of greater and interesting complexity but not sure if it will be entertained here as it looks primarily as something related to microg & they have unfortunately turned off the option of faster interactions
> 
> A google search on bhim's inability to autoread otp throws a wide range of suggested solutions with changed goal posts. From turning on mobile data on the sim to be verified (hinting at the ability of the h/w to manage standby or two active sims, to changing default messaging app, default keyboard, make the sim to be verified installed in the physical slot-1, to probable issue with autofill service used. So many points of failures including the app's implementation of autoreading.
> 
> From your log, it looks like the selinux logs attempts of reads from something that originated from bhim & reports the attempts were denied. If these were the autoread requests, then they were clearly denied by selinux. But. What makes it interesting is that it probably was allowed on los (i assume you had gapps) where the selinux must be set enforcing as well. In that case there is microg that's doing something different. I assume their next release is on 13th nov cause of an issue with the last one

Thank you for the detailed explanation. I don't wanna be rude but I have tried almost every suggested solutions on web search, except for default keyboard solution. I don't think that would work because auto-fill sms worked with los-official-build with same aosp keyboard.
And yes, I flashed gapps after flashing los-21-official-build. I also mentioned earlier that auto-fill does not work for any app, not just the BHIM app.
So, do you think this is fixable? 
P.S. I am not an engineer, developer, programmer, coder or tester.

**Comment by sibhjas048** [comment]
> > 2. After reading qokrb2t 's comment, I updated MicroG, btw f-droid does not suggest the latest. I had to manually select versions.
> 
> If you enable 'Allow beta updates', you should be offered the latest `0.3.3` build
> 
> > 3. The pre-installed microG that comes with ROM is not up to date and most of the problems are solved after updating microG, but Auto-Fill SMS not working problem still persists.
> 
> We currently ship the latest _**stable**_ release of of microG services which, according to [the microG website](https://microg.org/download.html) is `0.2.27`: releases after that are all classified as 'preview' releases. I don't really want to start shipping 'beta' or 'preview' releases. It's easy enough to get the latest `0.3.3` version, by enabling 'Allow beta updates'. I will contact the microG project to see if and when they plan to designate the 0.3 branch as 'stable'.
> 
> I'm afraid I don't have time to start debugging or decoding your logcat output, but if you or @qokrb2t can find something that need changing in this project, I will try to help with getting that done. _**However**_, I think the problem is much more likely to be with microG than with this project.
> 
> If the problem _**is**_ with microG, then the fix will probably have to come from them. Have you raised either of these two issues (autofill SMS and maps) with them? If not I suggest you do raise it.
> 
> Worth looking in the following places t see if these issues have been raised, fixed or worked-around there.
> 
>     * microG reddit https://www.reddit.com/r/MicroG/ - someone has [raised it already](https://www.reddit.com/r/MicroG/comments/1g1w9c4/microglos_21_flame_autofill_issue/) - is that you
> 
>     * gmsCore issue tracker https://github.com/microg/GmsCore/issues - nothing about SMS -auto-fill there yet. I suggest raising an issue there and attaching your logcat.txt. If you want to raise the maps issue, I suggest raising it _**in a separate issue**_ as it's clearly a different problem.
>       Good luck!

Yes, that is me who wrote on reddit. Until now, I did not know that lineageos4microg and microg are two different teams. Thankyou for the suggestion, I will raise an issue there with my logcat. I am keeping this issue open for the moment, if @qokrb2t found a solution. Thanks again.

**Comment by petefoth** [comment]
> I also forgot to mention that I also installed CalyxOS, it also comes preinstalled with microG. Auto-read SMS worked in CalyxOS except for the BHIM app and other banking apps.

Then it's almost certainly an issue with how those apps interact with microG. As the problems in CalyxOS seem to be the same as the problems in LineageOS for microG, then it's clearly not an bug caused by this project, so I'm going to close te issue.

**Comment by qokrb2t** [comment]
Will you consider raising an issue at https://github.com/microg/GmsCore/issues if you still got the logs?

With 2 logcats for 2 different applications on los-microg?
1. BHIM - this will fail with the selinux related messages
2. Swiggy ( https://play.google.com/store/apps/details?id=in.swiggy.android ) - this should succeed (at least it does for me)

N if possible the BHIM logcat on los-gapps as where it succeeds

I guess inviting the attention of a microg developer or even an app developer who has implemented/knows autoread is the fastest way to find the bug

I still think its a microg related issue but unable to understand the cause

**Comment by petefoth** [comment]
> Will you consider raising an issue at https://github.com/microg/GmsCore/issues if you still got the logs?

I guess that is aimed at @sibhjas048 - I don't have time to raise issues against microG unless they are ones that specifically cause problems for LineageOS for microG.

Good luck, and  hope you find a fix

**Comment by qokrb2t** [comment]
Yes. I was checking with @sibhjas048. I wish i was more clear
