### ISSUE TITLE
device need patched sources

### ISSUE THREAD

**Issue by skulko** [lineageos4microg/docker-lineage-cicd#7]
I am trying to compile for an unofficial device which needs a device specific patch before compiling  (lineage).

How can I do that with Docker??

**Comment by corna** [comment]
You can use a userscript: mount a volume on `/srv/userscripts` (`-v "<your folder>:/srv/userscripts"`) and put two files inside that folder, `pre-build.sh` and your patch (both owned by `root`, non writeable by standard users).

All the files in this folder will be copied in `/root/userscripts` in the Docker container and `pre-build.sh` will be run just before starting the build from the source root, so it should contain something like this:

```
#!/bin/sh

cd frameworks/base
git am /root/userscripts/mypatch.patch
```

(or any script able to patch your source tree). See [here](https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L283-L286).

**Comment by skulko** [comment]
many thanks, I will try.

**Comment by skulko** [comment]
would this also be ok:
`pre-build.sh`
`#!/bin/sh

cd device/samsung/smdk3470-common/patch/
sh ./apply.sh
`
?

**Comment by corna** [comment]
Yes, just remember that the patching is not reverted across different builds.

**Comment by corna** [comment]
So you should make sure that apply.sh doesn't complain if the patch has already been applied

**Comment by htsmi** [comment]
Hey, resurrecting this issue because I had a similar situation. Only I wasn't able to deal with it with the `pre-build.sh` approach because the patches need to be applied to the device tree, and that isn't retrieved until the brunch command which proceeds to build everything.

I ended up running the container with `--entrypoint /bin/bash` and ran all the commands manually up to the build step. Then, in place of `brunch $codename`, I `breakfast $codename`, apply the patch, then `mka bacon`. This seems to work, and I could make my own script to do this and add another userscript location here. I'm not all that experienced with all this stuff though, so I wonder if there is a cleaner/better way of doing this.

**Comment by muranava** [comment]
> Hey, resurrecting this issue because I had a similar situation. Only I wasn't able to deal with it with the `pre-build.sh` approach because the patches need to be applied to the device tree, and that isn't retrieved until the brunch command which proceeds to build everything.
> 
> I ended up running the container with `--entrypoint /bin/bash` and ran all the commands manually up to the build step. Then, in place of `brunch $codename`, I `breakfast $codename`, apply the patch, then `mka bacon`. This seems to work, and I could make my own script to do this and add another userscript location here. I'm not all that experienced with all this stuff though, so I wonder if there is a cleaner/better way of doing this.

hi
i am interested in trying to apply a security patch before build and your method seems interesting, any chance you have documented this somewhere with associted script?
thanks

**Comment by htsmi** [comment]
It's pretty much all in what I said, I didn't write any new script, I manually ran all the commands in `build.sh` for my device with the changes I described. Line 291 is where the `brunch $codename` is that both fetches the device tree and builds it.

A patch like so: [fetch-before-pre-build.patch.txt](https://github.com/lineageos4microg/docker-lineage-cicd/files/5712788/fetch-before-pre-build.patch.txt) should do the trick if you want `pre-build.sh` to run after fetching the device tree and before the build.

**Comment by muranava** [comment]
> It's pretty much all in what I said, I didn't write any new script, I manually ran all the commands in `build.sh` for my device with the changes I described. Line 291 is where the `brunch $codename` is that both fetches the device tree and builds it.
> 
> A patch like so: [fetch-before-pre-build.patch.txt](https://github.com/lineageos4microg/docker-lineage-cicd/files/5712788/fetch-before-pre-build.patch.txt) should do the trick if you want `pre-build.sh` to run after fetching the device tree and before the build.

hi okay thanks!

**Comment by muranava** [comment]
> It's pretty much all in what I said, I didn't write any new script, I manually ran all the commands in `build.sh` for my device with the changes I described. Line 291 is where the `brunch $codename` is that both fetches the device tree and builds it.
> 
> A patch like so: [fetch-before-pre-build.patch.txt](https://github.com/lineageos4microg/docker-lineage-cicd/files/5712788/fetch-before-pre-build.patch.txt) should do the trick if you want `pre-build.sh` to run after fetching the device tree and before the build.



> Hey, resurrecting this issue because I had a similar situation. Only I wasn't able to deal with it with the `pre-build.sh` approach because the patches need to be applied to the device tree, and that isn't retrieved until the brunch command which proceeds to build everything.
> 
> I ended up running the container with `--entrypoint /bin/bash` and ran all the commands manually up to the build step. Then, in place of `brunch $codename`, I `breakfast $codename`, apply the patch, then `mka bacon`. This seems to work, and I could make my own script to do this and add another userscript location here. I'm not all that experienced with all this stuff though, so I wonder if there is a cleaner/better way of doing this.

hi again
sory to bother got a question about the entrypoint method; how do you enter just the build.sh script, i.e. let docker set variables and run init.sh first before stopping to start the build.sh?
thanks for any help

**Comment by htsmi** [comment]
I did something like:
```
docker run \
    -it --entrypoint /bin/bash \
    -v "$build_dir/lineage:/srv/src" \
    -v "$build_dir/zips:/srv/zips" \
    -v "$build_dir/logs:/srv/logs" \
    -v "$build_dir/ccache:/srv/ccache" \
    -v "$build_dir/manifests:/srv/local_manifests" \
    -v "$build_dir/keys:/srv/keys" \
    lineageos4microg/docker-lineage-cicd
```
But you'll have to improvise a little because I didn't follow a fixed recipe, just copied and pasted commands from `init.sh` and `build.sh` as was necessary to more or less simulate the build process that the scripts follow. You'll have to research the manual build process if you aren't already pretty familiar with it.

**Comment by muranava** [comment]
> I did something like:
> 
> ```
> docker run \
>     -it --entrypoint /bin/bash \
>     -v "$build_dir/lineage:/srv/src" \
>     -v "$build_dir/zips:/srv/zips" \
>     -v "$build_dir/logs:/srv/logs" \
>     -v "$build_dir/ccache:/srv/ccache" \
>     -v "$build_dir/manifests:/srv/local_manifests" \
>     -v "$build_dir/keys:/srv/keys" \
>     lineageos4microg/docker-lineage-cicd
> ```
> 
> But you'll have to improvise a little because I didn't follow a fixed recipe, just copied and pasted commands from `init.sh` and `build.sh` as was necessary to more or less simulate the build process that the scripts follow. You'll have to research the manual build process if you aren't already pretty familiar with it.

right okay i think i see, thanks!

**Comment by muranava** [comment]
hi @htsmi 

sorry to bother you, but i have an issue with trying to patch things before build starts, and hoping maybe you have seen this issue?

thanks to your previous info i have been able to patch before build fine until now. 

what happens now is after running init.sh, and then the following commands upto `mka bacon` the build fails by complaining about:
`tried to lock out/.lock, but timed out polling every 1s until 10s . Make sure no other Soong process is using it`

thanks for any help!
