### ISSUE TITLE
November Build run status

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#702]
Full run
- started: >> [Fri Nov  1 00:00:04 UTC 2024]
- [x] 21.0 branch
    - started: >> [Fri Nov  1 00:00:04 UTC 2024]
    - expected failures: none
    - unexpected failures: `heart,NB1,quill,quill_pad`
    - completed: >> [Thu Nov 28 22:17:34 UTC 2024]
- [ ] 20.0 branch
     - started: >> [Thu Nov 28 22:17:55 UTC 2024]
     - expected failures: none
     - unexpected failures: none
     - not done `violet,X00TD,xmsirius,z2_plus,zangya,zangyapro`
     - completed: 
 - [ ] Retry  failed 21.0 devices
 - [ ] 21.0 builds for devices added or promoted since 1st xxx
 - [ ] Retry failed 20.0 devices
- completed:

---------------------

21.0 devices: `a52q,a52sxq,a71,a72q,a73xq,akari,akatsuki,akita,alioth,apollon,aura,aurora,axolotl,barbet,beckham,berlin,berlna,beryllium,billie,bluejay,blueline,bonito,borneo,bramble,beyond0lte,beyond1lte,beyond2lte,beyondx,caprip,cebu,channel,cheeseburger,cheetah,cheryl,chiron,cmi,coral,crosshatch,d1,d1x,d2s,d2x,davinci,deadpool,devon,dipper,discovery,dopinder,dre,DRG,dubai,dumpling,earth,enchilada,equuleus,evert,f62,fajita,felix,flame,foster,foster_tab,FP3,FP4,FP5,g710n,g710ulm,gemini,grus,gta4l,gta4lwifi,gta4xl,gta4xlwifi,gtowifi,gts4lv,gts4lvwifi,guacamole,guacamoleb,guam,guamp,hawao,haydn,heart,hotdog,hotdogb,husky,ingot,instantnoodle,instantnoodlep,joan,judyln,judyp,judypn,kane,kebab,kiev,kirin,lake,lemonade,lemonadep,lemonades,lisa,lmi,luigi,lynx,m5,m5_tab,m52xq,marlin,mars,martini,mata,mermaid,messi,Mi439,Mi8917,Mi8937,miatoll,munch,nairo,nash,natrium,NB1,nio,nx,nx_tab,nx606j,nx619j,ocean,odroidc4,odroidc4_tab,onclite,oriole,oscar,panther,payton,pdx203,pdx206,pdx214,pdx215,pdx234,perseus,pioneer,PL2,polaris,porg,porg_tab,pro1,pro1x,pstar,pyxis,quill,quill_tab,racer,radxa0,radxa0_tab,raven,redfin,renoir,rhode,river,rtwo,sabrina,sagit,sailfish,salami,sargo,shark,shiba,sif,socrates,sunfish,surya,sweet,taimen,tangorpro,TP1803,troika,umi,ursa,vela,voyager,wade,walleye,xpeng,xz2c,Z01R,zippo`

20.0 devices: `alphaplus,bardock,bardockpro,betalm,crownlte,G,gauguin,lancelot,liber,merlinx,mh2lm,nx659j,sake,star2lte,starlte,tissot,vayu,violet,X00TD,xmsirius,z2_plus,zangya,zangyapro`

**Comment by petefoth** [comment]
*Thu 07 Nov 24*
- Build run failed during build of d2s
```
>> [Wed Nov  6 23:27:15 UTC 2024] Starting build for d2s, lineage-21.0 branch
Building branch lineage-20.0
Building devices alphaplus,bardock,bardockpro,betalm,crownlte,G,gauguin,lancelot,liber,merlinx,mh2lm,nx659j,sake,star2lte,starlte,tissot,vayu,violet,X00TD,xmsirius,z2_plus,zangya,zangyapro
Using default tag: latest
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
- restart from `d2s`

**Comment by Machion** [comment]
Sorry to ask, but since the build failures in August and other changes from LOS, I stopped updateing my device (nio/21). 
Can you say, it's save/stable again?

**Comment by petefoth** [comment]
> Sorry to ask, but since the build failures in August and other changes from LOS, I stopped updateing my device (nio/21).
> Can you say, it's save/stable again?

No problems reported that I know of with the September and October builds for this device. And I don't think the problems with the August build affected this device either. Should be as safe as ever installing the October build (or the November buold which has just started, and should be available in ~4 hours time

**Comment by petefoth** [comment]
*Sat 23 Nov 24*
- Build for `quill` failed:  `recovery.img too large`. I remember this happening in September: see [this comment](https://github.com/lineageos4microg/docker-lineage-cicd/issues/683#issuecomment-2383596335). Upstream chages will be needed before these devices build

<details>

```
[ 99% 171476/171947] Target vendor fs image: out/target/product/quill/vendor.img (priority: 7)
FAILED: out/target/product/quill/vendor.img
/bin/bash -c "(mkdir -p out/target/product/quill/vendor ) && (mkdir -p out/target/product/quill/obj/PACKAGING/vendor_intermediates && rm -rf out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_fs_type=ext4\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_size=536870912\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_disable_sparse=true\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"vendor_selinux_fc=out/target/product/quill/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"building_vendor_image=true\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"ext_mkuserimg=mkuserimg_mke2fs\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"fs_type=ext4\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"erofs_sparse_flag=-s\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"f2fs_sparse_flag=-S\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"avb_avbtool=avbtool\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"avb_vendor_hashtree_enable=true\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"avb_vendor_add_hashtree_footer_args=--prop com.android.build.vendor.os_version:14 --prop com.android.build.vendor.fingerprint:\$(cat out/target/product/quill/build_fingerprint.txt) --prop com.android.build.vendor.security_patch:2022-04-05 --rollback_index 0\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"avb_vendor_key_path=external/avb/test/data/testkey_rsa4096.pem\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"avb_vendor_algorithm=SHA256_RSA4096\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"avb_vendor_rollback_index_location=5\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"root_dir=out/target/product/quill/root\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (echo \"skip_fsck=true\" >>  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (sort -o  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt  out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt ) && (PATH=out/host/linux-x86/bin/:system/extras/ext4_utils/:\$PATH out/host/linux-x86/bin/build_image --input-directory-filter-file out/target/product/quill/obj/PACKAGING/vendor_intermediates/file_list.txt out/target/product/quill/vendor out/target/product/quill/obj/PACKAGING/vendor_intermediates/vendor_image_info.txt out/target/product/quill/vendor.img out/target/product/quill/system ) && (size=\$(for i in out/target/product/quill/vendor.img out/target/product/quill/recovery.img; do stat -c \"%s\" \"\$i\" | tr -d '\\n'; echo +; done; echo 0); total=\$(( \$( echo \"\$size\" ) )); printname=\$(echo -n \"out/target/product/quill/vendor.img out/target/product/quill/recovery.img\" | tr \" \" +); maxsize=\$((536870912)); if [ \"\$total\" -gt \"\$maxsize\" ]; then echo \"error: \$printname too large (\$total > \$maxsize)\"; false; elif [ \"\$total\" -gt \$((maxsize - 32768)) ]; then echo \"WARNING: \$printname approaching size limit (\$total now; limit \$maxsize)\"; fi )"
error: out/target/product/quill/vendor.img+out/target/product/quill/recovery.img too large (602931200 > 536870912)
18:56:26 ninja failed with: exit status 1
```

</details>

**Comment by Machion** [comment]
> No problems reported that I know of with the September and October builds for this device. And I don't think the problems with the August build affected this device either. Should be as safe as ever installing the October build (or the November buold which has just started, and should be available in ~4 hours time

Latest November build runs without problems, but I had to sideload it again, because the updater app didn't find any updates at all and manual update within the app also didn't work.

**Comment by petefoth** [comment]
> but I had to sideload it again, because the updater app didn't find any updates at all and manual update within the app also didn't work.

Yes. This is a known problem: see #704

**Comment by Machion** [comment]
I rejoiced too soon. With this build I don't have any audio processing. No input (mic), no output (speaker/headphones). Some apps crash or behave strange, which depend on audio. I wish there would be one release without major problems 😅 
It seems to be more a LOS problem, than a problem of this build, right? I will try to file a ticket there.

**Comment by petefoth** [comment]
Worth trying to reproduce thr issue on sn unofficial build. Otherwise they will probably respond with 'Unofficial! We only support official builds'.

What device yo you have?

**Comment by Machion** [comment]
I know, but if the problem is very general and not really connected to microg, maybe it's ok for them? 
My device is MotoG100/nio

**Comment by petefoth** [comment]
- 20.0 builds won't finish: will probably need to start the next run with 2.0.0 builds for `violet,X00TD,xmsirius,z2_plus,zangya,zangyapro`
