### ISSUE TITLE
cannot check for updates

### ISSUE THREAD

**Issue by tomo90** [lineageos4microg/docker-lineage-cicd#704]
I noticed that since Nov 16th (last successfull check) I am not able to check for updates (Settings - System - Check for updates). I have tried it on several different networks including mobile data.

Device: Mi8937

**Comment by petefoth** [comment]
Reported to the person who maintains the OTS server. I'll keep you posted

**Comment by petefoth** [comment]
The OTA server does now seem to be servig OTA updates. But I am not sure if they will work. Is anyone brave enough  to try?

**Comment by petefoth** [comment]
The OTA server now appears to be serving updates. But I'm not sure whether or not they will work. Is anyone brave enough to try?

Also asked in the XDA thread https://xdaforums.com/t/lineageos-for-microg.3700997/post-89822982

**Comment by petefoth** [comment]
I have successfully updated
- `xz2c`: `lineage-21.0-20240829-microG-xz2c` ->`lineage-21.0-20241002-microG-xz2c`
- `sunfish`: ? (didn;t note the build number -> `lineage-21.0-20241026-microG-sunfish`

**Comment by petefoth** [comment]
@tomo90 Please can you let me know if update checks are working for you now? Thx

**Comment by petefoth** [comment]
> Also asked in the XDA thread https://xdaforums.com/t/lineageos-for-microg.3700997/post-89822982

Reported in XDA as working for 

> Surya ok, from 2024-10-26 to 2024-11-26

Closing
