### ISSUE TITLE
LineageOS 22.0 is coming

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#708]
There is a `lineage-22.0` branch [in the `LineageOS/android/` repo](https://github.com/LineageOS/android/tree/lineage-22.0)

I know we will need the following:
- [] changes to `src/new_build.sh` 
    - allow `lineage-22.0` as a valid branch
- [] Keep the most recent 21.0 build for promoted device, until we are sure the 22.0 build is stable.

We don't need 
- a new signature spoofing patch as LineageOS has supported 'restricted' signature spoofing for a while now and we build with `SIGNATURE_SPOOFING=no`. With no signature spoofing patch, we will not support `SIGNATURE_SPOOFING=yes` or `SIGNATURE_SPOOFING=restricted`. These are already not supported in the restructured `new_build.sh`, so no changes required for this

Anything else?

**Comment by petefoth** [comment]
I successfully made a  lineage-22.0 for `tokay` on the new build server. It's available on the download server: https://download.lineage.microg.org/tokay/

Closing

**Comment by TheEdgeOfRage** [comment]
I assume other devices will be added on the January build?

**Comment by petefoth** [comment]
> I assume other devices will be added on the January build?

Don't assume 😄 

The `tokay` build was to check that we are capable of making 22.0 builds: it is the target 22:0 device in [LOS's `experimental` target list](https://github.com/LineageOS/hudson/blob/main/lineage-experimental-targets).

The January build run will include whichever devices are in [the main LOS build target list](https://github.com/LineageOS/hudson/blob/main/lineage-build-targets) at midnight on 31st December. At the moment there re no 22.0 devices in that list.

You could try asking in the LOS support channels when the 22.0 builds will be starting: they are really helpful when it comes to ETAs 😉
