### ISSUE TITLE
Possible typo in new_build?

### ISSUE THREAD

**Issue by OdinVex** [lineageos4microg/docker-lineage-cicd#715]
Should this line be using `bacon` or rather `$codename`?

https://github.com/lineageos4microg/docker-lineage-cicd/blame/4020df94691be42926fc96b037e10418bc1fcbff/src/new_build.sh#L437

**Comment by petefoth** [comment]
> Should this line be using `bacon` or rather `$codename`?

No. `bacon` in this context is a build target in the Android build system as described in this quote ***not*** a device codename

> brunch
> -
> Defined simply, brunch is equivalent to
> 
> breakfast [device name] && mka bacon
> 
> This means that it sets up your build environment to be configured for your device, and then commences the build process. mka bacon is just CyanogenMods's way of saying build the code for your device. It's generally only used for officially supported devices (ones that you use can choose through the breakfast menu).
> 

from this web page

https://www.trcompu.com/MySmartPhone/AndroidKitchen/Breakfast-Brunch-Lunch.html
