### ISSUE TITLE
system spoofs signature failing on latest microG

### ISSUE THREAD

**Issue by je-vv** [lineageos4microg/docker-lineage-cicd#716]
With:

- microG Services 0.3.6.244735
- microG Companion 0.3.6.40226
- microG Services Framework 0.1.0

Lineageos for microG fails the self-checks:

- System spoofs signature
- Play Services(GmsCore) has correct signature
- Play Store (Phonesky) has correct signatue

It is supposed lineageos for microG is one of the few AOSP based ROMS which support signature spoofing, as documented by microG itself on (Signature Spoofing)[https://github.com/microg/GmsCore/wiki/Signature-Spoofing], and up until now there were no microG self-checks failing.  However with latest upgrade on microG Services and Companion, that got no longer working.

Are new images from lineageos for microG required, so that they keep supporting signature spoofing?

BTW, it's the same on pixel 4a (5g) and moto one 5g ace, so this behavior doesn't seem to be phone dependent.

**Comment by BurhanBudak** [comment]
They just added PI stub, so give it time.

**Comment by ale5000-git** [comment]
This is not a bug, new Google libs have changed the way to check signature so microG detect that the signature spoofing patch in yout ROM is incomplete.
LineageOS (so even LineageOS for microG) have already fixed it, so all builds from 2024/12/17 should have it fixed, just update.

**Comment by je-vv** [comment]
well, I'm on latest LOS for microG versions on both phones (already with their December upgrade) I mentioned, so I guess it'll be next month upgrade?  Or is there an early upgrade coming?

Feel free to close this if you think it's not a bug.

**Comment by ale5000-git** [comment]
I'm not related to LineageOS for microG, I just wanted to exaplain the issue.
All the details are explained here: https://github.com/microg/GmsCore/issues/2680#issuecomment-2538425189

**Comment by je-vv** [comment]
I see.  I'm wondering if that means the next month upgrade won't be able to be an OTA one.

I'm closing this one then.

Many thanks for clarifying, and I guess it'll take some time to propagate to LOS for microG.

**Comment by je-vv** [comment]
BTW, the good news is that OTA updates bring the patch in, so they are enough to eventually get the changes, :)

Many thanks for the clarifications !
