### ISSUE TITLE
moto one 5g ace (kiev) December version OTA upgrade (21.0-20241216) made the phone get into a boot loop

### ISSUE THREAD

**Issue by je-vv** [lineageos4microg/docker-lineage-cicd#717]
I haven't read about this behavior on LOS, I just experienced it only on LOS for microG.  With the latest LOS for microG OTA upgrade, to "21.0-20241216", the moto one 5g ace (kiev) phones got into a boot loop after reboot.  No way to get them out of there, even by reverting to the immediate previous working image (still 21.0).  The only way to take the phones out of the boot loop was to do a factory reset, which by all means is like the last and saddest solution.  Something similar happened to the pixel 4a (5g) months ago, but in that case a factory reset was of no help, a posterior image sort of made the phone come back from the dead, and if I'm not mistaken that was a LOS issue.

Maybe something broke for these motos with the latest upgrade, can't really tell anymore since I performed the factory resets...

**Comment by petefoth** [comment]
Did you have any add-ons (e.g. Magisk) installed?

**Comment by je-vv** [comment]
No, I don't.  Nothing OS related, nothing LOS, and not even microG beyond the the 3 compoonents the come with LOS for microG.

**Comment by petefoth** [comment]
OK. I've kicked off a new build for this device

**Comment by je-vv** [comment]
Just so you know, I got on the phones Today's update, and things went smooth.  Hopefully you guys find out why the boot loop.  In my case, as the phones were needed I went for the factory reset on the past update...  Thanks !
