### ISSUE TITLE
OnePlus 11 (salami CPH2451) 20241227 build bootloops when installed via adb and ota

### ISSUE THREAD

**Issue by deckultra734** [lineageos4microg/docker-lineage-cicd#718]
Tried installing lineage-21.0-20241227-microG-salami through lineageos recovery results in bootloop, formatting data/factory reset doesn't fix the problem, build is broken.

**Comment by petefoth** [comment]
> Tried installing lineage-21.0-20241227-microG-salami through lineageos recovery

Maybe try using the recovery that comes with lineageos4microg [`lineage-21.0-20241227-microG-salami-recovery`](https://download.lineage.microg.org/salami/lineage-21.0-20241227-microG-salami-recovery.img)

Were you flashing over
1. a previous build of lineageos4microg
2. official LineageOS build
3. Stock ROM
4. Something else

 > build is broken.

Not according to [this post](https://github.com/lineageos4microg/docker-lineage-cicd/issues/710#issuecomment-2563727451) . More likely to be a problem with your device or your environment

**Comment by deckultra734** [comment]
> Maybe try using the recovery that comes with lineageos4microg [`lineage-21.0-20241227-microG-salami-recovery`](https://download.lineage.microg.org/salami/lineage-21.0-20241227-microG-salami-recovery.img)

I did, follow the official instructions with all the downloads from the lineageos for microg build, like i have done for years.

I flashed over the 20241125 build and when that didn't work, factory reset and did a clean flash.

> Not according to [this post](https://github.com/lineageos4microg/docker-lineage-cicd/issues/710#issuecomment-2563727451) . More likely to be a problem with your device or your environment
Can't be my device or environment when factory resetting and installing the older 20241125 boots without problems.

**Comment by petefoth** [comment]
Only thing I can think of is thst the rom zip file was corrupted during download. Did youcheck against the SHAsum file?

**Comment by deckultra734** [comment]
> Only thing I can think of is thst the rom zip file was corrupted during download. Did youcheck against the SHAsum file?

Yes, I have.

![Screenshot_20241228_222433](https://github.com/user-attachments/assets/17a04f2f-e8c1-44ab-8014-189a8dd5fd1f)

**Comment by vs49688** [comment]
So, like I said in the other thread, it worked fine on my device. It's a CPH2449 model.

The only thing I might have done differently was get Magisk (28101) to install itself to the inactive slot before rebooting.

`21-20241227-microG-salami`

`lineage_salami-userdebug 14 AP2A.240905.003 eng.root.20241227.035023 dev-keys`
