### ISSUE TITLE
Touch completely non-functional on Essential PH-1 (mata)

### ISSUE THREAD

**Issue by BigGriddle** [lineageos4microg/docker-lineage-cicd#72]
Hi,

When flashing L4M 16.0 on my Essential PH-1 (mata) following the LOS installation instructions, the touchscreen is completely non-functional after rebooting into the operating system. I use the following instructions to install L4M 16.0, https://wiki.lineageos.org/devices/mata/install

However, if I first flash the official nightly build of LOS to the device in TWRP, then without rebooting, follow the clean migration steps, (wipe system, data, dalvik, cache), and lastly flash the latest L4M, the touchscreen works.

The touchscreen becomes non-functional again though after a OTA update using the updater on the phone. I have not been able to find any workaround, other than reinstalling the whole system following the above steps.

The touchscreen also does not work in recovery, unless I flash L4M as mentioned earlier that temporarily fixes the touchscreen issue, until the next update.

This issue does not occur on the official LOS ROM. From first flash, to OTA updates, it works without issue on my device. This leads me to believe this issue is specific to L4M.

So, that it is fully understood from start to finish how I am flashing L4M 16.0 onto my device, the steps I take to flash custom ROMs are listed below.

Use official Essential OEM August, 2018 fastboot package, and run the flashall.bat file to flash back to this build. This is to fix the issue where touch doesn't function in TWRP. Enable USB Debugging again. Bootloader has already been unlocked. Then, flash TWRP to boot_a. Next, reboot into TWRP, and follow the instructions here, https://wiki.lineageos.org/devices/mata/install to wipe data, and system. Then, lastly sideload L4M. Upon rebooting, the touchscreen doesn't work at all. The same happens in recovery.

I have posted on Reddit about this seeking assistance regarding this issue, more information may be found here, https://www.reddit.com/r/MicroG/comments/fgdu8f/touch_completely_nonfunctional_on_the_lineageos/

Any help on having this issue resolved in future builds would be appreciated.

Thanks!

**Comment by BigGriddle** [comment]
I do want to give an update to this. I have now tested L4M after flashing the latest OEM Pie build from Essential. While touch is broken in TWRP, giving the commands via the adb twrp shell to wipe, and flash the L4M ROM does result in touch working. So, this does appear to depend on which version of the stock ROM you have on the device prior to flashing L4M from that may have this issue.

**Comment by spolack** [comment]
mata was promoted to LineageOS 17.1. Therefore its not sure whether this issue still exists and relates to microG. Please reopen if it still occurs.
