### ISSUE TITLE
Memory error with default command

### ISSUE THREAD

**Issue by angarod** [lineageos4microg/docker-lineage-cicd#76]
Just pull the docker image today and execute the build of beacon as the wiki said to begin.
The build failed and the log said : 
`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`
I think rebuilding the docker image with an `export _JAVA_OPTIONS="-Xmx3g"` before the building of the ROM.
My specs : 4gio RAM 30 Gio swap 1to ssd and previous building of lineageos 17 the default way is working with 3g of java heap.

**Comment by DeeUnderscore** [comment]
See also #68

**Comment by angarod** [comment]
I put `ENV _JAVA_OPTIONS "-Xmx3g"` in the Dockerfile and the build complete successfully

**Comment by SolidHal** [comment]
This fix is now included in https://github.com/lineageos4microg/docker-lineage-cicd/pull/70
