### ISSUE TITLE
No more weekly updates for device (D855) because lineage 17.1 replaced the lineage 16 builds.

### ISSUE THREAD

**Issue by tokariu** [lineageos4microg/docker-lineage-cicd#77]
I was eagerly waiting for aprils android security updates but my device suddenly doesn't get any new weekly updates from lineage.microg.org anymore.
I headed over to the lineageOS website and saw that from now on, only lineageos 17.1 builds are released.
However, lineage.microg.org only makes a build for the final (and now outdated and lacking security updates) lineageos 16 build.

compare:
https://download.lineage.microg.org/d855/
with
https://download.lineageos.org/d855

are there any plans to support microg updates for LineageOS 17.1 builds (directly from the microg.org website)?

**Comment by tokariu** [comment]
ok, I found the answers here:
- https://www.reddit.com/r/MicroG/comments/g3mng7/is_anyone_even_wondering_about_why_marvin_might/
- https://www.reddit.com/r/MicroG/comments/g2szse/replacements_for_lineageos_for_microg/
- https://www.reddit.com/r/MicroG/comments/g22yuh/does_everything_work_on_android_10_now/
- https://www.reddit.com/r/MicroG/comments/g076ig/lineageos_for_microg/

obviously the dev of microg (marvin) is missing and he doesn't push updates. bugfixes are in queue but they don't get applied. so people considering changing to OmniROM or microg forks as there are no signs that microG gets updated anytime soom. 

too bad, many lineageOS roms switched to lineageos 17.1 now and don't support v16 updates anymore, so the automatic microG releases won't work anymore.

**Comment by eike-fokken** [comment]
Have a look at
https://gist.github.com/mar-v-in/c8254168c63361c5094de13a7afea344

**Comment by thequint-lab** [comment]
That's the developer of microg. Lineageos4microg is not maintained by the same developer as microg fyi

**Comment by Iey4iej3** [comment]
See https://github.com/lineageos4microg/docker-lineage-cicd/pull/70. It has not been merged yet, maybe due to the fact that microg is not working on Android 10.

**Comment by theScrabi** [comment]
Uff this is bad.

**Comment by carlin-q-scott** [comment]
I think this is a duplicate of issue #68

**Comment by derhagen** [comment]
Well, shouldn't it be possible to provide up-to-date 16.0 builds at least? LineageOS didn't stop developing 16.0, it just doesn't build any 16.0 images for some devices any more. I was thinking that LOS4microG builds their own images anyway, so what is the reason we don't see any more weekly 16.0 builds?

**Comment by spolack** [comment]
Both Devices were promoted to LineageOS 17.1 which is now supported. 
This is  related to the master issue #89
