### ISSUE TITLE
omnirom/android_packages_apps_OpenDelta no longer exists

### ISSUE THREAD

**Issue by DeeUnderscore** [lineageos4microg/docker-lineage-cicd#78]
`docker build` currently fails because [it tries to clone](https://github.com/lineageos4microg/docker-lineage-cicd/blob/e724032a86cfd469b97c82027a7617a83149f05e/Dockerfile#L181) from a repo that is no longer available:

https://github.com/omnirom/android_packages_apps_OpenDelta.git

I don't know why it's not there or what happened to it.

**Comment by tjburrows** [comment]
I tried replacing it with https://github.com/lineageos4microg/android_packages_apps_OpenDelta and it seems to work fine, but I'm not sure what the differences are...

**Comment by SolidHal** [comment]
I'm dropping it all together in #70 , I don't think opendelta is supported or used anymore anyway

**Comment by spolack** [comment]
We dont use OpenDelta, therefore i accepted the drop Commit.
