### ISSUE TITLE
VOIP calling impossible

### ISSUE THREAD

**Issue by daedhel** [lineageos4microg/docker-lineage-cicd#8]
Hi, I cannot call via VOIP with Lineageos MicroG, either with the native Phone app nor 3rd party apps like Linphone. But both of those options work with LineageOs.

Device: LG G3 (canadian) D852
Voip settings: port=5080, UDP, authentification via username+password

Tested LineageOs and LineageOs-MicroG with multiple releases versions for both, even the latest ones, with always the same results.

I'm available to provide more info if required.

**Comment by rugk** [comment]
> But both of those options work with LineageOs.

With or without Google Apps?

Because maybe that is just a feature implemented in the Google Apps. If so, this needs to be reported to microG.

**Comment by nExXxuS** [comment]
As rugk explained this is unlikely a L4M bug. Therefore please report it upstream, either to lineageos or microg. Closing for now.
