### ISSUE TITLE
FAILED: /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar 

### ISSUE THREAD

**Issue by DPTJKKVH** [lineageos4microg/docker-lineage-cicd#80]
I use a fork that includes all patches made by @SolidHal + the small user-agent fix made by @evan-goode . (Many thanks to you both if you read this!) No other modifications have been made.

I use an Ubuntu Server 20.04 guest in VirtualBox with 2 CPU cores and 4GB RAM, KVM paravirtualisation enabled. My host is an Ubuntu 20.04 with IntelCore i7-2600k and 16GB RAM.

My build instructions are:

> sudo docker run \
>     -e "BRANCH_NAME=lineage-16.0" \
>     -e "DEVICE_LIST=lithium" \
>     -e "SIGN_BUILDS=true" \
>     -e "CCACHE_SIZE=100G" \
>     -e "WITH_SU=true" \
>     -e "SIGNATURE_SPOOFING=restricted" \
>     -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
>     -v "/home/user/lineage:/srv/src" \
>     -v "/home/user/zips:/srv/zips" \
>     -v "/home/user/logs:/srv/logs" \
>     -v "/home/user/cache:/srv/ccache" \
>     -v "/home/user/keys:/srv/keys" \
>     -v "/home/user/manifests:/srv/local_manifests" \
>     name_of_my_docker_image

**ISSUE:**
The Build process runs fine up until 90% and then failes with the following error:

> [ 90% 85640/94804] //system/core/liblog:liblog header-abi-linker liblog.so.lsdump
> [ 90% 85641/94804] Target Java: /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar
> 
> **FAILED: /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar** 
> /bin/bash -c "(rm -f /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar ) && (rm -rf /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/anno ) && (mkdir -p /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/ ) && (mkdir -p /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/anno ) && (/srv/src/LINEAGE_16_0/out/soong/host/linux-x86/bin/zipsync -d /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/srcjars -l /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/srcjar-list -f \"*.java\"  /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/aapt2.srcjar ) && (if [ -s /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/java-source-list -o -s /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/srcjar-list ] ; then /srv/src/LINEAGE_16_0/out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath /srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  -classpath /srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-auto-value-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/org.apache.http.legacy_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-common_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/com.android.vcard_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-commons-io-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-dagger2-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-disklrucache-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-gifdecoder-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-glide-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-all-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-context-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-core-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-okhttp-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-protobuf-lite-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-stub-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-javax-annotation-api-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-javax-inject-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-libshortcutbadger-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-mime4j-core-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-mime4j-dom-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-error-prone-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-guava-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-glide-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-glide-annotation-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/dialer-zxing-target_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/jsr305_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/libbackup_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/legacy-test_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/libphonenumber_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/volley_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/org.lineageos.platform.internal_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/libprotobuf-java-lite_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-support-dynamic-animation_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-support-core-ui_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-support-design_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-support-transition_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-support-v13_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-support-v4_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-appcompat_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-cardview_intermediates/classes-header.jar:/srv/src/LINEAGE_16_0/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-recyclerview_intermediates/classes-header.jar  -d /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes -s /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/anno  -source 1.8 -target 1.8 -g:source,lines  -processorpath /srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-auto-value_intermediates/classes.jar:/srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-javapoet_intermediates/classes.jar:/srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-dagger2_intermediates/classes.jar:/srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-dagger2-compiler_intermediates/classes.jar:/srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-dagger2-producers_intermediates/classes.jar:/srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-glide-annotation_intermediates/classes.jar:/srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-glide-compiler_intermediates/classes.jar:/srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-guava_intermediates/classes.jar:/srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-javax-annotation-api_intermediates/classes.jar:/srv/src/LINEAGE_16_0/out/host/common/obj/JAVA_LIBRARIES/dialer-javax-inject_intermediates/classes.jar -processor com.google.auto.value.processor.AutoValueProcessor,dagger.internal.codegen.ComponentProcessor,com.bumptech.glide.annotation.compiler.GlideAnnotationProcessor \\@/srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/java-source-list \\@/srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/srcjar-list || ( rm -rf /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes ; exit 41 ) fi ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar     @<(find /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh /srv/src/LINEAGE_16_0/out/target/common/obj/APPS/Dialer_intermediates/classes; echo \"-C /srv/src/LINEAGE_16_0/out/empty .\") )"
> Picked up JAVA_TOOL_OPTIONS: -Xmx6g
> Note: Generating a Provider for com.android.dialer.glidephotomanager.impl.GlidePhotoManagerImpl. Prefer to run the dagger processor over that class instead.
> Note: [1] Wrote GeneratedAppGlideModule with: []
> [ 90% 85642/94804] //system/core/liblog:liblog header-abi-diff liblog.so.abidiff
> [ 90% 85643/94804] //system/keymaster:libkeymaster_portable link libkeymaster_portable.so
> [ 90% 85644/94804] //external/llvm:libLLVM_android link libLLVM_android.so
> ninja: build stopped: subcommand failed.
> 16:19:55 ninja failed with: exit status 1

I spent 4 hours searching for a solution however while the highligted log entry does come up in some threads none of them have a solution to my problem. I did a second try and failed at exactly the same package.

I'm pretty desperate since building does take a long time and I can't make out what's the issue here. The log just says "FAILED" without giving any reason how and why it failed.

Does anybody have an idea how I could fix this?

Many thanks in advance!

**Comment by DPTJKKVH** [comment]
Just as I was about to close my VM I noticed this message. (I ssh into my VM so I didn't see this message in my terminal windows.)

![memory](https://user-images.githubusercontent.com/7238653/80288027-58241e80-8735-11ea-8f9b-6302bfd698eb.png)

This seems releated I guess? However I can't remember my 4GB of RAM for the VM ever running out? It usually hovered around 1.6GB to 2GB.

Is there some way to increase the java heap size? The build script seems to use ` JAVA_TOOL_OPTIONS: -Xmx6g`. I would like to increase that if required but none of the files in this repo seem to set this option.

**Comment by Findus23** [comment]
see https://github.com/lineageos4microg/docker-lineage-cicd/issues/76

**Comment by DPTJKKVH** [comment]
I already use the SolidHal's 6GB settings, so I'll try to increase it even more. I will report back here.

**Comment by DPTJKKVH** [comment]
I increase my CPUs to 4 and the RAM to 8GB. I upped the swap to 32GB. I changed the `ENV ANDROID_JACK_VM_ARGS` to `-Xmx8g` and the `ENV JAVA_TOOL_OPTIONS` to `-Xmx12g`.

Now the build process went through without errors.

THANKS! <3
