### ISSUE TITLE
No new build for gemini (Mi 5) since 24 March

### ISSUE THREAD

**Issue by opusforlife2** [lineageos4microg/docker-lineage-cicd#81]
Hi. Gemini is one of those devices which haven't been promoted to 17.1 yet. It has been shifted to weekly 16.0 builds instead. But the download page doesn't have any of these builds.

**Comment by motorto** [comment]
Yeah , chiron (mi mix 2) is in the same situation

**Comment by spolack** [comment]
Both Devices were promoted to LineageOS 17.1 which is now supported. 
This is  related to the master issue #89
