### ISSUE TITLE
Update to lineageos 17.1 for harpia

### ISSUE THREAD

**Issue by AntoineD** [lineageos4microg/docker-lineage-cicd#84]
LineageOS for Harpia device has been [updated to 17.1](https://download.lineageos.org/harpia), would it be possible to get an updated [microg version](https://download.lineage.microg.org/harpia/)?

**Comment by ahstro** [comment]
There's work being done to support 17.1 in #70 😊

**Comment by AntoineD** [comment]
Thanks!
