### ISSUE TITLE
muppets script missing branch for lineage-17.1

### ISSUE THREAD

**Issue by JuniorJPDJ** [lineageos4microg/docker-lineage-cicd#86]
I'm getting error like this when building:
```
microg_1  | >> [Thu Jul 23 21:45:57 UTC 2020] Can't find a matching branch on github.com/TheMuppets, using lineage-15.1
```
Which seems to be placed here in code: https://github.com/lineageos4microg/docker-lineage-cicd/blob/e724032a86cfd469b97c82027a7617a83149f05e/src/build.sh#L129
And there seems not to be lineage17 version in if

**Comment by soladev** [comment]
LineageOS 17.1 is not supported for now, but PR #70 is opened to add support for it. Until it's merged to the main project, you can use [this repository](https://github.com/SolidHal/docker-lineage-cicd/tree/lineageos-17.1) instead to build your image for lineageOS 17.1

**Comment by JuniorJPDJ** [comment]
What do you think about mentioning which version are supported in readme or somewhere?

**Comment by spolack** [comment]
I dont think thats required, but now we get a rather informative error message.

Fixed.
