### ISSUE TITLE
Mi A2 (jasmine_sprout) not available

### ISSUE THREAD

**Issue by dferrg** [lineageos4microg/docker-lineage-cicd#88]
Mi A2 is officially supported by lineage OS [https://download.lineageos.org/jasmine_sprout](https://download.lineageos.org/jasmine_sprout) but it doesn't appear in https://download.lineage.microg.org/

I'll try to build it myself, but it would be great to have official support and OTA updates.

**Comment by soladev** [comment]
The lineageOS4MicroG developer is not as active right now, and this is why new phones officially supported by LineageOS aren't supported with microG. You can read more on this subject on [this gist](https://gist.github.com/mar-v-in/c8254168c63361c5094de13a7afea344) and on [this issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/77)

**Comment by Iey4iej3** [comment]
> The microG developer was not as active as he used to be and microG wasn't supported for Android 10, and this is why new phones officially supported by LineageOS aren't supported with microG. You can read more on this subject on [this gist](https://gist.github.com/mar-v-in/c8254168c63361c5094de13a7afea344) and on [this issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/77).
> 
> Concerning this project, it's kinda sad but this project is almost dead. There are some explainations of why in the PR #70

Does the [latest microG](https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.11.202414) support Android 10?

**Comment by soladev** [comment]
I think it does. From what I've read the latest release was supposed to be a fix for Android 10. Still, I have a custom build of LineageOS4MicroG 17.1 on my phone for like two months and I never had an issue with MicroG.

**Comment by githtz** [comment]
Yes, the latest microG works with LineageOS 17.1

**Comment by spolack** [comment]
This is and was related to the master issue #89
