### ISSUE TITLE
LineageOS 17.1 Devices are not built

### ISSUE THREAD

**Issue by spolack** [lineageos4microg/docker-lineage-cicd#89]

**Comment by spolack** [comment]
Current master supports LineageOS 17.1. Build are running again.

**Comment by spolack** [comment]
Reopen until the builds are available.

**Comment by ethael** [comment]
@spolack thank you for the update! what about shamu (nexus 6), is it in a build queue?

**Comment by Unb9rn** [comment]
@spolack will star2lte (Galaxy S9+) be included?

**Comment by Iey4iej3** [comment]
`polaris` has not been built yet.

**Comment by ethael** [comment]
nexus 6 has a build. thanks

**Comment by spolack** [comment]
> One week is over. Is `bardock` still included or only `bardockpro`?

Bardock build is covered by issue #93

**Comment by mawed** [comment]
Anyone knows what's up with the beryllium built?

It's officially supported by los, but not anymore by L4M?
