### ISSUE TITLE
Provide "unofficial" Builds for legacy LineageOS or oficially demoted devices.

### ISSUE THREAD

**Issue by spolack** [lineageos4microg/docker-lineage-cicd#90]

**Comment by kurt-by** [comment]
Thank you for taking over this project. What's your plan to make it visible? The XDA thread seems to lack sustaining.

**Comment by ashimokawa** [comment]
A great example would be the S4 Mini which still builds from official lineage 17.1 sources and runs perfectly. I am self-building for that device but it would be great if I could switch back to official.

**Comment by JuniorJPDJ** [comment]
I've the same issue with ZTE Axon 7 (codename axon7 in lineage and ailsa_ii for twrp).
There's my manifest for this phone: https://github.com/JuniorJPDJ/lineage-building/blob/master/manifests/axon7.xml

**Comment by spolack** [comment]
Devices so far which were dropped due to deprecation of lineageos-15.1
* angler
* bullhead
* che10
* cherry
* dogo
* dragon
* foster
* fugu
* hayabusa
* huashan
* mint
* odin
* pollux
* pollux_windy
* tsubasa
* yuga

I started a build for those.

**Comment by spolack** [comment]
I'm not considering building from unofficial repositories for now.

**Comment by neopostmodern** [comment]
@spolack 

> I started a build for those.

Where are you publishing / releasing them?

**Comment by spolack** [comment]
https://download.lineage.microg.org/

Those "unofficial" builds are marked with the release type "UNOFFICIAL-microG".

**Comment by neopostmodern** [comment]
Nice! :tada: 
Are you considering also building up-to-date versions (e.g. 17.1), which might exceed the last official version (e.g. 15.1 in the case of `angler`)? That would be even more amazing. Or is it not possible?

**Comment by spolack** [comment]
I dont think so, because it seems there are some reasons why there were not promoted yet, isnt it?

**Comment by spolack** [comment]
I'm now spinning up a LineageOS 16.0 mido build. Mido was only discontinued due to the developer doesnt own the device anymore, even though its one of the top devices in terms of install count.

**Comment by ljl-covid** [comment]
@spolak they were not promoted, or they were dropped, possibly like in the case @ashimokawa mentions (I don't know which it is: official LinageOS deleting old builds completely makes it hard for me to follow things). In the latter situation I assume things would be similar to 15.1 or 16.0 devices that were dropped... in the former, if you have users who can confirm it actually works fine, then why not?

For my information, do you plan to build axon7 or is there something stopping that one? That was also dropped while on 15.1, I'm still using the last available LineageOS for microG for it which works pretty decent.

**Comment by JuniorJPDJ** [comment]
@ljl-covid I use it with own unofficial build from manifest I mentioned above.
It works very good with microG lineage 16.0.

**Comment by ashimokawa** [comment]
serranoltexx (S4 Mini) is still maintained in the official sources 17.1 branch by the same maintainer who maintained it until it was dropped during the 14.1 releases.

The reasons are unclear, but I remember that a lot of devices went unofficial after new rules were applied to official builds since 15.1. See https://www.lineageos.org/Changelog-16/ and read paragraph "Device support: new rules".

From my own experience I can say that 17.1 runs great, and I know some other people who still use that phone. Builds would be really great. :)

**Comment by spolack** [comment]
> serranoltexx (S4 Mini) is still maintained in the official sources 17.1 branch by the same maintainer who maintained it until it was dropped during the 14.1 releases.
> 
> The reasons are unclear, but I remember that a lot of devices went unofficial after new rules were applied to official builds since 15.1. See https://www.lineageos.org/Changelog-16/ and read paragraph "Device support: new rules".
> 
> From my own experience I can say that 17.1 runs great, and I know some other people who still use that phone. Builds would be really great. :)

If you could provide me the commit, which removes seranoltexx, then i'll take a look.

**Comment by ashimokawa** [comment]
@spolack 

https://review.lineageos.org/c/LineageOS/hudson/+/218560/2

There is no discussion and no reason. This was even before 14.1 was discontinued, at the same time the author continued to support 15.1,16.0,17.1 in the official tree. See here:

https://github.com/LineageOS/android_device_samsung_serranoltexx/commits/lineage-17.1

**Comment by matteo-gallo-bb** [comment]
@spolack do you think it could be possible to provide an unofficial build for the nexus 4 (mako)? This is the post on XDA with the source code repositories of linageOS 17.1: https://forum.xda-developers.com/nexus-4/development/rom-lineageos-15-1-t3758779

**Comment by ashimokawa** [comment]
@matteo-gallo-bb 

I think this issue is about reactivating device builds that are still maintained in the OFFICIAL lineage repositories.
Just building from inofficial sources and signing the builds is a bit too much trust IMO.

**Comment by von-nihil** [comment]
LineageOS is [dropping support for a bunch of popular devices](https://www.xda-developers.com/lineageos-17-1-supports-nextbit-robin-moto-g5-moto-e5-plus-drops-galaxy-s9-note-9-redmi-note-7-oppo-find-7/) (including mine, Galaxy S9).

Is there any chance that these could live on for some time in the LineageOS microG builds?

**Comment by spolack** [comment]
@von-nihil yes i plan to continue those builds. Current list of inofficial builds:

**lineageos-17.1**
* crownlte
* lavender
* star2lte

**lineageos-16.0**
* anne
* berkeley
* capricorn
* charlotte
* f1f
* figo
* find7
* gts210vewifi
* gts28vewifi
* ham
* kccat
* land
* lentislte
* mido
* ms013g
* r5
* r7sf
* r7plus
* santoni
* X00TD
* X01BD
* YTX703F
* YTX703L
* zangya
* zangyapro
* zenfone3

**lineageos-15.1**
* angler
* bullhead
* che10
* cherry
* dogo
* dragon
* foster
* fugu
* hayabusa
* huashan
* mint
* odin
* pollux
* pollux_windy
* tsubasa
* yuga

**Comment by FintasticMan** [comment]
Even though anne is on the list, there haven't been any builds for it, ever. I made an issue for it a while ago, and was wondering if that could be revisited. #122

**Comment by von-nihil** [comment]
> @von-nihil yes i plan to continue those builds. Current list of inofficial builds:
> 
> **lineageos-17.1**
> 
>     * crownlte
> 
>     * lavender
> 
>     * star2lte

@spolack That's great! Two questions: when might we expect to see updated downloads available? [Most recent builds currently seem to be from January](https://download.lineage.microg.org/star2lte/); and, any chance of having starlte on the list? :D

**Comment by Androidiana** [comment]
hi @spolack I am trying to make a xiaomi land build, to learn with my spare phone, but I have some troubles with the 17.1 vendor blobs download, do I need to add something to the local manifest?
What kind of adaptation you have made to regular lineageos?
If I recall well they stopped with 16....
BTW thank you for your "resurrection work"!

**Comment by r-a-y** [comment]
> @spolack do you think it could be possible to provide an unofficial build for the nexus 4 (mako)? This is the post on XDA with the source code repositories of linageOS 17.1: https://forum.xda-developers.com/nexus-4/development/rom-lineageos-15-1-t3758779

`mako` was last officially released on Lineage 15.1: https://github.com/LineageOS/lineage_wiki/blob/master/_data/devices/mako.yml. So if `mako` was re-introduced, it would probably be for Oreo and not Android 10.

**Comment by kurt-by** [comment]
@r-a-y what a strange reasoning is that? There is no official lineageOS oreo. For no device. You can build whatever version you want. Best chances to get an usable OS is when you can start with an existing unofficial lineageOS. That defines the android version.

**Comment by r-a-y** [comment]
Unless I'm wrong, this ticket is about re-introducing LineageOS builds for devices that had an official LineageOS release as mentioned above: https://github.com/lineageos4microg/docker-lineage-cicd/issues/90#issuecomment-814080278.

`mako` previously had an official 15.1 release and was dropped in July 2019: https://lineageos.org/Changelog-23/. `mako` would be a good candidate for a new unofficial 15.1 build.

**Comment by petefoth** [comment]
I am closing this issue because 
1. It's very old and has had no input for a year
2.The current strategy is that we make and host builds for devices which are officially supported by the three most recent LOS versions (at present 18.1, 19.1 & 20.0). There are no plans to change this strategy

It might be interesting to look at whether we could provide hosting (or even build infrastucture) for "unofficial" builds of devices which are not supported by LOS, but that is another  issue ;)

**Comment by Komprogue** [comment]
> @von-nihil yes i plan to continue those builds. Current list of inofficial builds:
> 
> **lineageos-17.1**
> 
>     * crownlte
> 
>     * lavender
> 
>     * star2lte
> 
> 
> **lineageos-16.0**
> 
>     * anne
> 
>     * berkeley
> 
>     * capricorn
> 
>     * charlotte
> 
>     * f1f
> 
>     * figo
> 
>     * find7
> 
>     * gts210vewifi
> 
>     * gts28vewifi
> 
>     * ham
> 
>     * kccat
> 
>     * land
> 
>     * lentislte
> 
>     * mido
> 
>     * ms013g
> 
>     * r5
> 
>     * r7sf
> 
>     * r7plus
> 
>     * santoni
> 
>     * X00TD
> 
>     * X01BD
> 
>     * YTX703F
> 
>     * YTX703L
> 
>     * zangya
> 
>     * zangyapro
> 
>     * zenfone3
> 
> 
> **lineageos-15.1**
> 
>     * angler
> 
>     * bullhead
> 
>     * che10
> 
>     * cherry
> 
>     * dogo
> 
>     * dragon
> 
>     * foster
> 
>     * fugu
> 
>     * hayabusa
> 
>     * huashan
> 
>     * mint
> 
>     * odin
> 
>     * pollux
> 
>     * pollux_windy
> 
>     * tsubasa
> 
>     * yuga

Any chance to make a 15.1 build for discontinued **bullhead** with all security/vulnerability patches, e.g. [this](https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/344174) one?

**Comment by petefoth** [comment]
Sorr

> Any chance to make a 15.1 build for discontinued **bullhead** with all security/vulnerability patches, e.g. [this](https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/344174) one?

Sorry, but no. We build for the most recent three branches, currently 18.1, 19.1 & 20.0 We don't have the resources to build for older branches.

The most recent 15.1 build for `bullhead` (from April 2022) is still available [for download ](https://download.lineage.microg.org/bullhead/), and no plans to remove it. As far as I know, there are no more recent updates to the LineageOS 15.1 branch. The link you posted is targeted at the 16.1 branch.
